### ISSUE TITLE
React Script Editor Webpart - gulp serve --> Throws error

### ISSUE THREAD

**Issue by MaxDaxDax** [SharePoint/sp-dev-fx-webparts#1002]
## Category

- [x] Question
- [x] Bug
- [x] Enhancement

I have cloned the git via Cmder and have executed the following commands:

-npm install
-npm gulp serve 

please find here my verions:
λ npm version
{ 'pzl-script-editor': '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.39.2',
  node: '10.16.3',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.54',
  zlib: '1.2.11' }

Here is the error which I get after executing "gulp serve"

λ gulp serve
gulp serve[9060]: c:\ws\src\node_contextify.cc:635: Assertion `args[1]->IsString()' failed.
 1: 00007FF67152DD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF671508886 node::MakeCallback+4534
 3: 00007FF67150893F node::MakeCallback+4719
 4: 00007FF6714DCD70 node::DecodeWrite+13120
 5: 00007FF671A35BF2 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+79442
 6: 00007FF671A36D59 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+83897
 7: 00007FF671A3609C std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80636
 8: 00007FF671A35FBB std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80411
 9: 00000338B98DC5C1

Thanks in advance for helping me with this problem.

Best regards,

Max

**Comment by boscowsu** [comment]
Hi @MaxDaxDax,
I was experiencing the exact same error, with very similar versions: 
λ npm version
{ 'pzl-script-editor': '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.34.0',
  node: '10.16.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.52',
  zlib: '1.2.11' }

Using [this link](https://gulpjs.com/docs/en/getting-started/quick-start) as a reference, I ran the following commands from my project directory and got it working.

npm rm -g gulp
npm install -g gulp-cli
npm install --save-dev gulp@3.9.1
gulp -v

My gulp version after running these:
λ gulp -v
CLI version: 2.2.0
Local version: 3.9.1

I believe it was necessary to target 3.9.1 based on the entry in the devDependencies section of the package.json folder: 
       "gulp": "^3.9.1"

Per the node.js semver documentation at [this link](https://nodesource.com/blog/semver-a-primer/) the caret character indicates 

> a range of acceptable versions that include all patch and minor versions from the ones specified up to, but not including, the next version. So "^1.2.3" can be approximately expanded as ">=1.2.3 <2.0.0".

**Comment by lumayara** [comment]
@boscowsu Thank you! This helped me!

**Comment by hugoabernier** [comment]
Hey @MaxDaxDax  I hope that @boscowsu 's answer helped you?

I'll mark this issue as closed. Feel free to re-open it if you need more help.

Thanks @boscowsu for helping with this!
