### ISSUE TITLE
Add-PnPClientSideWebPart : After parsing a value an unexpected character was encountered: m. Path 'properties.script'

### ISSUE THREAD

**Issue by shekharmyediary** [SharePoint/sp-dev-fx-webparts#1007]
I am adding script editor webpart via powershell in a loop,
Code:-
  #If a web part Title was provided in function call then add it to the web part properties hashtable
    $Properties = "{'title':'Custom Editor webpart for SPO $Counter'}"
    $str = $webPartProperties | Out-String
    Add-Content -Path $buildLog -Value '--WP Properties--'
    Add-Content -Path $buildLog -Value $str
    
    If (($Section -eq 0) -and ($Column -eq 0)) {
        Write-Warning -Message "The Section and Column fields for the [$WebPartTitle] web part have been left blank or have zero values"
        try {
            
           $addedApp= Add-PnPClientSideWebPart -Page $PageName -Component $SpfxApp  -WebPartProperties $Properties -ErrorAction Stop
           if($addedApp){
           Set-PnPClientSideWebPart -Page $PageName -Identity $addedApp.InstanceId -PropertiesJson $webPartProperties
            }
           Write-Host ''
            
        }
        catch {
            Write-Log -Exception $_
            Write-Error -Message "Unable to add [$WebPartTitle] web part to the [$PageName] page. Check that there is a section [$Section] with [$Column] columns"
        }
    }
    Else {
        try {
            
            $addedApp= Add-PnPClientSideWebPart -Page $PageName -Component $SpfxApp # -WebPartProperties $Properties -Section $Section -Column $Column -ErrorAction Stop #-Order $Order
            if($addedApp){
           Set-PnPClientSideWebPart -Page $PageName -Identity $addedApp.InstanceId -PropertiesJson $webPartProperties
            }
            
        }
It is working fine for one of the app and appending script to it,but on adding app to second section it is causing error as:

Add-PnPClientSideWebPart : After parsing a value an unexpected character was encountered: m. Path 'properties.script' in below line

$addedApp= Add-PnPClientSideWebPart -Page $PageName -Component $SpfxApp  -WebPartProperties $Properties -ErrorAction Stop

ANY HELP IS APPRECIATED,AS IT IS A BIT URGENT :)

**Comment by hugoabernier** [comment]
Hey @shekharmyediary  did you ever get this issue resolved.

I'll mark this issue as closed as there hasn't been any activity for a while.

If you need more help, please feel free to open a new issue. I encourage you to fill the issue template -- especially for urgent matters -- as it will help route the issue to the right people and, hopefully, get you answers faster.
