### ISSUE TITLE
Color Coding SPSecurityGrid

### ISSUE THREAD

**Issue by mikezimm** [SharePoint/sp-dev-fx-webparts#1009]
## Category

- [x] Enhancement
- [ ] Question
- [ ] Bug

## Authors
@russgove , @hugoabernier 

## Expected or Desired Behavior
I was wondering how hard it would be to create an alternate view of this part.  The basic layout and most of the web-part would be the same.

The only difference would be that instead of having a drop down with each of the permission types, rank the types by "severity" and apply a color scale to the severity.  Then instead of a solid gray circle icon, set the color based on the permission level.

I've done this on a smaller simpler scale today on premise where Red means Full Control, Yellow means Contribute, Green means read.  This would make it easy to get an idea of who has what level of permissions in general at a quick glance.

## Expanding on my simple color scheme, one that might have a little more detail might be:

1. Red - anyone who can edit site/list settings (Full Control, Edit)
2. Purple - any who can approve
3. Yellow - anyone who can contribute (edit files)
4. Green - anyone who can read

## Here's kind of what I am thinking it would look like:
![SPSecurityGrid Color Coding (2)](https://user-images.githubusercontent.com/49648086/65849063-cd9e4c80-e316-11e9-830f-e594795e8fed.PNG)

Thanks for your contribution! Sharing is caring.

**Comment by russgove** [comment]
Hi @mikezimm,
i like your idea, i hope to upgrade this to the latest spfx release this year, and will look into color coding as well.
Alsomhoping tomget it working with azure AD groups.
Russell

**Comment by russgove** [comment]
Hi @mikezimm 

I'm hoping you'll be able to help me test this:

![image](https://user-images.githubusercontent.com/2412956/70087501-72bcf600-15e2-11ea-9d71-37d3e3c5c4be.png)

**Comment by russgove** [comment]
OK, Theres working version in my repo at https://github.com/russgove/sp-dev-fx-webparts/tree/master/samples/react-securitygrid

**Comment by mikezimm** [comment]
@russgove ,
I'm trying to clone your fork now but it's currently at download marker 600MB... I think I may be getting all the files, not just the source folder... will let you know if it works though.

**Comment by mikezimm** [comment]
@russgove ,
I cloned your fork, switched to dev, npm installed using gitDesktop.
Then I got the following error about isDomainIsolated:
After that I tried npm install again and didn't get any errors.
However, when I load it on the page it does not seem to show any data like it does in the master branch.

The first screenshot shows the web part on the page with property pane open... looks like I have the option to edit colors, but you can see there is no data in the grid part.

The second screenshot shows what I see when I click the edit colors button.... again looks like it's just not loading any data for me.  I tried in 2 different tenants in both Chrome and IE.

Thoughts?



```
Error - Unknown 
 JSON validation failed:
C:\Users\myfolder\projects\Git\russ-sp-dev-fx-webparts\samples\react-securitygrid\config\package-solution.json

Error: #/solution
       Additional properties not allowed: isDomainIsolated
[17:27:57] ==================[ Finished ]==================
Error - Unknown 
 JSON validation failed:
C:/Users/myfolder/projects/Git/russ-sp-dev-fx-webparts/samples/react-securitygrid/config/package-solution.json

Error: #/solution
       Additional properties not allowed: isDomainIsolated
```

![image](https://user-images.githubusercontent.com/49648086/70095862-c6840b00-15f3-11ea-9fcc-4bb5483c2b6b.png)

![image](https://user-images.githubusercontent.com/49648086/70095881-cdab1900-15f3-11ea-9033-6d05b2a9afab.png)

**Comment by russgove** [comment]
Hey, after i posted last email, i,found a bug (if no permissions selected it would,error out). I pushed an update about an hour ago. please get latest when u can.

**Comment by russgove** [comment]
and after you click 'edit permissions,and colors', ther is a menu on the rop of that panel. you need to,click 'add permission' to add a row. (i should make it add a blank row by default if there are no selected permissions)

**Comment by mikezimm** [comment]
@russgove ,

Ok, got the commit 350e5d5f (fix if no permissions selected).  I can now see my groups and edit colors.  Concept is pretty cool because the end user can do just about anything they want.

Here's what I see now:  I can edit the colors for a level and see empty circles (not solid gray like before).  But the color is not visible yet.  Maybe your still working on it?

![2019-12-04 00_37_43-Window](https://user-images.githubusercontent.com/49648086/70115791-c5bc9a80-162e-11ea-9e7a-bf67e451d02b.png)

**Comment by mikezimm** [comment]
@russgove ,
I see some color now on people, but not groups yet:

I had an idea also to make it easier to select some pre-built options.  If I can get a chance today, I will try to build it up and send it to your repo.

![image](https://user-images.githubusercontent.com/49648086/70150309-d34a4280-1677-11ea-8a5c-1c25b681545d.png)

**Comment by mikezimm** [comment]
@russgove ,
I forked your fork, made some updates and created a pull request back to you.
I've never done this before so I apologize if I messed something up.

Basically, this is the result:
In property pane, you have a dropdown to pick a color scheme... (Screenshot 1 - red arrow).

You select it, refresh the page and it populates your selectedPermissions[] array (Screenshot 1 - yellow highlight).

I wasn't able to get it to re-render without a refresh but I am pretty new at SPFx/react so you may be able to get it working smoother.

As you can see by the second screenshot, I actually did get it to work.

How you can manage all those choices and in a separate file and easily create new configurations.  Let me know if you want to do any kind of skype or team call and I can walk you through it.

![image](https://user-images.githubusercontent.com/49648086/70189864-6f00a080-16c2-11ea-94c0-833bdd6b2b32.png)

![image](https://user-images.githubusercontent.com/49648086/70189870-74f68180-16c2-11ea-9fa1-4bbc81489d16.png)

**Comment by russgove** [comment]
Thanks mike,I have some pressing issues in my “day” job. Can I ping you in 2 weeks?

**Comment by mikezimm** [comment]
No problem Russell,
I’ll keep poking at it as well.  By the time you get back to it there will probably be a few more updates.

Regards,

**Comment by russgove** [comment]
Mike, THANK YOU!

This looks great!

Hope to get back to this next week.

I found a  big issue in that if you use the webpart on a subsite it does
not seem to pull in the sharepoint groups. Have you noticed that ?

**Comment by mikezimm** [comment]
@russgove ,

Yes I did notice that groups were not showing a permission "level" in the webpart.
But since I have only tested on a subsite, I just thought it was yet to be finished.

If you need any help testing let me know...

Also note that I created a new "Issue" to add an enhancement #1081.  I think that's what we are supposed to do to track that discussion separately right?

**Comment by russgove** [comment]
Ah, that was not an issue , was 'as desigened' . I never show the sp groups, only AD groups.
I finished [i think] the color coding. It now lets the user select the colors as well as the person confifiguring the webpart.

I'll tale a look at your PR this weekened. So you added some preset configurations and Icons? 
Can wait to have a look!

**Comment by mikezimm** [comment]
One other thing on the color PR I sent... I put a placeholder in the pre-configured object for a "Label" with the color so we can put a word that people recognize (like "Full Control") instead of "manageWebs".

Or maybe we can tap into the roles definition you already have.... (see screenshot).  Do you know if the role definitions you get back in your call are browser language dependent?  If so, maybe in our pre-configured section, we could find a way to tag a specific role and get the highlighted "name" property.

![image](https://user-images.githubusercontent.com/49648086/70446780-9f9e5c80-1a6b-11ea-9d24-eae9a213e888.png)

**Comment by russgove** [comment]
Hi,
those role definitions are configurable by the end user, so we can't rely on them. I like your idea though. I am going to add. a friendly name to display on the legend.

i just uploaded an intitial version to let you select icons. 
russell

**Comment by hugoabernier** [comment]
Hey @mikezimm  thanks again for helping make these samples better.

It looks like @russgove made some of the changes you described. I'll mark this issue as closed, but absolutely feel free to open a new issue with more suggestions.
