### ISSUE TITLE
Multiple Search Results Webpart on one Page: Custom Result Templates not loading in Version 3.6.3.0

### ISSUE THREAD

**Issue by devCherif** [SharePoint/sp-dev-fx-webparts#1011]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Multiple Search Result Webparts with different custom Search Result Layout loading & showing both on the same page after reload in Version 3.6.3.0 of ModernSearch.

## Observed Behavior

By using 2 or more search result webparts on one page with custom results layout, there's a loading/handlebar template error since version 3.6.3.0. By multiple reloads of the page, one of the both webparts is showing, the other will stay hidden. We've upgraded our running Version from 3.3.0.0, in this version it's working fine for us (With default search result layouts it's working fine even with version 3.6.3.0).

I've used Chrome to produce this error.

## Steps to Reproduce

1. Install ModernSearch Webparts in Version 3.6.3.0
2. Insert 2 Search Result Webparts on the same page
3. Set a custom search results layout for both
4. Reload the page will not show one of both webparts or even not showing both webparts

**Comment by hugoabernier** [comment]
Hey @devCherif , I couldn't find which web part you were referring to. Did you ever get the issue resolved?

Typically, when adding a second web part does not work, it is related to code that manipulates DOM by element ID.

I'll mark the issue as closed, but if you're still experiencing issues, feel free to open a new one. The issue template now has an **Author** section to help us route the issues to the original authors which should help get you answers sooner.

Thanks!
