### ISSUE TITLE
React Calendar is not working in Internet explorer

### ISSUE THREAD

**Issue by prathimapilli** [SharePoint/sp-dev-fx-webparts#1012]
Hi Team,

React Calendar is not working in Internet explorer. 

It is working in google chrome but not in IE. Please suggest.

Thanks

**Comment by prathimapilli** [comment]
in Uncontrolled(Component)    in ForwardRef    in div    in div    in div    in Unknown    in Unknown
--

**Comment by prathimapilli** [comment]
I resolved the issue by installing and adding polyfill.
npm install --save @pnp/polyfill-ie11
import "@pnp/polyfill-ie11";

Dont forget to add the path in CDN(writemanifest.json) and upload the temp files in path.

**Comment by VelizarT** [comment]
@prathimapilli I installed the polyfill but still getting "in Uncontrolled(Component)in ForwardRef in div in div in div in Unknown in Unknown" error message.

**Comment by prathimapilli** [comment]
> @prathimapilli I installed the polyfill but still getting "in Uncontrolled(Component)in ForwardRef in div in div in div in Unknown in Unknown" error message Did you do anything else? Thanks

I also got the same issue.. I think u missed adding CDN path in code and copy the temp files in that path..that resolve my issue

**Comment by SaghirA** [comment]
I followed the instruction, but i am getting error 
`Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `

Can you post the steps of what you did?

Thanks

**Comment by Armachillo** [comment]
Can anyone post step by step instructions on how to resolve this, as well as what files need modified?

**Comment by hugoabernier** [comment]
@Armachillo I just updated the sample and upgraded the browser compatibility library. Can you see if this solves your issue?

**Comment by vishal591** [comment]
I also facing this issue tried lots of things but finally, it is working
for my case it will require this sequence, you need to use it across everywhere on the solution


import "@pnp/polyfill-ie11";
import 'core-js/stable/object/assign';
import "es6-map/implement";
import "core-js/modules/es.symbol.js";
