### ISSUE TITLE
react-image-gallery not loading

### ISSUE THREAD

**Issue by physics515** [SharePoint/sp-dev-fx-webparts#1013]
## Category

- [ ] Question
- [x] Bug
- [x] Enhancement

## Authors
@ejazhussain 

## Expected or Desired Behavior

I am not sure if this describes a bug or an enhancement I guess it depends on how you look at it. I would like to be able to select a library from the webparts properties instead of typing it manually to make setup easier. I cannot seem to get this to work on my subsite. I get to the loading screen with the little circle spinning and it just sits there and spins forever with no feedback on what went wrong.

## Observed Behavior

1. I created a Subsite on our companies intranet called "photos"
2. I created a document library called "Photos"
3. Put images in the "Photos" document library
4. Created a column called "Department Metadata" in the document library "Photos"
5. Created a term set called "Department Term" and added child terms
6. Linked term set "Department Term" to "Department Metadata" column
7. Added info to "Title" column and "Department Metadata" column
8. Uploaded image-gallery webpart to our webpart library and deployed
9. Added webpart to home page of "photos" subsite
10. Typed "Photos" in "Image Library Name" field and adjusted "Page Size" field and hit "Apply"
11. Waited forever and it never loads.
12. Cries himself to sleep... :)

Am I entering the correct information?

## Steps to Reproduce

See above

Thank you for your help!!

**Comment by mikezimm** [comment]
I tried over the weekend with similar result.  Only difference was my Termset was just called "Department" so I thought I did something wrong.

**Comment by ejazhussain** [comment]
@physics515 @mikezimm - sorry you had issue running the solution. I have just downloaded the same repo again from and run under workbench and did not find any issue. 


see below this is how my image gallery looks like if that helps.

![image](https://user-images.githubusercontent.com/19267065/66349407-bf70b180-e950-11e9-86a1-49f45bf23605.png)

web part properties.  
![image](https://user-images.githubusercontent.com/19267065/66349523-ffd02f80-e950-11e9-9c32-2205d8ef1f6f.png)

However, there is one which i have notice that, if you click on Apply, it does not automatically refresh the web part. So quick workaround is, refresh the page after clicking Apply button.

I will create another pull request to update this package.

Let me know if you still experiencing same issue. Happy to go through issue on call if that helps you

**Comment by physics515** [comment]
I was never able to get it to work, so we ended up going in a different direction. Maybe the documentation just needs to be clarified.

**Comment by hugoabernier** [comment]
Hey @physics515 sorry that the answers provided didn't help.

I'll go ahead and mark this issue as closed, but feel free to re-open the issue if you need more help. We'd also love to hear how you worked around the issue.
