### ISSUE TITLE
Indexable properties get's persisted in the Description managed property

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-fx-webparts#102]
#### Category
- [x] Question
- [x] Bug?

#### Expected or Desired Behavior
The properties should be perhaps searchable by default, and get their own crawled properties.

#### Observed Behavior
By adding

`
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      'Foo': { isHtmlString: true },
      'Bar': { isHtmlString: true }
    };
  }
`

into my SPFx web part, the values of those properties appear concatenated in the ***Description*** managed property. This means I need to type: ***Description:term*** in order to get a match.

Is this a bug or by design? Seems to me a property named ***Foo*** should get a crawled property named ***ows_Foo*** which I can map as I please - making it default searchable, or at least not tied to using the *Description* managed property.

**Comment by wobba** [comment]
@patmill any input on this?

**Comment by patmill** [comment]
Hi Mikael - sorry for not responding here.  I was looking at the sp-dev-docs issues list.

So the current implementation of this should result in all of the webpart content being in the index with the rest of the page content.  The goal being primarily to surface all of the user content in the full text index, rather than having arbitrary crawled / managed properties.  It is something we could consider in the future, but would require a fair chunk of work.  I'll bubble up the request though.  Thanks,

**Comment by wobba** [comment]
Thank you @patmill. But it still doesn't make sense that all web part properties are appended to the Description managed property upon indexing, or? So some work is already in place here ;)

I do get the point of having custom properties as part of the fti, but using this as a way to add metadata instead of doing content types seems to make a whole lot of sense to me. But at least I know how the current implementation works.

**Comment by Divyeshkotadia** [comment]
I am facing slightly different issue in which I want SPFX webpart content to be crawled and popup in search result but it doesn't. Any idea how I can make it work or it is something that current implementation does not support. Please provide valuable inputs... @wobba @patmill

**Comment by wobba** [comment]
@Divyeshkotadia by adding the function in my question - propertiesMetadata(), you should be able to specify which web part properties are added to the index. If you want the rendered html crawled, you need to add that as part of a webpart property.

**Comment by Divyeshkotadia** [comment]
@wobba thanks for your prompt response.. I have tried what you mentioned but it does not work out... Is it possible for you to share sample code.. Secondly will it work on classic pages as well because my implementation is used on those pages and content that user has entered should be searchable through search. Let me know if you don't relate any part of my query...
Thank you very much...Cheers!!!

**Comment by wobba** [comment]
Here's a sample React part:
`
	import * as React from 'react';
	import * as ReactDom from 'react-dom';
	import { Version } from '@microsoft/sp-core-library';
	import {
	  BaseClientSideWebPart,
	  IPropertyPaneConfiguration,
	  PropertyPaneTextField,
	  IWebPartPropertiesMetadata
	} from '@microsoft/sp-webpart-base';

	import * as strings from 'puzzlepartMetadataStrings';
	import PuzzlepartMetadata from './components/PuzzlepartMetadata';
	import { IPuzzlepartMetadataProps } from './components/IPuzzlepartMetadataProps';
	import { IPuzzlepartMetadataWebPartProps } from './IPuzzlepartMetadataWebPartProps';

	export default class PuzzlepartMetadataWebPart extends BaseClientSideWebPart<IPuzzlepartMetadataWebPartProps> {

	  public render(): void {
		const element: React.ReactElement<IPuzzlepartMetadataProps> = React.createElement(
		  PuzzlepartMetadata,
		  {
			Keywords: this.properties.Keywords,
			Kash: this.properties.Kash
		  }
		);

		ReactDom.render(element, this.domElement);
	  }

	  protected get dataVersion(): Version {
		return Version.parse('1.0');
	  }

	  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
		return {
		  pages: [
			{
			  header: {
				description: strings.PropertyPaneDescription
			  },
			  groups: [
				{
				  groupName: strings.BasicGroupName,
				  groupFields: [
					PropertyPaneTextField('Keywords', {
					  label: strings.KeywordsFieldLabel
					}),
					PropertyPaneTextField('Kash', {
					  label: "Extra"
					})
				  ]
				}
			  ]
			}
		  ]
		};
	  }

	  protected get propertiesMetadata(): IWebPartPropertiesMetadata {
		return {
		  'Keywords': { isHtmlString: true },
		  'Kash': { isHtmlString: true }
		};
	  }
	}
`

**Comment by Divyeshkotadia** [comment]
Thanks a ton @wobba appreciated your efforts.

We tried propertiesMetadata() method and following are the behavior we are getting:

1) Content does not appear in the Search results for classic pages. 
2) For modern pages, the behavior is even more baffling.  It actually indexes content with a webpart ID as a prefix to the Search text.  The user would then need to enter a search string that looks like this: “{WebpartID}SearchText”.

Please let us know your valuable comments.
