### ISSUE TITLE
Script Editor Web Part - gulp serve typescript errors

### ISSUE THREAD

**Issue by Hitinthegit** [SharePoint/sp-dev-fx-webparts#1021]
I'm unable to load local workbench with 'gulp serve'.

Node.js v8.16.1
npm v6.11.3
Typescript v2.4.2
gulp CLI v2.2.0 / local 3.9.1

Steps taken:
1. Downloaded the repo.
2. Ran 'npm install'
3. Ran 'gulp trust-dev-cert'
4. Ran 'gulp serve'

Basically, I'm getting multiple typescript errors everytime I'm trying to load in localhost.
Like so: "
Error - typescript - node_modules\@types\prop-types\index.d.ts(31,37): error TS1005: '=' expected. 
Error - typescript - node_modules\@types\prop-types\index.d.ts(33,38): error TS1005: ';' expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,46): error TS1005: ';' expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,47): error TS1109: Expression expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,48): error TS1109: Expression expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,75): error TS1109: Expression expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,99): error TS1005: ';' expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,102): error TS1109: Expression expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,118): error TS1109: Expression expected.
Error - typescript - node_modules\@types\prop-types\index.d.ts(35,143): error TS1005: ';' expected.
"

Any ideas folks?

**Comment by bencleary** [comment]
Yeah same issue for me, used to work fine...i found a work around, its not idela but it works.

In your current branch checkout commit e7db64e016bdc952a306f89c02134d235863a17c, delete your node_modules and package-lock.json and run npm install

Not ideal but at least its working 🤷‍♂

**Comment by hugoabernier** [comment]
@Hitinthegit did you ever solve this issue?

I'll mark it as closed as there hasn't been any activity for a while, but feel free to open a new issue if you still need help.

I also encourage you take the time to fill the issue template next time, as it helps us route the issue to the author of the sample and -- hopefully -- get you answers sooner.
