### ISSUE TITLE
loading web part second time chart is not showing up instaed it is updating the first webpart chart any idea?

### ISSUE THREAD

**Issue by pyalam** [SharePoint/sp-dev-fx-webparts#1022]
![image](https://user-images.githubusercontent.com/8193674/66437936-ccdd7880-e9f0-11e9-9431-235405ff0f26.png)

**Comment by hugoabernier** [comment]
Hey @pyalam this seems to be a pretty old issue. Did you ever solve it?

Usually, these types of issues (second web part does nothing) is usually related to code that uses DOM manipulation by element ID.

If you're still experiencing this issue, please open a new issue and take the time to fill the issue template, it'll help us route it to the authors of the sample, if applicable.
