### ISSUE TITLE
Build Failed when running npm install-react-modern-charts

### ISSUE THREAD

**Issue by kcronic** [SharePoint/sp-dev-fx-webparts#1024]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@joelfmrodrigues @VesaJuvonen
 
## Expected or Desired Behavior
 Expected behavior should be that when I run "npm install" and package builds. 

## Observed Behavior

When I run "npm install" I get the following errors.

C:\DevTools\react-modern-charts>npm install

> deasync@0.1.12 install C:\DevTools\react-modern-charts\node_modules\deasync
> node ./build.js

C:\DevTools\react-modern-charts\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DevTools\react-modern-charts\node_modules\deasync
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-10-10T16_20_51_394Z-debug.log

C:\DevTools\react-modern-charts>

## Steps to Reproduce

Using node version 10.16.3 go to the directory path of react-modern-charts run the command "npm install"

**Comment by hugoabernier** [comment]
@kcronic this issue appears to have been pretty quiet for a while... did you ever get it resolved?

I'll mark it as closed, but if you're still experiencing this issue, feel free to re-open it.
