### ISSUE TITLE
Keep getting "Verification failed while extracting @microsoft/sp-polyfills@1.2.0"

### ISSUE THREAD

**Issue by ZeweiS** [SharePoint/sp-dev-fx-webparts#1027]
## Category

- [x] Question
- [x] Bug
- [ ] Enhancement

When running "npm install" I am getting following error, already tried to very and clean the cache with no luck:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= integrity checksum failed when using sha1: wanted sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= but got sha512-SZARibyCQB+1j5b7g/6CrsUBA8pz9Yh1z+2RhXMlJcLyGkUmSriKgRmHnPjpjogQSGUAARTIFaYIMncfqL+8Pg== sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=. (1467748 bytes)

**Comment by djtrustgod** [comment]
I too have this issue . . . tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted

**Comment by NPrice99** [comment]
Same here npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.

**Comment by nurdena** [comment]
Same for me:
`npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.`

**Comment by NPrice99** [comment]
Start from new machine - yo @microsoft/sharepoint - Congratulations!  Solution pzl-script-editor is created.  Run gulp serve to play with it! Run Gulp Serve and get this error - Error: Cannot find module '@microsoft/sp-build-web' so run npm i @microsoft/sp-build-web - get error tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted

**Comment by nurdena** [comment]
Could try this solution instead for a script editor I haven't tried to deploy it yet: https://github.com/jcoleman-pcprofessional/True-Script-Editor

**Comment by NPrice99** [comment]
Hi Mikael why does the file package-lock.json in react-script-editor refer to "https://onedrive.pkgs.visualstudio.com/_packaging/odsp-npm/npm/registry" in the dependencies section rather than https://registry.npmjs.org ?  Regards  Nigel

**Comment by DanielJudele** [comment]
I had the same issue with @microsoft/sp-polyfills@1.2.0. 
I solved the issue by updating my development environment to use a higher version of the @microsoft/sp-polyfills package: nodejs version 10.17.0 (this is the working version for SharePoint Framework), Yoeman (version 3.1.0). I deleted **node_modules**, the **package-lock.json** in the solution folder, then I run **npm install**. 
Now I'm using @microsoft/sp-polyfills@1.4.1 and seems to be fine.

**Comment by kanthvr** [comment]
hi Daniel Judele, can i have mail id. mine ramakanth.v.vreddy@gmail.com

**Comment by ZeweiS** [comment]
Got it working: modified \package-lock.json, line 874, correct value is “sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=” for "integrity". Also needed to modify name attribute, line 4, in \config\package-solution.json because "@" made the value invalid.

Owner of this project: please fix the issues as described above!

**Comment by Maya-Mostafa** [comment]
@ZeweiS thanks a lot! This fixed the issue for me :D 
How did you reach this solution?

**Comment by JeanBarros** [comment]
After a long day struggling with this, @DanielJudele solution save me from a from a headache. Thank you so much for sharing.

**Comment by ravaldivia001** [comment]
@ZeweiS and @DanielJudele - combination of both solutions worked for me!  Thank you so much!!!

**Comment by ChrisMenning** [comment]
Tried both of the work-arounds by @DanielJudele and @ZeweiS but am getting nowhere. Now I'm getting "PhantomJS not found on PATH" with an "ELIFCYCLE" code.

**Comment by Philzy610** [comment]
> Got it working: modified \package-lock.json, line 874, correct value is “sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=” for "integrity". Also needed to modify name attribute, line 4, in \config\package-solution.json because "@" made the value invalid.
> Owner of this project: please fix the issues as described above!

@ZeweiS THANK YOU!  This worked.

**Comment by hugoabernier** [comment]
Hi @ZeweiS  I'll mark this issue as closed as it seems that an earlier pull request may have solved this issue.

If you find that you're still experiencing the issue, feel free to re-open it.
