### ISSUE TITLE
Getting "Verification failed while extracting @microsoft/sp-polyfills@1.2.0" while running "npm install" on react-script-editor

### ISSUE THREAD

**Issue by ZeweiS** [SharePoint/sp-dev-fx-webparts#1031]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Observed Behavior

>npm install

......
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= integrity checksum failed when using sha1: wanted sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= but got sha512-SZARibyCQB+1j5b7g/6CrsUBA8pz9Yh1z+2RhXMlJcLyGkUmSriKgRmHnPjpjogQSGUAARTIFaYIMncfqL+8Pg== sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=. (1467748 bytes)
......

## Steps to Reproduce

npm install

=============================

When running "npm install" on react-script-editor I am getting following error, already tried to very and clean the cache with no luck.

**Comment by AnthonyAtApex** [comment]
Work around posted here:
[https://github.com/SharePoint/sp-dev-fx-webparts/issues/1027#issuecomment-551942972](url)
https://github.com/SharePoint/sp-dev-fx-webparts/issues/1027#issuecomment-551942972

**Comment by ChrisMenning** [comment]
> Work around posted here:
> https://github.com/SharePoint/sp-dev-fx-webparts/issues/1027#issuecomment-551942972
> #1027 (comment)

That workaround is no longer showing up.

**Comment by hugoabernier** [comment]
Hey @ZeweiS  it looks like this issue was resolved with earlier pull requests.

If you're still experiencing issues, feel free to re-open this issue.
