### ISSUE TITLE
Page Navigator Heading IDs missing

### ISSUE THREAD

**Issue by hristochr** [SharePoint/sp-dev-fx-webparts#1054]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Authors
@aakashbhardwaj619 

## Expected or Desired Behavior

After deploying the [page navigator](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-page-navigator) one should be able to navigate the page by means of the corresponding headings. 

## Observed Behavior

We have deployed the web part and it successfully generated the list of headings on the page. However, by default the headings have no id attribute, therefore the navigation is not working (i.e. clicking on a heading from the navigator web part does nothing)

Can you please let me know how to set up the id's on the page headings? I watched the demo and it does not seem like anything additional is required?

**Comment by aakashbhardwaj619** [comment]
Hi Chris,

Thanks for reaching out. You are right that the web part does not require any additional configuration.

Could you please provide me a screen shot of the page? I would also like to confirm if anchor links are getting created for headings that you add on the page and to what URL does any of the Nav link redirect to when you click on it?

Regards,
Aakash

**Comment by hristochr** [comment]
Hi @aakashbhardwaj619 

thanks for replying. Here is a screenshot:
![pnav](https://user-images.githubusercontent.com/22388580/68370192-36f65400-013c-11ea-81a7-793f3e178f22.png)


You can see that the link in the navigator does have an anchor id but the heading does not, same for the other headings. I added the web part after the page was created but I also tried adding headings after the web part was put on the page to no result. 

Thanks for the help.

**Comment by aakashbhardwaj619** [comment]
Hi @hristochr ,

Since you say that the headings do not have an anchor tag associated with them, it seems that the **On Page Anchors** feature has not been rolled out to your tenant yet. The [roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Rolling%20out%2CSharePoint#owRoadmapMainContent) says that it is still rolling out so once it is rolled out to your tenant the web part should start working successfully.

Regards,
Aakash

**Comment by hristochr** [comment]
Hi @aakashbhardwaj619,
Thanks for the input! I am following the roadmap but I thought your solution had a workaround :)

**Comment by hugoabernier** [comment]
Hey @hristochr I hope you found a workaround for this?

i'll mark this issue as closed because this issue has been pretty quiet for a while.

Feel free to re-open it if you need more help.
