### ISSUE TITLE
react content query webpart - recursive not working

### ISSUE THREAD

**Issue by coolvijaymca** [SharePoint/sp-dev-fx-webparts#1056]
## Category

- [x] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior
I have selected a site into **Site Url** property and selected **Web Url** as **/**. My assumption is that if we selected **/** then it will go recursively into  every site under **/**. Lastly I have selected **List Title**. I have same list tile under every sub-site. 
From my understanding is that webpart should look into every subsite under **/** and get the data from **List Name** which I choose on step one.

But this is not happening. It can get the data from single site but not from all site. Can someone confirm the behavior?

## Observed Behavior
Data from sub-site list should be displayed.

## Steps to Reproduce
![Capture](https://user-images.githubusercontent.com/27564614/68314240-dd325300-0083-11ea-9edc-333ba2e38fba.JPG)
1. Create a sub site under any site
2. Configure the Web Part
3. Choose site url as top level site
4. Choose **/** as web URL
5. Choose list title 

No data being displayed from sub-site.

Thanks for your contribution! Sharing is caring.

**Comment by spplante** [comment]
@coolvijaymca this is not the expected behavior, the CQWP uses the CAML query to perform a query on a specific list, as you can see when selecting the list in question.

There is no such thing as a CAML query performed on multiple libraries and subsites in CSOM.

**Comment by kmprasad4u** [comment]
You need content search for getting what you need. Refer to the below solution

https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch/react-search-refiners

**Comment by hugoabernier** [comment]
@coolvijaymca I hope that @spplante 's answer helped you.

i'll mark this issue as closed. Feel free to open a new issue if you need more help.

Thanks @spplante  and @kmprasad4u for helping with this.
