### ISSUE TITLE
Load the selected Item Details In Model POPUP in SPFX React

### ISSUE THREAD

**Issue by jayendrachowdary** [SharePoint/sp-dev-fx-webparts#1057]
HI All,

I am getting the SharePoint List Data and showing in a Table in table their are two action button are their 1 is Edit and 2 is Delete.Here I when i am click on Edit popup is showing popup but in popup I have to get the Selected List Item Data in popup I don't know how to Do that one Can any one suggest the solution or any links .

Regards,
Jayendra.

**Comment by sudharsank** [comment]
Try to store the **_Item ID_** in the state variable when an item is selected or any option is selected for the item. Using the **_item ID_** from the state variable, you can get the details of the item before opening the Model Popup or you can even show the **_Spinner_** and then try getting the item after the popup is shown to the users.

**Comment by hugoabernier** [comment]
@jayendrachowdary I hope that @sudharsank 's answer helped you solve this issue.

If you still need more help, please let us know. in the meantime, I'll mark this issue as closed.

Thanks again @sudharsank for your help! (Feels like I've typed this a thousand times today!)
