### ISSUE TITLE
when will the support for attachment available for list form?

### ISSUE THREAD

**Issue by wrvishnu** [SharePoint/sp-dev-fx-webparts#1059]
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Authors

> Because of the way this repository is setup, samples authors do not get a notification when you create an issue. *It makes it less likely for you to get your issue resolved or to get help*. For the section above **@mention any author of the sample**. Authors' github handle can be found on the main sample documentation page, under the "solution" section. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Expected or Desired Behavior

> _If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Observed Behavior

> _If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Steps to Reproduce

> _If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by jindalv10** [comment]
@wrvishnu 

Here is file you can create under components/formfields.

Called AttachmentRender.tsx

`
import * as React from 'react';
import { ISPFormFieldProps } from './SPFormField';
import styles from './FormField.module.scss';
import { Dialog, DialogType, DialogFooter } from 'office-ui-fabric-react/lib/Dialog';
import { Icon, PrimaryButton, Image } from 'office-ui-fabric-react';
import * as strings from 'ListFormStrings';

interface IAttachmentProps {
    fieldProps: ISPFormFieldProps;
}

interface IAttachmentState {
    waitingImageUpload: boolean,
    imagePreviewUrl: any,
    fileBuffer: any,
    hideDialog: boolean
}



export class AttachmentRender extends React.Component<IAttachmentProps, IAttachmentState> {

    private myref = null;

    constructor(props: IAttachmentProps) {
        super(props);
        this.state = { waitingImageUpload: null, imagePreviewUrl: null, fileBuffer: null, hideDialog: true,};
        this.handleFileSelect = this.handleFileSelect.bind(this)
        this._handleImageChange = this._handleImageChange.bind(this);
        this._handleRemoveImage = this._handleRemoveImage.bind(this);
    }

    private handleFileSelect = (e) => {
        e.preventDefault();
        this.myref.click();
    }

    private _handleRemoveImage(ev) {
        this.setState({
            imagePreviewUrl: null
        });
    }

    private _handleImageChange = async event => {
        event.persist();
        const fileInformation = []

        if (!event.target || !event.target.files) {
            return;
        }

        this.setState({ waitingImageUpload: true });
        const fileList = event.target.files;
        // Uploads will push to the file input's `.files` array. Get the last uploaded file.
        const latestUploadedFile = fileList.item(fileList.length - 1);

        try {
            const fileContentsAsDataURL = await this.getFileAsDataURL(latestUploadedFile);
            const fileContentsAsBuffer: any = await this.getFileAsBuffer(latestUploadedFile);
            this.setState({
                imagePreviewUrl: fileContentsAsDataURL
            });

            fileInformation.push({
                fileName: fileList[0].name,
                bufferLength: fileContentsAsBuffer.byteLength,
                buffer: fileContentsAsBuffer
            });
            this.props.fieldProps.valueChanged(fileInformation);
        } catch (e) {
            this.setState({
                waitingImageUpload: false
            });
        }
    };


    private getFileAsDataURL = inputFile => {
        const temporaryFileReader = new FileReader();
        return new Promise((resolve, reject) => {
            temporaryFileReader.onerror = () => {
                temporaryFileReader.abort();
                reject(new DOMException("Problem parsing input file."));
            };
            temporaryFileReader.onload = () => {
                resolve(temporaryFileReader.result);
            };
            temporaryFileReader.readAsDataURL(inputFile);
        });
    }

    private getFileAsBuffer = inputFile => {
        const temporaryFileReader = new FileReader();
        return new Promise((resolve, reject) => {
            temporaryFileReader.onerror = () => {
                temporaryFileReader.abort();
                reject(new DOMException("Problem parsing input file."));
            };
            temporaryFileReader.onload = () => {
                resolve(temporaryFileReader.result);
            };
            temporaryFileReader.readAsArrayBuffer(inputFile);
        });
    }

    private _showDialog = (): void => {
        this.setState({ hideDialog: false });
      };
    
      private _closeDialog = (): void => {
        this.setState({ hideDialog: true });
      };
    



    public render() {
       
        let { imagePreviewUrl } = this.state;
        let imagePreview = null;

        if (imagePreviewUrl) {
            imagePreview = (<Image src={imagePreviewUrl} />);
        }


        return (

            <div className={styles.attachmentContainer}>
                {
                    !imagePreviewUrl ?
                        <div className={styles.attachmentComponent}>
                            <div className={styles.attachmentDescription}>
                                <h3>{strings.AttachmentHeadingLabelOne}</h3>
                                <p>.jpg, .gif, .png, .svg</p>
                                <h3>{strings.AttachmentHeadingLabelLegal}</h3>
                                <p>{strings.AttachmentHeadingLabelDesc} &nbsp; 
                                    <a onClick={this._showDialog}>{strings.AttachmentHeadingLabelDescLink}</a>
                                </p>
                                <input accept="image/gif, image/svg, image/png, image/jpeg" style={{ display: "none" }} ref={(r) => { this.myref = r }} type='file' onChange={(e) => this._handleImageChange(e)} />
                                <a onClick={this.handleFileSelect}>{strings.ImageButton}</a>
                                <Icon iconName='CirclePlus' className={[styles.CirclePlusIcon, "ms-Icon"].join(' ')} />
                            </div>
                        </div>
                        :
                        <div className={styles.imgPreview}>
                            {imagePreview}
                            <Icon iconName='Cancel' className={[styles.removeCloseIcon, "ms-Icon"].join(' ')} />
                            <PrimaryButton
                                data-automation-id="RemoveButton"
                                allowDisabledFocus={true}
                                text={strings.RemoveButtonLabel}
                                onClick={this._handleRemoveImage} />
                            <span className={styles.replaceButtonImg}></span>
                            <input accept="image/gif, image/svg, image/png, image/jpeg" style={{ display: "none" }} ref={(r) => { this.myref = r }} type='file' onChange={(e) => this._handleImageChange(e)} />
                            <PrimaryButton
                                data-automation-id="ReplaceButton"
                                text={strings.ReplaceButtonLabel}
                                allowDisabledFocus={true}
                                onClick={this.handleFileSelect} />
                                   
                        </div>
                }
                <Dialog
                    hidden={this.state.hideDialog}
                    onDismiss={this._closeDialog}
                    className={styles.termConditionmodal}
                    containerClassName={'ms-dialogMainOverride ' + styles.termConditionmodal}
                    dialogContentProps={{
                        type: DialogType.normal,
                        title: strings.AttachmentTermsConditionTitleText,
                        isMultiline:true,
                        subText: strings.AttachmentTermsConditionText
                    }}
                    modalProps={{
                        titleAriaId: "test",
                        subtitleAriaId: "this._subTextId",
                        isBlocking: true,
                        styles: { 
                            main: { maxWidth: 792, maxHeight: 617 },
                        },
                        onDismissed: this._closeDialog

                    }}>
                    <DialogFooter>
                    <PrimaryButton 
                    onClick={this._closeDialog} 
                    allowDisabledFocus={true} 
                    text="Close"> 
                            <Icon iconName="ChromeClose" className="ms-IconExample" />
                    </PrimaryButton>        
                    </DialogFooter>
                </Dialog> 
            </div>
        )
    }
}`

Create another file in same place call SPAttachmentFormFieldEdit.tsx

`import * as React from 'react';
import { ISPFormFieldProps } from './SPFormField';
import { AttachmentRender } from './AttachmentRender';

const SPAttachmentFormFieldEdit: React.SFC<ISPFormFieldProps> = (props) => {
    if (props.fieldSchema.FieldType !== 'Attachment') {
        return <AttachmentRender fieldProps={props} />
    }
};

export default SPAttachmentFormFieldEdit;`

Refer this file under spformField.tsx

import SPAttachmentFormFieldEdit from './SPAttachmentFormFieldEdit'

Add following line under: EditFieldTypeMappings
  Attachments: SPAttachmentFormFieldEdit,


You will be able to achieve attachment functionality.

**Comment by Fnu-Avi** [comment]
@jindalv10 I used the code and changes to the files necessary. I'm able to upload the file but my files are not saved to SharePoint list. Any thoughts on it?

**Comment by jindalv10** [comment]
@Fnu-Avi Can you try to debug the code and let me know what errors are you getting on your end. 

Please remove following lines from code. 

Attachments: { component: SPAttachmentFormFieldEdit } in const DisplayFieldTypeMappings

I haven't tested this with display form yet.

**Comment by hugoabernier** [comment]
I'll mark this issue as closed as there hasn't been any activity for a while.

Feel free to reopen it if you need more help with it.

@wrvishnu, please take the time to fill the issue template next time, as it makes it easier for everyone to help with these issues.
