### ISSUE TITLE
Is REACT the only supported method of using People Pickers fields?

### ISSUE THREAD

**Issue by vaderj** [SharePoint/sp-dev-fx-webparts#1060]
## Category

- [x ] Question
- [ ] Bug
- [] Enhancement

## Authors

> Because of the way this repository is setup, samples authors do not get a notification when you create an issue. *It makes it less likely for you to get your issue resolved or to get help*. For the section above **@mention any author of the sample**. Authors' github handle can be found on the main sample documentation page, under the "solution" section. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Expected or Desired Behavior

I would like to be able to build a SPFX web part utilizing a People Picker field

## Observed Behavior

I am not able to find any methods of implementing a People Picker field in a SPFX (JS) web part WITHOUT committing the whole project to React

## Steps to Reproduce

Attempt to implement a People Picker web part

**Comment by Harshagracy** [comment]
Yes, you can do it using JS. Check the client side people picker. 
https://www.c-sharpcorner.com/blogs/client-side-people-picker-in-sharepoint-2013

**Comment by hugoabernier** [comment]
Hey @vaderj , I hope that @Harshagracy 's answer helped you?

I'll mark this issue as closed. Feel free to re-open it if you need more help.

Thanks @Harshagracy for your help with this! #SIC
