### ISSUE TITLE
How we can configure and Run the code

### ISSUE THREAD

**Issue by spo365** [SharePoint/sp-dev-fx-webparts#1071]
Hi All,

I new to SPFX can you please share how we can configure and run **react-search** sample code in local environment.
My helloword webpart is running fine.
 
![image](https://user-images.githubusercontent.com/5062256/69208860-3c768400-0ba9-11ea-8829-53c8b85e5820.png)

**Comment by sudharsank** [comment]
Try using this link below which is the latest version of the search web part using the latest spfx version.
https://github.com/microsoft-search/pnp-modern-search/tree/3.10.0

**Comment by hugoabernier** [comment]
Hey @spo365  I hope @sudharsank 's answer helped you getting the web part working.

I'll mark the issue as closed, but feel free to re-open it if you need more help.

Thanks @sudharsank for your help with this.
