### ISSUE TITLE
How to get the list of all choice field values from SharePoint list

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/sp-dev-fx-webparts#1072]
Hi Team,

I am working in SPFx development project. In that, I want to get all the choice field values from the specific list. I am using the below code to get the choice field value for the given column in the specific list. How to get all the choice field column values spHttpClient approach?

`public async getListFieldChoices<T>(
    listTitle: string,
    fieldName: string
  ): Promise<T> {
    const queryString = `?$filter=EntityPropertyName eq '${fieldName}'`;
    const listUrl = `${this.currentWebUrl}/_api/web/lists/GetByTitle('${listTitle}')`;
    const queryUrl = listUrl + `/fields` + queryString;
    const response = await this.spHttpClient.get(
      queryUrl,
      SPHttpClient.configurations.v1
    );
    const json = await response.json();
    return Promise.resolve(json.value.length > 0 ? json.value[0].Choices : []);
  }`

Please help me on this.

**Comment by hugoabernier** [comment]
Hey @spvjebaraj I hope you got this issue resolved since you submitted it.

Typically, you'd want to use `RenderListData` or `RenderListDataAsStream` to get all the information you need to render a list.

I'll mark this issue as closed, but feel free to re-open it if you need more help with this.
