### ISSUE TITLE
React Calendar events are not working in IE

### ISSUE THREAD

**Issue by prathimapilli** [SharePoint/sp-dev-fx-webparts#1073]
Hi team,

React Calendar events are not working in IE. It is working fine in chrome.Am I missing anything?

Please let me know if anybody has idea.

Thanks

**Comment by gauti786** [comment]
install polyfills for foreach, it should work fine

**Comment by prathimapilli** [comment]
> install polyfills for foreach

Hi I installed polyfills using below command still getting the issue. kindly suggest if I am missing anything.

Thanks

**Comment by gauti786** [comment]
install missing polyfills for IE as well.

> > install polyfills for foreach
> 
> Hi I installed polyfills using below command still getting the issue. kindly suggest if I am missing anything.
> 
> Thanks

**Comment by prathimapilli** [comment]
> install missing polyfills for IE as well.
> 
> > > install polyfills for foreach
> > 
> > 
> > Hi I installed polyfills using below command still getting the issue. kindly suggest if I am missing anything.
> > Thanks


It is working.. 

thanks,
