### ISSUE TITLE
React-Chartcontrol web part doesn't appear inside "Add a web part"section in modern sites

### ISSUE THREAD

**Issue by MrFearLess98** [SharePoint/sp-dev-fx-webparts#1074]
Hello everyone!

## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Today, I've added to my office 365 tenant the [react-chartcontrol](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-chartcontrol) web part created by @VesaJuvonen ,
 I got no errors in the package solution but when i tried to check for this web part in the add web part section, i was not able to find it in my modern site even on the developer site.

I checked back the app in my cataloge i get the following [take a look here](https://i.imgur.com/4nBWkqV.png). 

So what would be the issue for this app not displaying to sites? Maybe because it's not deployed on tenant ? If yes what would be the solution ?

Any help will be greatly appreciated.
Thank you!

**Comment by yborghmans** [comment]
Hi @MrFearLess98,
Did yo install the app on that specific site?
Because the app package is not tenant wide deployed (as I can notice in your printscreen)

So simply:
1. Go to the site where you want to use the webpart
2. Gear icon (top right) 
3. Add a app
4. Install react-chartcontrol

**Comment by MrFearLess98** [comment]
Hi @yborghmans 
No,i have just imported the app to my app catalog without implementing the steps you mentioned above. After i have followed your steps the web part finally worked like charm.
Thank you very much for your support and have good day!
