### ISSUE TITLE
SPFX Webpart: Out of stack space issue

### ISSUE THREAD

**Issue by gvijh** [SharePoint/sp-dev-fx-webparts#1076]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Expected or Desired Behavior

SPFX V1.8.1 web part works fine in IE11.

## Observed Behavior
In IE11 spfx webpart is not loading. It shows below error message in console. I am able to  reproduce the same issue with plain vanilla (no custom code) SPFX webpart as well.

The issue is only in IE11. It works fine in Edge & Chrome

![SimpleWebPart_ErrorConsole](https://user-images.githubusercontent.com/41356327/69695315-08aed780-1130-11ea-92a6-c7535d68f12d.jpg)

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@gvijh I hope that this issue was resolved by updating to the latest version of SPFx?

I'll mark this issue as closed, but feel free to re-open it if you need more help with this.
