### ISSUE TITLE
 SPSecurityGrid - Drill down/filter people/groups displayed based on permission level.

### ISSUE THREAD

**Issue by mikezimm** [SharePoint/sp-dev-fx-webparts#1081]
## Category
- [x] Enhancement

## Authors
@russgove 

## Expected or Desired Behavior
Now that we have color coding on SPSecurityGrid working, I was thinking it would be helpful to have an easy way for the end user to quickly change/drill down on who has specific permissions.

For instance, in the attached screenshot you see a lot of columns with empty permissions.
The idea would be a simple button to quickly toggle through either different groups of permissions or drill down to a specific level... not necessarily going to that giant dropdown list of all permission levels (which would confuse a lot of end users) but maybe only switch to the ones that we have color coded.

The finished result would be when I click, it would change from the first screenshot to the second one only showing who as specific permissions and hiding all the extra columns.

**Before drill down**
![image](https://user-images.githubusercontent.com/49648086/70271698-e68f0800-1774-11ea-8216-1e53d434f7d4.png)

**After drill down click**
![image](https://user-images.githubusercontent.com/49648086/70271834-3372de80-1775-11ea-974e-4610a3490e67.png)

**Comment by russgove** [comment]
Hey mike, I like the icons. 

Yeah , I was thinkin of adding something to filter out the ones with no permission.

Take a look at my last build. It has a legend up top. I'm thinking maybe they click the icon in the legend to filter.

**Comment by russgove** [comment]
PS, is that Pink Floyd on your tenant?

**Comment by mikezimm** [comment]
I like the click on legend idea.  Would it behave like a pivot where it just shows one permission level at a time or would it be a compounding filter where you can toggle each one on individually like you did with showing specific groups, people and lists?

Maybe a compromise between ultimate flexibility and less complexity would be to filter the selected level and "higher".  By that I mean if I click on Edit, it also shows Full Control because it essentially has Edit rights as well.  That might make more sense.

Quick other question on the color coding, I presume it picks the first one in order that the colors are added in the web part props correct?  So you want to put Full Control before Read or someone with Full Control would show read?

Oh and no that's not Pink Floyd :)  My dev partner created an account Pink Fluffy Unicorns.

Thanks again for the attempts!

**Comment by russgove** [comment]
Oh man, i like your ideas, we can do a compound filter.

**Comment by russgove** [comment]
Hey mike , 
can you scan through the icons at https://uifabricicons.azurewebsites.net/ and pick a hundred or so that you think make sense in the grid?
Thanks
Russell

**Comment by mikezimm** [comment]
A hundred?  Do we have to use separate import statements only for the ones we want to trim bundle size?  I'm a newbie so that's a real question :)

**Comment by russgove** [comment]
No, I just need an array of strings of the icon names we want to include. I cannot do an import to get them all. 

OK, just pushed the 'Freindly names'
Now just need to set up the 'schemes'. Like you were saying, not sure where to store those. For now, will just store a json file in the root Site Assets to hold defaults/ . so if someone adds  the webpart it  will 'just work' using the defaults

**Comment by mikezimm** [comment]
Here are the ones I used in [my current iteration](https://github.com/mikezimm/sp-dev-fx-webparts/blob/dev/samples/react-securitygrid/src/webparts/spSecurity/colors/AvailablePermissionMapping.ts)

BUT to be honest, **I would rather have it be a plain text field** with a link to the place to search Icons vs a dropdown of choices.  If you are going to not use the easy choices (and the idea is to have a good selection to cover all common scenarios out of the box with an easy way for a developer to add custom pre-built scenarios), then you should know enough to type in the  proper name of an icon.

Plus in the unlikely event that one of us typed the IconName wrong in the file, you can still get it :)

But take a look at my pull request... I broke it up into component files so you have a file.  If you want, we could even have a quick chat on Teams or Skype.

But here are the ones I used:
FavoriteStarFill
EditSolid12
RedEye
TriangleSolid
Design
LockSolid

If you have to add more, maybe add:
Edit
LaptopSecure
SecurityGroup
eDiscovery
People
Contact
Error
Admin
IncidentTriangle
Emoji2
Sad
PinSolid12
UserWarning
Cat
AuthenticationApp


Regards
Mike

**Comment by mikezimm** [comment]
@russgove , also note that when I did my pull request I added a way to change the font size of the icon in the JSON file.  I found that some of them were just easier to read when a little bigger... especially if there was a lighter or lower contrast color.  This also makes it a lot easier to adjust even if you do not put it in the Prop Pane itself.

**Comment by russgove** [comment]
Hey, I just added aq toggle to 'Show only users with permission."  
![image](https://user-images.githubusercontent.com/2412956/70644312-c1851400-1c10-11ea-9aa7-9965f4cfbd72.png)



Not sure that we need the drilldown from the menu now.

Would be great to have a quick chat. I'm at russell.gove@tronox.com

**Comment by russgove** [comment]
Hey, I  also made it so yo ucan now just type in the name of a fabric icon instead of selecting one from the dropdown.

Now I just want to load defaullt settings from somewhere, (probably a json file in the top level sites site asstes library) so that if you  add the webpart anywhere on your tenant, by default it will look the same.

After that,, good to go!

**Comment by hugoabernier** [comment]
Hey @mikezimm  thanks for collaborating with @russgove to make this already awesome sample even better.

I'll go ahead and mark this issue as closed since @russgove submitted his PR. Feel free to re-open it if we still need to do more stuff.
