### ISSUE TITLE
Items Grouping Function

### ISSUE THREAD

**Issue by Cloudmaister** [SharePoint/sp-dev-fx-webparts#1089]
Can we add an items grouped by field function?  This would be another content query feature from the old content query webpart.

Thanks!!!!

**Comment by spplante** [comment]
@Cloudmaister grouping can be done using your own handlebar helper, see #1029 for an example.

**Comment by hugoabernier** [comment]
@Cloudmaister I hope that @spplante 's answer helped you solve this?

I'll mark this as closed, but feel free to re-open it if you need more help.

Thanks @spplante for your help!
