### ISSUE TITLE
Queries in React OfficeGraph example return nothing

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-fx-webparts#109]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The queries in the react-officegraph example don't seem to return anything (anymore). Is something changed in the implementation of the queries on SP level perhaps?

**Comment by waldekmastykarz** [comment]
Are you sure that the tenant that you are using has valid data that could be returned by the Office Graph?

**Comment by NickSevens** [comment]
@waldekmastykarz I believe so? Browsing to
```
{siteUrl}/_api/search/query?querytext='*'&properties='GraphQuery:actor(me\\,or(action\\:1001\\,action\\:1003)),GraphRankingModel:{"features"\\:[{"function"\\:"EdgeTime"}]}'&selectproperties='Author,AuthorOwsUser,DocId,DocumentPreviewMetadata,Edges,EditorOwsUser,FileExtension,FileType,HitHighlightedProperties,HitHighlightedSummary,LastModifiedTime,LikeCountLifetime,ListID,ListItemID,OriginalPath,Path,Rank,SPWebUrl,SecondaryFileExtension,ServerRedirectedURL,SiteTitle,Title,ViewCountLifetime,siteID,uniqueID,webID'&rowlimit=10&ClientType='MyRecentDocuments'&RankingModelId='0c77ded8-c3ef-466d-929d-905670ea1d72'
```
returns me
```
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-1, Microsoft.Office.Server.Search.REST.SearchServiceException</m:code>
<m:message xml:lang="en-US">We didn't understand your search terms. Make sure they're using proper syntax.</m:message>
</m:error>
```

The query `{siteUrl}/_api/search/query?Querytext='*'&Properties='GraphQuery:ACTOR(ME)'` DOES return PrimaryResults, including _edges_ in the result set. Adding `or(action:1001,action:1003)` to it makes the query fail again...

**Comment by wobba** [comment]
@NickSevens Try crafting the REST call using the sp query tool..and use that URL.

**Comment by waldekmastykarz** [comment]
@NickSevens when in browser could you try using a single \ instead of \\?

**Comment by NickSevens** [comment]
Thank you @waldekmastykarz that worked indeed!
