### ISSUE TITLE
Modern Script editor doesnt appear in the webpart.

### ISSUE THREAD

**Issue by flintuser** [SharePoint/sp-dev-fx-webparts#1090]
Hi,

I have the App in Appcatalogs site, and the app has been added to the Site contents as well.

But no luck, i dont see the webpart appear.

Not sure, what might have gone wrong. Can somebody please help?

Placing the screenshots below:
Appcatalog:
![image](https://user-images.githubusercontent.com/41613682/71151221-426b8d80-2259-11ea-9f91-b7f7a5f72855.png)

Site contents:
![image](https://user-images.githubusercontent.com/41613682/71151305-734bc280-2259-11ea-9442-d302e15a3476.png)

Webpart bucket:
![image](https://user-images.githubusercontent.com/41613682/71151619-2f0cf200-225a-11ea-8af9-1ef86b3d8737.png)

Thanks in advance.

**Comment by wobba** [comment]
Is this a modern site? If so, you have two options. Enable scripting on the site collection, or re-build the web part to be allowed on any site as per the readme file https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites

Let me know if either of these apply.

**Comment by kashiel** [comment]
Hi @flintuser,

I have a question, what version npm(node.js), gulp,  did you use??, I will go crazy, because I can made the package but when i upload to my App catalog, it show me an id error correlation.

**Comment by wobba** [comment]
I believe the latest version should build with both node 8 and 10. It builds at least just fine with node 10 and SPFx v1.9.1 installed. What's your environment @kashiel?

**Comment by elpinto007** [comment]
I am having the same issue as well. I enabled scripting on my tenant, but I also followed the steps in the readme and set requiresCustomScript as false. But the app wont show up on a site collection for me for some reason. 
I just did some testing and it seems the script editor works for modern sites in my tenant, but for some reason, its not showing up on the one site I actually need it on.
Any ideas why the web part would not show in the list on one site collection?

**Comment by wobba** [comment]
If you set requireCustomScript to false and add the app to the site, it should appear. Try another part and verify. Did you deploy a version without flipping the flag first?

**Comment by elpinto007** [comment]
Yup, I definitely set that flag to false and added it to the site. I also tried to add the script web part to a subsite (where it worked!!). I am trying to remove it once again and re-add it.

**Comment by hugoabernier** [comment]
Hey @flintuser did you ever solve this issue? Did @wobba 's answer help you?

If you solve it, we'd love to hear how you did.

**Comment by Sarvesh700** [comment]
I'm facing the same issue and only happening for one site collection. Can you suggest something?

**Comment by PathToSharePoint** [comment]
If only one Site Collection, see @wobba 's suggestion above. It's likely that scripting is disabled.

**Comment by DragonMamaZ** [comment]
I had the same issue.  I ran this script that I found on sharepointdiary.com, and it worked for me.

#Config Parameters
$AdminSiteURL="https://sitename-admin.sharepoint.com"
$SiteURL="https://sitename.sharepoint.com"   

#Connect to SharePoint Online Tenant Admin portal
Connect-SPOService -URL $AdminSiteURL   

#sharepoint online enable custom scripts powershell - Disable DenyAddAndCustomizePages Flag
Set-SPOSite $SiteURL -DenyAddAndCustomizePages $False

**Comment by wobba** [comment]
@DragonMamaZ beware of possible security implications by doing this and allowing custom script on sites.

**Comment by Kalpesh2** [comment]
Hi - anyone got this working? I've have got it to work on 1 tenant but not another with the same settings. Any help?

**Comment by Kalpesh2** [comment]
For me changing the settings of external sharing to 'Only people in your Organisation' worked after hours of troubleshooting.

**Comment by eshratanjum64** [comment]
I am facing the same issue. **@DragonMamaZ** The way you suggested also didn't work for me. Can anybody help me on this please

**Comment by wobba** [comment]
@eshratanjum64 I suggest you read the readme, especially https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor/README.md#deploy-to-non-script-sites--modern-team-sites to ease deployment. If you really need this web part - as it's a security concern to deploy (like the classic one was).
