### ISSUE TITLE
spfx webpart added to appcatalog, installed to site. unable to find in webparts options on editing the page

### ISSUE THREAD

**Issue by dhheeraj** [SharePoint/sp-dev-fx-webparts#1092]
using latest version of spfx and react.
package build successfully, bundled successfully (--ship), packaged-succesfully(--ship).
sppkg packages added to appcatalog and app installed to site collection.
on edit page unable to get the webparts to add on page.

**Comment by sudharsank** [comment]
Hi,

Once the package is deployed to the App Catalog, you have to add the app to the site and then you can try adding the web part to the page.

**Comment by hugoabernier** [comment]
Hi @dhheeraj ! Did @sudharsank 's answer help you solve this issue?

I'll mark this as closed, but by all means feel free to re-open the issue if you need any more help with this.

Thanks @sudharsank for your help!
