### ISSUE TITLE
_api/search/suggest?querytext='*' returns empty result using azure AD authention

### ISSUE THREAD

**Issue by pravin080317** [SharePoint/sp-dev-fx-webparts#1099]
Iam calling the search api "_api/search/suggest?querytext='*" using httpclient in azure functions. Authentication is done via azure ad application. Application permissions sites.fullcontrol is provided. But when ever i tried to call this suggest api, it returns empty results.

i can able to retreive the results of suggest api using username and password but using the azure ad app auth it gives the empty results.

whether we can able to call this suggest api using application permissions set in azure ad ? kinldy let me know if there are any alternatives

**Comment by wobba** [comment]
Closing as per https://github.com/SharePoint/sp-dev-docs/issues/5068
