### ISSUE TITLE
SharePoint Framework - SPFX Webpart is not visible under the root sitecollection

### ISSUE THREAD

**Issue by mhijazi** [SharePoint/sp-dev-fx-webparts#1103]
Hey all,

I have SharePoint 2019 (on-prem) and one web app; one root site collection for Intranet Portal and other one /sites/apps for the app catalog, where I deployed react-script-editor (Modern Script Editor).

The issue is that the webpart is only visible under the apps site collection but NOT under the root site collection.

Any help???

Thank you.

**Comment by sudharsank** [comment]
Have you added the app to the root site collection for Intranet Portal where you need it?

**Comment by hugoabernier** [comment]
@mhijazi I hope that @sudharsank 's answer helped you solve this issue.

I'll go ahead and mark this as closed, but if you still need help with this, feel free to re-open the issue.

Thanks @sudharsank for your help!
