### ISSUE TITLE
open the .eml file in outlook  client directly without downloading it in the browser

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-fx-webparts#1104]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Question:
Is it possible to open the .eml file in outlook directly without downloading it in the browser?

I have a requirement to create spfx list view extension. The user will select multiple documents and will click the extension button. The extension should open outlook client with the selected documents as attachment. I have created eml file and attached attachments using base64 encoding. But currently, I am only able to download the eml file, and not able to open it directly with outlook client. 

Other approaches which I am not using and their reason: 

- **mailto** : I cannot attach file using mailto. So this option is not used.
- **ActiveX control** : It works only in IE. for some reason, it didn't work in IE also today. 

Article to refer for the code - https://blogs.perficient.com/2016/10/17/create-a-microsoft-outlook-email-using-javascript/

Please let me know programmatically how I can achieve this?(through Javascript/ typescript/React JS) 

#spfx, #spfx-webparts

**Comment by oumaima1234** [comment]
Hello, 
@Harshagracy did you find an answer please ? 
Thanks.

**Comment by Harshagracy** [comment]
@olegrumiancev What is the issue you are facing? I solved my issue through a different approach.

**Comment by Harshagracy** [comment]
Closing the issue as the file is saved using MS Flow.

**Comment by underwater** [comment]
Hello

> @olegrumiancev What is the issue you are facing? I solved my issue through a different approach.

Hello, may I ask what your alternative approach was ?
