### ISSUE TITLE
Group events 1 day out of sync (react-graph-calendar)

### ISSUE THREAD

**Issue by RWilliams1997** [SharePoint/sp-dev-fx-webparts#1108]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@sebastienlevert 
@VesaJuvonen 

## Expected or Desired Behavior
(react-graph-calendar)
The calendar whether in WebPart format or in Teams should pull through group events and re-present them to the viewer showing the correct start and end dates.

## Observed Behavior

The calendar in both Teams and SharePoint shows all events as a day later than they are when they were created. If I add an event to the group that is scheduled for all day on the 10th January (10/01/2020 at 00:00 to 11/01/2020 at 00:00), it will display in the webpart or team app on the 11th January (11/01/2020 at 00:00 to 12/01/2020 at 00:00).

## Steps to Reproduce

I have added the Teams app and SharePoint WebPart to various teams, both recently created and 1 Year + old teams and it does the same on all of them. I have checked the timezones on the teams and my client and everything is UK/London as the same as my Outlook client. I have also tried cloning a fresh version and re-installing it to my app catalog however it still does the same thing.

If I add Microsoft's own Group Calendar web part, the events show the correct date and times. Also, if I use the Microsoft Graph explorer and pull the events for that group it shows them with the correct timings so it doesn't appear to be anything to do with the groups themselves.

**Comment by sebastienlevert** [comment]
We might be in the middle of a fun Timezone hunt! Can you add screenshots of both Calendars (the Teams app one and the Outlook one). Here I get this :

![image](https://user-images.githubusercontent.com/7620955/72095730-09b65580-32e7-11ea-95ab-2f20a07dc15f.png)

![image](https://user-images.githubusercontent.com/7620955/72095754-176bdb00-32e7-11ea-881d-7474d8c5d50f.png)

**Comment by RWilliams1997** [comment]
Certainly, here they are next to eachother:

[cid:image002.jpg@01D5CB12.254D7220]

**Comment by RWilliams1997** [comment]
It seems to also be assuming that the event is all day and then adding a day onto it. I made an event that was only for 1:30hrs and in Teams it says the event is all day.

[cid:image003.jpg@01D5CB12.E6535B10]

From: Rhys Williams
Sent: 14 January 2020 19:38
To: SharePoint/sp-dev-fx-webparts <reply@reply.github.com>; SharePoint/sp-dev-fx-webparts <sp-dev-fx-webparts@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [SharePoint/sp-dev-fx-webparts] Group events 1 day out of sync (react-graph-calendar) (#1108)

Certainly, here they are next to eachother:

[cid:image002.jpg@01D5CB12.E64D1980]

**Comment by RWilliams1997** [comment]
Certainly, here they are next to eachother:
![Requested image](https://i.gyazo.com/a89da5f8db86fabc9445d961689a23d2.png
)

It seems to also be assuming that the event is all day and then adding a day onto it. I made an event that was only for 1:30hrs and in Teams it says the event is all day.
![Requested image](https://i.gyazo.com/677ad6ff382bec368588ceaa7a7a293d.png
)

**Comment by RWilliams1997** [comment]
UPDATE:
I pushed the latest release of the webpart out and that appears to have fixed the issue for events that aren't all day, however ones that are listed as all day are still a day out.

![Image](https://i.gyazo.com/62044a41672dc33cbead4c813cf91153.png)

**Comment by hugoabernier** [comment]
@RWilliams1997 if you don't mind, I'll mark this issue as closed. If there are more issues regarding this, please open a new issue and we see if we can get more folks from the community to help.
