### ISSUE TITLE
Events created via Microsoft Flow to calendar is represented 1 hour behind and color of this event is constant.

### ISSUE THREAD

**Issue by yarrahdevi** [SharePoint/sp-dev-fx-webparts#1109]
#974  Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I expect to see all past and new events created via Microsoft Flow represented properly on the calendar.

## Observed Behavior

1. Events represented on the calendar via Microsoft Flow displays 1 hour later that applied for. For example, if I request personal time off from 12pm - 4pm, the event registered on the calendar displays the time as 13:00H - 17:00H. If I were to add an event directly to the calendar via the property panel, the event registers correctly. However, we are not allowing this functionality, as our only method of adding events to the calendar is via Microsoft Flow.

2. Items created by Microsoft Flow that are represented on the calendar displays in the color of blue and does not randomize. If I were to add an event directly to the calendar via the property panel, and I refresh the page, the event color randomizes. In my previous calendar, I had specific colors to represent each type of event.

**Comment by hugoabernier** [comment]
@yarrahdevi it is unclear which sample code you're referring to. Do you mind giving us more info so that we can try to see if the original author can help us?
