### ISSUE TITLE
react-list-form DateTime Issue

### ISSUE THREAD

**Issue by Fnu-Avi** [SharePoint/sp-dev-fx-webparts#1115]
##  Category

- [x] Question
- [ ] Bug
- [x] Enhancement

While working on this project, I setup this with the environment. I've a SharePoint Site with the list named _Events_ and I try to fill up the form for adding events to the list. Everything is working as expected except on field.

## Expected or Desired Behavior

The expected behavior should be that it asks for both date and time as the type of the field in the list is 'Date and Time'.

## Observed Behavior

I have various fields in the list and one of the field named _Start Time_ has a Type as 'Date and Time' and when I use the default form provided by SharePoint it gives me option for choosing both date and time for that field [can be seen in [pic1](https://imgur.com/a/Lgd8apZ)]. But, when I use react-list-form webpart for the same that field doesn't give me option to select time (it only provides me with the option to select date) [can be seen in [pic2a ](https://imgur.com/a/xXDevrr)-> [pic2b](https://imgur.com/a/viRuhRk)]. 

Thanks for your contribution! Sharing is caring.

**Comment by jindalv10** [comment]
@Fnu-Avi Unfortunately, at this time there is no Date And Time picker control exist in office-ui-fabric-react. 

You can see the see the list of controls here: https://developer.microsoft.com/en-us/fabric#/controls/web

**Comment by Fnu-Avi** [comment]
Thanks @jindalv10 for the reply. 

Is there any other way by which this functionality can be achieved. I researched and figured out that we could use some other datetime picker (e.g. [react-datetime-picker](https://github.com/wojtekmaj/react-datetime-picker) ). 

Do you think this can work for getting this functionality working.

**Comment by jindalv10** [comment]
@Fnu-Avi I haven't tested dateTime picker into react-list-form web part but you can go ahead and update DatePickerField.tsx file with npm package. 

Will try this npm package sometime this week and will update you.

FYI: 
You may able to achieve this functionality by using drop down control and values in options  attribute to complete this functionality for now. It all depends on your business model and requirements.

**Comment by Fnu-Avi** [comment]
@jindalv10 Looking forward to your update. Thanks.

**Comment by jindalv10** [comment]
@Fnu-Avi Sorry forgot to mention. You can try to use following sp-dev-fx-controls-react. This library has date and time picker control

https://sharepoint.github.io/sp-dev-fx-controls-react/controls/DateTimePicker/

**Comment by Fnu-Avi** [comment]
@jindalv10 I tried with both and was able to make just the front end changes (by making changes in the DateFormField.tsx file). 

I looked into other files (SPFieldDateEdit.tsx, SPFormField.tsx and ListForm.tsx), but didn't felt the need to make changes in them. 
Later when I tried to submit the form with the changes made only in DateFormField.tsx file; the form goes away and I see this error in console.

`backend.js:formatted:962 TypeError: Cannot set property 'props' of undefined
    at D (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at StyledIconBase (styled.tsx:61)
    at FormField (FormField.tsx:66)
    at Xl (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Ci (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Di (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Qa (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Ka (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Oo (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)
    at Po (sp-webpart-workbench-assembly_en-us_3ab584a511e3422b9d1b98c5480d60cd.js:21)`

Also, I looked into the developer window for the components and figured out the following:

- DateTimePicker: The props and state reflect the changes when date and time is changed.
- DateFormField: Shows the changes only in state; I don't see props (with value).
- SPFieldDateEdit: Here in props the value is set to [today].

Ideally in SPFieldDateEdit: the value should be set to the date selected and in DateFormField: props should have the value property.

What do you think on this? I think I'm very close to resolving the issue but propagating values from child component to parent component is troubling me (I believe). 

Can you please look into this..

**Comment by Fnu-Avi** [comment]
@jindalv10 Did you get a chance to look into this?
@wobba Can you also please look into this enhancement?

**Comment by wobba** [comment]
I recommend using https://sharepoint.github.io/sp-dev-fx-controls-react/controls/DateTimePicker/ and then handling the picked date in the `onChange` event.

As the webpart samples are samples, you can change the code to your liking, but there is no promise from the original author to extend the sample. If you extend it and improve it, we're happy to take PR's.

**Comment by Fnu-Avi** [comment]
Thanks @jindalv10 for the reply. It's working but not fully. Now, the data is being saved to the list. Unfortunately, the time which I select; sometimes it's saved accurately and the other times it takes 12:00 as the default time.

**Eg**: If I select 2/7/2019 as the date for both the start and end date; and I select start time as 10:00 AM and end time as 11:30 AM. 

It doesn't record the exact timings in the list; sometimes it takes what is provided as an input and other times it takes 12:00 PM and 12:30 PM.

**Comment by jindalv10** [comment]
@Fnu-Avi  Let me verify and get back to you on this.

**Comment by Fnu-Avi** [comment]
@jindalv10 Are you still working on this?

**Comment by jindalv10** [comment]
@Fnu-Avi I'm little busy in other work. But I think you can try to change props value and able to achieve that functionality. 

But if you need solution then you have to wait.
