### ISSUE TITLE
react-script-editor fails at npm install because of dependency on phantomjs, which is at end of life cycle.

### ISSUE THREAD

**Issue by ChrisMenning** [SharePoint/sp-dev-fx-webparts#1116]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@wobba @VesaJuvonen 

## Expected or Desired Behavior
Running "npm install" should install all dependencies so that I can then progress onto testing the build, and then ideally deploying it.

## Observed Behavior

After running "npm install", I get a number of warnings followed by the following errors.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.

Upon looking deeper into what phantomjs is, I've discovered that the project has been suspended.
https://github.com/ariya/phantomjs/issues/15344

## Steps to Reproduce

git clone https://github.com/SharePoint/sp-dev-fx-webparts.git
cd C:\dev\sp-dev-fx-webparts\samples\react-script-editor
npm install

**Comment by wobba** [comment]
It builds on SPFx v1.4.1. If you are targeting spo feel free up upgrade it and build, if that dep stops it from building.

What SPFx and node versions do you have installed and in what environment (mac,windows)?

**Comment by ChrisMenning** [comment]
I have Node 10 LTS installed. Had to downgrade to get through HelloWorld.
The SPFx installed is @microsoft/generator-sharepoint@1.10.0. And I'm using Windows 10.

To upgrade the project's SPFx framework, do I just update the version numbers for all of the SharePoint dependencies in the web part's package.json?

**Comment by wobba** [comment]
Not that easy :) Check out the o365 cli https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/

I'll try test rebuilding and see if I can reproduce your issue with 1.10.

**Comment by wobba** [comment]
This is what I get on phantom when I run `npm i` for phantom

![image](https://user-images.githubusercontent.com/51104/72705996-1f384480-3b5d-11ea-9f92-52cd620e9bf8.png)

which means I cannot really repro your issue, and it builds and run fine with SPFx v1.10 and node v10 on my Win10 box.

**Comment by ChrisMenning** [comment]
Using SPFx v1.10 and node v10 on Windows 10, I've tried the following.

I've deleted the project, then run a fresh clone.
git clone https://github.com/SharePoint/sp-dev-fx-webparts.git

Next, I go to the react-script-editor folder...
cd sp-dev-fx-webparts\samples\react-script-editor

Then...
npm install

Then I get the following warning twice in a row...
npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.

This is followed by hundreds of warnings like...
npm WARN tar ENOENT: no such file or directory,

This is followed by the following errors:
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:

Then there are some "verification failed" errors that include some hashes that I'm thinking I probably shouldn't post publicly.

**Comment by wobba** [comment]
That leaves us at "works on my machine". Could you try to build one of the other samples? For example react-events-aggregator which is also based off 1.4.1.

**Comment by ChrisMenning** [comment]
react-events-aggregator failed on npm install, also referencing PhantomJS.

Saving to C:\Users\*****\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wobba** [comment]
Then it's your environment somehow I believe. Can you create a new SPFx v1.10 project and have that build?

**Comment by ChrisMenning** [comment]
Yes! Following the instructions from the Microsoft Hello World tutorials
<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part>
works.

**Comment by wobba** [comment]
Can you try the workaround mentioned here: https://github.com/SharePoint/sp-dev-docs/issues/2092#issuecomment-399424162

**Comment by ChrisMenning** [comment]
As recommended in the workaround, I tried this:
npm install phantomjs-prebuilt@2.1.16 --ignore-scripts

This seems to resolve the issue with phantomjs, but then the next point of failure occurs on sp-polyfills@1.2.0.

I get this:
npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @microsoft/sp-polyfills@1.2.0 (sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg=) seems to be corrupted. Trying one more time.

Then that is followed by hundreds of "npm WARN tar ENOENT: no such file or directory," messages.
Then those are followed by:
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:

And then it mentions some sha1 hash mismatches.

**Comment by wobba** [comment]
You might just want to upgrade the solution using the o365 CLI to SPFx v1.10. Still weird that I have no issues.

**Comment by ChrisMenning** [comment]
I got o365 CLI installed. 
I successfully ran the upgrade report.

The very first command that the upgrade recommends is:
npm i -SE @microsoft/sp-core-library@1.10.0

This gives me the same warning about @microsoft/sp-polyfills@1.2.0 being corrupted followed by all those same failures.

From where I'm sitting, a fresh install of this project appears to have a very long list of dependencies on apparently corrupted files.

**Comment by wobba** [comment]
@waldekmastykarz any ideas?

**Comment by wobba** [comment]
Are you running via VPN or have some proxy running? https://github.com/npm/npm/issues/20925 Or a piehole, router with filtering etc. 

Would be interesting if you tried with yarn instead of npm as well.

**Comment by ChrisMenning** [comment]
I tried with Yarn and found "self signed certificate in certificate chain." One of the first things I did in setting everything up was ran gulp trust-dev-cert. From here, I suspect that our firewall is probably not trusting the self-signed dev cert. I'm going to talk with our network admin in the morning and see if I can get any further.

**Comment by Neonexus29** [comment]
Hi, I've got the same error when trying to do the npm install, and found this solution: removing the node_modules folder and the package-lock.json, and tryint again with npm-install. Hope it helps.

https://github.com/SharePoint/sp-dev-fx-webparts/issues/1027#issuecomment-550209837

Regards,
Iosune.

**Comment by wobba** [comment]
Removing package_lock might be the clue here indeed.

**Comment by ChrisMenning** [comment]
After having our network admin take a look at the firewall, I was able to successfully, build and deploy! I'm closing this issue since the root cause was our firewall configuration.
