### ISSUE TITLE
Site property bag

### ISSUE THREAD

**Issue by Noeky** [SharePoint/sp-dev-fx-webparts#1119]
Is it possible to access the site property bag (onPremis) with the react content by query webpart?

**Comment by jindalv10** [comment]
@Noeky Yes, you can call site property bag by using following REST API

https://<webApplication/sites/<siteurl>/_api/web/allProperties

Here is link that helps you to create pull property bag information:

https://www.c-sharpcorner.com/article/add-and-retrieve-property-bag-values-in-sharepoint-using-javascript-object-model/

I hope this answer your questions.

**Comment by hugoabernier** [comment]
@Noeky did @jindalv10 's answer help you?

I'll mark this issue as closed, but feel free to re-open it if you still need help.
