### ISSUE TITLE
react-pagecontributors [SPLoaderError.loadComponentError], Failed to load URL, There was a network problem

### ISSUE THREAD

**Issue by ChrisMenning** [SharePoint/sp-dev-fx-webparts#1123]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@SPParseError  

## Expected or Desired Behavior

Adding the webpart to a page should display the page's contributors.

## Observed Behavior

Installing dependencies, building, and deploying went fine. But after adding the webpart to a page, I get the following:

[SPLoaderError.loadComponentError]:
***Failed to load component "dfb5229a-c1c3-4e98-870b-c40dd6e4ec4b" (PageContributorsWebPart). Original error: ***Failed to load URL 'https://nwtcedu-admin.sharepoint.com/react-pagecontributors-pagecontributorsstrings_en-us_6ae41e2edb727df21538267edcd92249.js' for resource 'pageContributorsStrings' in component 'dfb5229a-c1c3-4e98-870b-c40dd6e4ec4b' (PageContributorsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://nwtcedu-admin.sharepoint.com/react-pagecontributors-pagecontributorsstrings_en-us_6ae41e2edb727df21538267edcd92249.js' for resource 'pageContributorsStrings' in component 'dfb5229a-c1c3-4e98-870b-c40dd6e4ec4b' (PageContributorsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_89883fcaad48b39834bf83396b7c7f40.js:4:53499)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_89883fcaad48b39834bf83396b7c7f40.js:20:119640)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_89883fcaad48b39834bf83396b7c7f40.js:20:129574)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_89883fcaad48b39834bf83396b7c7f40.js:20:125599)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_89883fcaad48b39834bf83396b7c7f40.js:20:115852)

## Steps to Reproduce

I have tried this by leaving the code as-is, and by replacing "Path to CDN" with the pass to my CDN that works on other web parts.

**Comment by ValerasNarbutas** [comment]
hey, maybe some options in the issues described here would help?
https://github.com/SharePoint/sp-dev-docs/issues/3871
https://github.com/SharePoint/sp-dev-gdpr-activity-hub/issues/51

**Comment by hugoabernier** [comment]
@ChrisMenning did @ValerasNarbutas 's suggestions help solve this issue?

I'll go ahead and mark this issue as closed, but feel free to re-open it if you're still experiencing issues. 

Otherwise, we'd love to hear how you solved the issue. #SharingIsCaring
