### ISSUE TITLE
react-script-editor deployed tenant-wide, but not showing up in available webparts on some modern sites.

### ISSUE THREAD

**Issue by ChrisMenning** [SharePoint/sp-dev-fx-webparts#1128]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@wobba 

## Expected or Desired Behavior

A webpart deployed to the whole tenant should be able to be used on any site on the tenant. 

## Observed Behavior

After successfully building and deploying react-script-editor tenant-wide, and after using it on some of my sites, for some reason it does not show up in my available webparts on new sites created today.

## Steps to Reproduce

Deploy react-script-editor to the whole tenant. 
Create a new modern experience site.
Edit the site. See if "Modern Script Editor" appears. In my case, it's not appearing.

**Comment by ChrisMenning** [comment]
After some googling I learned that I needed to run the following powershell command and it worked.
set-SPOsite <the site> -DenyAddAndCustomizePages 0

I don't know why I didn't need to do that on sites created before deploying the webpart but I do today. I'm going to change this from a bug to a question, because I'd still appreciate if someone could tell me the answer.

**Comment by wobba** [comment]
@ChrisMenning if you read the whole read.me for the web part, you see what security is by default added in the build configs, and also what has to be done if you want to change it.

Here's a direct link to the applicable section: https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-script-editor/README.md#deploy-to-non-script-sites--modern-team-sites
