### ISSUE TITLE
reactdirectory: npm build errors

### ISSUE THREAD

**Issue by webbrewer** [SharePoint/sp-dev-fx-webparts#1132]
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [X ] Question
- [ ] Bug
- [] Enhancement

## Authors

@hugoabernier 
## Expected or Desired Behavior

Solution will be built when running npm install

## Observed Behavior

Errors out:
46618 warn The package @types/react is included as both a dev and production dependency.
46619 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
46620 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
46621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
46621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
46621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
46621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
46622 verbose stack Error: node-sass@4.9.3 postinstall: `node scripts/build.js`
46622 verbose stack Exit status 1
46622 verbose stack     at EventEmitter.<anonymous> (C:\Users\i56743\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
46622 verbose stack     at EventEmitter.emit (events.js:210:5)
46622 verbose stack     at ChildProcess.<anonymous> (C:\Users\i56743\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
46622 verbose stack     at ChildProcess.emit (events.js:210:5)
46622 verbose stack     at maybeClose (internal/child_process.js:1021:16)
46622 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
46623 verbose pkgid node-sass@4.9.3
46624 verbose cwd C:\Users\i56743\Documents\GitHub\sp-dev-fx-webparts-master-new\sp-dev-fx-webparts-master\samples\react-directory
46625 verbose Windows_NT 10.0.15063
46626 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i56743\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
46627 verbose node v12.13.1
46628 verbose npm  v6.9.2
46629 error code ELIFECYCLE
46630 error errno 1

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by webbrewer** [comment]
Somehow I had ended up with node 12x  so downgraded to node 10.1x and though it still throws an stderr error, it builds the solution.
We can close this.

**Comment by PrasadKasireddy** [comment]
The current supported LTS version of NodeJS for the SharePoint Framework is Node.js v8.x and Node.js v10.x. Notice that 9.x, 11.x or 12.x versions are currently not supported with SharePoint Framework development.
