### ISSUE TITLE
React-Calendar gulp build --ship Fails

### ISSUE THREAD

**Issue by donshults** [SharePoint/sp-dev-fx-webparts#1134]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Authors
João Mendes

## Expected or Desired Behavior
**Sample: \samples\react-calendar**
Sample should perform the gulp build --ship without error

Standard gulp build is successful and running the Webpart in a O365 Dev Clients works. But attempting to package the Webpart fails due to this error.
Node Version: 10.19.0

## Observed Behavior
Currently is reporting the following error:
**src/webparts/calendar/components/Calendar.module.scss
 4:1  ×  Unexpected unknown pseudo-class selector ":export"   selector-pseudo-class-no-unknown
 5:3  ×  Expected "themeDark" to be "themedark"               property-case
 5:3  ×  Unexpected unknown property "themeDark"              property-no-unknown**
...
**The build failed because a task wrote output to stderr.
Exiting with exit code: 1**

## Steps to Reproduce
 - `npm install`
  - `gulp build`
  - `gulp bundle --ship`

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by donshults** [comment]
Quick Screen Capture of Error Reported:
![image](https://user-images.githubusercontent.com/4684182/74075157-f53caa00-49c5-11ea-9ac0-75ac5b2b5ee4.png)

**Comment by KaushalKhamar** [comment]
Is this error lead to error in packaging webpart solution?

**Comment by donshults** [comment]
Yes the build does not complete.
