### ISSUE TITLE
React script editor

### ISSUE THREAD

**Issue by sheiknaveed87** [SharePoint/sp-dev-fx-webparts#1136]
@wobba hi,
I cannot add the script editor package to appcatalo in sharepoint online modern page. I am getting below error.
There were errors when validating the App manifest.: Xml Validation Exception: 'The 'Name' attribute is invalid - The value 'Modern Script Editor web part by @mikaelsvenson' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/2012/app/manifest:NameDefinition' - The Pattern constraint failed.' on line '1', position '110'.

Please help me to resolve this issue. Also it would be really grateful if you can provide steps to solve this.

**Comment by elpinto007** [comment]
I just resolved this issue. There is an '@' character in the Solution name. Remove the '@' from package-solution.json file and you should be good to go.

**Comment by sheiknaveed** [comment]
Thanks, now I am able to add the package but after adding the package to the site. It doest not show

**Comment by neshan02** [comment]
As said by @elpinto007  the issue get resolve and its work nicely.
Thank you

**Comment by sheiknaveed** [comment]
Yes. I just need to enable custom script to display in Webpart browser.

**Comment by wobba** [comment]
Fixed the package name - thank you for bringing this up @elpinto007 👍
