### ISSUE TITLE
Scripteditor.tsx (not working correctly)

### ISSUE THREAD

**Issue by Slurbisaur** [SharePoint/sp-dev-fx-webparts#1137]
Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I added the Screenshots of my Problem down below. In the Scriptseditor.tsx there seem to be 2 missing attributes for the super class constructor and I don't know why and the second error is with the onChanged there seems to be no connection to IntrinsicAttributes? I actually would like to understand how this code works, cause I am very much learning it.

![Screenshot (16)](https://user-images.githubusercontent.com/60918994/74232693-9d55ba00-4cc9-11ea-94de-437b53746f3e.png)
![Screenshot (17)](https://user-images.githubusercontent.com/60918994/74232699-9f1f7d80-4cc9-11ea-9ace-aaa9b3cccf2a.png)

**Comment by hugoabernier** [comment]
@Slurbisaur there was a recent PR which addresses this issue.

I'll go ahead and close this issue, but if you still experience problems after downloading the latest version of the web part, feel free to open a new issue and refer to this one.
