### ISSUE TITLE
Wordpress with Sharepoint

### ISSUE THREAD

**Issue by sheiknaveed** [SharePoint/sp-dev-fx-webparts#1139]
Dear Team,
I need your help to know how to display a new on landing page in sharepoint from website created in wordpress. We have news which is in a website(wordpress), I need that to be displayed in Sharepoint page.,
How can this be achived.

**Comment by MrShed** [comment]
> Dear Team,
> I need your help to know how to display a new on landing page in sharepoint from website created in wordpress. We have news which is in a website(wordpress), I need that to be displayed in Sharepoint page.,
> How can this be achived.

Not really an issue - however, you can do this by:
1) Installing the react-rss-reader sample
2) Using this web part on your sharepoint page, choose Direct Feed and on whatever news page you are on on Wordpress add "/feed" at the end of the url (e.g. if your news page is https://www.somenews.com/news, put in https://www.somenews.com/news/feed).

We do this successfully.

**Comment by sheiknaveed** [comment]
Thanks for you answer. This will help me a lot. Also if I need to display the image from the new, can this be possible from this RSS reader

**Comment by MrShed** [comment]
> Thanks for you answer. This will help me a lot. Also if I need to display the image from the new, can this be possible from this RSS reader

I believe so but we havent done this part ourselves (yet). This will require some customisation of your RSS feed from Wordpress as well as creating a custom template on the web part, if you google this there are a few articles on how to do this.

Bear in mind that you may encounter some CORS issues which you may need to ensure your WP site is allowing CORS requests.

**Comment by hugoabernier** [comment]
@sheiknaveed did @MrShed 's answer help you?

I'm going to go ahead and close this issue. If you still need help, feel free to open a new issue with more questions and refer to this issue.
