### ISSUE TITLE
Scripteditor.tsx (not working correctly

### ISSUE THREAD

**Issue by bnagasuri** [SharePoint/sp-dev-fx-webparts#1144]
In script.tsx file there are two error super() constructer and on Change unable to call the function for text box filed

**Comment by ValerasNarbutas** [comment]
@bnagasuri  maybe you could provide more details on this? code sample?

**Comment by hugoabernier** [comment]
@bnagasuri I recently merged a PR that fixes this issue.

If you don't mind, I'll mark it as closed. If you find that the issue isn't resolved, please feel free to re-open it so the community can help finding what else is wrong.

Thanks for reporting the issue in the first place!
