### ISSUE TITLE
React Script Editor - Issue with images

### ISSUE THREAD

**Issue by JulienValentin78** [SharePoint/sp-dev-fx-webparts#1149]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Authors

@wobba 

## Expected or Desired Behavior

I have a problem: when I use the React Script editor Web Part on a modern site, I have a problem with somes images: the url of these images is based on the SharePoint site.
If I use the same code with a classic site, the image URLs are based on a CDN or other places.
Strange behavior ... would there be no URL rewriting on Modern Site ?

Thanks for your help !

Example with same JS code :

**Modern Site Screenshot :** 

![modern](https://user-images.githubusercontent.com/51909546/75188589-ad02e300-574c-11ea-999a-fcd4b2ef8d73.png)

**Classic Site Screenshot :** 

![classic](https://user-images.githubusercontent.com/51909546/75188539-93fa3200-574c-11ea-8b76-2430767fc088.png)

Regards

**Comment by wobba** [comment]
I'll close this one as the script editor wp will do nothing special with the markup you output. If you output `files/robot.png` that is what is rendered. If classic web parts has some parser which re-writes URL's and you figure out how this happens I'd happily add the functionality - or do a PR to add it :)

**Comment by JulienValentin78** [comment]
I do not produce any markup, it is the Web Part which seems to misinterpret the URLs of the images. Why in Modern UI is the image's path truncated ?
Same JS code works fine in Classic UI

**Comment by wobba** [comment]
The difference seems to stem from the loaded script incorrectly fetching the base path of the script itself, as the script is loaded dynamically and not via an original <script> tag on the page as in classic.
