### ISSUE TITLE
error code EINTEGRITY

### ISSUE THREAD

**Issue by rahuldayal** [SharePoint/sp-dev-fx-webparts#1168]
I am getting below error while doing NPM install.
 error code EINTEGRITY
error Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
 error Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
 error sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= integrity checksum failed when using sha1: wanted sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= but got sha512-SZARibyCQB+1j5b7g/6CrsUBA8pz9Yh1z+2RhXMlJcLyGkUmSriKgRmHnPjpjogQSGUAARTIFaYIMncfqL+8Pg== sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=. (1467748 bytes)

attached screenshot for more reference. 
![Capture](https://user-images.githubusercontent.com/8329420/76168539-d08b4c00-6196-11ea-8c79-02c8cf747f3f.PNG)

**Comment by O365DevHero** [comment]
@rahuldayal 

With latest version of SPFx ,they have launched a new command "spfx doctor" which will verify the compatibility of Node versions and spfx
