### ISSUE TITLE
Cannot add the web part on the /layouts/workbranch.aspx

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-fx-webparts#118]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I expect that web part shows content after adding on the /_layouts/workbench.aspx

#### Observed Behavior
When I add a web part, I see the error:
![image](https://cloud.githubusercontent.com/assets/11289124/22618118/fc973e10-eae5-11e6-81e9-42f89df9d7e9.png)

This is what I can see in the edge developer tools console:
![image](https://cloud.githubusercontent.com/assets/11289124/22618228/2f79e916-eae8-11e6-89f9-5d9105af8794.png)
There seems to be some mistake in the file url,
https://<devtenant>.sharepoint.com/SiteAssets/react-officegraph/trending-in-the-sites-i-follow.bundle
file does not exist, though
https://<devtenant>.sharepoint.com/SiteAssets/react-officegraph/trending-in-the-sites-i-follow.bundle_21c4e3f094cecda54ac2755942a0a584.js
does.

#### Steps to Reproduce
1. clone repository
2. copy "react-officegraph" into work folder 
3. "cdnBasePath": "/siteassets/react-officegraph/"
4. `gulp bundle --ship`
5. `gulp package-solution --ship`
6. upload files from ../temp/deploy to https://<devtenant>.sharepoint.com/siteassets/react-officegraph
7. upload ../sharepoint/react-officegraph.spapp to https://<devtenant>.sharepoint.com/sites/<appcatalog>/AppCatalog, +deploy
8. add add-in on the https://<devtenant>.sharepoint.com/sites/<testsite> +wait until it is installed
9. open https://<devtenant>.sharepoint.com/sites/<testsite>/_layouts/workbench.aspx
10. add web part "Trending in the sites I"

![image](https://cloud.githubusercontent.com/assets/11289124/22618187/8fd6c988-eae7-11e6-8d55-4a372bac02c1.png)

**Comment by giostra** [comment]
Yep have the same issue. Had any chance figuring it out?

**Comment by luismanez** [comment]
I had a similar issue some days ago. I have no idea what happened, but my workaround was to re-install the @microsoft\sharepoint package again. it seemed something was corrupted when bundling the solution, and only was fixed re-installing the package.

**Comment by shurick81** [comment]
@giostra, well, the only clue I found is that the versions of components in this solution are quite old:
```
{
  "name": "react-officegraph",
  "version": "1.3.0",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "author": {
    "name": "Waldek Mastykarz",
    "url": "http://www.rencore.com"
  },
  "dependencies": {
    "@microsoft/sp-client-base": "~0.2.0",
    "@microsoft/sp-client-preview": "~0.2.0",
    "office-ui-fabric-react": "0.36.0",
    "react": "0.14.8",
    "react-dom": "0.14.8"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~0.5.0",
    "@microsoft/sp-module-interfaces": "~0.2.0",
    "@microsoft/sp-webpart-workbench": "~0.2.0",
    "gulp": "~3.9.1"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp nuke",
    "test": "gulp test"
  }
}
```

**Comment by shurick81** [comment]
@luismanez , how did you reinstall? Do you mean running `npm i` or something else? Are you sure you have used project from this repository, that we discuss (https://github.com/SharePoint/sp-dev-fx-webparts)? I suspect you didn't use sp-dev-fx-webparts but empty sharepoint solution instead.

**Comment by waldekmastykarz** [comment]
@shurick81 as you've noticed this project is quite old and is not in sync with SPFx version supported by the hosted version of the workbench. Ideally, you would create a new SPFx project using SPFx RC0 and move the relevant code pieces to the new project.

**Comment by shurick81** [comment]
Hi Waldek, if I make it, should I commit to the project so other developers benefit from my effort too?

**Comment by giostra** [comment]
@shurick81 Ye I'll work on it as well and see how far I manage to get.
