### ISSUE TITLE
react-directory Error on Build

### ISSUE THREAD

**Issue by mschrade** [SharePoint/sp-dev-fx-webparts#1183]
#437  Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@hugoabernier 

## Expected or Desired Behavior
Successful Build

## Observed Behavior

Getting an error during build at subtask 'tsc'
Error - [tsc] src/webparts/directory/components/PersonaCard/PersonaCard.tsx(153,36): error TS2345: Argument of type 'ServiceScope | ServiceScope' is not assignable to parameter of type 'ServiceScope'.
Error - 'tsc' sub task errored after 11 s
 exited with code 2

## Steps to Reproduce

running Gulp Build referencing the package.json file

Thanks!

**Comment by mschrade** [comment]
Disregard, I'm a noob - didn't install the types/react dependency before running npm install.  For anyone else who needs it:
`npm install --save @types/react`

**Comment by hugoabernier** [comment]
Thanks @mschrade  for documenting the solution for others who may experience this issue in the future
