### ISSUE TITLE
Error - [tslint] No valid rules have been specified for TypeScript files

### ISSUE THREAD

**Issue by tejasthite** [SharePoint/sp-dev-fx-webparts#1200]
I am trying to build this solution react-script- editor i keep getting the error message - Error - [tslint] No valid rules have been specified for TypeScript files
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor

Much appreciate for the Help, Thank you.

**Comment by hugoabernier** [comment]
@tejasthite can you re-submit this issue using the provided issue template please?

It helps route the issue to the right people who can hopefully answer your questions.
