### ISSUE TITLE
Error on get user task in Chrome Browser

### ISSUE THREAD

**Issue by rmapps006** [SharePoint/sp-dev-fx-webparts#1208]
![image](https://user-images.githubusercontent.com/45232473/79050259-854ed800-7c31-11ea-9dfc-db50ef3467c7.png)

**Comment by hugoabernier** [comment]
@rmapps006 we'll need more information in order to help you.

Please feel free to open a new issue and take the time to fill the issue template so that we can help you accordingly.

Thanks for your understanding
