### ISSUE TITLE
Opening link does not work.

### ISSUE THREAD

**Issue by bashdx** [SharePoint/sp-dev-fx-webparts#1216]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement
- [ ] Sample request

## Expected or Desired Behavior

When using the `react-my-personal-apps` after creating an entry with a valid link - I expect the link to open, after clicking the corresponding tile.

## Observed Behavior

A new blank-only tab is opened.

## Steps to Reproduce

Package sample, install the package, add the webpart to any page.

What happens is this:

![image](https://user-images.githubusercontent.com/28575699/79300494-2f0abf00-7ee7-11ea-8543-4524abe5610c.png)

the code in the IListItem interface is expecting a URL with a lowercase "u", but Graph seems to provide it with "U" - this does not match (mind that all the other properties start with lower case).

I fixed the problem by changing the `url` property of IListItem to `Url`.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

@joaojmendes

**Comment by joaojmendes** [comment]
Hi,  Thanks for the reporting the bug.

On my last change I accidently changed the  name of  the field on the  table list from  ‘url’ to ‘Url’  when I changed the title   in the ManageApps.tsx  see (image)

I will change the field name to “url’, to maintain the coherence , and will create a new PR  and everything works fine.

To test , if  you have associated link on user you must delete all links and create again.

Thank you very much !
Sharing is caring!



    {
        title: "Url",
        field: "Url",
        editComponent: props => (
          <TextField
            underlined
            required
            placeholder="Enter URL here"
            onGetErrorMessage={(newValue: string) => {
              try {
                const _URL = new URL(newValue);
                return "";
              } catch (error) {
                return "Please enter valid Url";
              }
            }}
            validateOnFocusOut
            validateOnLoad={false}
            value={props.value}
            onChange={(event: React.FormEvent<HTMLInputElement>, newValue) => {
              props.onChange(newValue);
            }}
          />
        )
      },
