### ISSUE TITLE
react-calendar-feed convert from UTC does not work in narrow widths

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-fx-webparts#1228]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement
- [ ] Sample request

## Authors
@hugoabernier 

## Expected or Desired Behavior

Events display local time when convert from UTC is toggled.

## Observed Behavior

Events continue to display UTC when web part is in narrow widths.

## Steps to Reproduce

Select event source.
Enable convert from UTC.
Move web part into a narrow width column.

## Submission Guidelines

Bug is in EventCard.tsx  _renderNarrowCell() method. 

code reads: const eventDate: moment.Moment = moment.utc(start);

code should read: const eventDate: moment.Moment = moment(start);

**Comment by hugoabernier** [comment]
Great catch @Annie-Johnson ! I'll work on it
