### ISSUE TITLE
React-Birthdays

### ISSUE THREAD

**Issue by NikolaiDeket** [SharePoint/sp-dev-fx-webparts#1233]
- [ ] Question
- [ ] Bug
- [x] Enhancement
- [ ] Sample request

Hello,

I checked the forum out and seems like i found the right forum where i can maybe get a help.

I have issues on syncing data with azure function to sharepoint list.
I've uploaded successfully funtion from vscode to function also and i think it has also all the access's.

From where i should start the troubleshooting or anyone has some idea what could be wrong?

![Õigused](https://user-images.githubusercontent.com/58508704/80037662-abf7f300-84fc-11ea-91d6-7c6fc996aef8.PNG)

**Comment by hugoabernier** [comment]
Hey @NikolaiDeket we'll need more information in order to help you.

If you take the time to fill the issue template provided when you open a New Issue and answer all the questions that you can, we can hopefully route your question accordingly and help you.
