### ISSUE TITLE
React-Modern-Charts Can't Read Taxonomy Field Name and Value

### ISSUE THREAD

**Issue by tanweeteck** [SharePoint/sp-dev-fx-webparts#1242]
Dear All,

This modern chart can't display the taxonomy field value as the chart displayed the label name as object-object. The value cant be retrieved.
Please advise on how to enhance or modify the code to ensure that the function is able to retrieve taxonomy field.

Thanks.

**Comment by tanweeteck** [comment]
any clue?

**Comment by hugoabernier** [comment]
@tanweeteck I recommend that you re-open this issue and take the time to fill the template. This will ensure that the author of the sample gets notified and, hopefully, help you.

Authors don't get notified of new issues unless you fill the issue template provided.

Thanks for your understanding.

**Comment by tanweeteck** [comment]
> take the time to fill the template

Could I know where is the template that I could fill in?
Thanks.
