### ISSUE TITLE
Wanted: Updated version of vuejs-todo-single-file-component

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-fx-webparts#1256]
## Authors
@s-KaiNet 

## Expected or Desired Sample

The `vuejs-todo-single-file-component` is a great sample, but some of the NPM packages it uses have since been updated.

A few of the NPM packages have been updated with security patches.

It would be great to have an updated version of this sample with an updated `package.json` which uses the newer patched versions of this libraries:

- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/set-value/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/lodash.mergewith/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/lodash.merge/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/lodash.template/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/mem/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/stringstream/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/open/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/diff/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/is-my-json-valid/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/nwmatcher/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/braces/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/clean-css/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/js-yaml/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/base64-url/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/fstream/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/tar/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/morgan/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/node.extend/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/extend/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/merge/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/randomatic/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/atob/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/cryptiles/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/macaddress/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/sshpk/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/lodash/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/mixin-deep/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/parsejson/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/fresh/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/growl/open
- https://github.com/SharePoint/sp-dev-fx-webparts/network/alert/samples/vuejs-todo-single-file-component/package-lock.json/hoek/open

For the most part, the work simply consists of following the recommended changes to the `package.json` and testing the updated web part to make sure that it still works, and changing the `package-solution.json` version to reflect the change.

Thanks for your contribution! Sharing is caring.

**Comment by s-KaiNet** [comment]
Right... this one is quite old and hasn't updated for more than two years!  
I added the corresponding PR.   

Thank you for catching this up!
