### ISSUE TITLE
Yammer Webpart

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-webparts#129]
#### Category
- [ ] Question

What is the best way to load the below code in SharePoint Framework WebPart?

` <script type="text/javascript" src="https://c64.assets-yammer.com/assets/platform_embed.js"></script>
          <div id="embedded-feed" style="height:400px;width:100%"></div>
          <script>
          yam.connect.embedFeed({
          container: '#embedded-feed',
          network: 'tenant.onmicrosoft.com',
          feedType: 'open-graph',
          config: {
          defaultGroupId: 12345,
          showOpenGraphPreview: false,
          promptText: "Comment on this article",
          header: false, footer: false
          }
          });
          </script>
`

**Comment by waldekmastykarz** [comment]
I would start with trying to load the platform_embed.js as an external script in config.json. The rest of the script I'd execute in the render method in a `if (this.renderedOnce === false)` clause. I haven't tried it, so can't tell for sure if it works, but that's what I'd start with.

**Comment by sprider** [comment]
Hi Waldek,

Thank you for your guidance. I am trying to import the external file with the below approaches but i am unable to get this working. Am i doing anything wrong?

Error: Cannot find module 'yammer'.

Option -1
**External configuration** 
"yammer": "https://c64.assets-yammer.com/assets/platform_embed.js" 
**WebPart code** 
import yammer from 'yammer';

Option -2
**External configuration** 
"yammer": {
      "path": "https://c64.assets-yammer.com/assets/platform_embed.js",
      "globalName": "yammer"
    }
**WebPart code** 
import * as yammer from 'yammer';

**Comment by sprider** [comment]
@waldekmastykarz 

Any suggestions?

**Comment by waldekmastykarz** [comment]
If you haven't installed TypeScript typings for yammer then you can't use `import * as yammer...`. Instead, you would have to use `require('yammer')`.

**Comment by sprider** [comment]
@waldekmastykarz 

I guess If I do not install typings for yammer then I will get the below error when I use yam.connect.embedFeed()

Cannot find name 'yam'

**Comment by waldekmastykarz** [comment]
I haven't worked with the Yammer API and can't say if it has typings and in what state they are. If there are none, or if you can't use them, you can always fall back to not using types at all like:

```ts
(yam as any).connect.embedFeed();
```

While you will loose TypeScript's type safety features, you should be able to use the API.

**Comment by sprider** [comment]
@waldekmastykarz 

I am getting the below error now 

![error](https://cloud.githubusercontent.com/assets/21008316/23376068/6ebfe17e-fcf0-11e6-85e4-339a4cc7a951.png)

**Comment by waldekmastykarz** [comment]
Have you installed Yammer TypeScript typings? Have you configured them as global typings in **tsconfig.json**?

**Comment by sprider** [comment]
@waldekmastykarz 

No i did not install any typings and tried as per your previous suggestion

**Comment by sprider** [comment]
@waldekmastykarz 

Temporarily I have added the platform_embed.js code(https://c64.assets-yammer.com/assets/platform_embed.js) directly in my angular controller file to make this work. 

I will have to figure out a way to load this platform_embed.js from external CDN

**Comment by sidjustsid** [comment]
Hi sprider ,
I have the same requirement of calling yammer api in sharepoint framework. Just wanted to check did you had any luck?

Thanks

**Comment by sprider** [comment]
@sidjustsid 

For now I just added the platform_embed.js code directly in my JS file and it is working. You can check [here](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angular-yammer)

**Comment by sidjustsid** [comment]
Hi Sprider,
Firstly thanks for the reply.
In the article you have provided, there is only data coming from feed. Can i call another yammer api .

**Comment by sprider** [comment]
@sidjustsid 

Could you please share the api details? I will try and let you know

**Comment by sidjustsid** [comment]
Hi Sprider,
I tried to use home controller.js and included my own js. It is working fine.
But how can i call the functions specified in js  in .ts file?
Also, can i use this without angular JS?

My api is a simple yammer api: https://www.yammer.com/api/v1/messages.json

Thanks
Sid

**Comment by waldekmastykarz** [comment]
@sprider if `yam` is a global object, then you would have to change the way you reference it to `(window as any).yam`.

**Comment by sprider** [comment]
@waldekmastykarz 

Will this work without installing typings for the platform_embed.js file?

**Comment by sprider** [comment]
@sidjustsid 

Hope you went through [this](https://github.com/SharePoint/sp-dev-fx-webparts/tree/f137105fb407adc9ed0fbabfd5c1f55262b6555e/samples/angular-msgraph) awesome example for your requirement. 

This example describes about token generation logic. Once you get the token, you just need to pass that as a request header as shown below 
Authorization: Bearer {TokenValue}

**Comment by waldekmastykarz** [comment]
@sprider yes, it should, because by casting the `window` object to `any` you basically explicitly state that you want to disregard typings and use it like plain JavaScript.

**Comment by sprider** [comment]
@waldekmastykarz 

Perfect, Thank you. Let me try and keep you posted.

**Comment by sidjustsid** [comment]
@waldekmastykarz  So can we call a function inside that js like (window as any).yammer.platform.request

**Comment by waldekmastykarz** [comment]
@sidjustsid yes, you should be able to do that.

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
I don't know where i am doing wrong, 
Please find the steps i am following below:
Specifying details in config.json:
 "externals": {},
  "localizedResources": {
    "oneSpfxStrings": "webparts/oneSpfx/loc/{locale}.js",
    "yammer": {
"path": "https://c64.assets-yammer.com/assets/platform_js_sdk.js",
"globalName": "yammer",
"globalDependencies": [ "yammer" ]
}

Calling in .ts file:


(window.any).yam.platform.request

Error:
platform is identifying by (window.any).yam

**Comment by sidjustsid** [comment]
I want to call this function 
yam.platform.request(
   { 
      url: "https://api.yammer.com/api/v1/messages/in_group/GroupID.json" //replace the group ID with yours
      , method: "GET"  

    			 
      ,success: function (data) { }
)};

**Comment by waldekmastykarz** [comment]
Ok, so by adding **yammer** to externals you only specify its URL but actually not load it. So on top of what you're already doing you'd need to add `require('yammer');` just under the last `import` statement in your web part.

If you want to call `yam.platform.request` then you should use `(window as any).yam.platform.request` instead of `(window as any).yammer.platform.request`

**Comment by sidjustsid** [comment]
![image](https://cloud.githubusercontent.com/assets/26655462/24521215/fa0f5f7c-15a8-11e7-8a4a-c68262a12cf3.png)

![image](https://cloud.githubusercontent.com/assets/26655462/24521293/42f3f81a-15a9-11e7-88aa-4813bb59e999.png)

![image](https://cloud.githubusercontent.com/assets/26655462/24521309/4fbaba3e-15a9-11e7-812b-e5e313527cbf.png)

@waldekmastykarz  I would be thankful if you can tell me where iam going wrong by looking those images attached.

**Comment by waldekmastykarz** [comment]
yammer in config.json should go to externals instead of localizedResources

**Comment by sidjustsid** [comment]
Now 
![image](https://cloud.githubusercontent.com/assets/26655462/24524812/94f72108-15b5-11e7-8849-084631d0f1cd.png)

**Comment by waldekmastykarz** [comment]
One more thing I noticed in your externals section is that you defined yammer as dependency for itself. You should remove the **globalDependencies** entry from the **yammer** definition in your config.json file.

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz  I have removed global dependencies, but why is yammer module not recognizing by SPFX? Im afriad..!!

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 

A big Cheers for you!

 Finally i have called a js file function. The only issue is i am able to call the function only if i enable CORS extension in the browser.
Because i am getting below error.
XMLHttpRequest cannot load https://www.yammer.com/api/v1/messages/in_thread/GID.json. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'SharepointURL' is therefore not allowed access.

**Comment by waldekmastykarz** [comment]
This could have to do with how Yammer is hosting its scripts and is nothing you can really do about other than not use their SDK and call the REST API instead.

**Comment by sidjustsid** [comment]
@waldekmastykarz  I am facing the same issue if i use Yammer RESTAPI as well by using httpClient.

**Comment by waldekmastykarz** [comment]
Unfortunately I don't know the Yammer API so I'm afraid I won't be able to much of much more help. Perhaps you could reach out to Yammer and see if they can help?

**Comment by sidjustsid** [comment]
@waldekmastykarz  Thanks a ton. This thread will perhaps helps more folks by your valuable suggestions which you have given above. Cheers..!!!! 

Thanks
Siddhartha

**Comment by sidjustsid** [comment]
@waldekmastykarz  This issue got resolved by providing the site URL in the javascript origin of Yammer app.

**Comment by waldekmastykarz** [comment]
Excellent!

**Comment by sprider** [comment]
As we resolved this issue, I am going to close this thread.
