### ISSUE TITLE
Not Deploying Latest SPFX Webpart(GA Release) in Non Developer Tenants

### ISSUE THREAD

**Issue by poovarasan14** [SharePoint/sp-dev-fx-webparts#134]
I Uploaded the latest SPFX Webpart in Apps site but i can't deploy the webpart in office 365 tenants by admin@xxxxxxx.onmicrosoft.com(office 365 user)
![issue](https://cloud.githubusercontent.com/assets/17897443/23359999/0574000a-fd0f-11e6-9fcb-3841af873cba.png)
![issue1](https://cloud.githubusercontent.com/assets/17897443/23360015/11e4853a-fd0f-11e6-9059-4f17acc57a90.png)

**Comment by VesaJuvonen** [comment]
That would indicate that the package is not valid due reason or another. Would update the Yo templates with 'npm install @microsoft/generator-sharepoint -g' and then test the basic deployment with tutorial guidance available from https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part. 

Your package.json has still sp-client-preview there, which should not be there at this point, if you are using GA packages. You can also have a look on existing tutorial web parts (updated to GA) at https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/tutorials.
