### ISSUE TITLE
Issue while deploying in the dev site..

### ISSUE THREAD

**Issue by Soumyawrk** [SharePoint/sp-dev-fx-webparts#143]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [*] Bug
- [x] Enhancement

#### Expected or Desired Behavior

It should return the current weather of the provided locality

#### Observed Behavior

It is working fine in local workbench but throwing some issue after we deploy it in the dev site 
![issue in dev site](https://cloud.githubusercontent.com/assets/25977928/23653729/8a8a1a1e-0353-11e7-9a39-333d4d0ff6d0.PNG)

Thanks for your contribution! Sharing is caring.

**Comment by rgarita** [comment]
Hello, 

I saw it before.. It happened to me when I did a deployment updating the CDN but not updating the client side solution package on the app catalog.

To fix it try update the client solution package (.sppkg) on the app catalog. that should fix it

Raul
