### ISSUE TITLE
Provisioning SharePoint Assets using SPFX

### ISSUE THREAD

**Issue by sudarsanan** [SharePoint/sp-dev-fx-webparts#145]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I was trying to provision SharePoint assets using framework, I am using elements and custom schema file for creating list and content type and also in the list instance i have updated the custom schema file.

I have followed the steps as mentioned in the below link.
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/provision-sp-assets-from-package

But when I install the package to app catalog I dont see any issues, but when i add the app to the site I see installation error "List schema 100 doesnt exist". Let me know if anyone faced similar issues.

**Comment by VelinGeorgiev** [comment]
Not enough details here.

Can you paste the exact error message and your elements.xml file?

Have you tried with the sample from the tutorials - https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/tutorials/asset-deployment-webpart?
