### ISSUE TITLE
Let us delete all SPFx examples

### ISSUE THREAD

**Issue by Danny-Engelman** [SharePoint/sp-dev-fx-webparts#146]
#### Category
- [XX] Enhancement

#### Expected or Desired Behavior
Make SPFx examples valuable research/learning assets for all developers

#### Observed Behavior
* SPFx examples are single-developer entries, I haven't seen an example yet where examples are enhanced by other developers as is common in Github projects.
* Documentation is hard to find, 99.9% is code only
* Several examples use ES3 coding patterns where ES6 (TypeScript) patterns can create shorter, faster and better readable code

**I propose to delete all but 5 examples and work together to make them the best examples ever**

**Comment by VesaJuvonen** [comment]
thx Danny for your input. We do acknowledge that not all samples currently are using all the modern techniques, but PnP is community driven initiative and dependent on the community contributions. If you'd like to see some specific areas demonstrated, we do welcome you to contribute as well. We will absolutely do cleaning of the sample gallery as needed during our journey, but will certainly not delete current samples, which community has worked hard and shared for the benefit of others.
