### ISSUE TITLE
vuejs sample throws vue warning and does not work.

### ISSUE THREAD

**Issue by scharinger** [SharePoint/sp-dev-fx-webparts#157]
Hi, I wanted to try the vuejs sample but got some errors early on I would like to report. Thereafter the demo does not seem to work because of `mytodos` no existing.

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

### The issue
`
[Vue warn]: Property or method "mytodos" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <Todo> at C:\Users\tisc\Documents\Repos\sp-dev-fx-webparts\samples\vuejs-todo-single-file-component\lib\webparts\todo\components\todo\Todo.vue)
`
![image](https://cloud.githubusercontent.com/assets/724211/23849760/0a326450-07dd-11e7-934d-7d117e8b2e92.png)

#### What I've done
1. Cloning the repoe
1. Installed dependencies
1. run `gulp serve` 
1. Browsing the page

#### Versions
Visual Studio Code 1.10.12
Chrome 56.0.2924.87

**Comment by Tim86** [comment]
I got the demo working by replacing the mytodos references to simply todos. I think the mytodos might not be finished. Commit the change to [my fork](https://github.com/Tim86/sp-dev-fx-webparts/commit/4c6cc77f326fdc547c0b0a5eb18c78353c646bb7), if you'd like to merge it.
