### ISSUE TITLE
angular msgraph not working with GA

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-fx-webparts#161]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
gulp serve should open browser

#### Observed Behavior
many compile time issues with ga bits.

#### Steps to Reproduce
here: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angular-msgraph

thanks!

**Comment by ndepaoli** [comment]
Same problem here

**Comment by davidhartman** [comment]
I updated the code to work with RC0 and I think some updates are causing some issues when they went to GA. I'll work on fixing the code soon. Thanks for reporting this!
