### ISSUE TITLE
External Templates for Angular 2

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-fx-webparts#165]
#### Category
- [ ] Question
- [x] Bug
- [x] Enhancement

#### Expected or Desired Behavior
I should be able to reference external templates in an SPFx Angular 2 project.

#### Observed Behavior
This gives:

> GET https://localhost:4321/temp/some.component.html 404 (Not Found)
> Unhandled Promise rejection: Failed to load some.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load some.component.html

#### Steps to Reproduce
I should be able to do:

```
templateUrl: './some.component.html',
```

Workaround is to only use inline template.

See:

https://github.com/webtechy/sp-dev-fx-webparts/tree/master/samples/angular2-taxonomy

**Comment by waldekmastykarz** [comment]
Please note that the relative URL to your template is resolved on runtime and is therefore relative to the page where the web part is placed and not where the web part bundle is hosted and where your template would also be. While the difference on the local workbench is subtle, when you deploy your web part to SharePoint you would see that the browser would try to load the template from SharePoint rather than from the server hosting your bundle.

For this to work your template URL would have to be absolute. You can easily get the URL of the web part bundle using the following method:

```ts
import {
  IClientSideComponentLoaderConfiguration,
  IPathModuleConfiguration
} from '@microsoft/sp-module-interfaces';

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  // ...
  private getBaseBundleUrl(): string {
    const loaderConfig: IClientSideComponentLoaderConfiguration = this.context.manifest.loaderConfig;
    let baseUrl: string = loaderConfig.internalModuleBaseUrls[0] +
      (loaderConfig.scriptResources[loaderConfig.entryModuleId] as IPathModuleConfiguration).path;
    return baseUrl.substr(0, baseUrl.lastIndexOf('/')+1);

  }
  // ...
}
```

**Comment by webtechy** [comment]
Thanks @waldekmastykarz - that certainly helps. I would also need to consider which are transposed, and which are referenced at runtime (as it varies). Some additional notes:

This works (not SCSS reference is OK):

```
//templateUrl: './app.component.html',
//template: require('./app.component.html'), // You need html-loader for this.
template: `<div class='wt-header'><img src="https://somecompany.sharepoint.com/sites/Development/SiteAssets/somefolder/FormHeader.png"></div>`,
//styleUrls: ['./header.scss'],
styles: [
        String(require('./header.scss'))//,
] // You need sass-loader for this. Also do not call it "something.module.scss" (see https://bob1german.com/2016/12/12/html-templates-in-spfx/), and also read more here: https://github.com/jtangelder/sass-loader
```

But I have to do:

```
SPComponentLoader.loadCss("https://someurl.sharepoint.com/sites/Development/SiteAssets/somefolder/assets/font-awesome/css/font-awesome.min.css");
```

As a simple workaround I am using absolute URLs for images too. It's pretty bonkers that something so trivial (adding an image to a webpart!) needs a hack such as this or a custom method to figure things out. :-(

**Comment by webtechy** [comment]
Can a config fix be used something like you mentioned here:

https://blog.mastykarz.nl/correctly-reference-images-sharepoint-framework-solutions/

**Comment by waldekmastykarz** [comment]
The config fix applies only to `require` statements in your TS code that are processed by Webpack. Everything that's referenced on runtime, has to be fixed separately.
