### ISSUE TITLE
Fully automating SharePoint framework webpart deployment

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-fx-webparts#169]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
I'm working on fully automating the process from source to production with the SharePoint framework. The only thing that doesn't allow me to complete this flow is the .sppkg (app package) consent.
Uploading the file to the app catalog is possible leveraging either pnp provisioning, spsave, spsync or other mechanisms like that. However there's still no programmatic way to consent to an application. And the application is then not surfaced to be installed.
The Addin part of the PnP Provisioning Schema doesn't seem to accept .sppkg files, the template is always invalid with those.
This has been an issue since the app/add-in model came-out back in 2012/2013.
We need a way to close the loop on that, providing a web service in SharePoint + SPO cmdlet or PnP provisioning support would be a great help.

I know this issue spreads across multiple teams: the product team, this one and the pnp core team but resolving it would help a lot with implementing release pipelines and devops processes.

**Comment by webtechy** [comment]
Related: https://github.com/SharePoint/sp-dev-docs/issues/415

**Comment by michel-weber** [comment]
Hello @baywet 
could you give me some guidance on implementing the file upload to the app catalog? 
> Uploading the file to the app catalog is possible leveraging either pnp provisioning, spsave, spsync or other mechanisms like that.

I'm fairly new to SharePoint and I couldn't figure it out (i tried pnp provisioning via powershell).

I already automated the whole deployment by using Selenium (automating the browser interaction) and AutoIt (automating the windows upload dialog). 

There are some really nasty side effects if you want to run that code in a custom VSTS build agent (using an Azure VM).
In order for it to work, it needs:
- An active Remote Desktop (RDP) connection to the VM
  - [How to run remote headless GUI automation](https://autumnator.wordpress.com/2011/11/18/how-to-run-remote-headless-gui-automation/)
- The RDP-Client window can't be minimized
  - It switches to GUI-less mode if minimized. See [Running Tests in Minimized Remote Desktop Windows](http://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html).

Uploading the file via scripts would help this alot (because I would not be forced to use AutoIt).

**Comment by michel-weber** [comment]
There's hope for the future - it is already on the [roadmap] :+1: (https://dev.office.com/sharepoint/docs/spfx/roadmap).

**Application Lifecyle Management**
- Streamlined approval experience: no need to know who your tenant admin is anymore
  - Owner initiate the approval process
  - Tenant admin gets automatically notified
  - Settings to control the default experience around approval process
- **ALM REST APIs - Deploy, activate, delete and upgrade apps and add-ins**
- **ALM REST APIs targeted to support everything in the App Catalog, including add-ins**
- Automatic CDN hosting for code
  - Package JavaScript bundle into app package, which is automatically then deployed to a library that gets hosted on your tenant Office 365 CDN

**Comment by michel-weber** [comment]
I solved the problems with AutoIt. 

It was possible to use a Selenium only solution. I could remove AutoIt and now I can run it on my custom build agent without the nasty side effects.

**Comment by joeljeffery** [comment]
Hi!

If anyone is still looking for a way to automate trusting a SharePoint add-in/app either on-prem or online, there's an article that shows the general approach of submitting HTTP POSTs to fake SP Online button presses here: 
https://blogs.msdn.microsoft.com/vesku/2013/11/04/ftc-to-cam-advance-http-remote-operations-for-sp2013

Note that this technique is liable to break if Microsoft change the design or layout of the AppInv.aspx page in SharePoint Online.

I've forked the excellent work by Vesu and Bert, and I've implemented it here specifically to trust SP add-ins/apps:
https://github.com/joeljeffery/ContosoRemoteHttpCommands

You could then call this from code or PowerShell:

```
$targetWebUrl = "https://....."; ### the url to your host web
$myAppInstance = Get-PnPAppInstance .....; ### get your specific app that you already installed in the host web

Add-Type -Path "Contoso.Remote.Core.HttpCommands.dll";
$ctx = Get-PnPContext;
$remoteTrust = New-Object Contoso.Remote.Core.HttpCommands.RemoteTrustAddin -ArgumentList @($targetWebUrl, [Contoso.Remote.Core.HttpCommands.AuthenticationType]::Office365, $ctx.Credentials);
$remoteTrust.AppInstanceId = $myAppInstance.Id;
$remoteTrust.Execute();
```

Hope this helps someone!

Joel
http://joelblogs.co.uk
https://jfdi.info

**Comment by HTEredrock** [comment]
Haven't tested this process fully: https://www.eliostruyf.com/configure-a-build-and-release-pipeline-for-your-sharepoint-framework-solution-deployments/

But it looks like it will do the trick.

**Comment by michel-weber** [comment]
This issue can be closed - it is now possible to fully automate it. 

Use the ALM APIs for doing the upload to the app catalog and installing it to a site.

**Comment by baywet** [comment]
Thanks for reminding me about this issue, closing
