### ISSUE TITLE
Build preparation based environment

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-webparts#171]
#### Category
- [ ] Question

Do we have an option in SPFX to prepare the build based on environment? 

I have 3 tenants to Develop, Test and Production Deployment. Currently I am editing few properties every time when I prepare the build based on the environment where I deploy such as externals files in config.json, cdnBasePath in write-manifests.json, iconImageUrl in {}WebPart.manifest.json, Environment specific app config variables, etc.,

Thoughts ? 

@waldekmastykarz 

Thanks for your contribution!

**Comment by waldekmastykarz** [comment]
Unfortunately not at the moment. Ideally this would be done by parametrizing build tasks so that you can specify the values as arguments of the gulp bundle/package-solution tasks, this would however need to be done by Microsoft. A workaround for the time being could be to create a custom gulp task and have it replace the URLs.

**Comment by sprider** [comment]
@waldekmastykarz 
Sure, I will try from my side. 
I am sure you are going to guide us here with a new article in your website :) 
Thank you Waldek

**Comment by Danny-Engelman** [comment]
The Gulp route is interpreted, 

 * CMD file ► Node ► (Gulp)JavaScript ► system I/O

So it sucks at performance.

Once you have to update more than a couple of files and are in a Continuous Built you will start looking for (way) faster alternatives.

We switched back to the tools we used long before Gulp

http://www.gnu.org/software/m4/m4.html
is based on templating tools going back only 40 years
But I wouldn't start with it until Gulp really is making you walk to the coffee corner more often

## One Easy Tiny Tool (on Windows)

the [File And Replace Tool](http://fart-it.sourceforge.net/) is one executable for doing replaces

 * CMD file ► FART ► system I/O

is a whole lot faster than that Node stuff

So from the FullStack we are back to the ShortStack, and execute CMD (Batch) code again

Like:
```
REM Set ProjectDate in files
for /F "usebackq tokens=1,2 delims==" %%i in (`wmic os get LocalDateTime /VALUE 2^>NUL`) do if '.%%i.'=='.LocalDateTime.' set timestamp=%%j
set shorttime=%timestamp:~0,4%-%timestamp:~4,2%-%timestamp:~6,2% %timestamp:~8,2%:%timestamp:~10,2%
w:\fart.exe %projectSRC%\%project%.js "$$$dateDEV" "%shorttime%"
```

https://www.google.nl/search?q=fart+replace

<hr>

> Those young punks laughed at me when I said I could speed up the build by 40%
> And then the old geezer just did it

**Comment by sprider** [comment]
@Danny-Engelman 

Thank you for sharing this. I will this thread open for now.
