### ISSUE TITLE
Adding Modern spfx OOb webparts to classic page.

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#172]
@waldekmastykarz  Is there any way to add Modern OOB web parts to classic pages in SharePoint online.

#### Category
- [x] Question

#### Expected or Desired Behavior
We have a requirement of adding Site Activity web part to classic page in SharePoint online.

Many Thanks
Siddhartha

**Comment by waldekmastykarz** [comment]
Not that I know of.

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
Iam facing an issue with binding html . I am unable to bind html in **.then** function. But i am able to do it above **.then** function.
Sample below:
**private _renderList(items: ISPList[]): void {
    let html: string = ''; 
     items.forEach((item: ISPList) => {
        
      const spOpts: IHttpClientOptions = {
      
            
             headers: {
              
              
    Authorization: 'Bearer Token',} 
            };  
 

    this.context.httpClient.get(`https://api.yammer.com/api/v1/messages/in_thread/GID.json`, HttpClient.configurations.v1, spOpts)
       .then((response: any) => {
         //I am able to do it here..
response.text().then(function(text) {
  var ResponseData = JSON.parse(text).messages[1].liked_by.count;
  //The below is  the html i want to bind from above resonse
         html += `
		  <ul class="${item.Title}">
 		 	<li class="${item.Title}">
 		  		<span class="ms-font-l">${item.Title}</span>
           <span></span>
 		 	</li>
		   </ul>`;
      
});
const listContainer: Element = this.domElement.querySelector('#spListContainer');
     listContainer.innerHTML = html;**

Would be thank ful for any help.

Thanks
Siddhartha

**Comment by waldekmastykarz** [comment]
Have you tried changing:

```
response.text().then(function(text) {
```

to:

```
response.text().then((text) => {
```

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz  

Good Morning!
Firstly Thanks and cheers for you for addressing the issues.

My problem is how to make a function synchronous in SPFX.


Thanks
Siddhartha

**Comment by sidjustsid** [comment]
@waldekmastykarz  You are amazing!!!

The above piece of code worked for me :)

Thanks a ton ....
