### ISSUE TITLE
Applying Carousel to spfx webpart

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#173]
@waldekmastykarz  Do you have any idea , how to apply carousel to the fetched list items in spfx webpart.

We want to apply carousel to the items fetched from list in spfx webpart.

Would be thankful for the solution :)

Thanks
Siddhartha

**Comment by StfBauer** [comment]
Do you have any specific question? If you are in general interested to write a carousel web part I would recommend you to read one of the following tutorials:

* "[Keep it simple: Coding a carousel](https://www.christianheilmann.com/2015/04/08/keeping-it-simple-coding-a-carousel/)"
* "[Carousels Don’t Have to be Complicated](http://mediatemple.net/blog/tips/carousels-dont-have-to-be-complicated/)"
* "[Create a carousel out of nothing but CSS](http://www.creativebloq.com/css3/create-carousel-out-nothing-css-21410819)"

After reading this basic tutorials on how to build a carousel you should be able to integrate it into an SPFx web part too.
Or you can choose one of the available [Carousel Script](https://dcrazed.com/free-responsive-jquery-carousel-slider-plugins/).

**Comment by frankchen76** [comment]
[Angular UI Bootstrap](http://angular-ui.github.io/bootstrap/#!#carousel) also provides a carousel directive. You can leverage the [SPFx angular samples](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples) and this component to create a carousel client side web part. 
hope it helps.
