### ISSUE TITLE
React-Officegraph Web part returns error

### ISSUE THREAD

**Issue by Padmapriyashree** [SharePoint/sp-dev-fx-webparts#174]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When I add a web part on the page, I expect it to show content

#### Observed Behavior
I face the same issue still with the Officegraph web part.
The aspx page created as directed in Readme page returns nothing and after adding app on the site,
add new modern page, add web part "Trending in the sites I"
I get the below in the added webpart.

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.83f0e319-95a2-4cff-84ca-d50d693e92ee,Error: ***Failed to load component "90a04bb9-fbdf-43d1-bfe1-0491d34941be" (undefined). Original error: ***Failed to load entry point from component "90a04bb9-fbdf-43d1-bfe1-0491d34941be" (undefined). script resources due to: {1}. CALLSTACK:: Error at t.prototype._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:25072) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:24062) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25406) at t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25848) at e.prototype._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:55681) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:46096) at k (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2381) at L (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2469) at A (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2291) at D (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:1887)

**Comment by waldekmastykarz** [comment]
This sample is built using a pretty old version of the SharePoint Framework (drop 2) which might explain why it isn't working with SharePoint. Ideally you would either have to update the sample to the GA version of the SharePoint Framework or wait for someone else to do it. Meanwhile, is there anything specific that you were looking for in this sample? Perhaps there are other samples that could be helpful as well?

**Comment by Cecildt** [comment]
This web part and other web part examples that are using the GQL and SharePoint Search API must be updated or remove since the GQL API is being discontinued by August 2017. Also the API will stop working by 19 June 2017 if not used with a special query parameter.

https://msdn.microsoft.com/en-us/office/office365/howto/query-office-graph-using-gql-with-search-rest-api
