### ISSUE TITLE
React-AAd-Webapi

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#175]
Hi @waldekmastykarz 

When i was struggling for an issue, i have found the below link:

My requirement:
Call external rest api service with authentication by passing an authorization header.
 The link i have found is 

 **https://github.com/SharePoint/sp-dev-fx-webparts/tree/6b3a9df59cc3d5eaa2d7b848937e00d3f458b9c1/samples/react-aad-webapi**

So, i hope there will be authentication between Sharepoint and API service..

Is this applicable for GA version?

Many Thanks
Siddhartha

**Comment by waldekmastykarz** [comment]
Yes, it is. For additional guidance on this topic see https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.

**Comment by sidjustsid** [comment]
@waldekmastykarz  Thanks for the guidance. 
I hope we can now secure the web api from sharepoint using the react aad without sending any authentication tokens explicitly in the headers.

Thanks
Siddhartha

**Comment by waldekmastykarz** [comment]
Unfortunately, you can't do that. Sine you're connecting to a secured API from the client, you have to send the bearer token in the header.

**Comment by sidjustsid** [comment]
@waldekmastykarz 
So, in your scenario what is the token you have passed ? Is it the SharePoint token?

Because in my scenario i should send a token from sharepoint, and i dont have idea if i can get any ADFS SAML token in the framework.

Can you help me in this.

**Comment by waldekmastykarz** [comment]
The web API called by the web part is registered with Azure Active Directory as a web application. Using OAuth implicit flow the ADAL JS library retrieves an OAuth access token for that particular API. Once retrieved that token is included in request headers to the API.

**Comment by sidjustsid** [comment]
Ok is it automatically happening in the React AAD? 
It means by using React AAD, i should not explictly mention any Tokens? I hope React AAD is handling that.

**Comment by waldekmastykarz** [comment]
Unfortunately, you will have to explicitly request and include tokens when using React. The only library that does all of that automatically for you is AngularJS. Here you can see how the token is first retrieved (https://github.com/SharePoint/sp-dev-fx-webparts/blob/6b3a9df59cc3d5eaa2d7b848937e00d3f458b9c1/samples/react-aad-webapi/webpart/src/webparts/recentOrders/components/RecentOrders.tsx#L134) and then added to the request to the API secured with AAD (https://github.com/SharePoint/sp-dev-fx-webparts/blob/6b3a9df59cc3d5eaa2d7b848937e00d3f458b9c1/samples/react-aad-webapi/webpart/src/webparts/recentOrders/components/RecentOrders.tsx#L185-L190)
