### ISSUE TITLE
Pop up in Sharepoint framework

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#177]
@waldekmastykarz 
Is there any way to show page in a popup in SPFX?

My requirement is:
I want to show each item details of the list in a popup with the properties given for that particular item.

Many Thanks

**Comment by waldekmastykarz** [comment]
Sure thing! Have you considered using `window.open` passing the URL of the item view form or do you need something else?

**Comment by sidjustsid** [comment]
@waldekmastykarz  **window.open** will open a page(Redirection). I want a page to be opened in a popup(Dialog box?)

**Comment by waldekmastykarz** [comment]
Do you mean something like https://dev.office.com/fabric#/components/dialog?

**Comment by davidhartman** [comment]
you could also use a bootstrap modal dialog

**Comment by sidjustsid** [comment]
@davidhartman  We want to use only fabric , since it has got all the responsive and updated features.

Thanks for the Answers @waldekmastykarz and @davidhartman
