### ISSUE TITLE
Web part loading issue after packaging

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#178]
@waldekmastykarz 
We have developed webparts in our dev environment and after packaging the web parts and adding in another site we are facing the below issue:
![image](https://cloud.githubusercontent.com/assets/26655462/24997566/aeebb23c-2054-11e7-803e-93af9b742343.png)

I feel you can help us with this.
Many Thanks

**Comment by waldekmastykarz** [comment]
If you paste the `https://spfx...` url pointing to the .js bundle in the browser, do you see the script or are there any errors? Is the script accessible anonymously or does it require authentication in order to be accessed?

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
The issue here is we have created a container in Azure and packaged our js files there.
We have deleted that container and created new container and packaged again to the new container.
If you can see the above screen, the js file is being referred from Old Container.
I have raised this issue in [this ](https://github.com/SharePoint/sp-dev-fx-webparts/issues/179#issuecomment-297503373)also.  Waiting for urgent help from any one since we are moving this to production.

**Comment by waldekmastykarz** [comment]
After changing the URLs have you rebuilt and redeployed the package to SharePoint? Also, have you increased package version number?

**Comment by sidjustsid** [comment]
@waldekmastykarz 
I haven't not rebuilt , followed the same commands below and took the packaged file.
**gulp --ship
gulp deploy-azure-storage 
gulp package-solution --ship** 


Can you tel me to what number i should increase the number.
Below is my package.json file:
**{
  "name": "spfx-40-fantastics",
  "version": "1.0.2",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
   "@microsoft/sp-client-base": "~1.0.0",
    "@microsoft/sp-core-library": "~1.0.0",
    "@microsoft/sp-http": "^1.0.0",
    "@microsoft/sp-loader": "^1.0.0",
    "@microsoft/sp-webpart-base": "~1.0.0",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "office-ui-fabric-react": "0.83.0",
    "jquery": "2.2.4",
    "jqueryui": "^1.11.1",
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "orchestrator": "^0.3.8",
    "sp-client-custom-fields": "^1.1.7",
    "through2": "^2.0.3",
    "typewriting": "^1.2.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.0.1",
    "@microsoft/sp-module-interfaces": "~1.0.0",
    "@microsoft/sp-webpart-workbench": "~1.0.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "~3.9.1"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  }
}**

**Comment by waldekmastykarz** [comment]
You should update the version in the `config/package-solution.json` file which is the version number of the generated .sppkg file that you upload to the AppCatalog. When that version is increased, you should be able to update the existing package and have your URLs point to the new location.

**Comment by sidjustsid** [comment]
@waldekmastykarz 
we are changing the version number when ever we package the solution.Screen shot below:
![image](https://cloud.githubusercontent.com/assets/26655462/25572812/96bcb27c-2e5c-11e7-87b8-59c08ea9da80.png)
What does rebuilt means ? Do we need to change the number in any other file other than config/package-solution.json file??

**Comment by waldekmastykarz** [comment]
Theoretically it should be sufficient. It seems though you're running into an error similar to https://github.com/SharePoint/sp-dev-docs/issues/550. Could it be that it's the same issue?

**Comment by sidjustsid** [comment]
@waldekmastykarz  Yes, its the same issue, But the problem is even after 20 Minutes ,and after days even, old references are being shown sometimes.

**Comment by mcmynn83** [comment]
@sidjustsid - in order to diagnose if it is a cache issue or something else you can add the cookie ClientSideDisableThirdPartyCache to your browser (the value doesn't matter, if it is not null the server will NOT use the cache).  If you are still seeing the old values after setting that value, it means the app catalog does not have the version you expect.  If you are seeing the problem after days I don't believe it is a cache issue.
