### ISSUE TITLE
App Install Error

### ISSUE THREAD

**Issue by davidhartman** [SharePoint/sp-dev-fx-webparts#181]
#### Category
- [ X] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I installed an app and got an install error. I want to either remove the app from the site or upgrade the app.

#### Observed Behavior
I am unable to remove the app from the site or upgrade the app.

#### Steps to Reproduce
Install an app that has a deployment error. Then try to remove it from the site. There is no uninstall/remove feature.

**Comment by mcmynn83** [comment]
This is currently a bug in the modern UI.  If you revert to the classic UI you will be able to remove the app.

**Comment by davidhartman** [comment]
Thanks I definitely should have checked the classic UI before posting!

**Comment by mcmynn83** [comment]
Excellent glad it worked for you.  The issue for fixing the modern UI is now tracked and we should fix it soon.
