### ISSUE TITLE
SPFX WebPart - AngularJS 1.5.8 - Error on Preview 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-webparts#188]
#### Category
- [ ] Question

I have created a SharePoint Framework WebPart using AngularJS 1.5.8. This is not using TypeScript. 

The WebPart works fine until I press Preview button in the workbench.html page. Once I click Preview button, I see the following error: 

Sometimes I see this error in the SharePoint Page where this WebPart is added. 

Any Idea?

![snip20170502_1](https://cloud.githubusercontent.com/assets/21008316/25623725/3af09dac-2f1d-11e7-8b1a-6692cf7cc47a.png)

![snip20170502_2](https://cloud.githubusercontent.com/assets/21008316/25623733/417ea3b2-2f1d-11e7-85a5-a431e56b9f6f.png)

**Comment by sprider** [comment]
@waldekmastykarz - Any suggestions?

**Comment by waldekmastykarz** [comment]
Could it be that you're bootstrapping the Angular application in the web part render method without wrapping it in `if (this.renderedOnce === false) { }`?

**Comment by sprider** [comment]
You are correct @waldekmastykarz. Will this affect the other SPFX WebParts in the same page which uses the same angualr js file?

**Comment by waldekmastykarz** [comment]
Could you also share the contents of `./config/config.json`? I'm curious how you are loading Angular and if you're seeing any errors related to it.

**Comment by sprider** [comment]
Hi @waldekmastykarz 

Please find the details below 
{
  "entries": [
    {
      "entry": "./lib/webparts/Recognition/RecognitionWebPart.js",
      "manifest": "./src/webparts/Recognition/RecognitionWebPart.manifest.json",
      "outputPath": "./dist/recognition.bundle.js"
    }
  ],
  "externals": {
    "angular": {
      "path": "https://<Our Akamai CDN path>/js/vendor/angular.1.5.8.min.js",
      "globalName": "angular"
    }
  },
  "localizedResources": {
    "RecognitionStrings": "webparts/Recognition/loc/{locale}.js"
  }
}

**Comment by sprider** [comment]
The issue is intermittent. Sometime it is working and sometime not. I feel there is a delay in loading the angualrjs file.

**Comment by waldekmastykarz** [comment]
Can you reproduce the issue with only one web part on the page?

**Comment by sprider** [comment]
No, The WebPart works consistently when I add it in a different page without other WebParts. 

We tried to load the angular file from page layout to see if it works when we have multiple WebParts but no luck.

**Comment by waldekmastykarz** [comment]
Do you see the issue only when loading Angular from CDN or also when it's included in the bundle?

**Comment by sprider** [comment]
Yes @waldekmastykarz. 

We can see the error when loading Angular from CDN as well bundle.

**Comment by waldekmastykarz** [comment]
I can't seem to repro it. Do you have a sample project with the issue that I could have a look at?

**Comment by sprider** [comment]
As it is company sensitive code, I just created sample files for your review. 

Please check your inbox for repository details.

**Comment by sprider** [comment]
I saw an issue posted for Jquery for similar scenario. 

https://github.com/SharePoint/sp-dev-fx-webparts/issues/192

**Comment by waldekmastykarz** [comment]
If I understood it correctly, in that case jQuery was already present on the page, plus the issue was with plugins, not jQuery itself.

**Comment by sprider** [comment]
Hi @waldekmastykarz 

We are getting the similar error when the webparts are failing. 

<object>.bootstrap is not a function. 

<object> = angular and this can be a.bootstrap or c.bootstrap based on bundled file.

**Comment by sprider** [comment]
@waldekmastykarz 

I found the root cause. The issue occurs when we have JavaScript custom actions with jQuery and angularJS SPFX WebParts in the page. 

The jQuery(1.11.1) loads from custom action giving some conflict to SPFX angularJs(1.5.8).

We have few site collection level custom actions(example : global navigation, site analytics telemetry, custom site request link) runs with jQuery(1.11.1). Now I have to find the jQuery version angularJs 1.5.8 likes or resolve the jQuery conflict issue. 

Changing the custom action jQuery version to 3.2.1 resolves the problem in all the browsers. I have verified this with one custom action and SPFX webpart combination in a page. 

Thoughts?

**Comment by sprider** [comment]
@waldekmastykarz 
I have created a repo with sample code and added you as contributor. Please check your account connected to your github. Please refer the readme file for more details.

**Comment by waldekmastykarz** [comment]
@sprider not sure if it's indeed the case, but jQuery v3.2.1 is being listed amongst AngularJS dependencies. You could try using that version to see if it helps to solve your issue.

**Comment by sprider** [comment]
@waldekmastykarz 

When I use V3.2.1 in custom action the SPFX webpart works in all the browsers except Safari. 
Are you suggesting to add jQuery 3.2.1 in SPFX WebPart as dependency?

**Comment by sprider** [comment]
@waldekmastykarz 

We have resolved this issue by removing JQuery from our custom actions for now. 

But I am not sure about MS recommendation for Custom Actions with JQuery added in the page with SPFX webPart plus Safari combination. It is definitely not working as we worked with MS engineer regarding this. 

I am closing this issue for now. Please reopen if required

**Comment by waldekmastykarz** [comment]
@sprider what was the error that you were getting in Safari?

**Comment by sprider** [comment]
Safari was not throwing any errors specifically. But other browsers threw the below error

TypeError: s.bootstrap is not a function

**Comment by waldekmastykarz** [comment]
> When I use V3.2.1 in custom action the SPFX webpart works in all the browsers except Safari.

This is why I asked specifically about Safari.

**Comment by sprider** [comment]
The SPFx web parts were failing intermittently with JQuery 3.x as well as 2.x but in safari we could reproduce this issue consistently. 

We have deployed our custom actions without JQuery and SPFx Webparts are 100% working in all the browsers including iPhone and iPad Safari.

**Comment by waldekmastykarz** [comment]
When the web part was failing in Safari, were you seeing a specific error?
