### ISSUE TITLE
Auto Image Slider

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#190]
@waldekmastykarz 
We have developed a web part which brings the data from a list which has images.
We want an auto slide for that images, for that we have used news carousal from [this ](https://github.com/OlivierCC/spfx-40-fantastics)from git hub.
This is a big problem for us , which is not working in classic pages with page layouts and master pages.
Always throws an error:
**Uncaught (in promise) TypeError: h(...).unitegallery is not a function**

Could you be able to help me in this? Or do you have any other alternative in spfx which suits my requirement?
Many thanks

**Comment by waldekmastykarz** [comment]
Could it be that there is another instance of jQuery already registered with the Master Page/Page Layout?

**Comment by sidjustsid** [comment]
@waldekmastykarz Yes we are having JQuery in master page as well.

**Comment by waldekmastykarz** [comment]
That would explain that the plugin is registering with the globally registered version of jQuery rather than the one you have in your web part.

What you could try is to load jQuery conditionally if there is no jQuery registered globally, using SPComponentLoader and then load the plugin. It would be something like:

```ts
  protected onInit(): Promise<void> {
    return new Promise<void>((resolve: () => void, reject: (error: any) => void): void => {
      if (!(window as any).jQuery) {
        SPComponentLoader.loadScript('https://cdn/jquery.min.js', {
          globalExportsName: 'jQuery'
        })
        .then((jQuery: any): Promise<void> => {
          (window as any).jQuery = jQuery;
          return this.loadPlugins();
        })
        .then((): void => {
          resolve();
        });
      }
      else {
        this.loadPlugins()
          .then((): void => {
            resolve();
          });
      }
    });
  }

  private loadPlugins(): Promise<void> {
    return new Promise<void>((resolve: () => void, reject: (error: any) => void): void => {
      SPComponentLoader.loadScript('https://cdn/plugin.js', {
          globalExportsName: 'jQuery'
        })
        .then((): void => {
          resolve();
        });
    });
  }
```
