### ISSUE TITLE
Double Jquery Issue

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#192]
Hi @waldekmastykarz  @mcmynn83 
I have two web parts and in both the web parts i am importing JQuery.
I am facing an Issue here, when one web part is loading the other is not loading because of double JQuery loading.

Screen shot of Config:
![image](https://cloud.githubusercontent.com/assets/26655462/25723495/d4abe2b6-3135-11e7-8160-f2f88fa67607.png)
Web part 1:
![image](https://cloud.githubusercontent.com/assets/26655462/25723511/eadb15c0-3135-11e7-999a-47798125a871.png)

web part 2:
![image](https://cloud.githubusercontent.com/assets/26655462/25723534/0576b204-3136-11e7-890c-f9f750e98032.png)

Is there any issue if i import Jquery in more than one web part? Or is there any other method to import?

**Comment by waldekmastykarz** [comment]
Do you have any errors in the console?

**Comment by sidjustsid** [comment]
@waldekmastykarz  Yes the functions in first web part are not working,
showing .Method is not a function.

Exact Error:

**Unite Gallery Error: You have some jquery.js library include that comes after the gallery files js include.
This include eliminates the gallery libraries, and make it not work.

To fix it you can:
    1. In the Gallery Settings -> Troubleshooting set option: Put JS Includes To Body option to true.
    2. Find the double jquery.js include and remove it.**

**Comment by waldekmastykarz** [comment]
If you have multiple web parts on the page, each loading its own copy of jQuery, then it can be the case that the plugin loads with a globally registered copy of jQuery instead of the copy registered with the particular web part. One solution could be to centralize loading of jQuery to a library, but that has currently a limitation of its own as libraries cannot be deployed beyond the local workbench.

One thing that you could try is to dynamically load jQuery using the `SPComponentLoader` only if it hasn't been already loaded. That should help you have only one copy of jQuery on the page and keep your plugins working.

**Comment by sidjustsid** [comment]
@waldekmastykarz 
Could you please point me to any article which has this example??
I am trying to do like below:
SPComponentLoader.loadScript('https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js', { globalExportsName: 'jQuery' }).then((jQuery: any): void => {
    this.jQuery = jQuery;        
  });

**Comment by waldekmastykarz** [comment]
This is correct, you should however run this code only if jQuery hasn't been previously registered on the page. You should be able to check it using `if (!window.jQuery) { ... }`

**Comment by sidjustsid** [comment]
@waldekmastykarz  Its is giving me below error  
![image](https://cloud.githubusercontent.com/assets/26655462/25736331/ca01f6ee-318e-11e7-9735-5a579abced8b.png)
My declaration:
![image](https://cloud.githubusercontent.com/assets/26655462/25736343/dd378eae-318e-11e7-9bd4-87b433429c19.png)

**Comment by waldekmastykarz** [comment]
You  should remove the old `jquery` reference from your web part.

**Comment by waldekmastykarz** [comment]
Which plugins are you using by the way, and how are you loading them?

**Comment by sidjustsid** [comment]
@waldekmastykarz  I am using Carousel from Unite gallery.
Below is the link i have followed
https://github.com/OlivierCC/spfx-40-fantastics/tree/master/src/webparts/newsCarousel

I am adding the web part in classic page.
Since i havent found any auto scroll or carousel , this was the only option for me in spfx.

**Comment by deanhtid** [comment]
I am having this exact issue but with the tiles Gallery. Can you please share how you resolved it?

Thanks

**Comment by dhavalshah01** [comment]
Do we have the resolution on the jquery conflict issue. I am facing an issue when we use two webparts both referencing jquery

**Comment by deanhtid** [comment]
No sorry, I never managed to resolve this.

**Comment by dhavalshah01** [comment]
Yeah, I have been trying out it for last week. Seems like there should be the way around this issue to work with multiple webparts referencing jquery.

**Comment by kmarwen** [comment]
I have the same issue with same webparts TilesMenu and AnimatedText, both use Jquery as a module
and when loading page Uncaught (in promise) TypeError is thrown
does anyone have workaround  plz ?
thx

**Comment by kmarwen** [comment]
So guys I found solution in another thread : 
[](https://github.com/OlivierCC/spfx-40-fantastics/issues/18)
like @OlivierCC did : 
it's a dirty solution but prevent jquery from multiple loadings, it consists of changing in jQuery source !!
in "\node_modules\jquery\dist\jquery.min.js" you can add in the first function
`if(window.jQuery)return;`
then you gulp serve and it's ok !

At the final I dont understand why jquery loads multiple times when it's not the same webpart (it should avoid this itself)
I think there's an issue with webpack 

so if one of you has the answer please let me know

**Comment by waldekmastykarz** [comment]
Unfortunately you can't quite do this. Because the node_modules folder is not committed to your source control by default, the next time someone else on your team restores project dependencies using the `npm install` command, your fix will be gone and they will build a broken version of the solution. A more reliable approach would be to load jQuery using SPComponentLoader and cancel loading in your code if jQuery is already present on the page.

**Comment by kmarwen** [comment]
Hi @waldekmastykarz 
I understand that node_modules is not controlled by source control
but also of course I tried to load only when Jquery is not yet loaded with SPComponentLoader, but it doesn't work, and each page load, one of the webparts (one of the jquery plugins) throws uncaught error

after that even with the dirty solution, when I load a page with 2 webparts from 2 different sppkg using jquery module also it throws uncaught error

it's weired that this issue doesnt occur for many people

**Comment by waldekmastykarz** [comment]
What isn't working exactly when using SPComponentLoader? Do you have a code sample that you could share to illustrate what you were trying to do?

**Comment by ymihir** [comment]
Hello @waldekmastykarz ,
I am also having similar issue. I am loading jQuery when it is not available. But I am using third party library for carousel. So after jQuery I have to load third party plugin as well which is dependent on jQuery. I am using below code.
```
public render(): void {        
    if(typeof(window['jQuery'])=='undefined'){
      SPComponentLoader.loadScript('https://code.jquery.com/jquery-3.2.1.min.js',{ globalExportsName: 'jQuery' }
    ).then(($: any) => {
      this.jQuery=$;
      //debugger;      
      require('MySlider');
      this.initProcess()
    });
    }
    else{
      require('MySlider');
      this.initProcess();
    } 
  }
```
But before checking jQuery, `require('MySlider')` code is executing. MySlider is loading thirdparty plugin, but at this time jQuery is not available.
Is there any other method that I can use to load the thirdparty plugin. This plugin doesn't have CDN so I cannot use `SPComponentLoader` method.

**Comment by waldekmastykarz** [comment]
If MySlider depends on jQuery then you can't use `require()` to load MySlider. Instead, you should load it using `SPComponentLoader` as well.

**Comment by ymihir** [comment]
If I try as below it is saying file not found.
```
SPComponentLoader.loadScript('/src/plugins/slider/jquery.lightslider.min.js').then((lightSlider:any)=>{
        this.initProcess();
      })
``` 
May be url i am passing is wrong. what could be the correct url?

**Comment by waldekmastykarz** [comment]
Check the browser's developer tools how the relative URL is being resolved and where is SharePoint trying to download the script from.

**Comment by ymihir** [comment]
I am checking at work bench url <siteurl>//_layouts/15/workbench.aspx. Error is saying `Error loading <siteurl>/src/plugins/slider/jquery.lightslider.min.js` of course yeah, it is wrong url. But no way to load local js files except import, require? SPComponentLoader is only taking url means js file has to be there in one of the library of SharePoint. By in my case, JS file is residing in the web part solution.

**Comment by kmarwen** [comment]
@ymihir try to load from cdn : 
[https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.js](url)

here the page for other componenet of lightslider 
[https://cdnjs.com/libraries/lightslider](url)

**Comment by ymihir** [comment]
True, this is not the plugin that I am using. I am using a very light weight one which doesn't have any CDN reference. Refer [github](https://github.com/Ajax30/lightslider). Can I use js file url from this project directly like `https://github.com/Ajax30/lightslider/blob/master/js/jquery.lightslider.min.js`?

**Comment by waldekmastykarz** [comment]
While you technically could, I wouldn't do it: it's too error prone and GitHub is not optimized for delivering static assets.

You're bringing up an interesting case. Let me see if I can find any more information about it.

**Comment by sidjustsid** [comment]
@waldekmastykarz  Is there any way that we can place the JS file in the project folder and call the function directly in any of my ts file ? I think this would solve the problem i feel.

**Comment by ymihir** [comment]
Right now I have kept the plugin js file site assets folder of SharePoint site and I am loading with `SPComponentLoader` method. This is working fine.

**Comment by ymihir** [comment]
@sidjustsid Yes, that is possible if we have any custom js file. But if we are using any third party plugins, and if we change something in it, we should be more extra cautious.

**Comment by sidjustsid** [comment]
@ymihir  can you send the snippet of how you are calling the function please? and , Do you need to load the file every time in the ts file?

**Comment by ymihir** [comment]
@sidjustsid  right now I am not using any custom js file to call the functions. But you need to load the file with import statement. In my case Importing js files as module not working as expected, so I always prefer `require`. 
Load your js file in the .ts file `mySlider = require('MySlider')` 
call the function now as `mySlider.moveLeft()`
Note: Don't forget that your custom js file should be registered in `config.json` as module

**Comment by cvharris** [comment]
I'm seeing the same but with AngularJS. There has to be a way that SPFX loads third party scripts with no conflicts, especially if they're the exact same file from a CDN.

**Comment by vipuliflex** [comment]
Any body got the solution of this issue we have got SPFX 1.10 release of the microsoft and still we are facing this issue.I am also facing this issue with "Kendo UI for Jquery" when multiple webparts are added on a page one of the webpart stops working randomly.I have tried all the options advised in this thread.Please suggest if anyone provide solution.

**Comment by hugoabernier** [comment]
Hey @vipuliflex are you still experiencing this issue or did you get a resolution for this?
