### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 ()

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-fx-webparts#196]
Hi @waldekmastykarz 
We are facing an issue with js files some times with **Failed to load resource: the server responded with a status of 429 ()**

Could you please help us in this?
I feel you are only the person who can guide us in this.

many thanks

**Comment by waldekmastykarz** [comment]
What files are those? Where are you loading them from?

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
They are JQuery files and yammer js https://c64.assets-yammer.com/assets/platform_js_sdk.js

We are loading them by placing in config.json and calling in wab part with require() for yammer and import * as jquery from "jquery " for jquery files.

The exact error is "rate limit is exceeded"

**Comment by waldekmastykarz** [comment]
What happens if you try to load the same scripts in the browser?

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
Below is the screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/26655462/25837147/b885f118-34a9-11e7-9a2a-53d53b35e595.png)

**Comment by Danny-Engelman** [comment]
429 is too many requests, the server allows an X amount of requests within a time-frame. 

Most often because the location/server is not meant to be used as CDN, 
or it is a Free service with a restriction, and you have to pay for unrestricted access.

You have to delay your request(s) and play the game by the Server rules.

**Comment by Danny-Engelman** [comment]
Note: 

That https://c64.assets-yammer.com/assets/platform_js_sdk.js
**also** contains jQuery

So it looks like you now load jQuery 3, 4, 5 times?

**Comment by sidjustsid** [comment]
@Danny-Engelman 

Thanks for the Info. 
Thats a default js we are using. Is there any way to restrict to load the JQuery only once?

Also, any idea on how to delay the requests in Typescript(SPFX)

Many thanks

**Comment by Danny-Engelman** [comment]
You are trying to run before you can walk.

Learn to deal with jQuery in a simple HTML page, 
**only** once you master that, can you apply your programming skills to SPFx

You are now learning things in the wrong order,

But you will only succeed with help from others
That means you will always need assistance from others

You don't learn how to delay requests in TypeScript...
you have to learn how to do it in JavaScript/ES6, 
TypeScript is only syntactic sugar to make writing ES6 easier

But if you don't understand ES6 ... you can never learn "TypeScript" (and you will always be copy/pasting snippets of code you don't understand)

You can't run before you have learned how to work

**Comment by sidjustsid** [comment]
@Danny-Engelman 
The issue is not with the JQuery or loading JQuery.

The issue is with the Rate Limit in Yammer. We will be seeing this error when the rate limit exceeds.
So, i just want to know is there any rate limit when we load client  side web parts.
If so, i would like to know how we can over come this.

**Comment by Danny-Engelman** [comment]
Rate limit is Server controlled,
it doesn't matter if you execute code as F12 Code Snippet, as Client Side
Web Part, as CEWP as NodeJS  or send them by pigeon

If you do too many requests you get a 429

**Comment by ashiqullah** [comment]
1.
