### ISSUE TITLE
WebPart Property containing HTML with <script> tag crash the WebPart

### ISSUE THREAD

**Issue by bpironet** [SharePoint/sp-dev-fx-webparts#201]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I'm creating a Client WebPart using SharePoint Framework. The idea is to have a custom property of type String using a PropertyPaneTextField where the user can put some HTML. The final idea is to allow users to integrate some social networks components (Twitter wall for example). 
If the property contains a <script> tag, the WebPart crash and display strange json content instead of the content. 
Example HTML causing the issue: 
`<a class="twitter-timeline" data-width="220" data-height="400" data-dnt="true" href="https://twitter.com/sharepoint">Tweets by SharePoint</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

When inserting the HTML, the script is not called and only the basic HTML is displayed in real time. When you save the WebPart and the page reload, the WebPart is broken and displays some json content:
`","Title":"My Twitter Feed"}}\" data-sp-splinksapplied=\"true\">
c82b67dc-2557-4dc2-a738-4ee411ad3583
", 1, 1, false, []); } catch (e) { if (application != null && application.logClientSideWebPartLoadError != null) { application.logClientSideWebPartLoadError("g_16d93d7a_ad57_4fb1_8220_6d434d49ac6e", "Cannot load a web part on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details."); console.error(e); } else { console.error("Cannot load a web part on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details."); console.error(e); } } }); } else { console.error("Cannot load the web part wrapper on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site."); } })(window);`

#### Observed Behavior
I would have expected that the HTML is displayed and the script called or at least that the script is blocked as it is the case for the Page Content but the WebPart should not crash. 

#### Steps to Reproduce
All steps already explained. 
I display my property with the render method: 
`  public render(): void {
    this.domElement.innerHTML = ``
      <div class="webpart webpart-html webpart-${this.context.instanceId}">
        <h2>${this.properties.Title}</h2>
        ${this.properties.HTMLContent}
      </div>``;  
  }`
(`` char have been doubled because of GitHub formatting)

The Edit Pane is coded with: 
`groupFields: [
                PropertyPaneTextField('Title', {
                  label: strings.PropertyTitleLabel
                }),
                PropertyPaneTextField('HTMLContent', {
                  label: strings.PropertyHTMLContentLabel,
                  multiline: true
                })
              ]`

Please note that even if I remove the ${this.properties.HTMLContent} is my render() method, so that the HTML is not displayed in the page, the WebPart still crash. 

Also note that when the WebPart is crashed, if I try to edit the properties, it says that there is no property to edit for this WebPart. My only way out is to delete the WebPart and start again. 

Thank you in advance,
Regards,
Benoit Pironet

**Comment by waldekmastykarz** [comment]
Have you looked at the Script Editor web part @wobba made (https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-script-editor) and check out how he deals with script references?

**Comment by wobba** [comment]
The clue is that you cannot just output a script tag and expect it to be loaded. Check out the executeScript method in https://github.com/SharePoint/sp-dev-fx-webparts/blob/dev/samples/react-script-editor/src/webparts/scriptEditor/ScriptEditorWebPart.ts which handle src tags and blocks - meaning loads the src scripts and evals blocks. A SPFx part is running after the dom is loaded, so injecting scripts has to be handled manually.

**Comment by Danny-Engelman** [comment]
**Question:**
In 2013 Microsoft did the same (blocking SCRIPT tags) with HTML content in
Calculated Columns, but events still can trigger JS execution.

My favorite is:

```
<img src="data:" onerror="alert('The blue pill or the red pill?')">
```

As it does not cause a network request

**Is this blocked by SPFx code as well?**

**Comment by bpironet** [comment]
Wow! Thank you for the support! 
I've analyzed the WebPart of @wobba and I tried to include what I needed from it. 
I've currently included the display of the code but not the react component for editing the properties in the popup... but my bug is still present... 
So my question, was the popup created to avoid this bug and just to demonstrate the saving of properties somewhere else than in the normal properties pane? 
I would like to avoid including React in my project (to keep things simple) and so I would like to avoid this popup and use the normal properties pane editor.

Thank you in advance for your precisions. 

Regards,
Benoit Pironet

**Comment by wobba** [comment]
Did you try to run encodeURIComponent/decodeURIComponent on the html fragmen on save/load to avoid any weird issues? Or btoa/atob if on IE10 or newer.

**Comment by bpironet** [comment]
@wobba, which method can I use for the save event? I had a look a the onBeforeSerialize() but it is called to much time.

**Comment by bpironet** [comment]
It is finally working! 
So I decoded my property before rendeing: 
`let HTMLContentDecoded = decodeURIComponent(this.properties.HTMLContent); `

And I set my WebPart as non reactive: 
`
protected get disableReactivePropertyChanges(): boolean {
    return true;
  }
`
Then, I used the method onAfterPropertyPaneChangesApplied to encode the HTML content: 
`
  protected onAfterPropertyPaneChangesApplied(): void {
    this.properties.HTMLContent = encodeURIComponent(this.properties.HTMLContent);
  }
`
A also used the method 'executeScript' as proposed by @waldekmastykarz and wrote by @wobba but I included a recursive analysis of the HTML element of the DOM of the WebPart to search for <script>. 

Thank you for your support!
