### ISSUE TITLE
[Question] Call SP rest api with error 403 (Forbidden)

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-fx-webparts#202]
Hi guys,

I'm trying to get sub webs for current user (with Read permission level) in SharePoint client-side web part (React framework) but I got an error 403 (Forbidden).
What I tried to use as the followings (send a request to "/_api/web/webs"):

1. Using SPHttpClient
2. $pnp.sp.web.webs.filter
3. httpClient

I thought I need to add a header "X-RequestDigest" to request header but I got the same error message when trying to get FormDigestValue for "/_api/contextinfo" endpoint.

For the current user, I was able to get sub webs (including app webs) for him by using JSOM:
webCollection = web.getSubwebsForCurrentUser(null);
context.load(webCollection);

Do you have any ideas to fix this issue?
Thanks!

**Comment by bpringe** [comment]
I'm having the same issue when trying to request items from a list in SharePoint Online using a SharePoint Framework webpart. I see this in the response header for the request:
X-MSDAVEXT_Error:917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
But I am logged into the site.
