### ISSUE TITLE
Re-render web part after Custom Property Pane Field Value has been changed

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-fx-webparts#216]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

In previous drops we had a `onPropertyChange` method that could be used in Custom Property Pane Field to update web part field and initiate re-render.

in GA drop this method is deprecated. And we're using next construction:

- first, we're passing on web part properties and `onPropertyPaneFieldChanged` to Custom Property Pane Field
- then, when needed, we use next construction:
`
// this here is Custom Property Pane Field
`
`this.properties.webPartProperties[targetProperty] = newValue;
`
`
this.properties. onPropertyPaneFieldChanged(targetProperty, oldValue, newValue)
`
It works fine in Workbench and `onPropertyPaneFieldChanged` initiates re-render of the web part.

But if you install your web part to the SharePoint Online, re-render will not be initiated. The reason for that is that in new code deployed to SharePoint re-render is called in **internal** `onPropertyPaneFieldChanged` method that is not available for us.

So, the question is **how to correctly initiate web part re-render after Custom Property Pane Field change?**

Thanks in advance

**Comment by VesaJuvonen** [comment]
Hi Alex, could you actually create this question to sp-dev-docs repository. That's where we have direct linking of issues cross GitHub and our internal tasks lists... since this is potential bug in the production. I'd suggest to close this one and move the question to sp-dev-docs, so that more wider audience from engineering can address it. thx.

**Comment by AJIXuMuK** [comment]
Moved to sp-dev-docs ([#594](https://github.com/SharePoint/sp-dev-docs/issues/594))
