### ISSUE TITLE
react-aad-implicitflow does not work well when deployed on modern web pages.

### ISSUE THREAD

**Issue by filionf** [SharePoint/sp-dev-fx-webparts#221]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I am expecting the webpart to work the same as on the workbenches when added to a modern web page.

#### Observed Behavior
It does work the same if the path I used for login ends with a backslash, but not if it ends with aspx. For example, 
`https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx` will proceed with signin, but does not show the upcoming events and `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx/` works as I would expect the first link to work. 

#### Steps to Reproduce
1. Assuming the webpart is well configured (Reply Urls, ...) and saved to the page. Go to `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx` in a Private or Incognito Window, 
2. Sign in to Office 365
3. Click the signin button of the web part.
The popup window will appear briefly, the loading spinner will appears on the web part and then display the following error: `Error: Token renewal operation failed due to timeout`

#### Redirection
When capturing the redirects, once I click the signin button, I see the following requests go through
- `https://login.microsoftonline.com/common/oauth2/authorize?...`: 302
- `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx`: 200
- A few js files.
- `https://contoso/sites/dev-portal/SitePages/access_token=...`: 400 - The request URL is invalid.
- `https://browser.pipe.aria.microsoft.com/Collector/3.0/...`: Cancelled

If I use the URL ending with a slash, the one that works, the `https://contoso/sites/dev-portal/SitePages/access_token=...` request does not appear.

#### Other notes
If the signin is done using the `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx/` url, going to `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx` will work. If the signin is done using the `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx` url, going to `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx/` will not work. That is why the incognoto window is important.

See https://sharepoint.stackexchange.com/questions/214887/react-aad-implicitflow-works-only-in-workbench for more context information.

**Comment by waldekmastykarz** [comment]
What URL have you used as the reply URL of your AAD application?

**Comment by filionf** [comment]
The App ID URI is : `https://contoso/sites/dev-portal/`
The Home page URL is `https://contoso/sites/dev-portal/`
And the following reply urls are defined:
- `https://contoso/sites/dev-portal/SitePages/Layout%20Test.aspx`
- `https://contoso/sites/dev-portal/SitePages/ModernLayoutTest.aspx`
- `https://contoso/sites/dev-portal/_layouts/15/workbench.aspx`
- `https://localhost:4321/temp/workbench.html`

**Comment by waldekmastykarz** [comment]
Have you tried changing the Home page URL to the URL of modern page on which you are testing the web part?

**Comment by filionf** [comment]
It gives the same behaviour.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
