### ISSUE TITLE
react-aad-implicitflow error in classic ui

### ISSUE THREAD

**Issue by iceshine34** [SharePoint/sp-dev-fx-webparts#222]
I'm trying to use react-aad-implicitflow in sharepoint online classic pages,not modern page,and there is an error.The message is "cannot read the component","cannot read entry point from UpcomingMeetingsWebPart" "did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support"

And also the same result using another sample "angular-msgraph". I am wondering if these webparts only works fine in modern UI,not the classic UI?

This is the error when I use IE11,but when I use Chrome,the error does not occur!

**Comment by waldekmastykarz** [comment]
Have you checked the developer tools console to see if there are any errors when loading the web part bundle?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
