### ISSUE TITLE
aad-api-spo-cookie POST call

### ISSUE THREAD

**Issue by MarianoPrz** [SharePoint/sp-dev-fx-webparts#230]
can i do a post call with this type of authentication? i can perform a get ca ll without problem, but the post call, i can't. I can't finde an example of that,. thanks

**Comment by waldekmastykarz** [comment]
Can you tell something more what kind of call you would like to execute?

**Comment by Greg-Hitchon** [comment]
I had a similar issue which was due to the following issue as described [here](https://stackoverflow.com/questions/38630765/azure-website-rest-api-only-accept-get-post-returns-403-possibly-cors)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
