### ISSUE TITLE
Lesson learned from SPFx examples 🎁

### ISSUE THREAD

**Issue by Danny-Engelman** [SharePoint/sp-dev-fx-webparts#232]
#### Category
- [X] Enhancement

(after 12 years) I am leaving the Microsoft Front-end world,  
I believe in WebComponents, and that ain't fun with [SharePoint rewriting my precious files](https://github.com/SharePoint/sp-dev-fx-webparts/issues/153)

For the past year I have used SPFx examples in my JavaScript classes.  
A shame to let educational resources go to waste. 

[https://github.com/Danny-Engelman/CKTA](https://github.com/Danny-Engelman/CKTA)

[![](http://i.imgur.com/l65o93Z.jpg)](https://github.com/Danny-Engelman/CKTA)

**Comment by VesaJuvonen** [comment]
This clearly is not an issue, so closing this one. We absolutely welcome pull requests towards existing samples. thx.
