### ISSUE TITLE
Missing option in SPFx Yeoman generator in latest

### ISSUE THREAD

**Issue by SPDoctor** [SharePoint/sp-dev-fx-webparts#233]
#### Category
- [ x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Yeoman @microsoft/sharepoint-generator prompts for solution name and then "Where do you want to place the files?". Options are current folder or subfolder with solution name. This is the behaviour for previous versions before the extensions preview.

#### Observed Behavior
Next question is "Which type of client-side component to create?"

#### Steps to Reproduce
Make sure you have latest version of generator:
`npm install -g @microsoft/generator-sharepoint
`
#### Question
Is this the intended behaviour? If it is we need to flag this in the documentation as some users will be habituated to creating a subfolder and, in the absence of the prompt, will dump the generated file structure in their top-level directory :-P

**Comment by chakkaradeep** [comment]
Thanks for reporting this. We will be fixing this soon.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
