### ISSUE TITLE
SPFx Webparts not working on classic pages

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-fx-webparts#234]
#### Category
- [X ] Bug

#### Expected or Desired Behavior
Microsoft people told us, SPFx Webparts should be able to work on modern and classic pages. Unfortunately they stopped working on classic pages. The page isn't trying to load anything from the Webpart. It just shows the webpart title and does nothing else.
In the console we can see an error related to not escaping string delimiters in the source of the SharePoint homepage.aspx:
                     try {
                        application.loadWebPart("g_388b6a68_273f_4436_8734_f2b8cb2c3ad6", "bb38fa95-ee46-40e2-a673-4034d2749e2e", "<div data-sp-webpart=\"\" data-sp-webpartdataversion=1.0 data-sp-webpartdata=\"&#123;&quot;id&quot;&#58;&quot;bb38fa95-ee46-40e2-a673-4034d2749e2e&quot;,&quot;instanceId&quot;&#58;null,&quot;title&quot;&#58;&quot;HelloWorld&quot;,&quot;description&quot;&#58;&quot;HelloWorld description&quot;,&quot;version&quot;&#58;&quot;0.0.2&quot;,&quot;properties&quot;&#58;&#123;&quot;description&quot;&#58;&quot;HelloWorld&quot;&#125;,&quot;htmlProperties&quot;&#58;null&#125;\"><div data-sp-componentid=\"\">bb38fa95-ee46-40e2-a673-4034d2749e2e</div><div data-sp-htmlproperties=\"\"></div></div>", 1, 1, false, []);
                        }
                     catch (e) {
                        if (application != null && application.logClientSideWebPartLoadError != null) {
                          application.logClientSideWebPartLoadError("g_388b6a68_273f_4436_8734_f2b8cb2c3ad6", "Ein Webpart auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website, und teilen Sie ihm die Informationen unter "Technische Details" mit.");
                          console.error(e);
                        }
                        else {
                            console.error("Ein Webpart auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website, und teilen Sie ihm die Informationen unter "Technische Details" mit.");
                            console.error(e);
                        }
                      }
                   });
                 }
                 else {
                   console.error("Der Webpart-Wrapper auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.");
                 }

Obviously all "console.error" statements that contain strings are not escaping the string delimiters inside the string. Maybe that's the reason why the Webpart isn't loading but at least it prevents the exception from being shown (console.error(e) is behind the error...)

#### Steps to Reproduce
Build the SPFx "Hello World" WebPart and try to display it on a classic page.

**Comment by BigEaseGueldi** [comment]
Hi @cwdata ,
you might want to have a look at the issues logged at https://github.com/SharePoint/sp-dev-docs.

https://github.com/SharePoint/sp-dev-docs/issues/587
https://github.com/SharePoint/sp-dev-docs/issues/596
https://github.com/SharePoint/sp-dev-docs/issues/552

-> It's a language problem. Toll. ;-)

**Comment by cwdata** [comment]
This bug has now been fixed. Reference: 
[SharePoint/sp-dev-docs#596](https://github.com/SharePoint/sp-dev-docs/issues/596)
