### ISSUE TITLE
React Textfield with ribbon

### ISSUE THREAD

**Issue by KEMiCZA** [SharePoint/sp-dev-fx-webparts#238]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Question
Hi all, I'm wondering if it's possible to use a Textfield with the ribbon included using React? The standard text webpart has it. I'm creating another webpart where the user is required to fill in some input/text but I would like to make the ribbon visible. Is this possible out of the box with React and Fabric UI or does SharePoint use some custom code to manage this? Thanks

![image](https://user-images.githubusercontent.com/3862716/27025964-8c810ff8-4f5c-11e7-935b-bce135bcb294.png)

**Comment by VelinGeorgiev** [comment]
The text webpart uses CKEditor "under the hood", but I do not think there is an api so you can re-use it.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
