### ISSUE TITLE
Error loading react-todo-basic webpart sample

### ISSUE THREAD

**Issue by ortiox** [SharePoint/sp-dev-fx-webparts#241]
Category
- [X] Question
- [X] Bug
- [ ] Enhancement

Expected or Desired Behavior:
Tried loading the react-todo-basic webpart sample on my dev site workbench.

Observed Behavior:
Received the following error within the webpart:
Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
***ERROR MESSAGE:
***Failed to load component "acbc7f18-e38b-40c1-bf84-3e9eea368ca5" (TodoWebPart).
Original error: ***Failed to load entry point from component "acbc7f18-e38b-40c1-bf84-3e9eea368ca5" (TodoWebPart).
Original error: Error loading https://component-id.invalid/acbc7f18-e38b-40c1-bf84-3e9eea368ca5_0.0.1
	Cannot find module "./TodoForm.module.css"

***CALLSTACK:
Error: ***Failed to load component "acbc7f18-e38b-40c1-bf84-3e9eea368ca5" (TodoWebPart).
Original error: ***Failed to load entry point from component "acbc7f18-e38b-40c1-bf84-3e9eea368ca5" (TodoWebPart).
Original error: Error loading https://component-id.invalid/acbc7f18-e38b-40c1-bf84-3e9eea368ca5_0.0.1
	Cannot find module "./TodoForm.module.css"
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-02.013/workbench-assembly_en-us_6328050b205606c7777c58b90cc2afcb.js:110:205268
    at <anonymous>

Steps to Reproduce:
Followed the basic instructions here:  https://github.com/SharePoint/sp-dev-fx-webparts#using-the-samples, then added the 'todo' webpart on my developer tenant workbench page.

**Comment by VesaJuvonen** [comment]
Fixed now with the latest version. Thx for reporting the issue.
