### ISSUE TITLE
Web Parts using GQL and SharePoint Search API needs to be updated.

### ISSUE THREAD

**Issue by Cecildt** [SharePoint/sp-dev-fx-webparts#242]
#### Category
- [ ] Question
- [x] Bug
- [x] Enhancement

#### Observed Behavior
Sample web parts that use the GQL and SharePoint Search API will stop working by 19 June 2017 and the GQL API will be discontinued by August 2017. The current samples will not provide the right guidance to developers.

According to the Microsoft article below the correct guidance is to use the Microsoft Graph API.

#### Steps to Reproduce
https://msdn.microsoft.com/en-us/office/office365/howto/query-office-graph-using-gql-with-search-rest-api

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
