### ISSUE TITLE
knockout-taxonomy - Error in httpClient cannot find Response, Body, Headers,...

### ISSUE THREAD

**Issue by Zllzn** [SharePoint/sp-dev-fx-webparts#245]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Gulp should build the typescript completely

#### Observed Behavior
Getting errors when I try to build knockout-taxonomy.
Error - typescript - node_modules\@microsoft\sp-http\lib\graphHttpClient\GraphHttpClientResponse.d.ts(11,26): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClient.d.ts(63,44): error TS2304: Cannot find name 'RequestInit'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(14,51): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(14,61): error TS2304: Cannot find name 'Body'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(15,30): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(19,26): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(25,19): error TS2304: Cannot find name 'ReadableStream'.
Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(73,22): error TS2304: Cannot find name 'Headers'.
Error - typescript - node_modules\@microsoft\sp-http\lib\spHttpClient\ODataVersion.d.ts(22,40): error TS2304: Cannot find name 'Headers'.
Error - typescript - node_modules\@microsoft\sp-http\lib\spHttpClient\SPHttpClientResponse.d.ts(10,26): error TS2304: Cannot find name 'Response'.
Error - 'typescript' sub task errored after 2.58 s
 "TypeScript error(s) occurred."

#### Steps to Reproduce
Get last version of knockout-taxonomy, install the dependancies with npm install.
Type gulp build or gulp serve.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
