### ISSUE TITLE
Pictures broken in angular sample

### ISSUE THREAD

**Issue by panjkov** [SharePoint/sp-dev-fx-webparts#248]
#### Category
- [x] Bug

#### Expected or Desired Behavior
Pictures should be visible in readme.md file of Angular-MSGraph sample https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/angular-msgraph

#### Observed Behavior
Pictures are not visible and seem broken. Issue appeared because in last commit all pictures in assets folder are overwriten by html documents.

#### Steps to Reproduce
1. Open readme file https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/angular-msgraph
2. Instead of pictures in documents, broken placeholder is rendered.

Last commit for all files in assets folder should be reverted.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
