### ISSUE TITLE
Create Item fails

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-fx-webparts#25]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
[ ] Question
[X ] Bug
[ ] Enhancement

#### Expected or Desired Behavior
Item Should be created

#### Observed Behavior
I error message :
[SPFX-CRUD.docx](https://github.com/SharePoint/sp-dev-fx-webparts/files/489782/SPFX-CRUD.docx)

#### Steps to Reproduce
I packaged solution as per Sample 3 (add sample to sharepoint) ran gulp serve --nobrowser.  Added webpart to page.  Created list with just title field.  Set up list name in webpart properties. Run Web part - clicked on create item and got this failure.

Thanks for your contribution! Sharing is caring.

**Comment by NPrice99** [comment]
OK - it looks as if the path of the List is hardwired to <tenant-name>\sites\.  If I create a new site collection <Tenant-Name>\sites\SPFx then it works.  BTW I was using the SP-PNP-JS version of the webpart.

**Comment by waldekmastykarz** [comment]
Thanks for reaching out Nigel! Could you please share the URL you entered in workbench.aspx and the raw request and response that failed from the browser's dev tools? If there is any bug in the sample these data could help us fix it for others 😄

**Comment by NPrice99** [comment]
Hi Waldek

<Tenant Name>.sharepoint.com/SitePages/SharePoint-CRUD.aspx failed  - 
![sharepointcrud-fail](https://cloud.githubusercontent.com/assets/8484048/18814510/465d04da-830d-11e6-8479-55ebb498afc2.png)

<Tenant Name>.sharepoint.com/sites/SPFX/SitePages/Home.aspx worked - 
![sharepointcrud-worked](https://cloud.githubusercontent.com/assets/8484048/18814529/b436cda6-830d-11e6-9ba7-d407007a9911.png)

Regards

Nigel

**Comment by waldekmastykarz** [comment]
Thanks Nigel. Could you please share both files so that we can have a look at their contents?

**Comment by NPrice99** [comment]
Hi Waldek

Which files ?

I just used the files which came with the CRUD example ?

I did not change anything.

Regards

Nigel

**Comment by waldekmastykarz** [comment]
One of the configuration steps described in the readme.md of the CRUD sample says to take the `workbench.html` file generated by your project, rename to .aspx and upload to SharePoint. Did you use that approach or did you add web parts to a classic page?

**Comment by NPrice99** [comment]
I used the add web part to a classic page method.

**Comment by waldekmastykarz** [comment]
On the **.sharepoint.com/SitePages/SharePoint-CRUD.aspx** page that's failing, could you please open the developer tools, copy the details of the failed request and share them here?

**Comment by NPrice99** [comment]
This is from Google Chrome dev tools console :-

p-pn-p-js-crud.bundle.js:2603 GET https://<tenant<https://%3ctenant> name>.sharepoint.com/_api/web/lists/getByTitle('CRUD-LIST')/items?$orderby=Id&$top=1&$select=Id 404 (Not Found)

**Comment by waldekmastykarz** [comment]
Could you please confirm that you have a list named **CRUD-LIST** in this site?

**Comment by NPrice99** [comment]
No My list is called SHAREPOINT-CRUD and is available on both the site which works and the site which does not.  I don’t have a list called CRUD-LIST in either site.

**Comment by NPrice99** [comment]
|HI Waldek

I have just checked the web part properties and the List Name was set to CRUD-LIST.  I have now changed it to SHAREPOINT-CRUD and it worked.

I thought I had changed it to SHAREPOINT-CRUD, perhaps the change was not taken.

Many apologies for wasting your time.

Could I suggest a small enhancement to the APP to prevent this happening with other people, that the name of the list being used is displayed by the web part in the first line say ?

Apologies again.

Nigel

**Comment by waldekmastykarz** [comment]
Not a problem Nigel! I'm glad we figured this out 😄

**Comment by NPrice99** [comment]
Hi Waldek

This is the changed line to add the name of the list to the heading –

            Sample SharePoint CRUD operations using the SP PnP JS library and using List ${this.properties.listName}

Regards

Nigel
