### ISSUE TITLE
Fabric Office-UI Label appends colon : inconsistent, not on workbench but packaged/shipped

### ISSUE THREAD

**Issue by DennisKuhn** [SharePoint/sp-dev-fx-webparts#254]
#### Category
- [X] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
That the Label produces the same output when using workbench and when packaged/shipped.

#### Observed Behavior
On the workbench, the Label displays only the text contained in it. When packaged/shipped, a colon : is append to the text content.

#### Steps to Reproduce
Create a Label with text content and compare the output on a workbench and when packaged/shipped:

```
import * as React from 'react';
import { Label } from 'office-ui-fabric-react';
export default class LabelTest extends React.Component<ILabelTestProps,{}> {
public render(): JSX.Element {
	return (
		<Label>
			{ "Hello World" }
		</Label>
	)
} }
```
On the workbench it displays `Hello World`
when packaged/shipped it displays `Hello World:` (colon appended)

[Ram](https://sharepoint.stackexchange.com/users/37262/ram) pointed out on my [stackexchange question](https://sharepoint.stackexchange.com/questions/219761/packaged-shipped-version-adds-to-data-workbenches-are-fine) that the colon is added by the CSS `label::after { content: ":"; }` . That CSS does not exist on the workbench.

My workaround is to add `label::after { content: ""; }` to my CSS, then the Label output becomes consistent without an appended colon.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
