### ISSUE TITLE
Vuejs sample, editing .vue files doesn't trigger TS to recompile

### ISSUE THREAD

**Issue by aozora** [SharePoint/sp-dev-fx-webparts#255]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
After run "gulp serve", editing a .vue file should trigger TS to recompile and reload the browser.

#### Observed Behavior
Editing .vue files doesn't have any effect, I have to stop the server and re-run "gulp build" or "gulp serve" to have the new code compiled and running.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
