### ISSUE TITLE
Angular MS Graph Web Part Built with Angular v1.x - The screen shots are missing

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/sp-dev-fx-webparts#264]
#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

#### Observed Behavior
In the Angular MS Graph Web Part Built with Angular v1.x sample the screen shots are missing.

#### Steps to Reproduce
see readme.

**Comment by henryoh007** [comment]
This appears buggy ... tried running is the new version still in Angular 1x ?
[msgraphErrors.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/1166504/msgraphErrors.txt)

Also getting a blank screen at 
https://telemetry.sharepointpnp.com/sp-dev-fx-webparts/samples/angular-msgraph

**Comment by henryoh007** [comment]
I am seeing the issue .. scratch this bug. It is built and works in Angular 1.x
