### ISSUE TITLE
sharepoint-crud  operation on my  personal site url 

### ISSUE THREAD

**Issue by Jiannko** [SharePoint/sp-dev-fx-webparts#270]
#### Category
- [ ] Question
- [ ] Bug

#### Desired Behavior
A webaprt added to a sitecollection1 which is performing SharePoint crud Operations  to a list in another sitecollection2
Below solution was used  ,  and  this.context.pageContext.web.absoluteUrl was hardcoded with sitecollection2 URL 
Reference :- https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/sharepoint-crud/src/webparts/noFrameworkCrud/NoFrameworkCrudWebPart.ts

#### Expected Behavior
The solution works for any other siteollection except for mypersonal site 
https://xxx-my.sharepoint.com/personal/xxx_xxx_onmicrosoft_com/ URL

#### Observed Behavior
-Item 'undefined' (ID: undefined) successfully created on Create Item
https://xxx-my.sharepoint.com/personal/xxx_xxx_onmicrosoft_com/_api/web/lists/getbytitle('ListName')/items?$select=Title,Id 403 Forbidden from console
https://xxx-my.sharepoint.com/personal/xxx_xxx_onmicrosoft_com/_api/web/lists/getbytitle('ListName')/items 403 Forbidden from console
But I am able to  Access Rest URL from the browser 

Thanks,

**Comment by Jiannko** [comment]
Does any Body have any thoughts on this issue ?

**Comment by waldekmastykarz** [comment]
I suspect the error to be cause by cross-domain communication as the personal site is located on another domain than your page. Does the web part work after you visited the personal site in the browser (and have a valid authentication cookie in your browser)?

**Comment by Jiannko** [comment]
No the Webpart doesnt work . 
So do we have any menas to acheive this senario using a spfx Webpart ?

**Comment by waldekmastykarz** [comment]
You could try registering an AAD app with sufficient permissions to create items in SharePoint. That AAD app would be used by an API that you could call from the web part. The communication between the API and SharePoint would be done using app-only context. Ideally, you would secure the access to the API with Azure AD and then using ADAL in your web part, you would communicate with it from your web part. For more information see this article https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad

**Comment by Jiannko** [comment]
@waldekmastykarz  Thankyou for the guidance . Do you if this Webpart will work for the Classic UI ?

**Comment by waldekmastykarz** [comment]
It should

**Comment by NewJ123** [comment]
Is there any other way instead of registering an AAD App? can i set (or change) context to get data from other site collection?

**Comment by waldekmastykarz** [comment]
@NewJ123 Not that I know of

**Comment by criminalloop** [comment]
Hello... sorry to bring this up... but I have exactly the same problem described by Jiannko.
I got a 403 forbidden querying a list in my personal site using REST. The rest url in the browser works fine and the rest url for other site collections works fine too.

Jiannko, how did you resolve this?

Thanks.

**Comment by hugoabernier** [comment]
@Jiannko were you able to solve this issue?

If you're still experiencing issues, you may want to look at the [Comparer Web Part sample](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-comparer/src/services/OneDriveServices/OneDriveServices.ts), which implements a File Picker. 

It uses `SP.RemoteWeb` to make a REST call to a personal site from a web part.

I'll close this issue because it is several years old and gets no visibility. If you're still running into problems, please open a new issue to help get more people looking at it.

I hope this helps?
