### ISSUE TITLE
Render error in /js-employee-spotlight/

### ISSUE THREAD

**Issue by dmcrock** [SharePoint/sp-dev-fx-webparts#274]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
On the main web part page, in the PropertyPane section it says it is missing the 'render' property

#### Observed Behavior
On the main web part page, in the PropertyPane section it says it is missing the 'render' property. Actual error reads:
[ts] Argument of type '{ label:string; initialColor: string; disabeled:false;onPropertyCahnge:any; properties:IEmpl...' is not assignable to paramenter of type 'IPropertyFieldColorPickerMiniProps'.
Property 'render' is missing in type '{ label:string; initialColor: string; disabeled:false;onPropertyCahnge:any; properties:IEmpl...'
(property) onGetErrorMessage: null

#### Steps to Reproduce
run web part, error

thank you for looking into this

**Comment by dmcrock** [comment]
So i solved the "render" issue by adding render: this.render.bind(this), however now I am getting this error when running 'gulp':

Error - typescript - node_modules/sp-client-custom-fields/node_modules/@microsoft/sp-http/lib/httpClient/HttpClientResponse.d.ts(14,21):
 error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
Error - typescript - node_modules/sp-client-custom-fields/node_modules/@microsoft/sp-http/lib/httpClient/HttpClientResponse.d.ts(25,19):
 error TS2304: Cannot find name 'ReadableStream'.

**Comment by dmcrock** [comment]
to better explain: I am running this sample as is, cloned repository->npm install->tsd install -> gulp serve and then this is the error chain: typescript in VScode is using 2.1.6

[15:34:42] ==================[ Finished ]==================
Error - typescript - node_modules/sp-client-custom-fields/node_modules/@microsoft/sp-http/lib/httpClient/HttpClientResponse.d.ts(14,21):
 error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
Error - typescript - node_modules/sp-client-custom-fields/node_modules/@microsoft/sp-http/lib/httpClient/HttpClientResponse.d.ts(25,19):
 error TS2304: Cannot find name 'ReadableStream'.
Error - typescript - src/webparts/employeeSpotlight/EmployeeSpotlightWebPart.ts(22,24): error TS2307: Cannot find module 'jquery'.
Error - typescript - src/webparts/employeeSpotlight/EmployeeSpotlightWebPart.ts(133,44): error TS2304: Cannot find name '$'.
Error - typescript - src/webparts/employeeSpotlight/EmployeeSpotlightWebPart.ts(428,65): error TS2345: Argument of type '{ label: string
; initialColor: string; disabled: false; onPropertyChange: any; properties: IEmplo...' is not assignable to parameter of type 'IProperty
FieldColorPickerMiniProps'.
Error - typescript - src/webparts/employeeSpotlight/EmployeeSpotlightWebPart.ts(438,67): error TS2345: Argument of type '{ label: string
; initialColor: string; disabled: false; onPropertyChange: any; properties: IEmplo...' is not assignable to parameter of type 'IProperty
FieldColorPickerMiniProps'.
Error - 'typescript' sub task errored after 3.58 s
 TypeScript error(s) occurred.
[15:34:42] Project js-employee-spotlight version: 0.0.1
[15:34:42] Build tools version: 2.7.3
[15:34:42] Node version: v6.10.0
[15:34:42] Total duration: 12 s
[15:34:42] Task errors: 7

**Comment by AzureDevOpsDemo** [comment]
Hello, 

Basically you need to add the below properties. 
render 
disableReactivePropertyChanges

See below example for reference

 PropertyFieldColorPickerMini('spotlightBGColor', {
                  label: strings.spotlightBGColorLableMessage,
                  initialColor: this.properties.spotlightBGColor,
                  disabled: false,
                  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
		  render: this.render.bind(this),
 		  disableReactivePropertyChanges: this.disableReactivePropertyChanges,
                  properties: this.properties,
                  onGetErrorMessage: null,
                  deferredValidationTime: 0,
                  key: 'spotlightBGColorFieldId'
                }), 

Hope it helps.

**Comment by hugoabernier** [comment]
Hey @dmcrock  did @AzureDevOpsDemo 's solution help you solve this issue?

I'll go ahead and close it, because it is a few years old, but we'd love to know if the solution worked.

Feel free to open a new issue if you continue to experience issues with this.
