### ISSUE TITLE
Version of @microsoft/sp-build-web depends on older version of TypeScript

### ISSUE THREAD

**Issue by airportyh** [SharePoint/sp-dev-fx-webparts#275]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I'd like to use the latest type definitions for React and React-Dom, which I believe required the latest version of TypeScript version 2.4.x in order to work.

#### Observed Behavior

When updating the dependencies section of my package.json for:

```
"@types/react": "^16.0.0",
"@types/react-dom": "^15.5.1",
```

and then trying to re-run the app via `gulp serve`, I got lots of errors: https://gist.github.com/airportyh/36f73be7ec284a43d5e3745956520b9f

I tried the [create-react-app](https://github.com/wmonk/create-react-app-typescript) starter which didn't have such problems. Checking the versions of TypeScript, I saw that create-react-app uses the latest: 2.4.x, while the Sharepoint framework tools, in particular: `@microsoft/sp-build-web` uses TypeScript version 2.2.x. 

#### Steps to Reproduce

Use `yo @microsoft/sharepoint` to generate a React application template. Update the package.json for @types/react and @types/react-dom:

```
    "@types/react": "^16.0.0",
    "@types/react-dom": "^15.5.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
```

Then do `npm update` and then `gulp serve`.

#### Summary / Question

Are there plans to update TypeScript to the latest version? The fact that the Sharepoint framework is not open sourced also makes me worried. Are there plans to publish the source code?

**Comment by bva999** [comment]
The same problem. I use Kendo UI last version, and jQuery 3.x.. Both of them use TypeScript version 2.3.

**Comment by waldekmastykarz** [comment]
The latest version of the SharePoint Framework Yeoman Generator (v1.2.0) uses TypeScript v2.4.2. If you would update your existing projects to the latest toolchain, then you could benefit of TypeScript v2.4.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
