### ISSUE TITLE
Unable to provision pages with SPFx webparts unless by the UI

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-fx-webparts#276]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior
Be able to provision pages (Classical and Modern) with SPFx webparts without using UI.

#### Observed Behavior
Cannot do this at the moment

#### Steps to Reproduce
You cannot do this at the moment.

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
