### ISSUE TITLE
SPFx webparts not working with external cdn in tenant with first release option configured

### ISSUE THREAD

**Issue by jbgeesink** [SharePoint/sp-dev-fx-webparts#277]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Working webpart which loads the external scripts from the defined cdns

#### Observed Behavior
Webpart with externals resources throw an exception on loading

#### Steps to Reproduce
1. Download the angular-todo from the samples section

2. Restore packages with _npm install_

3. Start workbench with _gulp serve --nobrowser_

4. Browse to workbench on tenant with first release option configured

5. Add angular-todo webpart to workbench

6. When loading the workbench, the following error is displayed
![image](https://user-images.githubusercontent.com/25585361/28936191-3c70b3ca-7887-11e7-987b-a29510a0196c.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
