### ISSUE TITLE
How to Generate code coverage

### ISSUE THREAD

**Issue by mithunbv** [SharePoint/sp-dev-fx-webparts#279]
Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

 Expected or Desired Behavior
on running command 'gulp test', should give coverage report or do have to manually install istanbul or other coverage report generator and configure

Observed Behavior
When we run the command 'gulp test', in console it says ‘writing to [dir]/temp/coverage/js’ but as such no reports get generated , the coverage folder under temp has index.html but when opened shows no data.

Steps to Reproduce
In cmd prompt run the command 'gulp test'

**Comment by buckyaustin** [comment]
Hi @mithunbv ,

Can you please check with the latest version of the spfx generator? We experienced some issues upgrading, but on the spfx framework 1.2 the above command appears to work. Did not check on the 1.1.3 version.

Are you using mocha, chai and sinon that comes as a dependency by default with the Microsoft yoeman generator?

**Comment by VelinGeorgiev** [comment]
I can confirm that is works with the SPFx 1.2 packages at least for me.

![image](https://user-images.githubusercontent.com/1049476/30349406-d253f76a-980a-11e7-8ca3-ae89cd524f04.png)

**Comment by VelinGeorgiev** [comment]
Hey Guys,
@estruyf created new blog post with more information ["SharePoint Framework code coverage reports for unit-tests"](https://www.eliostruyf.com/sharepoint-framework-code-coverage-reports-for-unit-tests/). Hope that can help.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
