### ISSUE TITLE
get current userId

### ISSUE THREAD

**Issue by raminahmadi1986** [SharePoint/sp-dev-fx-webparts#284]
Hi,
why this.context.pageContext.user doesn't include id or userId ?
and my other question is why I can't use _spPageContextInfo inside a SPFx webpart ?
I don't want to make a rest call or other methods to get the current user Id !!!

**Comment by pedropablo** [comment]
I'm using the email to get the Id. Example below. Ain't happy about it but works. Not sure about the followup here, but maybe we should post this on https://github.com/SharePoint/sp-dev-docs

```
 public getUserId(email: string): Promise<number> {
    return pnp.sp.site.rootWeb.ensureUser(email).then(result => {
      return result.data.Id;
    });
  }
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
