### ISSUE TITLE
js-modern-calendar is not working.  I Downloaded the code Ran 'npm install' then ran 'gulp server' but getting follwoing error  

### ISSUE THREAD

**Issue by hasanbit** [SharePoint/sp-dev-fx-webparts#286]
Error - typescript - node_modules/@types/jquery/index.d.ts(6909,18): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6909,31): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6909,44): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6911,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6912,45): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6912,92): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6922,32): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6922,45): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6923,18): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6923,31): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6923,44): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6924,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6926,45): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6926,92): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6936,32): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6936,45): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6939,45): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6939,92): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6948,32): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6948,45): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6949,18): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6949,31): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6949,44): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6950,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6951,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6952,37): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6961,32): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6961,45): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6963,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6964,37): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6972,32): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6972,45): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6973,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6975,37): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6984,33): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6984,46): error TS230
0: Duplicate identifier 'never'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6985,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6985,88): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,14): error TS236
8: Type parameter name cannot be 'any'
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,24): error TS230
0: Duplicate identifier 'any'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,24): error TS236
8: Type parameter name cannot be 'any'
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,34): error TS230
0: Duplicate identifier 'any'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,34): error TS236
8: Type parameter name cannot be 'any'
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,60): error TS231
4: Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,99): error TS231
4: Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6991,138): error TS23
14: Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(6994,32): error TS236
8: Type parameter name cannot be 'any'
Error - typescript - node_modules/@types/jquery/index.d.ts(6994,42): error TS230
0: Duplicate identifier 'any'.
Error - typescript - node_modules/@types/jquery/index.d.ts(6994,42): error TS236
8: Type parameter name cannot be 'any'
Error - typescript - node_modules/@types/jquery/index.d.ts(6994,55): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7011,28): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7028,28): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7045,29): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7098,43): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7106,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7118,41): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7123,45): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7135,24): error TS231
4: Generic type 'PlainObject<T, any>' requires 2 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7139,42): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7192,19): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7192,59): error TS231
4: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s)
.
Error - typescript - node_modules/@types/jquery/index.d.ts(7193,46): error TS231
4: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s)
.
Error - typescript - node_modules/@types/jquery/index.d.ts(7194,23): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7194,63): error TS231
4: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s)
.
Error - typescript - node_modules/@types/jquery/index.d.ts(7195,50): error TS231
4: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s)
.
Error - typescript - node_modules/@types/jquery/index.d.ts(7301,14): error TS242
8: All declarations of 'Event' must have identical type parameters.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,30): error TS269
3: 'Partial' only refers to a type, but is being used as a value here.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,30): error TS236
2: The left-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,30): error TS236
5: Operator '<' cannot be applied to types 'boolean' and '{ new (typeArg: string
, eventInitDict?: PointerEventInit): PointerEvent; prototype: PointerEvent; }'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,30): error TS269
5: Left side of comma operator is unused and has no side effects.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,38): error TS269
3: 'Pick' only refers to a type, but is being used as a value here.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,58): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,74): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,86): error TS236
2: The left-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,97): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7302,109): error TS23
63: The right-hand side of an arithmetic operation must be of type 'any', 'numbe
r' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,8): error TS2363
: The right-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,27): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,39): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,50): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,65): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,77): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,87): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,97): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7303,110): error TS23
63: The right-hand side of an arithmetic operation must be of type 'any', 'numbe
r' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,8): error TS2363
: The right-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,17): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,30): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,38): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,50): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,61): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,73): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,85): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,97): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7304,109): error TS23
63: The right-hand side of an arithmetic operation must be of type 'any', 'numbe
r' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,8): error TS2363
: The right-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,22): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,38): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,50): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,62): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,80): error TS236
3: The right-hand side of an arithmetic operation must be of type 'any', 'number
' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,94): error TS236
2: The left-hand side of an arithmetic operation must be of type 'any', 'number'
 or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7305,106): error TS23
63: The right-hand side of an arithmetic operation must be of type 'any', 'numbe
r' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7312,23): error TS230
4: Cannot find name 'TTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7319,14): error TS230
4: Cannot find name 'TData'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7326,24): error TS230
4: Cannot find name 'TTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7327,23): error TS269
3: '_Event' only refers to a type, but is being used as a value here.
Error - typescript - node_modules/@types/jquery/index.d.ts(7334,23): error TS230
4: Cannot find name 'TTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7341,16): error TS230
4: Cannot find name 'TTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,85): error TS269
3: 'EventHandlerBase' only refers to a type, but is being used as a value here.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,85): error TS269
5: Left side of comma operator is unused and has no side effects.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,102): error TS23
04: Cannot find name 'TCurrentTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,125): error TS23
39: Property 'Event' does not exist on type 'typeof JQuery'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,131): error TS23
04: Cannot find name 'TCurrentTarget'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,147): error TS23
04: Cannot find name 'TData'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7350,155): error TS23
63: The right-hand side of an arithmetic operation must be of type 'any', 'numbe
r' or an enum type.
Error - typescript - node_modules/@types/jquery/index.d.ts(7352,48): error TS230
4: Cannot find name 'object'.
Error - typescript - node_modules/@types/jquery/index.d.ts(7502,33): error TS231
4: Generic type 'Callbacks<T, Function>' requires 2 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7503,36): error TS231
4: Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7504,41): error TS231
4: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s)
.
Error - typescript - node_modules/@types/jquery/index.d.ts(7505,36): error TS231
4: Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7506,37): error TS231
4: Generic type 'AjaxSettings<TContext, any>' requires 2 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7510,28): error TS231
4: Generic type 'jqXHR<TResolve, any>' requires 2 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7511,35): error TS231
4: Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).
Error - typescript - node_modules/@types/jquery/index.d.ts(7517,32): error TS231
4: Generic type 'PlainObject<T, any>' requires 2 type argument(s).
Error - 'typescript' sub task errored after 3.84 s
 TypeScript error(s) occurred.
[09:49:41] Project modern-calendar version: 0.0.1
[09:49:41] Build tools version: 2.9.1
[09:49:41] Node version: v6.10.1
[09:49:41] Total duration: 8.2 s
[09:49:41] Task warnings: 20
[09:49:41] Task errors: 1154

**Comment by waldekmastykarz** [comment]
The sample is created using an older version of the SharePoint Framework. Because it doesn't use a lockfile, it could be that a combination of older and newer packages is installed which aren't compatible with each other. Unfortunately, the only solution is to update the sample and include a lockfile to avoid such issues in the future. /cc: @jcoleman-pcprofessional, @VesaJuvonen

**Comment by hasanbit** [comment]
I ran the follwoing command "npm install --save-dev @types/jquery@2.0.34" , And the Gulp Serve . every thing is working fine now. Thanks

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
