### ISSUE TITLE
Error in ngx bootstrap modal in spfx webpart

### ISSUE THREAD

**Issue by paigeflourin** [SharePoint/sp-dev-fx-webparts#287]
i know this isnt really part of this repository but i am really stuck with my issue and there is no one who can help me with this one. I am working on creating a webpart that when a button was clicked a modal would open. i have used ngx-bootstrap (http://valor-software.com/ngx-bootstrap/#/modals) 

#### Category
- [ x] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
i want to open a modal from my spfx webpart. i am using angular2 framework 

#### Observed Behavior
I get the following error:

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.OurApplicationsWebPart.1b908c57-79a0-4102-97fc-8c48e91c4899,Error: ***Failed to load component "0a847cdc-0309-4af4-a025-d084e8e66554" (OurApplicationsWebPart). Original error: ***Failed to load entry point from component "0a847cdc-0309-4af4-a025-d084e8e66554" (OurApplicationsWebPart). script resources due to: {1}. CALLSTACK:: Error at SPWebPartError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:13577:26) at new SPWebPartError (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:988:30) at Function.SPWebPartError.create (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:1012:18) at https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:1884:65 at <anonymous>

#### Steps to Reproduce
everything goes well from gulp clean, gulp build and gulp serve. then when i load the webpart i get that error.

```
This is my app.module.ts, when i add references to the ngx bootstrap.

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppSettings } from './shared/app.settings';
import { AppLoadingComponent } from './shared/loading/app.loading';
import { AppNotifyComponent } from './shared/notify/app.notify';
import { BsModalService, ModalModule } from 'ngx-bootstrap/modal';
import { AddApplicationComponent } from './add-application-modal';

@NgModule({
    imports: [BrowserModule,
        ModalModule.forRoot(),
    ], 
    providers: [
        AppSettings
    ],
    declarations: [
        AppComponent, 
        AddApplicationComponent,
        AppLoadingComponent,
        AppNotifyComponent],
    bootstrap: [AppComponent],
    entryComponents: [AddApplicationComponent]
})

export class AppModule {}
```

Then this is my config.json

```
{
  "entries": [
    {
      "entry": "./lib/webparts/ourApplications/OurApplicationsWebPart.js",
      "manifest": "./src/webparts/ourApplications/OurApplicationsWebPart.manifest.json",
      "outputPath": "./dist/our-applications.bundle.js"
    }
  ],
  "externals": {
  
  },
  "localizedResources": {
    "ourApplicationsStrings": "webparts/ourApplications/loc/{locale}.js"
  }
}
```
manifest.json
```

{
  "$schema": "../../../node_modules/@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/clientSideComponentManifestSchema.json",

  "id": "0a847cdc-0309-4af4-a025-d084e8e66554",
  "alias": "OurApplicationsWebPart",
  "componentType": "WebPart",
  "version": "0.0.1",
  "manifestVersion": 2,

  "preconfiguredEntries": [{
    "groupId": "0a847cdc-0309-4af4-a025-d084e8e66554",
    "group": { "default": "Under Development" },
    "title": { "default": "our-applications" },
    "description": { "default": "our-applications description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "our-applications"
    }
  }]
}

```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
