### ISSUE TITLE
npm repo missing for sharepoint framework samples.

### ISSUE THREAD

**Issue by mgerety** [SharePoint/sp-dev-fx-webparts#293]
The sample webpart migration project at =sp-dev-fx-webparts\tutorials\tutorial-migrate-datatables\01-migrated-sewp-to-spfx references an NPM repo that is unavailable.  Running npm install results in a number of errors: 

npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/convert-source-map/-/convert-source-map-1.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/normalize-path/-/normalize-path-2.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/useragent/-/useragent-2.1.13.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/which/-/which-1.2.14.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/q/-/q-1.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/isexe/-/isexe-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/rc/-/rc-1.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/type-is/-/type-is-1.6.15.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/webpack-stats-plugin/-/webpack-stats-plugin-0.1.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed http://cxovm01.cloudapp.net/artifactory/api/npm/npm-virtual/normalize-path/-/normal

**Comment by andrewconnell** [comment]
Delete the `npm-shrinkwrap.json` file and rerun `npm install`.

Looks like someone committed that project when they were pointing to a private NPM registry (hosted at `csovm0.cloudapp.net`) which you won't have access to.

**Comment by mgerety** [comment]
Thanks Andrew.

-- 
Michael Gerety

**Comment by mgerety** [comment]
After deleting npm-shrinkwrap I get the following:

```
npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @microsoft/node-core-library
npm ERR! 404
npm ERR! 404  '@microsoft/node-core-library' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@microsoft/gulp-core-build'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\sp-dev-fx-webparts\tutorials\tutorial-migrate-datatables\01-migrated-sewp-to-spfx\npm-debug.log
```

**Comment by waldekmastykarz** [comment]
Sorry for `cxovm01`, that's my bad. I'm working on a fix and will submit a PR as soon as it's done.

As for your other issue: there was a problem with missing packages but it seems to be fixed now. If you try to rerun `npm i` it should be working now.

**Comment by VesaJuvonen** [comment]
PR with the needed changes submitted. Should be all good now, so closing this one.
