### ISSUE TITLE
How to get current logged in user in WebApi controller

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-fx-webparts#294]
Hi there,
we are using the called react-sp-elevatedprivileges to allow elevated actions inside SPFx Webparts. 
As of know that works and every user can use those elevated privileges. 
The problem we are facing is, that we need to apply some rules based on the current logged in user to restrict usage of the elevated actions. So we tried to get a user token in the WebApi controller by using GetWebLoginClientContext from AuthenticationManager. Basically this should work in an Api call because the user is already logged in to SharePoint but it seems that the needed redirect to get the token is not allowed when using Cors.
Does anyone know of a way to get the current logged in user inside the Api? Basically we need the User object from SharePoint including id, login name and mail address to determine what he is allowed to do.

Thanks for your help.

**Comment by waldekmastykarz** [comment]
Do you have authentication setup on your API? If not, you would need to do it. You could use an approach similar to described in https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad#access-the-api-by-leveraging-sharepoint-online-authentication-cookie

**Comment by cwdata** [comment]
Thanks @waldekmastykarz 
I tried the suggested solution but it doesn't work reliable. Sometimes it works, sometimes not.
The problem is that the login through the iframe is not always working. Today I have seen several browsers (not Edge) going into an endless redirect loop on that login part...
Yesterday it worked in all browsers with two specific exceptions: Firefox and Chrome were unable to login from a machine that is connected via ADConnect Single Sign On. Both browsers worked on non domain joined machines though.
In the meantime I found another solution which so far seems to work all the time:
I'm using an hidden iframe to open "appredirect.aspx" which then loads my provider hosted Addin. The Addin generates an encrypted token containing the users logon name and sends it back to to the SPFx Webpart. The Webpart then uses this token for all requests to the WebApi. The WebApi decrypts it to get the user. 
The integrated authentication is turned off in the App Service.
What do you think about that? It seems to be reliable in my first tests.

**Comment by waldekmastykarz** [comment]
@cwdata what are you using to decrypt the token from appredirect.aspx? Could the token be spoofed?

**Comment by cwdata** [comment]
@waldekmastykarz The token gets encrypted and decrypted inside the same provider hosted Addin because this Addin also hosts the WebApi. Therefore the key is also securely stored there.

**Comment by waldekmastykarz** [comment]
Does your token have an expiration date so that it cannot be hijacked and reused later?

**Comment by cwdata** [comment]
Not yet but I'm thinking about making it valid only for the date it has been issued.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
