### ISSUE TITLE
TypeError: Cannot read property 'readCommentedJsonFile' of undefined

### ISSUE THREAD

**Issue by sharad2803** [SharePoint/sp-dev-fx-webparts#295]
Trying to explore the react-yammer-api sample code project from SharePoint/sp-dev-fx-webparts, 
Running the command "gulp serve --nobrowser" or "gulp serve" produces the following error and output:

H:\sp-dev-fx-webparts-master\samples\react-yammer-api>gulp serve --nobrowser
Build target: DEBUG
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
[19:01:51] Error - Unknown
undefined
[19:01:52] ==================[ Finished ]==================
[19:01:52] Project react-yammer-api version: 0.0.1
[19:01:52] Build tools version: 2.10.0
[19:01:52] Node version: v6.11.0
[19:01:52] Total duration: 1.17 min
[19:01:52] Task errors: 2
==================[ End ]==================
Using version are, Node.js v6.11.0
 yo --version 2.0.0
 npm --version 5.3.0

**Comment by VelinGeorgiev** [comment]
Hey @sharad2803, this is not issue related to the sample itself, but to the current NPM SPFx packages on npm.
Have an eye on the progress here: https://github.com/SharePoint/sp-dev-docs/issues/820.

Please also downgrade your npm manager to version 3.x or 4.x. NPM version 5.x is still not supported by the SPFx. See: https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md

Once the above issue is resolved and your npm package manager is version 3.x or 4.x you probably will be able to run the sample.

Cheers

**Comment by oyvindam** [comment]
I get the same error. Tested with npm 3.10.10,  4.0.5 and 4.6.11.

**Comment by sharad2803** [comment]
Hi @VelinGeorgiev , Thank you for valuable info but still getting same error with npm v3 and v4 also.

**Comment by VelinGeorgiev** [comment]
Can you please try now.  The issue should be resolved. Please delete the node modules and re-install them using v3 or v4 of the npm package manager.

**Comment by sharad2803** [comment]
Yup thanks @VelinGeorgiev , Works now.

**Comment by VelinGeorgiev** [comment]
Hey @sharad2803, just a hint there should be a button somewhere on the screen for you to close that issue if it is resolved :)
