### ISSUE TITLE
Gulp serve stops watching after compile error

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-fx-webparts#297]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
After running Gulp Serve, the watcher should continue to attempt compiling on future saves.

#### Observed Behavior
If there's any sort of compile error while coding, node throws the following error "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): TypeError: options.message.replace is not a function." Further changes aren't compiled on save.

#### Steps to Reproduce
1.  Create a new project
2. Run "gulp serve"
3. Do something that might cause a compile error.
4. Save File
5. fix compile error
6. save again
![image](https://user-images.githubusercontent.com/31546277/29979361-5eb4bc2e-8f02-11e7-9b46-f2ed6ec433b5.png)

**Comment by lukasmatiasko** [comment]
I have the same problem. I need to restart gulp each time I have an error in my code and the whole process of development becomes very tedious.

Do you have any updates on this?

**Comment by bratukham** [comment]
I have the same problem with the latest yeoman template.

**Comment by araver** [comment]
This isn't a fix, but it stops the error. (Also, don't normally suggest to edit nodes modules.)

Change line 359 in node_modules\node-notifier\lib\utils.js
from `options.m = options.message.replace(/\x1b/g, '');` to `options.m = options.message.toString().replace(/\x1b/g, '');`

It appears that whatever is calling `WindowsToaster.prototype.notify` is passing an object rather than a string as the message.

**Comment by ab18556** [comment]
Removing the else if statement at line 183 of \node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js fixes it.

**Comment by nickpape-msft** [comment]
Hello all, this issue will be fixed in the next release of SPFx. For now, you can bypass the error by disabling the toast. Simply update your gulpfile.js and add the following line of code before `build.initialize(gulp)`:

```
build.mergeConfig({
  showToast: false
});
```

I'm closing this issue, but feel free to re-open if you are still seeing issues in the 1.4.0 SPFx release.

**Comment by russgove** [comment]
So I am still having this issue.. When will 1.4.0 SPFx be released?
