### ISSUE TITLE
Does the sample aad-api-spo-cookie work for Chrome? 

### ISSUE THREAD

**Issue by larry-lau** [SharePoint/sp-dev-fx-webparts#298]
#### Category
- [ ] Question

#### Expected or Desired Behavior
Putting an AAD protected web site in iframe within SPO works for Internet Explorer and Chrome. 

#### Observed Behavior
However, in Chrome, the iframe is rendered empty. After inspecting the console log, I see the following errors.  The page appears in the iframe for Internet Explorer and Edge but not Chrome.
- Refused to display 'https://login.microsoftonline.com/... a frame because it set 'X-Frame-Options' to 'deny'.
- Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE

#### Steps to Reproduce
- Simply drop an Page Viewer Web Part on any SharePoint page and point to your AAD protected web app 
- Browser it in Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

#### Question
Is this approach meant to work only IE?

**Comment by waldekmastykarz** [comment]
I've just tried it and it's working correctly. At first, I'm getting an error, but after calling the API in a separate tab and then refreshing the workbench with web part on it, the call comes through.

**Comment by larry-lau** [comment]
Yes Waldek,  I have confirmed that if the user has not gone via the sign in process of the API app before this approach will not work in Chrome. 

So from the end user experience perspective, the spfx web part has to provide a way to launch a separate browser tab to the API app first in order for this approach to work properly reliably.   Do you have any recommendation on how to properly roll out such web part to large number users without causing confusion?

**Comment by waldekmastykarz** [comment]
I've tested the project locally where the certificate is not trusted. I suspect that this is what's causing this behavior. Have you seen the same behavior in a setup with a trusted certificate?

**Comment by larry-lau** [comment]
I have my API app deployed to Azure Web site.  All my testing is on the Azure web site.   I don't think the error has anything to do with certificate. 

The sample aad-api-spo-cookie is based on the assumption that the iframe will never need to hit login.microsoftonline.com but in the reality when the cookie will expire, the iframe will have to take the user to via login.microsoftonline.com and that is when Chrome refuse to display.  

Let me walk you through another scenario.  I have the Recent Order web part running on the workbench last Friday and was showing a list of orders on the screen,  today when I come back to the office and refresh the browser,  the web part display an error.  Reviewing the console reveals the browser is trying to take the user to login.microsoftonline.com and again Chrome refuse it.   
![spocookie-error1](https://user-images.githubusercontent.com/17136688/30072528-77403514-921f-11e7-969f-fb4e33962c76.png)

In this case, it is by design that the browser refuse to serve the login page.   I suspect we have a false assumption here.

**Comment by waldekmastykarz** [comment]
I understand what you're saying. It seems indeed that we stumbled upon a limitation of this approach, where it requires a valid cookie in order to work correctly. If the cookie expires, it cannot perform authentication because the login page cannot be displayed in an iframe.

**Comment by larry-lau** [comment]
So far this issue is happening in Chrome.

**Comment by larry-lau** [comment]
Hi Waldek, 

I stumble upon this API /_api/SP.OAuth.Token/Acquire and I thought to myself that this would have been the best approach to consume secured web API from user experience and security.  No user redirect and no exposing refreshToken in the browser.  The unfortunate part of this API is that it only supports MS Graph resource. 

Do you know if there is plan to support getting access token for other custom resource/api?

**Comment by waldekmastykarz** [comment]
@larry-lau this is an internal endpoint meant for use by first party solutions. As far as I know there are no plans for a similar approach to obtain tokens for other resources.

**Comment by MarianoPrz** [comment]
I've the same issue, only in chrome as well, @waldekmastykarz there are some something new to fix this? The cookie approach is excelent to avoid the user login everytime that open a webpart, calling the azure API in a separate tab fix it but for the end user it is not viable. Thanks in advance, great job!

**Comment by waldekmastykarz** [comment]
@MarianoPrz I'm not sure if this can be fixed in any way. The good news is, at Ignite the engineering team announced changes in this area where we will be able to call an API inside of the SharePoint Framework to obtain an access token for use with custom APIs. More details coming soon.

**Comment by MarianoPrz** [comment]
@waldekmastykarz Hi!  now it's work with the build 62 of Chrome, and not setting display none in the iframe ( despite this the iframe doesn't appear ) so its work great for me. There is an approximate date of the changes announced by the Ignite team? thanks for answering!

**Comment by waldekmastykarz** [comment]
@MarianoPrz great to hear it's working. Unfortunately, at this point there are no specific dates, but as mentioned by the team during Ignite, it should be coming soon. Stay tuned!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
