### ISSUE TITLE
aad-api-spo-cookie works for me but not other users

### ISSUE THREAD

**Issue by darrenparkinson** [SharePoint/sp-dev-fx-webparts#300]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

The expected behaviour is that the webpart works for all users visiting the sharepoint page that has the SPFX component on it.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

The component does not display the data.  It makes the request to the API from the frame, but the API just logs a message saying `Information Redirecting: https://login.windows.net...` which looks like it's redirecting for authentication even though the user is already logged in?

In addition, the client has the following error `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://myapiurl. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`  This is because my code doesn't get called to set the CORS header as the request is redirected for auth?

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

* Create simple node js api that has two endpoints -- one used by the iframe that returns an empty object, and one that returns some basic data
* Create basic SPFX component to use that API as per the aad-api-spo-cookie example
* Add the component to a page
* Log in as another user, not the one used to create/test/deploy the app
* Observe that the data is not displayed

**Comment by waldekmastykarz** [comment]
Have you consented the AAD application for the whole organization or only for yourself? If it's consented only for one users, then it would explain why others are getting errors.

**Comment by darrenparkinson** [comment]
That could be it. Any pointers on how to consent for the whole org? And is that a one time only operation.  For example, if sites with components are shared with external users after consent, are those new users covered?  Thanks.

**Comment by waldekmastykarz** [comment]
@darrenparkinson have you seen this doc https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#overview-of-the-consent-framework? Unfortunately, I don't know how it handles external users added after consent. This is something you'd have to test yourself.

**Comment by darrenparkinson** [comment]
Thanks.  I've used "Grant Permissions" in Azure AD which I think has worked although I am getting some odd and inconsistent behaviour across users which I'll need to test further.  

In addition, specifically using Firefox with a page that has a SPFX component on and is authenticated in this way actually redirects the whole page to the login.microsoftonline.com site for authentication and then redirects to the URL of the API -- any thoughts?

**Comment by waldekmastykarz** [comment]
I haven't seen anything alike. Have you noticed it only in Firefox or in other browsers as well?

**Comment by darrenparkinson** [comment]
Just firefox.  I tested with Chrome, IE and Edge which all seem fine.  Shall I do a bit more testing and log a separate issue for that?

**Comment by waldekmastykarz** [comment]
That would be very helpful. The more information we gather, the easier it will be to find the culprit and hopefully to fix it.

**Comment by darrenparkinson** [comment]
OK, thanks again.
