### ISSUE TITLE
react-taxonomypicker doesn't preserve selections

### ISSUE THREAD

**Issue by ahollandusc** [SharePoint/sp-dev-fx-webparts#302]
#### Category
- [x ] Bug

#### Expected or Desired Behavior
Expected behaviour is that when a page with a webpart containing a taxonomy picker property is edited and the property pane for that web part is opened, the taxonomy picker will show the current property value(s) as selected.

#### Observed Behavior
When a page with a webpart containing a taxonomy picker property is edited and the property pane for that web part is opened, the taxonomy picker shows the 'Type here to search...' placeholder instead of the selected item.

#### Steps to Reproduce
I was having this problem with a web part I created which used the react-taxonomypicker module. When it was deployed to SP and added to a page, saving and re-editing the page caused the setting to be lost. 

This can be repeated more easily with the OOTB sample though:

1. Clone the sp-dev-fx-webparts git repo locally then
> cd samples/react-taxonomypicker
> npm install
> gulp serve

The https://localhost:4321/temp/workbench.html page opens (in chrome)

2. Add the TaxonomyPickerSample web part to the workbench page.

3. Edit the properties for this web part and select 'English' then close the properties pane. The web part correctly shows 'Selected Language: English'
Reopen the properties pane - the picker correctly shows English as selected.

4. Hit F5 to refresh the page - the web part still correctly shows 'Selected Language: English'
Edit the properties for this web part - the picker doesn't know about the English selection and just shows 'Type here to search...'

The problem may be due to how the componentDidMount is handled in the react-taxonomypicker TaxonomyPicker.tsx file or perhaps an issue with the Custom control handling in the sample?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
