### ISSUE TITLE
aad-api-spo-cookie and statusRenderer.displayLoadingIndicator

### ISSUE THREAD

**Issue by darrenparkinson** [SharePoint/sp-dev-fx-webparts#305]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

When using the aad-api-spo-cookie sample, the component obviously has a hidden iframe which we need to render before making any API requests.  My question is around where and how you would implement the statusRenderer.displayLoadingIndicator whilst getting the data since it would seem quite different to the other samples which implement this.

Also, are you able to implement this in the sample?

Thanks.

**Comment by waldekmastykarz** [comment]
Showing the loading indicator is already in the code. Here it's being set: https://github.com/SharePoint/sp-dev-fx-webparts/blob/366c28a57753ad410a1b50376dd5738186bbb6ed/samples/aad-api-spo-cookie/webpart/src/webparts/latestOrders/LatestOrdersWebPart.ts#L41-L42 and here it's being cleared https://github.com/SharePoint/sp-dev-fx-webparts/blob/366c28a57753ad410a1b50376dd5738186bbb6ed/samples/aad-api-spo-cookie/webpart/src/webparts/latestOrders/LatestOrdersWebPart.ts#L62-L63

Is this what you're asking about or something else? 🙂

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
