### ISSUE TITLE
aad-api-spo-cookie token expired error on verification

### ISSUE THREAD

**Issue by darrenparkinson** [SharePoint/sp-dev-fx-webparts#306]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

When adding token verification to the API and verifying the x-ms-token-aad-id-token I would expect verification to complete successfully, with an appropriate unexpired token being passed to the API.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

The token that is passed to the API is expired.  If I open a separate/different browser and log in, the token is verified perfectly.  After one hour, refreshing the page will send the same token to the API which is invalid as it is expired.

I suppose the question is whether or not this is expected behaviour?

Many thanks.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
