### ISSUE TITLE
SPFx web part with react components on Classic page doesn't load/ behave properly

### ISSUE THREAD

**Issue by rahulsuryawanshi** [SharePoint/sp-dev-fx-webparts#307]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

I have developed SPFx web part using React and using react-fabric-ui components like Dropdown, spinner, dialog and command bar. These components works perfectly fine on SharePoint Workbench but when web part is added on classic page, I see various issues with these controls.

1. Drop down doesn't display options (it has option values but doesn't display it. looks like UI class issues)
2. Spinner control doesn't display.

3. Dialog control doesn't display its content but display header and OK button.
![image](https://user-images.githubusercontent.com/12417451/30141607-7887408a-934a-11e7-9746-8443d00caaa1.png)

4. In workbench, command bar displays overflow items as ellipse and when click it shows as dropdown. On classic page, it doesn't display proper ellipse nor drop down and fails to display text of menu items.
5. Command items click works without postback in workbench but does post back on classic page. When it does post pack, it shows error in console as below
![image](https://user-images.githubusercontent.com/12417451/30141497-e2fa14ac-9349-11e7-8e05-1cb4011f1398.png)
6. In IE browser, office-UI-Fabric classes like 'ms-Icon ms-Icon--CheckList' doesn't display icons.
In IE (Classic Page)
![image](https://user-images.githubusercontent.com/12417451/30141653-c97c921a-934a-11e7-8815-f94457cf114f.png)

In Chrome (Classic Page)
![image](https://user-images.githubusercontent.com/12417451/30141681-ed705dfa-934a-11e7-9e94-fe84d2312bea.png)

I am not sure if I am missing any office-ui-fabric package but they work fine on SharePoint workbench. Most of office-ui-fabric classes does work as expected.

**Comment by rahulsuryawanshi** [comment]
I found the issue. There was another third party component on the page loaded through custom action which was throwing exception. Because of which this SPFx web part was not rendering /behaving properly. When removed that component from site, it stated working as expected. Though I want to mention that there are few things which differs in classic page than what you see in workbench (SharePoint or local). Also both Local and SharePoint workbench don't behave same. We are seeing lot of differences in UI between these two workbench.

**Comment by ManjulaMasthanvali09** [comment]
Tree view PNP Controls are not loading on the classic Page in SPonline


![image](https://user-images.githubusercontent.com/70963603/153934868-b6942178-9a99-4431-af1f-09f2c9001603.png)


Please help me in this issue we are using Node 12.18.0 version
