### ISSUE TITLE
Need More steps.

### ISSUE THREAD

**Issue by srinivasamyneni** [SharePoint/sp-dev-fx-webparts#31]
can please mention steps to run the commands given. I'm using VS2013.

Getting below issue while running it.

The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that  the path is correct and try again.

**Comment by wictorwilen** [comment]
You need to follow the guidelines here: http://dev.office.com/sharepoint/docs/spfx/tools-and-libraries and http://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment

There is no support for Visual Studio 2013, you need to use at least Visual Studio 2015.

**Comment by VesaJuvonen** [comment]
Closing this one, since Wictor covered the key points already a year ago.
