### ISSUE TITLE
Dropdown broken, need to upgrade office-ui-fabric-react

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-webparts#311]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
A dropdown used within the toolpane should show the value that has been selected by the user after clicking on an item within the dropdown list.

#### Observed Behavior
The upgrade to **office-ui-fabric-react@4.32.0** introduced some regression, causing the dropdown to stop displaying the value selected by the user. Based on the issue [#2719](https://github.com/OfficeDev/office-ui-fabric-react/issues/2719) raised on the office-ui-fabric repository, the following bug was introduced in 4.32.0 :

> With multiselect update a bug was introduced where 'selected' was being applied to options in non mulitselect dropdowns, but it was never being removed when the next option was clicked. So in the end every options.selected clicked was set to true, and the 1st would be displayed.

They did fix the issue, but the SharePoint packages are still referring 4.32.0, so an update to a newer version would be required in order for us to be able to add dropdown in toolpanes without issues.

One temporary solution would be to specified my own version of office-ui-fabric-react in my package.json but I remember reading that using a different version than the one loaded by the SharePoint packages isn't recommended, is it still the case?

#### Steps to Reproduce
Create a new React WebPart based on the generator and add a dropdown in the toolpane. Select an option and see what happens.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
