### ISSUE TITLE
Not getting AD user with People Picker (React)

### ISSUE THREAD

**Issue by cooluchat** [SharePoint/sp-dev-fx-webparts#320]
I need is to get Active Directory user with people picker, not from the PeoplePickerExampleData in the  https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-peoplepicker.

**Comment by giuleon** [comment]
In the next days I'll submit a new pull request with the last changes in the meantime you can take a look to the new version on my fork:
https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker

**Comment by cooluchat** [comment]
https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker is same project which is regarding my issue on https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-peoplepicker

**Comment by giuleon** [comment]
Please try the solution on my github https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker
I added a user directly into the AAD and as you can see below I'm able to retrieve the user through the peoplepicker.
In the next days I'll make a pull request also on the official samples:

![image](https://user-images.githubusercontent.com/3914090/31014036-36d65e2e-a519-11e7-8cbd-b5cf2b8f96d9.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
