### ISSUE TITLE
Angular search example > Cannot find name 'object'

### ISSUE THREAD

**Issue by sharepointmike** [SharePoint/sp-dev-fx-webparts#324]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
After the Gulp serve I receive some errors

#### Observed Behavior
I receive a lot of "Cannot find name object" errors on buiding

#### Steps to Reproduce
Might be a user error as I am a newby on SPFX. But I followed instructions and set typescript to 2.1.5

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
