### ISSUE TITLE
"adalFrame style height = 106px" cannot set property 'height' of undefined or null reference

### ISSUE THREAD

**Issue by sohotra** [SharePoint/sp-dev-fx-webparts#325]
#### Category
- [ ] Question
- [ 1 ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
So I see in other threads that the following line was added to fix a token renewal timeout error WebPartAuthenticationContext.js: 
_adalFrame.style.width = adalFrame.style.height = '106px';_
However, for me in IE11, I'm getting an error on this line:
"TypeError: Unable to set property 'height' of undefined or null reference"

This is occurring in <tenant>/_layouts/15/workbench.aspx

**Comment by waldekmastykarz** [comment]
Can you confirm that the ADAL frame is being added to the page?

**Comment by sohotra** [comment]
I don't think it is and I have a feeling it's got something to do with my company's trusted sites. We have our tenant added to the trusted sites, I'm thinking I also need to add login.microsoftonline.com to that is that correct?

**Comment by waldekmastykarz** [comment]
Correct

**Comment by sohotra** [comment]
oh wonderful, I gotta go through this lengthy process of getting something added to trusted sites this will be a joy (I work for a bank, you can imagine :)) 

I'll close this as soon as I have it verified. thanks Waldek!

**Comment by waldekmastykarz** [comment]
You're welcome! Hope it's going to work for you and don't hesitate to reach out if you have any questions!

**Comment by sohotra** [comment]
That was it, was able to get the following added to the trusted zone and we're all good now.

1. login.microsoftonline.com
2. <tenant>.sharepoint.com

**Comment by waldekmastykarz** [comment]
@sohotra thank you for confirming!
