### ISSUE TITLE
Unable to fetch User Profile properties using rest api in spfx webpart 

### ISSUE THREAD

**Issue by ssingh28** [SharePoint/sp-dev-fx-webparts#327]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

Hi Team,

I am creating a webpart using react and typescript which needs to fetch the country (EDSCountry) of currently logged in user. below is my code but whenever **i try to debug this in the local workbench it throws access denied error. However, when i fire the url in browser i do get the xml response properly**.

I also followed this article but in the last step when this has to be published it is also throwing error.
 https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo

Can you please provide pointers as to why i am having this issue.

private _getUserLocale() : Promise<any> {
    let url: string = this.context.pageContext.web.absoluteUrl+"/_api/SP.UserProfiles.PeopleManager/GetMyProperties";
    console.log(url);
    return (fetch(url)
      .then(function(response){debugger;
        return response.text();
      })
      .then(function(data){
        console.log(data);
        return;
      }));
  }
![new issue](https://user-images.githubusercontent.com/11782656/31378988-9b49742c-adca-11e7-8e49-876cea5c1b22.PNG)

![issue2](https://user-images.githubusercontent.com/11782656/31379081-f1cb267e-adca-11e7-8592-a5f6f5774e34.png)

**Comment by ssingh28** [comment]
Hey Team,

Can anyone provide response to this question as well.

**Comment by waldekmastykarz** [comment]
@ssingh28 are you trying the exact same URL in browser or a different one? Looking at the error message, you're trying to call the API on the Microsoft tenant which won't work unless you're a Microsoft employee and have access to the tenant.

**Comment by ssingh28** [comment]
@waldekmastykarz  yes i am an employee of microsoft and have tried this same url in the browser and it works fine there.

**Comment by waldekmastykarz** [comment]
@ssingh28 thanks for confirming! When you enter the URL in browser: are there any redirects or are you getting a response immediately? You can double check that with developer tools and persisted logging enabled.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
