### ISSUE TITLE
NPM commands issues (install, etc)

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-fx-webparts#328]
#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

#### 
Hi,

Could you share valid version of NPM, node JS for each SPFX Version ? 
I feel I hit different versions problem each time...

Example of the last problem, when I install  @type/sharepoint
https://github.com/npm/npm/issues/18380

Thanks for your contribution! Sharing is caring.

**Comment by waldekmastykarz** [comment]
The latest information regarding the recommended versions of Node and npm is available at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment.

**Comment by seaSide974** [comment]
Indeed :)

I got errors after updating to last npm, trying to solve those issue , but it was actually due to windows defender or the antivirus (trend secure), disabling it solved those issue. Maybe it could be added to the official documentation, to ensure no antivirus is running ?

Thank you 

> spfx - Gulp serve error : Cannot find module '@microsoft/sp-build-web' - SharePoint Stack Exchange
> sharepoint.stackexchange.com
> 
> installation problem: semver module missing · Issue #588 · npm/npm
> github.com
