### ISSUE TITLE
Issue:When we come to our newly created SPFx Solution

### ISSUE THREAD

**Issue by Viipiin** [SharePoint/sp-dev-fx-webparts#329]
I don't know where I'm making a mistake but its something that I want to undersatnd why this is happening.
I created a brand new @micrsoft/sharepoint Solution and when I visit my VS Code 
It is something like 
![1](https://user-images.githubusercontent.com/9314627/31417451-1cd32fce-ae4d-11e7-9a3f-4694c9a52f65.jpg)
![2](https://user-images.githubusercontent.com/9314627/31417456-2312cd0e-ae4d-11e7-9cdd-e24f138dea84.jpg)
I tried almost every help on google but didn't get the solution .
Can someone please get arround ?

Help Expected !!!

**Comment by VesaJuvonen** [comment]
Issue around finding default scss is pretty much by design. That goes way when you bundle first time your code by using ´´´gulp serve´´´ or running ´´´gulp bundle´´´. Tslint message is a warning and does not cause any actual issues for using your solution. It really depends on the tslint configuration. 

There's no issues here which would block you for running local workbench by running ´´´gulp serve´´´.

**Comment by VelinGeorgiev** [comment]
You  are  using tslint extention for visual studio code. That extention complains about single quote to be double. Maybe tweak a bit the extention or the tsconfig,   to remove these warnings.

**Comment by Viipiin** [comment]
@VesaJuvonen Thanks Sir for the quickest response .I'll check and let you know.
@VelinGeorgiev Yes I'm using that but how that worked in my previous solutions .For now  ,I checked all the settings in tsconfig and tslint.json but no luck.It is really irritating when the red line comes under a code line.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
