### ISSUE TITLE
SPComponentLoader.loadScript() not working in an application extension

### ISSUE THREAD

**Issue by glapointe** [SharePoint/sp-dev-fx-webparts#330]
#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Attempting to use SPComponentLoader.loadScript() to load JSOM scripts within an application extension so that I can leverage the taxomony API. I can get this working without issue in a webpart using the workbench but not with an application extension.

#### Observed Behavior
When the init.js script is loaded (first in a series of scripts to be attempted) then I get an error: Unknown error when loading module "https://tenant.sharepoint.com/sites/gary-dev/_layouts/15/init.js". 

If I look at the stack trace I can see the error that requirejs is throwing: No define call for /sites/gary-dev/_layouts/15/init.js.

#### Steps to Reproduce
I created a bare bones hello world application extension and added code from the react-taxonomypicker sample (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-taxonomypicker). I've attached the sample application that I used to test this out. This is the query parameters I'm using to load it: ?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"6751e0dc-64e5-425c-93c2-7e6ad2081f93":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"termSetId":""}}}

[HelloWorld.zip](https://github.com/SharePoint/sp-dev-fx-webparts/files/1376712/HelloWorld.zip)

**Comment by TBag** [comment]
I can also reproduce this issue.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
