### ISSUE TITLE
Vuejs Sample do not compile

### ISSUE THREAD

**Issue by BeeMaia** [SharePoint/sp-dev-fx-webparts#336]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

@s-KaiNet, I try to run vue.js sample like as is on github repository but at compile time I have these errors:
![image](https://user-images.githubusercontent.com/22744022/31768400-89b6e86e-b4cf-11e7-8f2e-459d29718d68.png)

Any idea?

Thanks,
Andrea

**Comment by s-KaiNet** [comment]
I've just tried and it works fine for me. Make sure you use latest version of the source code. Then delete `node_modules` completely, run `npm install` and `gulp serve`

**Comment by BeeMaia** [comment]
I've just tried and it doesn't work. I've just downloaded the latest version of the source code, run `npm install` and `gulp serve` but I have same problem.
I've some warning of deprecated pkg when I run `npm install`.
My node version is 6.11.0.
My npm version is 3.10.10.
My @microsoft/generator-sharepoint version is 1.3.2

Thanks,
Andrea

**Comment by s-KaiNet** [comment]
I believe you need to update npm, current version is 5.5, I haven't tested it with earlier npm versions.

**Comment by BeeMaia** [comment]
After I updated npm to latest version (v 5.5.1) it works fine.

Thanks,
Andrea
