### ISSUE TITLE
Cannot see fonts and icons using SPFx on-premises offline

### ISSUE THREAD

**Issue by alexalexpod** [SharePoint/sp-dev-fx-webparts#343]
Hello.

I am examining SPFx on-premises version and I have noticed that all the fonts and icons cannot be loaded.
The problem is that we are offline and the workbench code tries to reach internet resources ("https://static2.sharepointonline.com/.......").
Is there a way to reconfigure SPFx to search for offline resources?
This point is crucial for us because we are on-premises offline.

Thanks, Alex.

**Comment by cmd64** [comment]
import styles from './YourWebPart.module.scss'; replace with this require('./YourWebPart.css');
YourWebPart.module.scss rename YourWebPart.scss

Create fonts folder in src/webparts/yourwebpart and add font files.
Add in css src: url('./fonts/artill_clean_icons.eot');

**Comment by alexalexpod** [comment]
Thank you for your answer, but the problem is that SPFx's **internal code** (like workbench) looks for these resources - not my code.
So I don't have any control of these calls to internal resources.
I think the only way to solve the problem is to reconfigure the SPFx settings to retrieve resources from my local machine.
And the question: **is there any way to reconfigure SPFx's internal settings for offline environment?**

Thanks, Alex.

**Comment by patmill** [comment]
Just to confirm, what project setting did you use in your yeoman generator?  OnPrem, or Cloud?

**Comment by alexalexpod** [comment]
Hi.
I have tried the both options (OnPremises and Cloud) but, unfortunately, the process still goes to the web address instead of a local one.
Alex.

**Comment by kgnugur** [comment]
I have the same problem, issue is open for 2 years. Isn't there any solution to this?

**Comment by hugoabernier** [comment]
Hi @alexalexpod  and @kgnugur there aren't any ways to configure SPFx's internal settings for offline environments.

@cmd64 's solution for custom web parts is a great one, but -- as you said -- it only takes care of custom code.

I'll make this issue as closed as this isn't something that we can resolve with samples, but if this is a feature you believe should be added, I'd recommend you open a suggestion on [UserVoice](https://sharepoint.uservoice.com/).
