### ISSUE TITLE
Client webpart using sp framework

### ISSUE THREAD

**Issue by alikniby** [SharePoint/sp-dev-fx-webparts#345]
I'm creating a Client WebPart using SharePoint Framework. The idea is to have a custom property of type String using a PropertyPaneTextField where the user can put some HTML. The final idea is to allow users to integrate some social networks components (Twitter wall for example).
If the property contains a <script> tag, the WebPart crash and display strange json content instead of the content.
Example HTML causing the issue:
<a class="twitter-timeline" data-width="220" data-height="400" data-dnt="true" href="https://twitter.com/sharepoint">Tweets by SharePoint</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

When inserting the HTML, the script is not called and only the basic HTML is displayed in real time. When you save the WebPart and the page reload, the WebPart is broken and displays some json content:
","Title":"My Twitter Feed"}}\" data-sp-splinksapplied=\"true\"> c82b67dc-2557-4dc2-a738-4ee411ad3583 ", 1, 1, false, []); } catch (e) { if (application != null && application.logClientSideWebPartLoadError != null) { application.logClientSideWebPartLoadError("g_16d93d7a_ad57_4fb1_8220_6d434d49ac6e", "Cannot load a web part on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details."); console.error(e); } else { console.error("Cannot load a web part on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details."); console.error(e); } } }); } else { console.error("Cannot load the web part wrapper on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site."); } })(window);

Observed Behavior

I would have expected that the HTML is displayed and the script called or at least that the script is blocked as it is the case for the Page Content but the WebPart should not crash.

Steps to Reproduce

All steps already explained.
I display my property with the render method:
public render(): void { this.domElement.innerHTML = `` <div class="webpart webpart-html webpart-${this.context.instanceId}"> <h2>${this.properties.Title}</h2> ${this.properties.HTMLContent} </div>``; }
(`` char have been doubled because of GitHub formatting)

The Edit Pane is coded with:
groupFields: [ PropertyPaneTextField('Title', { label: strings.PropertyTitleLabel }), PropertyPaneTextField('HTMLContent', { label: strings.PropertyHTMLContentLabel, multiline: true }) ]

Please note that even if I remove the ${this.properties.HTMLContent} is my render() method, so that the HTML is not displayed in the page, the WebPart still crash.

Also note that when the WebPart is crashed, if I try to edit the properties, it says that there is no property to edit for this WebPart. My only way out is to delete the WebPart and start again.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
