### ISSUE TITLE
How to upgrade/update an SPFx App Programmatically

### ISSUE THREAD

**Issue by pawanjajoo** [SharePoint/sp-dev-fx-webparts#346]
- [x] Question

- How can we upgrade/update a SPFx App? I know the web interface way of doing it, however, I have hundreds of site collections in the tenant and I want to push this update to all the sites that are using the app through an automated script.

**Scenario**: I have an app that provisions the site columns, a list and associates with a webpart. Now, there has been an update, where I have added one more site column and added it to the list to enhance the webpart use. How will I push this change to all the sites where the app is being used?

**Analysis**: I have done some research around it, mostly I get the articles on updating a PH App with .app extension. However, mine is an SPFx App with .sppkg extension, when I try to use the same objects that for PH App, I get an error that "Client Side Solutions cannot be used in this location." There are commands to add the SPFx App to the site but nothing that I could find to update/upgrade.

Any help or suggestions in this regard would be great.

**Comment by giuleon** [comment]
Hi,

maybe my blog posts could be useful for you:

http://www.delucagiuliano.com/automated-deployment-of-your-sharepoint-framework-solution-to-office-365-cdn

http://www.delucagiuliano.com/continuous-integration-and-deployment-for-your-sharepoint-framework-solutions

**Comment by andrewconnell** [comment]
FWIW, it's either "start clicking". 

However at Ignite MSFT said ALM APIs were on the way... while not committing to a specific date, it was clear that EOCY is the target... maybe we could call it _by end of year target-ish_.

**Comment by pawanjajoo** [comment]
@giuleon, thanks for your inputs. However, your articles do not help address the update issue. We have our CI/CD Process in-place for initial deployments. It's the increments that we want to address through a similar process.

@andrewconnell, thanks for the updates. Is there any user voice thread or any other forum where I can track the progress on this feature?

**Comment by andrewconnell** [comment]
Nothing I've seen where you can track it, but I watch the regular PnP JS SIG webcasts for details.

**Comment by joelfmrodrigues** [comment]
@pawanjajoo  I know this thread is old and hopefully you are already aware of it, but ALM APIs are already available for some time now. You can check the PnP SIG webcasts (as Andrew mentioned) to see this working

**Comment by hugoabernier** [comment]
@pawanjajoo  I hope that @andrewconnell  and @joelfmrodrigues 's answers helped you solve this issue.

I'll go ahead and close this issue as there hasn't been any activity here for a while. Feel free to open a new issue if you still need help with this.
