### ISSUE TITLE
SP-Client-Custom-Fields

### ISSUE THREAD

**Issue by hasan-abul** [SharePoint/sp-dev-fx-webparts#350]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
sp-client-custom-fields

Error - typescript - node_modules\sp-client-custom-fields\node_modules@microsoft\sp-webpart-base\node_modules@types\react\index.d.ts(3481,21): error TS2694: Namespace 'React' has no exported member 'DetailedHTMLProps'.
Error - typescript - node_modules\sp-client-custom-fields\node_modules@microsoft\sp-webpart-base\node_modules@types\react\index.d.ts(3488,23): error TS2694: Namespace 'React' has no exported member 'SVGProps'.
Error - typescript - node_modules/sp-client-custom-fields/node_modules//node_modules//index.d.ts(39,25): error TS1005: ',' expected.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
