### ISSUE TITLE
spfx deployment Manifest not found for Component

### ISSUE THREAD

**Issue by jtnicholson** [SharePoint/sp-dev-fx-webparts#352]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Created a web part using yo, tested on workbench, deployed to site and everything worked fine.  At some point today I went to update my code and redeploy and I got this error.  It works from the local workbench, and from dev workbench (using gulp serve) but not when I deploy it to a modern or classic page on sharepoint online.  Deploys without errors in my app catalog.

![webparterror2](https://user-images.githubusercontent.com/8990469/32248988-c86166e2-be5d-11e7-8737-eb70ffe9a61b.png)

**Comment by waldekmastykarz** [comment]
Could it be that you deployed the debug version of your .sppkg file and it tries to load the manifest from the dev server on localhost which isn't running at the moment?

**Comment by jtnicholson** [comment]
I did the package-solution --ship and when it deploys it does give me the right server location for the files.

**Comment by jtnicholson** [comment]
So I blew away the node_modules, temp, and sharepoint directory and redid the npm install and redid the package solutions and then everything worked again.  Guess something got corrupted on me.

**Comment by waldekmastykarz** [comment]
Good to hear you got it working!
