### ISSUE TITLE
SPFx(On-prem) React WebPart - How to get current list Title and Current ListItemID

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-fx-webparts#355]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

How  to get current list Title and current listItemID form this.context.pageContext in entry point file in my webPart?

The default edit form is replaced with my custom SPFx webpart:

Result for debugging is:
![asdsad](https://user-images.githubusercontent.com/14110861/32364432-8303582c-c07d-11e7-9449-6143531254c3.png)

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
Hey @geogikk92 did @BorisLand 's suggestion help you solve this issue?

I'll go ahead and close the issue as this thread has been pretty quiet, but feel free to open a new issue if you still need more help.
