### ISSUE TITLE
Inline anchor links not working with react-textboxio

### ISSUE THREAD

**Issue by paulculmsee** [SharePoint/sp-dev-fx-webparts#356]
[Hyperlink issue.zip](https://github.com/SharePoint/sp-dev-fx-webparts/files/1442716/Hyperlink.issue.zip)

- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The textboxio component supports inline hyperlinks to heading tags. One just clicks the arrow and it enumerates any <h> markup in the text.

#### Observed Behavior
The hyperlink is not created

#### Steps to Reproduce
Can be seen in workbench. Add the webpart, then add several headings and paragraph text to it. Click the hyperlink toolbar icon and choose one of the headings. The link will not be created. Regular hyperlinks work fine...

**Comment by FranckyC** [comment]
Hi @paulculmse, unfortunately, I think this feature is not supported by the editor by default. I can't really fix it on my own. You can try to use the editor in "Classic" mode instead of "Inline" mode [See the official doc](http://docs.ephox.com/display/tbio/Editor+types+-+Classic+vs+Inline)
