### ISSUE TITLE
Running gulp serve gives "ERR_SSL_PROTOCOL_ERROR" error  

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-fx-webparts#357]
I have recently installed new SharePoint framework 1.3.4. Now when i scaffold a new SPFx react solution and run gulp serve (https://localhost:4321/temp/workbench.html), it gives "ERR_SSL_PROTOCOL_ERROR" error.

#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Ability to scaffold SPFx project and run it on HTTPS

#### Observed Behavior
If i change the serve.json to serve it on http instead of https than it is working but i couldn't load on the https://[domain].sharepoint.com/_layouts/15/workbench.aspx.

##### Environment Configuration
-  NodeJs - (version 8.9.0)
- NPM (version 5.5.1)
- Gulp (version 3.9.1)
- YO (version 2.0.0)
- SPFx framework (version 1.3.4)
- Typescript (version 2.6.1)

#### Steps to Reproduce

- Run SharePoint Yeoman generator to create a new SPFx solution using react framework
- Run gulp serve
- When it serve to the browser, you will see the following error 

> This site can’t provide a secure connection
> localhost sent an invalid response.
> Try running Windows Network Diagnostics.
> ERR_SSL_PROTOCOL_ERROR

Thank you
Mugilan

**Comment by muges01** [comment]
Hi everyone,

I found another similar issue been raised under sp-dev-docs ( https://github.com/SharePoint/sp-dev-docs/issues/1013 and https://github.com/SharePoint/sp-dev-docs/issues/1002).

I seems that, the issue is with NodeJs 8.9.0. I have revert back to NodeJs 6.11.5 and i can run gulp serve without any problem.

**Comment by waldekmastykarz** [comment]
@muges01 have you tried applying the workaround mentioned in https://github.com/SharePoint/sp-dev-docs/issues/1002?

**Comment by muges01** [comment]
Hi @waldekmastykarz, sorry for the late reply, i didn't see your message until today. I was expecting to receive an email notification when someone comment here. 

However, i just tried the workaround by setting the NO_NODE_HTTP2 environment variable to 1 and it's worked. Thank you.

**Comment by waldekmastykarz** [comment]
Great to hear you got it to work @muges01

**Comment by vasavidurgaprasad** [comment]
I made NO_NODE_HTTP2 environment variable to 1. but it is not working. 
I am using SPFx framework 1.8 and Node 10.16.2

**Comment by michalhainc** [comment]
For me this doesnt fix the issue as well as like for @vasavidurgaprasad ... 

![image](https://user-images.githubusercontent.com/3962233/65405879-f20d9c80-dddd-11e9-8c8a-27c62b802484.png)
