### ISSUE TITLE
2nd webpart of same solution not available to be used in the SharePoint sites

### ISSUE THREAD

**Issue by kmarwen** [SharePoint/sp-dev-fx-webparts#360]
Hi all

I have 2 webparts (generated with yo) in one solution
both are available on workbench
but after deploying in the tenant only first one is available to be added in SitePages
I'm using chome and also tried IE

another scenario : when I use `"skipFeatureDeployment": true` in package-solution.json then both webparts are available. and when i get back to false only first one appears !

#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
all client webparts should be available for adding in site page

#### Observed Behavior
only first web part available for adding

#### Steps to Reproduce
yo @microsoft/sharepoint 
helloworld
yo @microsoft/sharepoint 
helloworld2

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)[https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.

here are my versions on package.json

`{
  "name": "generix-layout-webpart",
  "version": "1.0.6",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "@types/react": "15.0.38",
    "@types/react-dom": "0.14.18",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-update": "0.14.14",
    "@types/react-addons-test-utils": "0.14.15",
    "@microsoft/sp-core-library": "~1.3.0",
    "@microsoft/sp-webpart-base": "~1.3.0",
    "@microsoft/sp-lodash-subset": "~1.3.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.3.0",
    "@microsoft/sp-module-interfaces": "~1.3.0",
    "@microsoft/sp-webpart-workbench": "~1.3.0",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0"
  }
}
`

Does any one have a workaround plz ?
Thank you for helping

**Comment by bva999** [comment]
I ran into the same problem.

**Comment by kmarwen** [comment]
my solution was that I updated Yo to the last version : 

`npm outdated` to see modules with outdated versions
in my case it was Yo so I executed : `npm install @microsoft/generator-sharepoint@latest -g`

I followed these instruction : 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages

**Comment by kmarwen** [comment]
I added a 3rd webpart
and i'm facing the same problem !
the 3rd one is not available on webparts list  !!!

does any one had this issue plz ?

**Comment by waldekmastykarz** [comment]
@kmarwen What version of the SharePoint Framework Yeoman generator are you using?

**Comment by kmarwen** [comment]
Hi @waldekmastykarz 
for command `yo @microsoft/sharepoint --version` I have version : 2.0.0
when I run this : `npm @microsoft/generator-sharepoint --version` I have 3.10.10
it's the last one cause I updated the same day of this issue

thx
MK

**Comment by waldekmastykarz** [comment]
To check the version of the SharePoint Framework Yeoman generator please run:

```sh
npm ls -g @microsoft/generator-sharepoint
```

**Comment by kmarwen** [comment]
thank you @all
one year later I close this issue
