### ISSUE TITLE
react-to-do-basic sample componentWillReceiveProps not getting hit

### ISSUE THREAD

**Issue by MattGibz** [SharePoint/sp-dev-fx-webparts#363]
If you clone and package this app to deploy in a SharePoint environment (therefore using the SharePointDataProvider), the componentWillReceiveProps function in the ToDoContainer component is never being called. Therefore, it is not updating the state with the new items after choosing your list in the web part properties. Any idea why this is happening?

https://github.com/SharePoint/sp-dev-fx-webparts/blob/66b37f5b2483ec11a10a7970ee470d9459d9ce70/samples/react-todo-basic/src/webparts/todo/components/TodoContainer/TodoContainer.tsx#L40

**Comment by hugoabernier** [comment]
Hey @MattGibz  did you ever resolve this?

I'll mark the issue as closed because it has been quiet for a while, but feel free to re-open it if you still need help here.
