### ISSUE TITLE
react-content-query-webpart - Downgrading back to allow SharePoint 2016 on premesis?

### ISSUE THREAD

**Issue by alirobe** [SharePoint/sp-dev-fx-webparts#366]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

Hi @spplante 

Thanks so much for your great webpart. I'd love to be able to deploy it on SP 2016 On-Premesis FP2.

Would it be possible to restrict the versions of the dependencies that you've just upgraded back to 1.1.0, and introduce metadata so that the sppkg file produced by the build process is compatible with the current on-prem feature pack? Some guidance on how to achieve this would also be appreciated.

Looking forward to seeing this become the new standard webpart for rollups 🥇 
/cc @tallday

**Comment by spplante** [comment]
Hi @alirobe, 

Thank you for the comment :) I will admit that you basically just taught me that SP2016 was only supporting v1.0.0 as I was assuming the upgrade would have no impact on SP2016 :(

That being said, having a mechanism to build for SP2016 or O365 would be quite a mess as the differences aren’t only in dependencies but also in the code. When upgrading, I had to fix some code here and there, some classes were using properties that wouldn’t exist anymore etc...

If anything, the only solution would be to downgrade the solution back the v1.0.0 for everyone, I am just not sure if it’s a matter of weeks/months before SP2016 supports SPFX v2.0.0, of it’s planned to use v1.0.0 for a while.

Maybe @VesaJuvonen could have some informations for us?

**Comment by alirobe** [comment]
@spplante my understanding is that the dependencies will be updated every feature pack. FP2 is just 2 months ago (Sept 2017), and FP1 was November 2016. I think they promised a 6 month interval at some point, but so far it hasn't been the case... Who knows? Anyway, FP3 would probably be an OK target to keep in mind if FP2 is not doable...

If you update the yeoman generator, it provides you the option of producing a project that is SP2016 on-prem compatible plus online, or online only. If you generate a 2016 project, there is quite a bit of different metadata. I had a quick go at trying to convert your 1.2 project back to 1.1.0 by diffing the metadata, and gave up when I realised it wouldn't compile... so I didn't submit a PR. But here's the mess I managed to make, for what it's worth: https://github.com/alirobe/sp-dev-fx-webparts/commit/361bc98eb6761a0a58a17c9db8573502024fff47

**Comment by spplante** [comment]
@alirobe yeah like I said you will have problems at a couple of places in the code by changing versions. 

Anyway If I had to do it I wouldn’t try to play in the config files or anything in order to downgrade the WebPart, there is too many things that you can forget. I would just create a brand new yeoman generated project from the previous version, and start copying the files from one project to the other. At this point the only errors you will end up with are code errors that can be fixed with minimal efforts.

I will take a look at it this weekend, hopefully I can submit my PR by the end of sunday so you can use it for Monday :)

Thanks!

**Comment by spplante** [comment]
Hi @alirobe,

I just completed the pull request #370 with the solution reverted to 1.1.0 successfully. The good news is that all the code I modified back in the days to upgrade to 1.2.0, is backward compatible with drop 1.1.0, which means it will be a breeze to upgrade to 1.X.X later on if ever I need to.

If you don't want to wait for the PR to be merged to master, you can get the latest sources directly on the dev branch of [my fork](https://github.com/spplante/sp-dev-fx-webparts/tree/dev/samples/react-content-query-webpart) and you'll have a working project for SP2016 👍 

Cheers!

**Comment by alirobe** [comment]
Awesome! 

Will test and deploy in the next few days, and let you know how it goes go.

Thanks @spplante! You rock!🥇

**Comment by waldekmastykarz** [comment]
> Anyway, FP3 would probably be an OK target to keep in mind if FP2 is not doable...

FWIW: just because there would be a next version of SPFx available on prem, doesn't necessarily mean all organizations would have it installed. If you want to reach as broad audience as possible, use the lowest version supported.
