### ISSUE TITLE
After change regional settings, pages with SPFx webparts gives unexpected error has occurred. 

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-fx-webparts#367]
- [ ] Question
- [x] Bug
- [ ] Enhancement

After change regional settings in SharePoint 2016 On-Premise server to Bulgarian, Macedonian оr other Locale
![untitled](https://user-images.githubusercontent.com/14110861/32935570-6d0c397e-cb79-11e7-9359-305cc80f2610.png)

**I have following error:**
![untitled](https://user-images.githubusercontent.com/14110861/32935634-a60ea040-cb79-11e7-9d9e-194876a3a4c9.png)

**Error from log file is:**

> Message  : System.FormatException: String was not recognized as a valid DateTime.    at
>            System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetUpdateTimeFromAppCatalog(SPWebweb)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetDistributedUpdateTime(Guid tenantId, SPWeb web)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.EnsureCacheIsValid(SPWeb web, Guid tenantId)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetNotFoundComponents(SPClientSideComponentQueryResultCollection requests, SPWeb web)     at Microsoft.SharePoint.ClientSideCom...
> 

Thanks for your contribution! Sharing is caring.

**Comment by waldekmastykarz** [comment]
Did you customize the list's Add form and put a SharePoint Framework client-side web part on it?

**Comment by geogikk92** [comment]
Yes! I replace my default add listItem form with customized  SharePoint Framework client-side web part.

![asdf](https://user-images.githubusercontent.com/14110861/33016905-f0de9798-cdf8-11e7-9016-86f3581bd3fc.png)

My WebPart working with Locale(English(USA)), but others locale(Bulgarian, Macedonia and other) doesnt working, give above error.

**Comment by waldekmastykarz** [comment]
@VesaJuvonen do you have more information about if SPFx web parts are not meant to be used on list form pages and the behavior is by design or if this is a potential bug in SPFx that needs further investigation?

**Comment by geogikk92** [comment]
I have SPFx web parts In site classic pages and error is the same.

**Comment by waldekmastykarz** [comment]
Which version of the SharePoint Framework Yeoman generator did you use to scaffold the project?

**Comment by geogikk92** [comment]
The version of the SharePoint Framework Yeoman is:

![untitled](https://user-images.githubusercontent.com/14110861/33018005-4447ea70-cdfd-11e7-903d-92eb8e5e84af.png)

**Comment by darekjpro** [comment]
Having the same issue. 
Using the latest version of Yeoman (1.3.4). SPFx web part, solution targeted for SharePoint 2016 onwards. 
SPFx web part added to classic web part page working fine with English-US regional settings. Changing site regional settings to English-UK causes the same error in ULS (_String was not recognized as a valid DateTime._)
Thanks.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#1083

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue in the SPFx and not in any of the specific samples, moved it to the sp-dev-docs repository issue list, so that we get it tracked using our official process in engineering. In general would always recommend reporting generic SPFx issues in the sp-dev-docs repository, since we track those submissions closely.

**Comment by geogikk92** [comment]
Thanks @VesaJuvonen . We will know in the future. I hope the problem will be resolved. Best regards 👍
