### ISSUE TITLE
react-search-refiners requires the spanish version of lodash

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-fx-webparts#369]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

I expect the webpart to compile

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

The compilation fails with  import intersection from "lodash-es/intersection";
import clone from "lodash-es/clone";
fails - cannot find lodash-es

I am in the UK so I do not have lodash-es.

#### Steps to Reproduce
gulp serve

Thanks for your contribution! Sharing is caring.

**Comment by waldekmastykarz** [comment]
_-es_ in _lodash-es_ isn't referring to a locale. It's a specific version of the lodash package: https://www.npmjs.com/package/lodash-es.

**Comment by FranckyC** [comment]
@NPrice99 Updates have been made to this sample in the dev branch. Are you able to use it?

**Comment by FranckyC** [comment]
@VesaJuvonen I think you can close this one since it is not an issue.
