### ISSUE TITLE
how to change a sample to work with SPFx 1.3.4 or higher in "On-premise" mode

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-fx-webparts#371]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement
I found how to scaffold a new project with SPFx 1.3.4 in "On-premise" mode 
Now I want to adopt one of your samples but I know they target Sharepoint Online.
What are the steps to take to change the SPFx version and mode?
Also how to change versions of other frameworks like VUE and not break the Typings?

Thank you in advance

**Comment by waldekmastykarz** [comment]
The easiest would be to create a new project and move the relevant code pieces from the existing samples to your new project. That way you can ensure that all files as well as project structure match your version of the SharePoint Framework.

When building your SPFx solution you can see in the console the version of TypeScript used by the toolchain. When referencing types of other frameworks, check that they match the TypeScript version used by SPFx.

**Comment by VesaJuvonen** [comment]
Closing as answered.
