### ISSUE TITLE
Calling incorrect CRUD method for reading item

### ISSUE THREAD

**Issue by jxs0900** [SharePoint/sp-dev-fx-webparts#374]
https://github.com/SharePoint/sp-dev-fx-webparts/blob/20f59f8edd41471010e57129ccbb60c4907bbbcb/samples/sharepoint-crud/src/webparts/reactCrud/components/ReactCrud.tsx#L52

` <a href="#" className={`${styles.button} ${disabled}`} onClick={() => this.createItem()}>
                <span className={styles.label}>Read item</span>
              </a>`
**_SHOULD BE:_**
` <a href="#" className={`${styles.button} ${disabled}`} onClick={() => this.readItem()}>
                <span className={styles.label}>Read item</span>
              </a>`

**Comment by hugoabernier** [comment]
@jxs0900 thanks for suggesting a fix. I hope that @gautamdsheth 's update took care of this issue?

We encourage contributions on this repo. I hope you'll feel welcome to submit a pull request next time. 

If you're unsure how to go about making a pull request @PopWarner runs a free hands-on workshop where he walks people through making their first contributions. I encourage you to [sign up](https://github.com/pnp/sharing-is-caring) and contribute.

Thanks again for your help!
