### ISSUE TITLE
Upgrading SPFx Apps in a Site Collection App Catalog results in "Invalid App ID"

### ISSUE THREAD

**Issue by BigEaseGueldi** [SharePoint/sp-dev-fx-webparts#375]
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Once you increment a to a newer version, you should be able to upload that version to a **Site Collection App Catalog**, update the referenced files, and then to upgrade the App.

#### Observed Behavior
Updating the App works as expected (though I never understood why it has to be checked out). It also reflects the new version. Then my standard way (is that really the best way?) is: Go to Site Contents, pretend you want to add an app. Select "From your Organization" on the left, find you app, click on "Find out why" and then click on "GET IT". 
The problem: If you click on "Find out why" you will see this:

![image](https://user-images.githubusercontent.com/17311219/33335956-da014882-d46e-11e7-929e-086ef26030ca.png)

(this app id is not the one of the app)

#### Steps to Reproduce
(see above). I'm on SPFx 1.3.4. , Node 6.12.0

Thanks for your help! Dirk

**Comment by iroot123** [comment]
I've got the same issue. Did you find a solution?

**Comment by BigEaseGueldi** [comment]
Wasn't able to reproduce the error with SPFx 1.4. Therefore closing the issue.

**Comment by govinddk4444** [comment]
I am also facing the same issue.

![image](https://user-images.githubusercontent.com/27952352/61043854-ea507580-a3f4-11e9-9f1c-d825a1cf650b.png)

**Comment by a2life** [comment]
Same here.  If the same app is installed on tenant level, Detail is shown as expected. However, when uploaded to the site collection level app catalog, then the app can not display 'detail' page.

**Comment by sunishissac** [comment]
Same issue, tenant level it works but not on site collection.

**Comment by jaredbuttars** [comment]
This is still an issue for site collection app catalogs in our tenant. Using SPFx version 1.10.0
