### ISSUE TITLE
Should I change value of version in .yo-rc.json while upgrading the solution?

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-fx-webparts#377]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

If I want to upgrade the SPFx webpart to 1.3.4 which is created with the verion 1.3.2, then with the **package.json** should I also change the version 1.3.4 in **.yo-rc.json**? my current .yo-rc.json file is like below

```
{
  "@microsoft/generator-sharepoint": {
    "version": "1.3.2",
    "libraryName": "sp-fx-webparts",
    "libraryId": "e9a4c80f-ded6-4166-8906-44aecc0fa266",
    "environment": "spo"
  }
}

```

**Comment by craghavendra21** [comment]
Hi all, please answer this question I want to upgrade my solution.

**Comment by waldekmastykarz** [comment]
If you upgrade all dependencies and project structure to match projects created using v1.3.4 of the SPFx generator, then it would make sense to update the version in the .yo-rc.json file to indicate to the generator the project structure version. As far as I know, currently, the generator doesn't perform any checks based on that version number, but if this would change in the future, this version number should reflect what's in your project.
