### ISSUE TITLE
Build failed with property includeClientSideAssets

### ISSUE THREAD

**Issue by rupppat** [SharePoint/sp-dev-fx-webparts#384]
Build failed with additional property in package-solution.json file: "includeClientSideAssets": true

Added the property as described: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn#project-directory](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn#project-directory)

Error message in Terminal:

ERROR: Error parsing file 'package-solution.json'
(#/solution) Additional properties not allowed: includeClientSideAssets

package.json : 
[package_json.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/1542532/package_json.txt)

**Comment by waldekmastykarz** [comment]
This is an issue with the SPFx generator. As it refers to the SharePoint Framework and not the samples in this repo, could you please resubmit the issue in the https://github.com/SharePoint/sp-dev-docs repo where it will be triaged?
