### ISSUE TITLE
Missing PersonaCardHandler file in react-skype-status sample

### ISSUE THREAD

**Issue by tchagan** [SharePoint/sp-dev-fx-webparts#385]
#### Category
- [x] Bug

#### Expected or Desired Behavior
The react-skype-status should build without errors

#### Observed Behavior
The react-skype-status sample will not build, the build displays the following error:

error TS2307: Cannot find module './PersonaCardHandler'.

#### Steps to Reproduce
type gulp build

**Comment by JuanmCanamero** [comment]
If you remove this line, the webpart build correctly. But... I cant do work it....when I write the email and click subscribe, the page do postback and does nothing.

**Comment by baywet** [comment]
Hi @tchagan sorry for getting back to you this late.
The way this repository is currently setup, sample authors don't get a notification when an issue is logged against their sample.
My latest pull request adresses this issue and has been merged in dev (soon in master) https://github.com/SharePoint/sp-dev-fx-webparts/pull/547
Thanks @JuanmCanamero for replying on my behalf :)
