### ISSUE TITLE
Upgrading from Yeoman 1.3.4 to 1.4.0 causes working code to stop working.

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-fx-webparts#386]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

I have tried to upgrade a SPFx project from Yeoman 1.3.4 to 1.4.0 as a result of this React is upgraded from version 14 to version 15.6.

As a result my code has gone from working to not working :-

```typescript
private _showAlert(): void {
const alert: React.ReactElement<IAlertProps> = React.createElement(
Alert,
{
message: strings.CustomSearchPlaceholderModeOnAlert
}
);
ReactDom.render(alert, this.domElement);
}
```

```console
Error :-  
[ts]
Argument of type 'typeof Alert' is not assignable to parameter of type 'string | ComponentClass<IAlertProps> | StatelessComponent<IAlertProps>'.
Type 'typeof Alert' is not assignable to type 'StatelessComponent<IAlertProps>'.
Type 'typeof Alert' provides no match for the signature '(props: IAlertProps & { children?: ReactNode; }, context?: any): ReactElement<any>'.
import Alert
```

**Comment by iclanton** [comment]
Does `const alert: React.ReactElement<Alert> = React.createElement(...)` work? You should also be able to use the TSX syntax (`ReactDom.render(<Alert message={ strings.CustomSearchPlaceholderModeOnAlert } />, this.domElement);`).

If you open your project in Visual Studio Code, you should be able to mouse-over the line with the issue and see what type it's expecting.

**Comment by NPrice99** [comment]
Hi - apologies for not getting back to you earlier, but I did not get the notification you had replied. 
In the case of const alert: React.ReactElement<Alert> = React.createElement (...). The error message is Argument of type ‘typeofAlert’ is not assignable to parameter of type ‘string | ComponentClass<IAlertProps> | StatelessComponent,IAlertProps>’

In the case of ReactDom.render(<Alert message={ etc.   The error message is Argument of type ‘Alert’ is not assignable to parameter of type<’Component<any,{}>’ and also the left hand side of an arithmetic operation must be of type ‘any’, ‘number’ or an enumeration type.

**Comment by joelfmrodrigues** [comment]
@NPrice99  try creating a new project and move your code into it. Worked for me

**Comment by joelfmrodrigues** [comment]
You will also need parts of some files within the config folder, but it
will depend on your solution. Compare all the files in that folder between
both projects and it should be really easy to understand which ones you
will need. I would advise to only copy the sections of content that are
related to your solution and not the whole file.

**Comment by joelfmrodrigues** [comment]
Also add any additional packages you may have on the packages.json file of your existing solution

**Comment by andrewconnell** [comment]
@NPrice99 - Can you share any non-IP details about the project you were having issues with? Web Part / App Customizer / Field Customizer / Command Set?

**Comment by NPrice99** [comment]
HI AC - here is the project I was trying to upgrade :- https://github.com/VelinGeorgiev/spfx-react-search-box-webpart .  This was the issue I was having :- https://github.com/VelinGeorgiev/spfx-react-search-box-webpart/issues/2

**Comment by VelinGeorgiev** [comment]
@NPrice99 I can try to update my own sample in the next days. Didn't know it get so popular that got all the way to the pnp webparts discussion :) . Maybe I could submit it as sample to this repo ;). Will let you know when is migrated to 1.4 here as well.

**Comment by NPrice99** [comment]
@VelinGeorgiev This is how I upgraded it, I am not sure it is the right way -> https://sharepoint.stackexchange.com/questions/233642/i-have-upgraded-from-yeoman-1-3-4-to-1-4-0-and-i-cannot-import-mystrings-d-ts

**Comment by VelinGeorgiev** [comment]
@NPrice99 I updated the sample to 1.4.0. That issue can be closed now.

**Comment by hugoabernier** [comment]
Thanks @VelinGeorgiev for your contributions!

**Comment by VelinGeorgiev** [comment]
You are welcome
