### ISSUE TITLE
Page is randomly requesting different versions of web part .js files from CDN

### ISSUE THREAD

**Issue by luis-ribeiro** [SharePoint/sp-dev-fx-webparts#388]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When .sppkg solution file is updated in appcatalog and app is updated in site, web part instances should read new web part .js files (like "web-part_7f556bc0c3f0905fa3a2dc04542xxxxx.js") from O365 CDN, not old files from a previous bundle.

#### Observed Behavior
When I reload the page, a web part  instance (same page, same browser, same session) is requesting different versions (old version) of webpart files from CDN. It looks random behavior when refreshing page.

I have attached requested webpart files in same page, after refreshing a couple of times.   

Up to date file request:
![capture1-ok](https://user-images.githubusercontent.com/16116591/34000619-b808105c-e0e5-11e7-8c49-a1b0e32eeac5.PNG)

After some page reloads, requesting old file:
![capture2-oldversion](https://user-images.githubusercontent.com/16116591/34000637-bfe0f776-e0e5-11e7-8e27-acdd0818e739.PNG)

I have checked .sppkg file and is referencing the new version of file.
Also removed and installed app to make sure it is up to date, removing and adding the webpart to page.

- There is some synchronization process that is not completed and I am accessing different servers? 
- Whats the best practice, shouldn't the old bundle file versions be removed from CDN?

**Comment by hugoabernier** [comment]
Hey @luis-ribeiro did you ever resolve your issue here?

I'll close the issue as it is from a few years ago and most likely resolved, but if you're still running into problems feel free to open a new issue.
