### ISSUE TITLE
sppkg file size increasing for each and every package-solution --ship

### ISSUE THREAD

**Issue by vamsi981** [SharePoint/sp-dev-fx-webparts#397]
Package file Size keep on increasing without any changes in the Code, i have created a webpart and deploying to production for each and every production build the file size keep on increase by **100-150kb**

**Comment by VelinGeorgiev** [comment]
Are you executing `gulp clean`, before `gulp build, bundle and package-solution`?

**Comment by vamsi981** [comment]
Thanks @VelinGeorgiev i forget the `gulp clean`  almost
