### ISSUE TITLE
CDN path in sample manifest not correct?

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-fx-webparts#402]
#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Hi, shouldnt the CDN path be: 
`{
  "cdnBasePath": "https://publiccdn.sharepointonline.com/<tenant host name>/sites/site/library/folder"
}`

This file:
https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/bootstrap-slider/config/write-manifests.json
`{
  "cdnBasePath": "https://dhartman.sharepoint.com/sites/PnPSlider/SiteAssets/"
}`

Has a path to a SP library directly, and not the publiccdn path.

I am pretty new to the SPFX samples on GitHub, so let me know if I am wrong. I got the CDN setup from the MS article: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn

Thanks!

-Eric

**Comment by VelinGeorgiev** [comment]
You are right. The CDN path should be as you mentioned if you really want to use CDN with caching, distribution and all the rest of features that come along with CDN.

Accessing the file with that path `{ "cdnBasePath": "https://dhartman.sharepoint.com/sites/PnPSlider/SiteAssets/" }` would not give the any CDN features. It can be used like that in case you do not want to use CDN features, but just host the files within your tenant. That approach would still load your javascript files, but would load them like a normal server call.

Do you know that as from 1.4.0, the SharePoint Framework can handle the wepbart/extention files for you and upload them automatically without the need to worry about. Have a look at that article for more information: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets

**Comment by VesaJuvonen** [comment]
Closing as answered.
