### ISSUE TITLE
react-bot-framework webpart keeps reloading entire page on classic site when sending message to bot

### ISSUE THREAD

**Issue by stephanbisser** [SharePoint/sp-dev-fx-webparts#407]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
If I send a message to a bot via direct line on a classic SharePoint Online page, the page won't be reloaded and the bot should receive the message and write back.

#### Observed Behavior
The page gets reloaded instantly after sending the message in the SPFX webpart and the message history is cleared. Interestingly the web part is behaving as it should on modern pages.

#### Steps to Reproduce
Package the solution and upload it to the app catalog. After adding it to a classic SPO page, the direct line secret has to be configured and the web part is ready to communicate with the bot. After inserting a message, the page will be reloaded, when hitting enter.

I also get the following error in the browser:

errObj: Error
columnNumber: 640375
crossDomain: true
fileName: "https://publiccdn.sharepointonline.com/solviondev.sharepoint.com/sites/appcatalog/ClientSideAssets/69787426-771f-4f6c-887d-a23453d7efe3/bot-framework-chat-web-part_debded6a8e37d6e99d609c501e46cdf6.js"
lineNumber: 33
message: "Request has been terminated\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."
method: "POST"
stack: "p.prototype.crossDomainError@https://publiccdn.sharepointonline.com/solviondev.sharepoint.com/sites/appcatalog/ClientSideAssets/69787426-771f-4f6c-887d-a23453d7efe3/bot-framework-chat-web-part_debded6a8e37d6e99d609c501e46cdf6.js:33:640375\np.prototype.end/n.onreadystatechange@https://publiccdn.sharepointonline.com/solviondev.sharepoint.com/sites/appcatalog/ClientSideAssets/69787426-771f-4f6c-887d-a23453d7efe3/bot-framework-chat-web-part_debded6a8e37d6e99d609c501e46cdf6.js:33:641176\n"
status: undefined
url: "https://directline.botframework.com/api/conversations/dRg0Ve9ngGHq0XUxQA0aZ/messages"

It looks like it's a CORS thing, but why is it working on modern pages?

Hope you can assist...

**Comment by MichaelHaushofer** [comment]
+1
i am also facing same issue but without the error mentioned above. 
it works fine in edit mode, but without edit mode it keeps reloading the page as mentioned above
