### ISSUE TITLE
spfx webpart provisioning to SP server page layout

### ISSUE THREAD

**Issue by HelloPnP** [SharePoint/sp-dev-fx-webparts#408]
I've a Home Page layout in SharePoint Server 2016 and i've to place 5 to 6 SPFX webparts to the page layout

how can i provision spfx webparts to the home page layout?

**Comment by HelloPnP** [comment]
anyone has added spfx components to page layout?????

**Comment by VesaJuvonen** [comment]
You can use the PnP provisioning engine or APIs to place the web parts automatically to the pages. Typically you'd use the PnP provisioning engine for that. Here's a PnP Webcast from January where the process is demonstrated - https://youtu.be/SKKOV9qB62w?t=1898.
