### ISSUE TITLE
Giving issue while adding web part to app catalog

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-fx-webparts#409]
I have adding SPFx web part to my site by adding .sppkg file to app catalog. Upto 4 days back it was worked fine. But all of sudden from yesterday web part is not visible on page. When I try to find the SPFx app in modern view, I am not able to find the web part. But if i see the site contents page in classic view web part is appearing. I have tried to remove the web part, it almost took 20 hrs to get deleted.
I thought something was wrong here. So I decided to add same web part with newer version. But while adding it is giving me following error.
![addapptocatalog](https://user-images.githubusercontent.com/7568187/35861996-11bad9ae-0b70-11e8-9960-baf8d2ddfb6f.PNG)
If I do `gulp serve` then in workbench it is working fine. Not in production.
I am using `gulp bundle --ship` and `gulp package-solution --ship `commands to generate the files.

**Comment by ymihir** [comment]
As per the information there is currently an outage that prevents you from uploading/adding/removing apps https://sharepoint.stackexchange.com/questions/235444/issue-while-adding-web-part-to-app-catalog

**Comment by vamsi981** [comment]
Hi @ymihir we are also facing same issue with our multiple Tenants, Thanks for the Update

**Comment by VelinGeorgiev** [comment]
That should be fixed by now. You can close that issue.

**Comment by VesaJuvonen** [comment]
Closing as this was related on the outage.
