### ISSUE TITLE
Is it Possible to use reference of one webpart in another webpart if available in same page

### ISSUE THREAD

**Issue by vamsi981** [SharePoint/sp-dev-fx-webparts#430]
#### Important

Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.

----

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

Hi while developing SPFX Webparts is it possible to reuse pnpjs or any 3rd party libraries used in one webpart and reuse the same if both the webparts are loaded in the same page .

**Comment by AustinBreslinDev** [comment]
Hi @vamsi981,

Could you clarify the question, I'm thinking of a few possibilities here.

1. Share data retrieved from one WebPart (data in a SharePoint List for example), you could use this sample to solve that: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-rxjs-event-emitter

2. Share state in a controlled manner from one WebPart to another, you could use redux as shown in this webpart samples:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-redux
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-redux-async-immutablejs

3. Share a library between the two webparts that isn't a part of the SPFX, you should refactor the both webparts, small refactor and updating one of the files in the webparts config folder. I can't remember which one.
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/add-an-external-library.md

4. You are talking about a library that you wrote yourself, and is in the same code base as the two webparts, you could move the library from the first webpart and place it into the SharePoint Online CDN, or your own CDN and reference it like in point 3. Or you could just move the library and import it into both webpart independantly.

Or are you talking about not doing any of the above and in that case your webparts would be coupled, not a good idea if your writing unit tests or debugging later on when you forget that the second webpart requires the first.

But to answer will the second webpart work with the first webparts imports? Yes and no. Webparts are loaded async and this means that their is no guarantee that the second webpart will load after the first.

**Comment by VesaJuvonen** [comment]
Closing due to no comments from the original submitter. The answer seems sufficient.
