### ISSUE TITLE
Communications Site Template

### ISSUE THREAD

**Issue by mstivoi** [SharePoint/sp-dev-fx-webparts#432]
This bug is about new "Communications Site" template and SEWP react web part.  
Communications Site have top navigation menu , which do not load page completely. 
So, when serfing between pages , SEWP do not re-execute scripts.

For reproducing you can just create <script> with very simple js code in it like alert(). It executes fine during complete page load , but not when top navigation used ..
- [ ] Question
- [ x ] Bug
- [ ] Enhancement

**Comment by waldekmastykarz** [comment]
@wobba

**Comment by wobba** [comment]
@waldekmastykarz  God damn async fake page loading :) I'll look into it.

**Comment by mstivoi** [comment]
I have already fixed that on my side . 
1) Added hidden label on page , indicates,  page was already loaded or not .
2) Used separate script loading for both cases . 
I only worry , how many surprises Modern Pages have ? My customer ask me , will it be working stable someday :)

**Comment by waldekmastykarz** [comment]
@mstivoi this is not really an issue with modern pages, but with the Script Editor Web Part not handling navigate events correctly.

**Comment by mstivoi** [comment]
Yes , i understand . I mean some modern pages functionality , i don't know about ...

I know one more modern SEWP issue/bug . I not able to load Angular Formly .And i am not sure , why .

**Comment by wobba** [comment]
@mstivoi for repro I did this:

1. Created a comm site
2. Create a page a.aspx
3. Added the wp and alert on that page
4. Added a link in top nav to /teams/CommSite/SitePages/A.aspx
5. Navigated to the home page
6. Click the nav entry, and the alert displayed

..so what am I doing wrong for repro?

**Comment by mstivoi** [comment]
Does page "a.aspx" Modern page ? Can you confirm, browser window loads partly , when you navigates between pages ?

**Comment by wobba** [comment]
@mstivoi it's modern indeed and I get a fetch with: `https://tenant.sharepoint.com/teams/CommSite/SitePages/A.aspx?as=json`

**Comment by wobba** [comment]
I have deployed the latest code built on 1.4.1, where I add the wp explicitly to the site as an app.

**Comment by mstivoi** [comment]
May be that was old code . You can close this issue...

**Comment by wobba** [comment]
The codelogic itself hasn't changed, and If you can repro with the latest build please re-open another issue so I can possibly fix it :) If you can create a small angular sample I can deploy easily create an issue for that as well and I can test.
