### ISSUE TITLE
Please note that Textbox.io is not free as you state in your readme

### ISSUE THREAD

**Issue by MichaelFromin** [SharePoint/sp-dev-fx-webparts#433]
Textbox.io is a commercial offering from Ephox and is not free or open source.   Can you please modify the readme (sp-dev-fx-webparts/samples/react-textboxio/) to not state that incorrect information.

**Comment by AustinBreslinDev** [comment]
@MichaelFromin,

Textbox.io is free but has a commercial offering of support from Ephox as described in Issue #410 by an Ephox employee.
