### ISSUE TITLE
react-tinymce only works in local workbench, not remote, and does not deploy

### ISSUE THREAD

**Issue by aaronhawryluk** [SharePoint/sp-dev-fx-webparts#438]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
react-tinymce deploys normally.

#### Observed Behavior
react-tinymce works normally in the local workbench.
It is invisible (no CSS, according to the console) when run in the remote workbench, and reports errors when attempting to deploy it to a web site. (It uploads normally to the App Catalog.)

When deploying to the site, it reports the following error: Sorry, something went wrong with adding the app. Click to retry.
Clicking to retry eventually fails.

When run in the remote workbench, it reports the following errors:
 HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://xxxxx.sharepoint.com/sites/xxxxx/src/webparts/reactTinyMce/skins/pnp//skin.min.css

 HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://xxxxx.sharepoint.com/sites/xxxxx/src/webparts/reactTinyMce/skins/pnp//content.min.css

Looks like the content in the src/webparts/reactTinyMce/skins directory is not getting added to the bundle, or is not being referenced properly.

#### Steps to Reproduce
Run gulp serve --nobrowser and test in remote workbench. Webpart will fail when added to page.
Bundle, package, upload, and install as usual, then try to deploy to a site. Deployment will fail.

**Comment by AustinBreslinDev** [comment]
It says it in the webpart sample code that where the skin is hosted is up to you, just using the code as is will not do.

https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-tinymce/src/webparts/reactTinyMce/components/ReactTinyMce.tsx

Read the first comment.

**Comment by aaronhawryluk** [comment]
Got it, thanks Austin, next time I'll RTFM (or RTFSC). ;-)

**Comment by aaronhawryluk** [comment]
I have tried with a specified path for the skin, but the app still doesn't deploy to a site in SPO.

Reproduce:
1) Upload to App Catalog. DO not check the box to deploy to all sites.
2)  Deploy to a site manually.
3) Site deployment fails with an error (attached).
4) "Click to try again" also fails.
![erroraddingrtmcapture](https://user-images.githubusercontent.com/37034139/37167882-1fe29620-22d1-11e8-82d1-f0f8f2d25481.PNG)

I am contacting SPO support to see if I can get details of the error.

**Comment by aaronhawryluk** [comment]
Follow up: Does the webpart require that it be deployed to all sites in the tenant when uploaded? I haven't tried that yet.

**Comment by aaronhawryluk** [comment]
That seems to solve the issue, if I deploy for all sites when uploading it works.
Any clue as to how I would change that? Is there a config setting I can change, or do I have to build a new web part from scratch with the generator if I want to make it deployable on a per-site basis?

**Comment by AustinBreslinDev** [comment]
Hi sorry, since people will have their own requirements I didn't even try to solve how to host the application, way too many variants to look after. It should be deployable to multiple sites, but maybe requries multiple builds with different CDN paths.

**Comment by aaronhawryluk** [comment]
Fair enough, I'll see what I can figure out. Thanks for the help!

**Comment by Tomatokun13** [comment]
Just in case, I notice the id is the same for the generated SharePoint package and the web part. When I try to add the app in a SharePoint site, an error occurs and I can't add the app (same behaviour as the Aaron's screenshot) 
When I changed the id for the web part (in ReactTinyMceWebPart.manifest.json), I could finally add the app.
