### ISSUE TITLE
react-search - Multiple webparts on same page causing issue

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-fx-webparts#441]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I'd like to be able to add multiple of the same webpart (react-search) to a single page.

#### Observed Behavior
When adding two or more of the same webpart, the last configured webparts overwrites the contents of the other webparts. I.e if you set webpart 1 to search for "images" and then add webpart 2 to the same page and set it to search for "documents", webpart 1 gets webpart 2's search results.

#### Steps to Reproduce
Add two or more react-search webparts to a page, change the queries to be something different on each. When clicking apply on the second it overwrites the contents of the first.

**Comment by estruyf** [comment]
@HTEredrock thanks for reporting this. You might want to take a look at the improved version of this web part which you can find here: https://github.com/estruyf/react-handlebars-search

There are various improvements in the new versions like:
- Better templating engine
- Debugging template
- Paging
- MUI coming later this week

**Comment by HTEredrock** [comment]
@estruyf , thanks! The new webpart works great. I was just wondering if its possible to access the field properties inside script tags?
