### ISSUE TITLE
Making react-tinymce, react-textboxio, and react-script-editor content indexable

### ISSUE THREAD

**Issue by aaronhawryluk** [SharePoint/sp-dev-fx-webparts#450]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

Hi there,

Several of the sample web parts allow one to enter rich text on a page. However, none of the samples provided makes the content they add searchable. It's on the page, but searching for it does nothing. This does not seem particularly useful.

When checking the page I see a property called CanvasContent1. It looks like source goes in here, and it looks like this is the source of the indexed content in modern pages, since when I check it, the contents of these specific web parts do not go in it.

How do I change that? Are there existing methods I can call to add my content to whatever field it is that gets indexed? If I need to roll my own, how do I have this happen when the page is saved/published? Workflow?

**Comment by FranckyC** [comment]
Hi @aaronhawryluk, Actually, the content in the react-textboxio sample Web Part is indexed as an HTML string according to this [configuration](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint):

```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
    'content' : {isHtmlString: true}
    };
}
```

As I remember and according to this [thread](https://github.com/SharePoint/sp-dev-fx-webparts/issues/102), the content is indexed and then available trough the "**Description**" managed property so it is not available trough the full text index. Can you check if you can get your content by querying this property explicitly?

**Comment by aaronhawryluk** [comment]
Thanks @FranckyC, I will test and see if I can retrieve it.

**Comment by aaronhawryluk** [comment]
Success! Tested react-textboxio content and it worked. Added the code listed to the react-tinymce web part file (ReactTinyMceWebPart.ts), re-deployed, and content added was put into the Description field and became searchable when the page was published (didn't even have to add anything to the index).
Works a treat! Thanks @FranckyC!
As this is undocumented (AFAIK after a search), might be useful to add it to the docs.

**Comment by FranckyC** [comment]
@aaronhawryluk Nice! You're welcome ;)

**Comment by FranckyC** [comment]
@aaronhawryluk Can you close the [techcommunity ](https://techcommunity.microsoft.com/t5/SharePoint-Developer/Getting-rich-text-from-SPFx-web-parts-into-the-search-index/m-p/171137#M4572)thread as well?
