### ISSUE TITLE
React Content Query - Fetching results recursively across folders

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-webparts#458]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
When querying a list/library with some folders in it, it would nice to be able to configure the Content Query WebPart to either return items/documents and root folders only (without returning items/documents inside folders), or return recursive results with all items/documents inside subfolders.

#### Observed Behavior
Right now, the React Content Query only returns items and folder at the first level of the a list or library. It works great when items/documents are all flat within the list/library, but when they are located within folders, the WebPart returns the folders and ignores the elements inside the folders.

#### Steps to Reproduce
Use the Content Query WebPart to query a library with the following structure :

- Document 1
- Document 2
- Folder 1
    - SubDocument 1
    - SubDocument 2

Currently, instead of returning **4** results, the WebPart will return 3 results : 

- Document 1
- Document 2
- Folder 1.

**Comment by spplante** [comment]
Fixed with pull #463 

Closing this issue.

**Comment by tonyhxh** [comment]
the recursive toggle with "<View Scope="RecursiveAll">{0}</View>" in caml xml is actually working?

**Comment by spplante** [comment]
Well yes it does it is an OOTB option for CAML queries?
