### ISSUE TITLE
Workbench on IE 11 not working

### ISSUE THREAD

**Issue by johnfabian** [SharePoint/sp-dev-fx-webparts#471]
I get the following error when trying to run spfx  on IE 11 in workbench On-Premise

@font-face failed OpenType embedding permission check. Permission must be Installable.
File: fabricmdl2icons-2.23.ttf

webpart wont' load in IE but works good in chrome

**Comment by VesaJuvonen** [comment]
Thank you for reporting this issue, but all SPFx or SP Dev issues should be reported in the [sp-dev-docs issue list](https://github.com/SharePoint/sp-dev-docs/issues) like noted in the issue template of this repository. This issue list should be only used for sample issue.

This is just to ensure that the issue you are reporting will be addressed and noted officially by our engineering. Thanks for moving this to the right location.
