### ISSUE TITLE
site column name can't be refresh

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-fx-webparts#472]
I think it is a bug http://peter.quantr.hk/2018/04/unsolved-site-column-does-not-refresh/

**Comment by VesaJuvonen** [comment]
All SPFx or SP Dev issues should be reported in the [sp-dev-docs issue list](https://github.com/SharePoint/sp-dev-docs/issues) like noted in the issue template of this repository. This issue list should be only used for sample issue. Closing this one.
