### ISSUE TITLE
where is the official repository of spfx library

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-fx-webparts#473]
where is the official repository of spfx library? I am not i should report spfx bug in here since here is the repo of sample codes
thanks
Peter

**Comment by luismanez** [comment]
Hi, this is the right repo to open an spfx issue:
https://github.com/SharePoint/sp-dev-docs/issues

**Comment by VesaJuvonen** [comment]
Like noted by Luis, all SPFx or SP Dev issues should be reported in the sp-dev-docs issue list like noted in the issue template of this repository. This issue list should be only used for sample issue. Closing this one.
