### ISSUE TITLE
Suggestion required to fetch data from another domain when building client side spfx webparts 

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-webparts#495]
Suggestions required need to fetch data from external site (from another domain).Eg like Rss feeds. 
In such scenario a client side code will not work as it will give cors error.
So in that case writing server side code is an option.
What are suggestions for creating service in sharepoint online?

**Comment by frankchen76** [comment]
As I understood correctly, the SPO doesn't allow server side code. have you thought about to create a Web API hosted on Azure or somewhere and use that Web API as a proxy to access your remote RSS feeds?

**Comment by harshdamaniahd** [comment]
Yes exactly when you fetch data fromm another domain , your client side will not work in SharePoint Framework.
When using Web Api is still would need to use cors , also host it at Azure.I guess there is no proper article for this.
Yes thought of Web API as well but another solution might be to use cors : https://cors-anywhere.herokuapp.com/
 or create your own cors at herokuapp.
https://github.com/Rob--W/cors-anywhere

**Comment by harshdamaniahd** [comment]
Yes this works great..thanks
Implemented and tested this out.

**Comment by harshdamaniahd** [comment]
Issue resolved hence closing

**Comment by pk091990** [comment]
Hi @harshdamaniahd ,
I need to implement the same custom SPFX webpart which will pull data from external RSS Feeds and as you've mentioned I'm getting the same cors header issue in Get request.
Could you please suggest what approach you've followed in your project (for production use) either using cors anywhere, already available free/paid services or create your own Web API. Please paste the article links which you've referred, if possible.

**Comment by harshdamaniahd** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient
you can fetch data by writing can azure function.
