### ISSUE TITLE
httpClient not working in SPFX

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-webparts#502]
this.context is showing undefined ?

**Comment by thechriskent** [comment]
Thanks for your question! However, this issue list is specifically for samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.

Please move your question when you are able. When you do, additional details about when you receive the error would be very helpful (SPFx version, where the error occurs, etc.). Thanks!
