### ISSUE TITLE
"react-content-query-webpart" is not running with spfx 1.4.1 version

### ISSUE THREAD

**Issue by bhanuprakash857** [SharePoint/sp-dev-fx-webparts#504]
@spplante ,

As per the Microsoft recommendation, We are trying to Create "react-content-query-webpart" in SPFx 1.4.1 version. 
 we are getting Below error , This is error is coming in lib folder files(.js) but not in ts file
![image](https://user-images.githubusercontent.com/12428545/39712437-ae427efa-5240-11e8-9d86-57aecac79a85.png)

Did anyone try to upgrade this app to 1.4.1?

Please let me know if we can upgrade this app to SPFx 1.4.1

Thanks,
Bhanu

**Comment by spplante** [comment]
@bhanuprakash857 , I did upgrade the WebPart to 1.4.1 successfully for my current client. Obviously it wasn't 100% transparent, I had to fix some API changes here and there but I can't remember if the error above was one of them. Give me a moment and I will send you an upgraded version, is that good for you?

**Comment by bhanuprakash857** [comment]
Thanks for the information @spplante . Could you please send me the upgraded one?

**Comment by spplante** [comment]
Yes, working on it.

Do you have an email I can send it to?

Thanks!

**Comment by spplante** [comment]
Just figured out that I can attch files directly in here hehe...

Here it is in 1.4.1 with the assets being included directly in the .sppkg 👍 

[content-query-webpart.zip](https://github.com/SharePoint/sp-dev-fx-webparts/files/1980744/content-query-webpart.zip)

**Comment by bhanuprakash857** [comment]
Thank you so much @spplante , You really saved my day.

**Comment by spplante** [comment]
My pleasure, have fun 👍

**Comment by sprider** [comment]
@spplante If possible merge this change. That will help others as well

**Comment by spplante** [comment]
@sprider thought about it but not sure how I would pull this off, because the main version has to stay 1.1 in order to stay compatible for SharePoint 2016. I could submit a completely new sample which runs on 4.1 but then changes would have to be sync between both projects which isn’t really convenient

**Comment by sprider** [comment]
Sure, Thank you.

**Comment by spplante** [comment]
@sprider @bhanuprakash857 , I just fixed an issue causing multiple filters to loose their sort order in IE. For you guys to get the update for the 1.4.1 version, I added a .zip at the root of the project which has the latest version upgraded to 1.4.1, you can download the .zip in the pull request #517 which I just submitted.

I will try to keep this .zip updated from now on every time I do some changes to the project. Thanks!

**Comment by prathimapilli** [comment]
> My pleasure, have fun 

Hi @spplante 

I downloaded your code when I try to build the code  im getting below error..

Assertion `args[1]->IsString()' failed

Im new to spfx, kindly suggest what im missing

**Comment by spplante** [comment]
Which one did you download, the one in this conversation or the one included in the repo? The 1.1 version or the 1.4.1?

I can build both of them maje sure your npm/node is up to date
