### ISSUE TITLE
CRUD sample fails on npm install

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-fx-webparts#51]
#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement
#### Expected or Desired Behavior

Doing npm install for the sharepoint-crud sample should work properly after execution
#### Observed Behavior

Getting exceptions on execution

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
#### Steps to Reproduce

Run npm install on the sharepoint-crud sample. Tested with Windows 10.

**Comment by VesaJuvonen** [comment]
Actual error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "<C:<\\Program Files\\nodejs\\node.exe>>" "<C:<\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js>>" "i" npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by waldekmastykarz** [comment]
The error states that node v6 is being used. According to the current specs only node v4 is being supported by SPFx. Could you check if you get the same error on node.js v4?

**Comment by jtlivio** [comment]
I had some similar problems in Linux node 6.0.0

npm rebuild node-sass
npm install typings -g

HTH

**Comment by chakkaradeep** [comment]
@waldekmastykarz Interesting. My todo-basic sample which is targeting Drop 5 does not give any errors. Are you checking for v4 anywhere?

**Comment by waldekmastykarz** [comment]
No, I am not, but the error that you're getting is also not specific to the sample code but rather something coming from the dependencies.

Btw. the CRUD sample is still based on drop 4 so when comparing it to a brand new project you should use the Yeoman generator from drop 4 rather than 5 to create a comparable project.

**Comment by Hamilcore** [comment]
I'am getting the same issue : 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\masassi\\AppDat
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! **node v4.7.0**
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin"
"arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by Hamilcore** [comment]
Downgrading to **npm 3.10.7** solves the issue for me.

**Comment by jinnia** [comment]
I am getting the issue
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "lodash._baseindexof" "--save"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall getaddrinfo

npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     F:\reference\jimbo\project\node-notes\npm-debug.log

anybody please help me

**Comment by ranjiit12** [comment]
I have the sort of the same issue. I have 3.10.10 version of npm. 
![capture](https://user-images.githubusercontent.com/18627521/29225574-4698b886-7ee8-11e7-82b5-157887707a34.PNG)

**Comment by waldekmastykarz** [comment]
@jinnia are you still having the issue? Seems like something related to npm being unable to connect to the NPM registry.

**Comment by VesaJuvonen** [comment]
Closing this one due no response.

**Comment by Kapsss** [comment]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\no
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, statusCode=503
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

Please Help Me!

**Comment by VesaJuvonen** [comment]
@Kapsss - this seems to be a configuration issue on your machine. Most likely there is a proxy used in your company, which is required to be used by all computers connecting to the Internet. Would confirm that and then check the guidance available from the Internet on the npm with proxy setting. This is really nothing specific on SharePoint Framework.
