### ISSUE TITLE
developer tenant  Public CDN issue 

### ISSUE THREAD

**Issue by krmoanh** [SharePoint/sp-dev-fx-webparts#519]
Hi, I have problem with CDN in my developer tenant. I made webpart and I already enable the cdn public and I check everything its look fine. but when I save the sppkg to sharepoint site appcatalog and then in the team site I try to use the webpart its give me error about loading from public cdn. and the when I try same way but different tenant I mean not my own developer tenant and it work fine, no any issue. I really don't know why its just only in my developer tenant. this issue also recently happen with some developers . my problem same this https://github.com/SharePoint/sp-dev-docs/issues/1353

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue and NOT related on any sample in this repository, moving to the sp-dev-docs issue list at http://aka.ms/spdev-issues.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2014
