### ISSUE TITLE
Cannot find module "contentQueryStrings" when adding react-content-query-webpart to page

### ISSUE THREAD

**Issue by Loevbo** [SharePoint/sp-dev-fx-webparts#520]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

When I run this [example](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-content-query-webpart). I run into a problem where i have to change `import { IWebPartContext } from '@microsoft/sp-webpart-base';` to `import { WebPartContext } from '@microsoft/sp-webpart-base';`

Now there is no errors in the code and when i run `gulp serve` it loads and open the workbench.

## Observed Behavior

When I add the webpart to the page I get this error message 

>[SPLoaderError.loadComponentError]:
***Failed to load component "3bbca76a-5369-4a92-af23-d4bfd1c4e3b4" (ContentQueryWebPart).
Original error: ***Failed to load entry point from component "3bbca76a-5369-4a92-af23-d4bfd1c4e3b4" (ContentQueryWebPart).
Original error: Error loading https://component-id.invalid/3bbca76a-5369-4a92-af23-d4bfd1c4e3b4_0.0.1
	Cannot find module "contentQueryStrings"

>***INNERERROR:
>***Failed to load entry point from component "3bbca76a-5369-4a92-af23-d4bfd1c4e3b4" (ContentQueryWebPart).
>Original error: Error loading https://component-id.invalid/3bbca76a-5369-4a92-af23-d4bfd1c4e3b4_0.0.1
	Cannot find module "contentQueryStrings"
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24)
    at new SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:21)
    at https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:38

Im not sure what the problem is but now after 2 days of trying to fix this im lost, This is the first time I'm posting an issue here, so sorry if I did it wrong.

**Comment by spplante** [comment]
@Leovbo any update on this?

**Comment by spplante** [comment]
@Loevbo any update on this?

**Comment by Loevbo** [comment]
@spplante Hello I get the same bug when I run this on both local Workbench and when I compile it into an app and use it on my live sharepoint site.

**Comment by spplante** [comment]
@Loevbo Hmmm that is strange, can you try doing the same thing using the "dev" version? I just submitted some changes in the current DEV branche, maybe it is fixed in this version for some reason.

Also, are you using this webpart in SPO or SharePoint 2016?

**Comment by Loevbo** [comment]
I'm trying to use it on SPO, Where can I find the the Dev branch? sorry I'm kinda new to the use of git

**Comment by spplante** [comment]
At the root of the repository, there is a **branch** button where you can switch between master and dev, if you cloned the repository using Visual Studio you also have the option to switch branch within visual studio.

Anyway here is the link for the dev version of this repository :

https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev

If you are using SPO, I made available (in the dev branch for now) a zip file at the root of the project called **content-query-webpart-1.4.1.zip**, this is the WebPart using SPFx version 1.4.1 which is a more recent version of SPFx which allows the WebPart to run without hosting the binaries to a CDN. With this version the binaries are now included directly within the .sppkg which is much more simple, so if you are using SPO and aren't looking for SP2016 compatibility, I would recommand you to use the 1.4.1 version of the .zip file.

**Comment by Loevbo** [comment]
I've opened the dev version of content query webpart and it returns the following erros when I run gulp serve to test it in local.

 src\controls\PropertyPaneTextDialog\components\TextDialog\TextDialog.tsx(6,30): error TS2307: Cannot find module 'react-ace'.
[14:12:01] Error - typescript - src\webparts\contentQuery\components\ContentQuery.tsx(77,72): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.
src\common\services\ContentQueryService.ts(312,112): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.

**Comment by Loevbo** [comment]
I think I've gone blind, Can't find content-query-webpart-1.4.1.zip anywhere :(

**Comment by spplante** [comment]
@Loevbo what are the exact steps you are taking from scratch? You need to perform these exact steps in order to use any SPFx WebPart : 

- npm install (to install all the dependencies)
- gulp bundle (without the --ship flag)
- gulp package-solution (without the --ship flag)
- Upload the generated .sppkg to app catalog
- Install app to a site collection
- gulp serve --nobrowser
- Add app to a page

The zip is at the root of the project in the dev branch :

https://github.com/SharePoint/sp-dev-fx-webparts/blob/dev/samples/react-content-query-webpart

**Comment by spplante** [comment]
@Loevbo, did you manage to make it work iwth the 1.4.1 version?

**Comment by stact** [comment]
Hi @spplante I'm trying to add this wp on a SharePoint 2019
When I compile with
gulp clean
gulp bundle --ship
gulp package-solution --ship

Not working on the environment cause the module try to use the cdn.
I tried to add on package-solution.json "includeClientSideAssets": true not working cause the project is using 1.1.0.
Then I try the solution 1.4.1 (that allow "includeClientSideAssets": true), got errors

```
Error - typescript - src/common/services/ContentQueryService.ts(56,99): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.
Error - typescript - src/common/services/ContentQueryService.ts(73,142): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.
Error - typescript - src/common/services/ContentQueryService.ts(78,16): error TS2322: Type '{ pageContext: PageContext; items: undefined[]; accessDenied: false; webNotFound: false; callTime...' is not assignable to type 'IContentQueryTemplateContext'.
Error - typescript - src/common/services/ContentQueryService.ts(78,16): error TS2322: Type '{ pageContext: PageContext; items: undefined[]; accessDenied: false; webNotFound: false; callTime...' is not assignable to type 'IContentQueryTemplateContext'.
Error - typescript - src/common/services/ContentQueryService.ts(88,101): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.
Error - typescript - src/common/services/ContentQueryService.ts(131,117): error TS2339: Property 'serviceScope' does not exist on type 'IWebPartContext'.

[...]
```
What are the steps to use this module on SharePoint OnPremises? 
Do you plan to upgrade the solution, that could allow to use this component on premise?

Thanks for your help!

**Comment by spplante** [comment]
@stact what do you mean when you say you tried 1.4.1, you tried updating the packages by yourself to 1.4.1?

**Comment by stact** [comment]
@spplante yes for on the project samples/react-content-query-webpart I've followed those instructions:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages

**Comment by spplante** [comment]
Ok well you don't need to, I did include a version of the project converted to 1.4.1, it is in a zip file at the root of the project called **content-query-webpart-1.4.1.zip**.

Simply unzip that file in another location and try gulping that version of the project instead 👍

**Comment by stact** [comment]
thx @spplante it's working fine :)

**Comment by poojakadam19** [comment]
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot find module 'ReactNewsWebpartStrings'

CALL STACK:
Error: Cannot find module 'ReactNewsWebpartStrings'
    at webpackMissingModule (https://localhost:4321/dist/react-news-webpart-web-part.js:22286:45)
    at Module.GlSv (https://localhost:4321/dist/react-news-webpart-web-part.js:22286:143)
    at __webpack_require__ (https://localhost:4321/dist/react-news-webpart-web-part.js:20:30)
    at https://localhost:4321/dist/react-news-webpart-web-part.js:84:18
    at https://localhost:4321/dist/react-news-webpart-web-part.js:87:10
    at Object.execCb (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_739a8b65a2b9798eb2b3e29fda93101a.js:1:1), <anonymous>:30:41)
    at Z.check (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_739a8b65a2b9798eb2b3e29fda93101a.js:1:1), <anonymous>:18:439)
    at Z.enable (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_739a8b65a2b9798eb2b3e29fda93101a.js:1:1), <anonymous>:23:439)
    at Z.init (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_739a8b65a2b9798eb2b3e29fda93101a.js:1:1), <anonymous>:17:108)
    at E (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_739a8b65a2b9798eb2b3e29fda93101a.js:1:1), <anonymous>:14:221)
