### ISSUE TITLE
Store and/or licensing mechanism for SPFx WebParts?

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-webparts#527]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Question

Is there any kind of road-map in regards to a licensing mechanism for validating licenses of custom SPFx WebParts kinda like the old app/add-in model? Is there any plans for a "store" where consumers could download/buy custom SPFx WebParts just like the current add-in store?

Creating custom WebParts and solutions for free is great, but as a developer, it would be really interesting to be able to get rewarded for our time/efforts, and SPFx being 100% client side, I just don't see an effective way to have a secure licensing mechanism unless there is some built-in server side logic involved.

I could for example have my own azure function HTTP endpoint responsible for validating the license of the caller, and then I could make sure my WebPart calls the said endpoint before rendering anything, but this could easily be bypassed by commenting the client side code responsible for calling the azure endpoint...I don't see how we could securely do this without having some backend built-in into SharePoint.

Anything planned for this? Maybe @VesaJuvonen has some insider info about this? 👍  

Thanks!

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue and NOT related on any sample in this repository, moving to the sp-dev-docs issue list at http://aka.ms/spdev-issues.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2013
