### ISSUE TITLE
Overwrite Loading  Indicator Text 

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-webparts#528]
Is there way through which we can overwrite loading indicator text in SPFX webparts
which by default is#  **"Loading WebpartName"**

**Comment by JayakumarB** [comment]
Yes, SPFx provides option for that as well you can use **statusRenderer**  option available in context provided by SPFx.

Please refer this [blog](https://thechriskent.com/2017/05/22/taking-advantage-of-the-loading-indicator-in-the-sharepoint-framework/) for more info.

**Comment by VesaJuvonen** [comment]
Closing as answered by @JayakumarB.
