### ISSUE TITLE
{{MyField.htmlValue}} Output HTML as Text

### ISSUE THREAD

**Issue by joker-it** [SharePoint/sp-dev-fx-webparts#531]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior
{{MyField.htmlValue}} Output HTML Code as HTML 

## Observed Behavior
{{MyField.htmlValue}} Output HTML Code as Text

![html](https://user-images.githubusercontent.com/35039321/41281920-f34ac4d6-6e32-11e8-999c-e310d7f0f078.png)

if i use {{MyField.textValue}} 

![text](https://user-images.githubusercontent.com/35039321/41281980-16bcc540-6e33-11e8-89eb-e2910f100900.png)

thanks for support and best regards 
Ivo

**Comment by brunokrieger** [comment]
Hi Ivo ;),
Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{.

Try to use {{{MyField.htmlValue}}}

Viel Glück :)
Bruno
