### ISSUE TITLE
react-documents-detailslist Not working in On-premise Sharepoint 2016

### ISSUE THREAD

**Issue by aravindmunna** [SharePoint/sp-dev-fx-webparts#533]
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Expected or Desired Behavior

> _If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Observed Behavior

> _If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Steps to Reproduce

> _If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
That's currently by design and this sample is using SharePoint Framework v1.3 and only supported SharePoint Framework version in the on-premises is v1.1. This is due to server-side dependencies on the provided capabilities.
