### ISSUE TITLE
SPFx webpart is not working if the classic page contains OOTB webpart

### ISSUE THREAD

**Issue by bhanuprakash857** [SharePoint/sp-dev-fx-webparts#534]
I have ~1.1.0 SPFx framework webpart with Angular1.x framework.
  
This webpart is working fine if the page does not contain the OOTB Webaprt. The moment i added the OOTB webpart, it stops working. Below is the Error

![image](https://user-images.githubusercontent.com/12428545/41395885-df69ebea-6fcc-11e8-8171-fae76b973019.png)

> Note: I have obsereved this behavior only in chrome

**Comment by VesaJuvonen** [comment]
As this is NOT around any samples in the this repository, moving this discussion to the sp-dev-docs repository like noted in the issue template.

"Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at https://github.com/SharePoint/sp-dev-docs/issues/new. This will help us respond to your issue faster."

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2048
