### ISSUE TITLE
react-search-refiners web part title

### ISSUE THREAD

**Issue by MichalExpP** [SharePoint/sp-dev-fx-webparts#557]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@FranckyC @VesaJuvonen 

## Expected or Desired Behavior

Will you be able to add WebPartTitle to searchBox and searchResults web parts?

## Observed Behavior

It's not possible to add a web part title without having to add the PnP WebPartTitle to a web part component manually. I usually add that by myself, but with recent (and amazing) handlebars addition and code refactoring I thought this could be added globally

## Steps to Reproduce

No steps

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @MichalExpP. Good suggestion, I didn't test with this Web Part. I'll see how it is complicated. Otherwise, you will have to use a separate WP as for now.

**Comment by MichalExpP** [comment]
I've added web part title without any problems to both web part following this https://sharepoint.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/ works great.
This guide omits one step, you need to add title:string to ISearchResultsWebPartProps.ts and ISearchBoxWebPartProps.ts

1) SearchResultsWebPart.ts

        const searchContainer: React.ReactElement<ISearchContainerProps> = React.createElement(
            SearchContainer,
            {
                /*Added By Michal*/
                title: this.properties.title,
                sortSearchResultsBy: this.properties.sortSearchResultsBy,
                updateProperty: (value: string) => {
                    this.properties.title = value;
                },
                /*Added By Michal end*/
2) ISearchBoxWebPartProps.ts & ISearchResultsWebPartProps.ts

title:string;

3) SearchResultsContainer.tsx & SearchBoxContainer.tsx

import { WebPartTitle } from "@pnp/spfx-controls-react/lib/WebPartTitle";

And then in SearchBoxContainer.tsx

      <div className="searchBox">
        <WebPartTitle displayMode={this.props.displayMode} title={this.props.title} updateProperty={this.props.updateProperty} />
        { renderErrorMessage }

Also in SearchResultsContainer.tsx

                        renderWpContent =
                            <div>
                                <WebPartTitle displayMode={this.props.displayMode} title={this.props.title} updateProperty={this.props.updateProperty} />
                                <FilterPanel availableFilters={this.state.availableFilters} onUpdateFilters={this._onUpdateFilters} refinersConfiguration={ this.props.refiners } /> 
                                <div className='searchWp__noresult'>{strings.NoResultMessage}</div>                                                  
                            </div>;
                    } else {
                        if (this.props.displayMode === DisplayMode.Edit) {
                            renderWpContent = <MessageBar messageBarType={ MessageBarType.info }>{ strings.ShowBlankEditInfoMessage }</MessageBar>;
                        }
                    }
                } else {
                    renderWpContent =
                        <div>
                            <WebPartTitle displayMode={this.props.displayMode} title={this.props.title} updateProperty={this.props.updateProperty} />
                            <FilterPanel availableFilters={this.state.availableFilters} onUpdateFilters={this._onUpdateFilters} refinersConfiguration={ this.props.refiners }/>
                            { renderOverlay }

4) Sorry for this, I'm a complete amateur atm working with SPFx for a week and I still don't know how to use Github and suggest code changes

**Comment by FranckyC** [comment]
Thanks @MichalExpP. To contribute, you can fork the sp-dev-fx-webparts repository, make your change and send a PR to the original repo.

Anyway, I will try to integrate your change as soon as possible!

**Comment by MichalExpP** [comment]
This has been added to the most recent release.
