### ISSUE TITLE
react-search-refiners Result Source Identifier not working

### ISSUE THREAD

**Issue by MichalExpP** [SharePoint/sp-dev-fx-webparts#559]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@FranckyC @VesaJuvonen 

## Expected or Desired Behavior

Adding id e.g. "4cd912b0-f9a3-47d5-89ac-12514bc6660f" in the "Search Results with Refiner" web part under "Result Source Identifier" should bring result source search results. As fix enhancement, could that also connect to the Search Box, if using {SearchBoxQuery} on the result source?

## Observed Behavior

Adding id e.g. "4cd912b0-f9a3-47d5-89ac-12514bc6660f" in the "Search Results with Refiner" web part under "Result Source Identifier" doesn't bring any results

## Steps to Reproduce

1) Create a Result Source and copy it's GUID. The result source can be with a query ContentType:Document
2) Add "Search Results with Refiner" web part and in web part properties under under "Result Source Identifier" paste the GUID
3) Publish the page and refresh

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
@MichalExpP . Hmm, I'm not able to reproduce this issue. Try to specify a query keyword in the property pane even if you don't actually use one in the result source.

**Comment by MichalExpP** [comment]
I've managed to get that working, but you need to add the GUID in both "Result Source ID" and "Search query keywords" fields. I'm not connecting Search Results to the Search Box in this example. If you connect Search Results to the Search Box, you don;t have to add the GUID in the "Search query keywords"
