### ISSUE TITLE
react-search-refiners skipFeatureDeployment -> true

### ISSUE THREAD

**Issue by MichalExpP** [SharePoint/sp-dev-fx-webparts#560]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@FranckyC @VesaJuvonen 

## Expected or Desired Behavior

I'd like to be able to deploy this app to the whole site collection, so there is no need to add the app to sites. I'm using Site Collection App catalog.

## Observed Behavior

It's not possible to add the app to the whole site collection.
I did set the "skipFeatureDeployment": true and deployed the app, but this seem to brake the feature "URL Query String Parameter" on both "Search Box" and "Search Results with Refiners" web part. I've logged few other tickets, but those issues were found on an unmodified solution

## Steps to Reproduce

No steps to reproduce, it's an enhancement

**Comment by FranckyC** [comment]
Hi @MichalExpP . What do you mean by "brake the feature "URL Query String Parameter" on both "Search Box" and "Search Results with Refiners" web part". Not sure to understrand.

**Comment by MichalExpP** [comment]
Sorry, my fault in not explaining well. I've changed "skipFeatureDeployment": true and uploaded the solution, there were no other modifications done. When I go to the site and add either web parts, (I'll do "Search Box" for this example) then open web part properties and try to select "Use a dynamic data source as search query" and then select a source, it's not possible to do that, the drop down is not showing anything. The same with "Search Results with Refiner", there is no option to use URL query string

**Comment by FranckyC** [comment]
@MichalExpP it is the expected behavior since the extension is deployed using...a feature:

"skipFeatureDeployment": false,
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "b28f9c2b-6e10-4764-8585-5f8e6533001b",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml"
          ]
        }
      }

**Comment by MichalExpP** [comment]
Sorry, forgot features are not deployed with that skipFeatureDeployment flag set to true.

**Comment by MichalExpP** [comment]
@FranckyC Do you think the skipFeatureDeployment can be set now to "true", since you are not deploying any assets anymore? Previously, not deploying those assets affected query string parameter functionality, but this has been now significantly updated. I'm wondering, if there are any constraints in making this change.

**Comment by FranckyC** [comment]
Hi @MichalExpP, since the extension is not used anymore (replaced by the hashtag '#'), you should be able to use the `skipFeatureDeployment` flag now
