### ISSUE TITLE
Uploading SPFx solution in a Site Collection App Catalog results in "Invalid App ID

### ISSUE THREAD

**Issue by a2life** [SharePoint/sp-dev-fx-webparts#568]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Observed Behavior

Clicking on 'App detail' shows 'AppStore,  invalid ID ....'  the ID shown is not an ID of the solution.
![sitecollectionapp](https://user-images.githubusercontent.com/2119984/42709032-18bed67a-86ad-11e8-8d3d-81ff99e87b9e.PNG)

The solution will still install If I just double click on the App Icon.   but there will be no upgrade path with the lack of detail page.  Happening in both development tenant and in production tenant.
## Steps to Reproduce

Create a 'Hello world' solution package and upload to Site Collection level app catalog.  go to any sub site under the site collection and go to Site contents ->Add an App.   Find your solution and click on 'App detail'.

 **The same solution package, when uploaded to tenant level App catalog,  will correctly show app detail with 'Add it' button**
![capturetenant](https://user-images.githubusercontent.com/2119984/42709303-139f2f2c-86ae-11e8-9431-c4ffc172f61c.PNG)

.

**Comment by llowevad** [comment]
@a2life, why was this closed?

I am seeing this issue with any app I add to the site collection app catalog, was there something you did to resolve this?

**Comment by millercanfield** [comment]
I am also seeing this issue when I add to a site collection app catalog.

**Comment by a2life** [comment]
I closed this because I was not sure if this is the right place to submit the issue report.  Yes the issue is still there.

**Comment by govinddk4444** [comment]
Facing the same issue even now. Any solution?

![image](https://user-images.githubusercontent.com/27952352/61043956-31d70180-a3f5-11e9-993c-23f27d2bf82e.png)

**Comment by a2life** [comment]
I will keep it open as the issue is still there although I am not sure if this is the right forum to log this issue.  This problem  effectively blocks Site collection level app to get updated because  "new version is available,  get it' action is in this detail view and therefore there is no way to update the web part that is installed through Site collection level catalog.

**Comment by a2life** [comment]
I ended up commenting this in [Docs.Microsoft](https://github.com/SharePoint/sp-dev-docs/issues/4657).
My assessment at this time is that the SPfX solutions uploaded to the Site Collection level appCatalog  appear to be missing "detail" information properly provisioned. I can still install those apps.   The annoyance is that one can not see "New version is available.  GET IT" button in the event of upgrading the app because it is a part of the detail page.   However, [ALM API ](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins) still works, so it was a matter of  writing a utility app to invoke the API for a selected app.   with this knowledge, I am closing this issue.
