### ISSUE TITLE
react-search-refiners - I can't seem to use the "q" Dynamic datasource

### ISSUE THREAD

**Issue by Aracnakid** [SharePoint/sp-dev-fx-webparts#581]
Great webpart by the way! As above I can't use the 'q' URL query string in  my environment as the option does not populate in the dropdown.

Steps to reproduce:

Add result webpart to page and edit datasource - No options are shown in the absence of a search box.

On another note:
I have a great set of handlebar templates now if anyone is interested -  they incorporate the default modern search styles to provide previews in a popup dialog.

**Comment by FranckyC** [comment]
Hi @Aracnakid. The data source for the 'q' parameter is provisioned using an SPFx extension. Did you deploy it with the Web Parts as well? Make sure it is included in the config.json and package-solution.json. Also make sure the "skipFeatureDeployment" is false.

For the handlebar templates, sure! A PR would be very appreciated! I suggest you to create a 'templates' folder [here ](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-search-refiners/src)+ a README file explaining briefly what your template do and if there are any prerequisites to use it.

Thanks again!

**Comment by FranckyC** [comment]
Hi @Aracnakid, any updates on this? 

Thanks!

**Comment by Aracnakid** [comment]
Thank you for your help - I was having a blonde moment and was trying to run it in the wrong Tenant,
I have held off uploading the templates as I am currently trying to work them into the code - I will fork and send a PR when I have completed it.

Here is a screenshot of the preview in action:

![screenshot01](https://user-images.githubusercontent.com/39385449/43680206-d733f9fe-9888-11e8-8468-20eefc87adc7.png)

And also another Idea I have been playing with: 

![screenshot02](https://user-images.githubusercontent.com/39385449/43680210-de719622-9888-11e8-9e15-feba3f954ea4.png)

The idea is to be able to add predefined KQL queries and titles to allow tabbed navigation like the old search pages - Items should be able to be added to both the Search Box and Results webpart - Clicking a tab will setState of the KQL Query string.

Thanks again for your help!

**Comment by FranckyC** [comment]
Nice @Aracnakid, do not hesitate to make a PR with your templates. It seems very promising.
