### ISSUE TITLE
How to get App Catalog Site URL from a SPFx Web Part

### ISSUE THREAD

**Issue by matthong** [SharePoint/sp-dev-fx-webparts#584]
From a SPFx Web Part, is there a way to get the tenant's app catalog site URL programmatically? 

## Category

- [x] Question
- [ ] Bug
- [] Enhancement

## Expected or Desired Behavior
Need a way to find the App Catalog site of the tenant programmatically from a Web Part.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2355

**Comment by VesaJuvonen** [comment]
As this is a generic question, moving it to the right repository.
