### ISSUE TITLE
react-search-refiners property pane layout

### ISSUE THREAD

**Issue by kchiragowni** [SharePoint/sp-dev-fx-webparts#590]
## Category

- [x ] Question
- [ ] Bug
- [] Enhancement

## Authors
@wobba  - react-search-refiners

## Expected or Desired Behavior

I have downloaded the latest code (react-search-refiners) and ran it locally/remotely. Webpart property pane should looks same as compared to screenshot (Page view) in README file.

## Observed Behavior

The property pane settings are in one big pane and not split into multiple pages.

## Steps to Reproduce

Clone/download 'react-search-refiners' webpart/extensions and run it locally/remotely.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
@kchiragowni Care to do a PR with a new screenshot? :)

**Comment by kchiragowni** [comment]
@wobba thank your for swift response.

Please see attached screenshot and let me know if you need any further information.

![react-search-refiners-property-pane](https://user-images.githubusercontent.com/10240615/43900345-7aca7880-9bdc-11e8-94cc-fb5d436e1e90.png)

**Comment by wobba** [comment]
@kchiragowni  I was thinking you could do the actual work :) But I updated the images just now.

**Comment by kchiragowni** [comment]
@wobba thanks again for updating the screenshot. 

Actually previous property pane was better organised so will update the property pane issue a PR shortly.

**Comment by wobba** [comment]
I disagree and wanted to align with oob part. Then again, the changes weren't meant to be merged right now anyways, but not harm done. Was a slip up.
