### ISSUE TITLE
can we check if the same package loaded twice on the page?

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/sp-dev-fx-webparts#593]
we are using private module (equivalent to dll) for logging the issue in SPFx to list. i am not sure if the private module is been downloaded multiple time or one time on the modern page.

we are using the same private module in different web part on the page. Please let me know how does module load at run time.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2354

**Comment by VesaJuvonen** [comment]
As this is a generic question, rather than specific to any sample in this repository, moving it to the right location.

**Comment by veeramanx** [comment]
any answers for this question please?
