### ISSUE TITLE
React 16.0.0 and greater

### ISSUE THREAD

**Issue by michalejoye** [SharePoint/sp-dev-fx-webparts#614]
## Category

- [ x] Question
- [ ] Bug
- [] Enhancement

We wanted to know if the SPFx works with React and React-Dom version 16+? We are trying to use kendo react controls but they need the react version to be 16+

**Comment by VesaJuvonen** [comment]
As this is a generic issue not related on the samples, it should be asked in the sp-dev-docs repository where we have more people helping on the incoming questions / other issues. React 16 support is planned with SPFx 1.7 - ETA in end of Oct, as mentioned in the SPFx community calls. Not supported yet.
