### ISSUE TITLE
react-aggregated-calendar

### ISSUE THREAD

**Issue by americo2015** [SharePoint/sp-dev-fx-webparts#616]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

Dhaval Shah

## Question
How can I add localization to the buttons that shows in the calendar? I have added localization to the settings panel and to the "Manage Calendar" popup by using localization files but I can't find the way to change the language in the view buttons of the calender, now is showing "month" - "week" - "day". The same for the month's name, now is in english. In the fullcalendar docs says that we can use locale: "es" to use spanish but I tested it in the containerEl and it seems don't work. How can I change these element's language?

**Comment by americo2015** [comment]
I found the solution in the FullCalendar documentation by using the localize js file

**Comment by hanaRose** [comment]
Hi @americo2015 I'm encountering the same issue and am not managing to add the localize js file, can you please give me more details on how to go about this?
Thank you!!
