### ISSUE TITLE
Debug tests in React

### ISSUE THREAD

**Issue by liricy** [SharePoint/sp-dev-fx-webparts#629]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

How do I debug tests? I tried putting breakpoints and they never hit. Please let me know if there is a way.

**Comment by VelinGeorgiev** [comment]
What testing framework are you using?

**Comment by licypal** [comment]
enzyme

**Comment by VelinGeorgiev** [comment]
Enzyme, mocha, sinon? or Jest, enzyme, sinon?

**Comment by licypal** [comment]
Jest, enzyme, sinon

**Comment by VelinGeorgiev** [comment]
You can visit my blog. There is a short 15 min video recorded by the PnP community on it. I hope that can give you more information: [https://blog.velingeorgiev.com/unit-test-your-sharepoint-framework-solution-with-jest](https://blog.velingeorgiev.com/unit-test-your-sharepoint-framework-solution-with-jest)

**Comment by licypal** [comment]
Yes, I am using that sample. Thanks!

**Comment by licypal** [comment]
@VelinGeorgiev Could you please share some links on writing tests using Jest, enzyme, sinon framework?

**Comment by VelinGeorgiev** [comment]
- The best resource on Jest for me would be the Jest API documentation -[Jest API](https://jestjs.io/docs/en/api)
- Good resource for Enzyme is
- [Enzyme API](https://airbnb.io/enzyme/docs/api/)
- Good resource for Sinonjs is
- [Sinonjs API](https://sinonjs.org/)

Blogs that use both:
- @estruyf  blogs on how to [test SPFx using Enzyme and Mocha](https://www.eliostruyf.com/writing-unit-test-for-your-sharepoint-framework-components/)
- @estruyf  blogs on how to [test SPFx using Enzyme and Jest](https://www.eliostruyf.com/sharepoint-framework-unit-tests-with-jest/)
- @VelinGeorgiev -  how to [test SPFx using Enzyme and Jest](https://blog.velingeorgiev.com/unit-test-your-sharepoint-framework-solution-with-jest)

Projects with unit tests:
- The [sp-dev-fx-controls-react](https://github.com/SharePoint/sp-dev-fx-controls-react) **- Enzyme and Sinon**
- The [sp-dev-fx-property-controls](https://github.com/SharePoint/sp-dev-fx-property-controls) - Sinon
- The [Office 365 CLI ](https://github.com/pnp/office365-cli/)that has over 5K Tests atm for Sinon

Samples with tests:
-  https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-jest-testing
-  https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-rxjs-event-emitter
- https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-yammer-api
- https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-events-aggregator
- https://github.com/estruyf/spfx-testing-wp

In general, there aren't any jump start tutorials, you will have to dig into samples and learn how the rest did it. I can try help you and answer as much as I can. My plan is to create GitHub readme document with basics, but it is at the bottom of my todo list :(

**Comment by liricy** [comment]
@VelinGeorgiev Thank you so much!

**Comment by liricy** [comment]
@VelinGeorgiev Do you have any samples on writing tests for redux-reducers?

For example, I have a reducer file as follows:

```
import { IAction, ActionTypes } from "../actions/ActionTypes";
import { SessionState } from "./SessionState";
import { Reducer } from "redux";

const initState = new SessionState();

/** Reducer determines how the state should change after every action. */
const session: Reducer<SessionState> = ( state: SessionState = initState,
                                         action: IAction): SessionState => {
  switch (action.type) {    
    case ActionTypes.GET_USER_STATUS_SUCCESS:
      return  .setIsSubmitter(action.payload);
    default:
      return state;
  }
};

export default session;
```

And the reducer state is:

import * as Immutable from "immutable";
import { escape } from "@microsoft/sp-lodash-subset";
import * as strings from "publishAppsStrings";

export interface ISessionState {
  isSubmitter: boolean;
}

const initialSessionState: ISessionState = {
  isSubmitter: false
};

/** Immutable State. */
export class SessionState extends Immutable.Record(initialSessionState) implements ISessionState {

  /** Getters */
  public readonly isSubmitter: boolean;

  /** Setters */ 
  public setIsSubmitter(response: string[] | undefined): SessionState {
    const isSubmitter = (response && (response.indexOf("AppSubmitter") > -1))? true: false;
    return this.set("isSubmitter", isSubmitter) as SessionState;
  }
}

How do I write test to check the return value of isSubmitter? Please let me know!
