### ISSUE TITLE
Tests for react components

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-fx-webparts#632]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

How do we write tests for react components like componentWillMount, componentWillUpdate?

**Comment by VelinGeorgiev** [comment]
You can use Sinonjs or other spy library and spy on those events. See how @estruyf  did it in his sample here: [https://github.com/estruyf/spfx-testing-wp/blob/master/src/webparts/helloWorld/tests/HelloWorld.test.tsx](https://github.com/estruyf/spfx-testing-wp/blob/master/src/webparts/helloWorld/tests/HelloWorld.test.tsx)

On Jest before each, you have to create a spy for the lifecycle event that you will be spying e.g.
```
beforeEach(() => {
        componentDidMountSpy = sinon.spy(HelloWorld.prototype, 'componentDidMount');
        renderedElement = mount(<HelloWorld description={descTxt} />);
    });
```

Then in your test you can check [if the event has triggered](https://github.com/estruyf/spfx-testing-wp/blob/ae1f806be891bfea94968578444561f51a75a3df/src/webparts/helloWorld/tests/HelloWorld.test.tsx#L49)

```
it('<HelloWorld /> should call componentDidMount only once', () => {
        // Check if the componentDidMount is called once
        expect(componentDidMountSpy.calledOnce).to.equal(true);
    });
```

Heavy usage of spies can be found in the [Office 365 CLI tool tests](https://github.com/pnp/office365-cli).

With the spies you can also monitor whether the function is being called with the right input params. Here is an [example from the Office 365 CLI tool](https://github.com/pnp/office365-cli/blob/3d67084243834b19a7db157a7767d167005c96dc/src/o365/spo/commands/customaction/customaction-get.spec.ts#L163)

Note the Sinonjs **stub** is also a **spy**, but it is used for mocking objects as well as spying on objects.

**Comment by samyaktelsang** [comment]
I've tried using the sinon library similar to @estruyf  's example.
My code looks as below:
```
let sinon = require('sinon');

it("Components are loaded", () => {
            const descTxt = "TestingThisOneOut";
            let componentDidMountSpy;
            let renderedElement;

            componentDidMountSpy = sinon.spy(ListSubmissionsComponent.prototype, 'componentWillUpdate');
            
           renderedElement = mount(<ListSubmissionsComponent description={descTxt}/>);;
           expect(componentDidMountSpy.calledOnce).toEqual(true);
           componentDidMountSpy.restore();
        });
```
The test fails as the received value is 'false'. @VelinGeorgiev  @liricy Could you let me know what might be the issue. Also, how would I explicitly call the componentWillUpdate lifecycle in order to test the same.

I have imported the latest version of sinon and my imports look like this:
```
import * as React from "react";
import * as sinon from 'sinon';
import { configure, mount, ReactWrapper } from "enzyme";
import * as Adapter from "enzyme-adapter-react-15";
```
