### ISSUE TITLE
Filter multi-selection choice columns using their component choices (react-search-refiners)

### ISSUE THREAD

**Issue by mgordin** [SharePoint/sp-dev-fx-webparts#646]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@wobba 
@FranckyC 

## Expected or Desired Behavior

Currently, when a choice column that supports multiple selected values is used as a filter, the filter options for items that have multiple values selected are presented as the each unique combination of selected values - e.g., all of "Choice A;#", "Choice B;#", and "Choice A;#Choice B".  It would be helpful if instead, filtering matched the SharePoint library behavior for multi-valued columns.  In this case, filter options would be just all individual choices (e.g., "Choice A", "Choice B"), and items with multiple values would be shown when filtering by any of their component values.  Although this would mean that you couldn't just filter to a combination of items, I think the usability would be much better - it's more intuitive and less likely to have someone miss the filter they want (because a value was listed second in a multi-valued entry).

**Comment by wobba** [comment]
A good suggestion indeed, and should be possible to work out.

**Comment by wobba** [comment]
Please re-add this to https://github.com/SharePoint/sp-dev-solutions repo.
