### ISSUE TITLE
On subsequent searches, filters appear selected but are not applied (react-search-refiners)

### ISSUE THREAD

**Issue by mgordin** [SharePoint/sp-dev-fx-webparts#655]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@wobba 
@FranckyC 

## Expected or Desired Behavior

When you search for something, apply filters, and then search for something else after, the search results should either:
* Show the filters you previously applied as selected and apply them to the results (best option).
* Clear all filters and show results with no filters (worse, but still clear to users).

## Observed Behavior

When you search for something, apply filters, and then search for something else after, your previous set of filters appears to still be selected, but is not actually applied to search results.  To apply those filters again you need to manually clear and re-apply them.

## Steps to Reproduce

1. Search for something.
2. Apply filters.
3. Without reloading the page, search again.
4. Observe that the filters are still listed as selected (shown at the top of the search results and checked in the filters panel), but they are not actually affecting the search results.
5. Manually uncheck and check the "selected" filters in the filters panel and observe that they are now being applied to the search results.

**Comment by FranckyC** [comment]
@mgordin should be resolved with the latest version.
