### ISSUE TITLE
How to proceed to add extra refiners ?

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-fx-webparts#662]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

> Mikael Svenson

## Observed Behavior

> Thank you for "react-search-refiners" webpart, as it meets our requirement we were looking for.However would you please suggest, whether there is any possibilities of adding extra refiners ? If yes, Would you please guide on the quick steps for the same ?

**Comment by wobba** [comment]
@dips23 can you elaborate on what you mean? The wp already support adding any refinable property.

**Comment by dips23** [comment]
Oppz, my bad - yes I was checking for the properties which were not refinable, on the other hand, for extra refinable properties to be added, does it require to be added in the code as well as indicated in below screen? Or it just to be configured in the webpart ? 

![image](https://user-images.githubusercontent.com/13658386/47833669-1d505d00-ddc2-11e8-9066-d64eed0267a0.png)

If only require to be configured in the web part, then we can close the issue.

Thank you for your time !

**Comment by wobba** [comment]
It's all in the webpart property pane UI :-)
