### ISSUE TITLE
NPM Install Frozen at Extract Webpack-Bundle-Analyzer

### ISSUE THREAD

**Issue by franzvarga** [SharePoint/sp-dev-fx-webparts#663]
## Category

- [X] Question
- [X] Bug
- [ ] Enhancement

## Authors
@FranckyC @wobba 

## Expected or Desired Behavior

The Expected Behavior is to clone the sp-dev-fx-webparts repository (used GitHub Desktop) and then navigate with the command prompt to folder GitHub\sp-dev-fx-webparts\samples\react-search-refiners. From there, I use npm install to install the necessary software. Following, I can either use gulp build --ship + gulp bundle --ship + gulp package-solution --ship or gulp serve to review the new functionality.

## Observed Behavior

When running npm install on the directory GitHub\sp-dev-fx-webparts\samples\react-search-refiners, the prompt freezes at the following line:
[       ...........] | extract:webpack-bundle-analyzer: verb lock using C:\Users\XXXXX\AppData\Roaming\npm-cache\_locks\staging-21a6e46022c8f611.lock for H:\My Documents\GitHub\sp-dev-fx-webparts\samples\react-search-refiners\node

I've left this running overnight and the install is at the same phase when I return the next morning.

## Steps to Reproduce

Using GitHub Desktop, select File --> Clone Repository --> URL. navigate within Command Module to directory of sample, and use npm install.

**Comment by FranckyC** [comment]
Hi @franzvarga , what version of Node.js are you using?

**Comment by franzvarga** [comment]
@FranckyC  - was using 5.6.0 - I just updated to 6.4.1. I'll keep you posted on if the error still occurs.

**Comment by franzvarga** [comment]
@FranckyC continues to freeze at the same point of install:
![image](https://user-images.githubusercontent.com/35532799/47811231-42d25d80-dd13-11e8-805f-e29f476413c4.png)

**Comment by franzvarga** [comment]
I'll go ahead and clear the npm cache using npm cache clean --force - if that solves this I'll feel a bit invalidated.

**Comment by FranckyC** [comment]
Weird. Do you have same issues with other samples?

**Comment by franzvarga** [comment]
I agree it's odd. I verified that install npm on react-search functions fine, so I'm unsure why the issue with react-search-refiners. I'm not hugely familiar with node.js - do you know if there is a way of clearing halted installs? I thought that the cache clean or deleting the lock might do it, but it doesn't appear so.

**Comment by franzvarga** [comment]
Well - that's bizarre. I took down the repository via zip and unpacked to a new directory and the install works fine. I do wonder if there is some type of stalled install in the other directory that I can't get to.

Either way, thank you for developing this web part - superbly useful as a base for web parts, and the refiners are amazing.

**Comment by franzvarga** [comment]
@wobba I was using the Master branch.

**Comment by franzvarga** [comment]
@FranckyC and @wobba I tried a different location and still received the same checksum error when using sha512.

**Comment by franzvarga** [comment]
@FranckyC and @wobba for the moment I'm playing with the 9/24 branch and it works fine.
