### ISSUE TITLE
QueryStringDataSourceApplicationCustomizer breaks default search in modern sites

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-fx-webparts#665]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@FranckyC 

## Expected or Desired Behavior

Searching from the search box in a modern site should show default search.

## Observed Behavior

With the application customizer hooking on ?q nothing happens when you search.

## Steps to Reproduce

> _If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Thanks for reporting this issue @wobba. I'll try to investigate this week. Initially I planned to use the default "PageContext" data source instead to get query string parameter but unfortunately, the source doesn't fire on browser history events, only with a full page refresh...

Do you have some repro steps so I could have the same setup as you?

**Comment by wobba** [comment]
@FranckyC Create a comm site. Add wp to site. That attaches the custom action. Try to search from the oob search box and you will see nothing happens.

**Comment by FranckyC** [comment]
@wobba Removed the extension data source. Should be resolved with the latest version.
