### ISSUE TITLE
React-search-refiner is not working

### ISSUE THREAD

**Issue by Rajrup-net** [SharePoint/sp-dev-fx-webparts#682]
When i am trying to install npm I am getting this error.. Can you please help me out why I am getting this permission issue ??

PS D:\react-search-refiner\spfx> npm i
npm WARN tarball tarball data for office-ui-fabric-react@5.131.0 (sha512-QOYu1uf92qhTTIlBAj8teKvRpCmpliRZjynYtgeeUbDm4C4
GtXdb/O1rPNFsfT0PNtPC8dCNeQ7/CXjQenUkyw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for typescript@3.0.3 (sha512-kk80vLW9iGtjMnIv11qyxLqZm20UklzuR2tL0QAnDIygIUIemcZMxlMWudl9O
Ot76H3ntVzcTiddQ1/pAAJMYg==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Basic.Example.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Example.scss.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Target.Example.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Basic.Example.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Basic.Example.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Example.scss.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Example.scss.js.map'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabr
ic-react-88aa0e34\lib-es2015\components'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Target.Example.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\examples\HoverCard.Target.Example.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\ExpandingCard.styles.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\HoverCard\index.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.checklist.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.styles.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.base.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.types.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBoxPage.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\index.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.styles.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.styles.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.checklist.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.base.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.types.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.checklist.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.types.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBoxPage.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBox.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\react-search-refiner\spfx\node_modules\.staging\office-ui-fabri
c-react-3b6a9d3c\lib-es2015\components\SearchBox\SearchBoxPage.js.map'

**npm ERR! path D:\react-search-refiner\spfx\node_modules\.staging\typescript-12733c61\lib\typingsInstaller.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\react-search-refiner\spfx\node_modules\.staging\typescript-12
733c61\lib\typingsInstaller.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\react-search-refiner\spfx\node_modules\.staging\typescript
-12733c61\lib\typingsInstaller.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\react-search-refiner\spfx\node_modules\.staging\typescri
pt-12733c61\lib\typingsInstaller.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'D:\\react-search-refiner\\spfx\\node_modules\\.staging\\typescript-12733c61\\lib\\typingsInstaller.
js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\react-search-refiner\\spfx\\node_modules\\.stagin
g\\typescript-12733c61\\lib\\typingsInstaller.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\react-search-refiner\\spfx\\node_modules\\.staging\\typescript-12733c61\\lib\\typingsInstaller.js'
,
npm ERR!   parent: '@microsoft/api-extractor' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).**

**Comment by muges01** [comment]
Hi guys, 

I'm having similar issue when i run the npm install. Please refer to the screen shot below.

![image](https://user-images.githubusercontent.com/22563887/48661216-81cc1700-ea66-11e8-80c7-31c5095fdc32.png)

Thank you

**Comment by FranckyC** [comment]
@Rajrup-net Is it the same issue if you run this command as an administrator?

**Comment by Ofer-Gal** [comment]
I have the same when running as administrator too

**Comment by muges01** [comment]
Hi @FranckyC ,

I have tried to delete the node_module folder and the package-lock.json but no luck.

**Comment by FranckyC** [comment]
@muges01 What version of node js are you using?

**Comment by Ofer-Gal** [comment]
That Made it work. Thanks. Tested on My o365 and it is fine.
Now I am trying it in SP2019.
The upload ends with error "There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsDomainIsolated' attribute is not declared.' on line '1', position '319'." 
Which file should I change? at all possible?

**Comment by FranckyC** [comment]
The solution has been made for SharePoint Online originally. Maybe starting over a new blank project targeting SP 2019 would be useful to see differences.

**Comment by FranckyC** [comment]
@muges01 You did all those steps + running as administrator as well?

**Comment by FranckyC** [comment]
@Rajrup-net does it work for you as well?

**Comment by Rajrup-net** [comment]
Hi @FranckyC !!! running in admin mode solved the issue.. Thanks..

**Comment by FranckyC** [comment]
@Rajrup-net  or @wobba you can close this issue I think.
