### ISSUE TITLE
Fix width on Sort Fields Dropdown

### ISSUE THREAD

**Issue by GeoffE1e6** [SharePoint/sp-dev-fx-webparts#703]
The sort combo box that is displayed on the results pane resizes based on the field chosen. For example:

The sort fields option includes these fields:

Title
Document Status
Renewal Date

When you choose say Title the sort combo resizes to the width of that field. That means if the user chooses say another field they wont be able to see the other two fields as they will be truncated

![image](https://user-images.githubusercontent.com/45271893/49233010-f3a04b00-f3ec-11e8-874c-a1573bd1041c.png)

Could the width of the combo be fixed width to say 20 characters? Hope this makes sense...

Cheers

G

**Comment by wobba** [comment]
Fixed with #704
