### ISSUE TITLE
react-search-refiners cannot be editable after searching anything and click on edit page

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-fx-webparts#713]
## Category

- [ ] Question
- [x] Bug
- [] Enhancement

## Authors
@wobba @FranckyC 

## Expected or Desired Behavior

I should be able to edit the page and also the web part after searching anything or if i use the KQL query directly on the results web part. 

## Observed Behavior

After searching anything with the search box or if the search result web part is configured to use the KQL (not dynamic source) and if i click "Edit" to edit the page the search result does not show anything and also blocks the loading of other web parts on the page. I also cannot edit the web part. 

## Steps to Reproduce

- Add web part to page and configure
- Enter search keyword on the first page of the configuration page that returns some results
- Publish the page
- Click Edit to edit the page
- The page will stay white and the web parts cannot be editable anymore

Web Part is configured:
![image](https://user-images.githubusercontent.com/13345587/49578056-22687500-f949-11e8-99f6-cb2b7b00e562.png)

Page published:

![image](https://user-images.githubusercontent.com/13345587/49578138-50e65000-f949-11e8-80e5-d2a4508db3e5.png)

Page is again in edit mode:

![image](https://user-images.githubusercontent.com/13345587/49578179-6c515b00-f949-11e8-81c1-f9ccce11ac0e.png)

Thank you!

**Comment by canturan** [comment]
@wobba i am using version 2.2.0.0. To test the issue, i did a fresh clone from the "master" and deployed it. 2.2.0.0 has this problem. 

Should i also test it with the 2.2.0.1?

**Comment by canturan** [comment]
@wobba it seems that the version 2.2.0.1 does not have this problem. I will examine it further..

**Comment by FranckyC** [comment]
@canturan ok let us know. Except the static keywords, did you configure any other option in the WP? Also, do you have an error message in the browser console when editing the page?

**Comment by canturan** [comment]
@FranckyC i did not configured any other options to test, if the master (2.2.0.0) has this problem. Unfortunately i don't get any specific errors on the console, just some handlebar register errors but i also see these sometimes when i refresh the page. 


Additional info:  the new "dev" branch - 2.2.0.1 does not have this problem. I can edit the page without any problem, after the results web part already has results (from static keywords or dynamic data) but if i bundle package the solution (--ship) the dynamic data does not work. The Webpart and also the site freezes:

![image](https://user-images.githubusercontent.com/13345587/49609651-68025d80-f99c-11e8-803d-fec91fd48aa9.png)

  
![image](https://user-images.githubusercontent.com/13345587/49609683-89fbe000-f99c-11e8-8712-54d77ce48eee.png)

If i use static query without the search box, the everything works as expected.

**Comment by FranckyC** [comment]
Never seen this kind of issue before. Can you try in a different browser or in an anonymous tab?

**Comment by canturan** [comment]
@FranckyC i have tested it on Edge and Chrome and naturally in private mode. it is really strange.

**Comment by canturan** [comment]
@FranckyC and also in 3 different tenants.. When you build and deploy the "dev" branch, is it working without any problem? - with search box using dynamic source/data?

**Comment by canturan** [comment]
@FranckyC To be sure, i have cloned the repository, builded, bundled and packaged the "dev" branch (always with --ship), deployed to a new tenant, configured the web parts just with dynamic source, no other changes on the options and i still get the same effect, freeze and the errors:

![image](https://user-images.githubusercontent.com/13345587/49612243-591fa900-f9a4-11e8-9f03-42b170923aaf.png)

**Comment by canturan** [comment]
It is really strange..The problem is, if i use the search box/dynamic source then the web part runs to a loop, in which it sends 2000 postquery and 2000 maptoicon requests. if i wait enough (like couple of minutes, i get the results)

![image](https://user-images.githubusercontent.com/13345587/49614098-963a6a00-f9a9-11e8-9da5-04d7ce89d81a.png)

![image](https://user-images.githubusercontent.com/13345587/49614205-de598c80-f9a9-11e8-9d23-e44116dc1c26.png)


if i use static keyword (also with *), then it is working without any problem. I need to deploy a debug version to find out why.

**Comment by canturan** [comment]
@wobba @FranckyC I could not find the problem on the new version "dev" branch but i could at least find the "edit page" problem on the "master". 
It was the "resize listener" without the try-catch block on the componentWillUnmount, which you had fixed on the new version. Webparts > searchResults > components > Layouts > SearchResultTemplate.tsx. It throws "defaultView" not exists by switching to the page edit mode and let the page freeze. 

public componentWillUnmount() {
        try { 
            this.resize.removeResizeListener(this.parentRef, this.onComponentResize);             
        } catch (error) {} 
    }

**Comment by wobba** [comment]
@canturan dev branch is usually the most "stable" for this web part, as this is where we commit fixes until it's merged to master on regular intervals. Which is why I added that try/catch.
