### ISSUE TITLE
Opening solution in Visual Studio 2015 with NodeJS Tools breaks TS build

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-fx-webparts#72]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior
I tried opening and running a new project (Drop 6) in Visual Studio with NodeJS Tools installed.
When running the `gulp serve` command however, I receive lots and lots of Typescript errors.

I tried investigating the issue myself, and I noticed that when opening the project in Visual Studio, an `index.d.ts` file is generated in the `typings` directory, with the following content, along with the `globals` directory and its content:
```
/// <reference path="globals/gulp/index.d.ts" />
/// <reference path="globals/node/index.d.ts" />
/// <reference path="globals/react-dom/index.d.ts" />
/// <reference path="globals/react/index.d.ts" />
```
Is this something I can disable? Removing the `index.d.ts` file fixes the `gulp` command, but I can't be expected to do this everytime I (or someone else) open the project...

#### Steps to Reproduce

1. Create a new project with yo generator
2. Open the project in Visual Studio 2015 with NodeJS tools installed
3. Run `gulp serve` either from VS Task Runner Explorer or command line

**Comment by Trickass** [comment]
@jtlivio a lot of errors actually :)
This is the output of the `gulp serve --verbose` command: http://pastebin.com/SkggPTPN

**Comment by chakkaradeep** [comment]
I replied to the related issue and doing the same here:

There seems to be some issues with Visual Studio and TypeScript. Visual Studio by default is looking for the TypeScript installed by Visual Studio and not what the web project is using. So, this is creating issues within Visual Studio. 

At this point, I think this is an issue with Visual Studio and I would recommend to discuss with the [Visual Studio Community](https://developercommunity.visualstudio.com/index.html).
