### ISSUE TITLE
SharePoint Framework search date refiner

### ISSUE THREAD

**Issue by yvonne70** [SharePoint/sp-dev-fx-webparts#729]
# [Category]
- [x] Enhancement

## Authors
@FranckyC @wobba @mikaelsvenson

## Expected or Desired Behavior
I have used your web part on a project and noticed that the date refiner uses todays date and allows you pick before today or after today. Would you have any guidance on how I could edit the code to produce the date refiner to match the OOTB that Microsoft use in the modern experience (pasted below)? 
![screenshot 2018-12-16 at 13 59 18](https://user-images.githubusercontent.com/10848982/50054600-87874c00-013b-11e9-8dc9-bb736357afaa.png)

## Observed Behavior
This is what I see for the date refiners.
![screenshot 2018-12-16 at 13 57 50](https://user-images.githubusercontent.com/10848982/50054605-966dfe80-013b-11e9-8e9d-c819e016a767.png)

## Steps to Reproduce
Using the refiners on the web part.

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @yvonne70. To do this, one approach would be to generate your own refiners data corresponding to each period range (see [FQL doc](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/fast-query-language-fql-syntax-reference#fql_range_operator)). However, doing this could lead to 0 results so you would have also to deal with this case in terms of UI/UX.

**Comment by wobba** [comment]
@FranckyC  @yvonne70 might be doable to get this in with the refiner spec to bucket it up. Been a while since I looked at this.

**Comment by MistahG** [comment]
I experience the same. It would be great to have the out of the box date range values.

**Comment by wobba** [comment]
I'll close this, please reopen in https://github.com/SharePoint/sp-dev-solutions
