### ISSUE TITLE
Refiner when clicked does not update Total Results count

### ISSUE THREAD

**Issue by GeoffE1e6** [SharePoint/sp-dev-fx-webparts#730]
When a set of results is displayed, and the filter selected, the count against the refiner does not update the total results counter. Can this be corrected? Check out the following screenshot - hope it makes sense?

![image](https://user-images.githubusercontent.com/45271893/50180941-eba83c80-0302-11e9-8a47-51ff5d747f66.png)

**Comment by FranckyC** [comment]
Hi @GeoffE1e6, good catch. Will be resolved next merge.
