### ISSUE TITLE
Angular-multipage sample: missing $

### ISSUE THREAD

**Issue by JskB2** [SharePoint/sp-dev-fx-webparts#74]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Hey guys, just a small correction: there's a tiny mistake in the **angular-multipage** example, the [VoteController.ts](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/angular-multipage/src/webparts/poll/app/poll/vote/VoteController.ts) is missing the Angular dollar sign ($) before the _event_ word on **line 55**. 
Please compare with line 75 for reference. 
The web part doesn't work during the voting phase because of the missing $.
Thanks much for the samples!

**Comment by waldekmastykarz** [comment]
Ah, good catch. Sorry for that. I will submit a PR asap.
