### ISSUE TITLE
Search Box not showing the Suggestion in react Search refiners Sample

### ISSUE THREAD

**Issue by vinit14360** [SharePoint/sp-dev-fx-webparts#740]
We were using SearchBox and Search result Result webpart from this sample https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-search-refiners

We have build and Installed the webpart in App catalog Succesfully.

Added the Search Box webpart to the page and Enable the Query Suggestion.

when ever i typed any keyword in Searchbox it does not result anything as suggestion though Search results Webpart displayed the results.

On further investigation using Developer Tools i found that below Rest query called successfully but no result returned.
https://mysite.sharepoint.com/_api/search/suggest?querytext=%27Shar%27&inumberofquerysuggestions=10&fprequerysuggestions=true&fhithighlighting=true&culture=1033&fprefixmatchallterms=true

Based on further search on Internet i found a link stating that _api/search/suggest is not supported in SharePoint Online.

https://sharepoint.stackexchange.com/questions/249176/api-search-suggestquerytext-returns-empty-result

could you please confirm the same or any configuration could be missing for me.

We are using Sharepoint online for your information.

Category
[X ] Question
[X ] Bug
[] Enhancement
Authors
@FranckyC @wobba

Expected or Desired Behavior

**Comment by wobba** [comment]
Haven't tested in a while, but suggestions also are dependent on results being clicked, which are also site collection scoped. Which means the feature is hard to get working (unless you manually add global suggestions). And we have not implemented click recording in this webpart (yet).

**Comment by wobba** [comment]
@FranckyC the docs says online is not supported for suggestions.

**Comment by FranckyC** [comment]
@wobba At the time when I've implemented it, the suggestions were available in SPO (the static keyword list). Don't know if MS shut down this feature since.

**Comment by FranckyC** [comment]
Works fine in my tenant. 
![image](https://user-images.githubusercontent.com/5659122/50699856-ffe47d00-1016-11e9-900d-1c807cfee5fa.png)

**Comment by wobba** [comment]
Which means docs are wrong 😄

**Comment by FranckyC** [comment]
Does it work in your tenant when you simply add some phrases?

**Comment by wobba** [comment]
@vinit14360 I assume that if we call `RecordClick` appropriately, this might work as well. Can we close this issue?

**Comment by vinit14360** [comment]
ok you can close this issue. do we have any reference link to implement Record click in Current Search Box Webpart.

**Comment by wobba** [comment]
There is some documentation around on `RecordPageClick` but not with REST. I've played with it before, and feel free to add an issue requesting the addition of this for the react search wp.

**Comment by pravin080317** [comment]
0


Iam calling the search api "_api/search/suggest?querytext='*" using httpclient in azure functions. Authentication is done via azure ad application. Application permissions sites.fullcontrol is provided. But when ever i tried to call this suggest api, it returns empty results.

i can able to retreive the results of suggest api using username and password but using the azure ad app auth it gives the empty results.

whether we can able to call this suggest api using application permissions set in azure ad ? kinldy let me know if there are any alternatives
