### ISSUE TITLE
SPFx react-search-refiners webpart | No results from teamsites displayed

### ISSUE THREAD

**Issue by mi-di** [SharePoint/sp-dev-fx-webparts#749]
## Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors
@FranckyC @wobba 

## Observed Behavior
I'm using the SPFx react-search-refiners webpart and I didn't know if this is a bug or this is due to SharePoint restrictions.

When I enter a KQL query I supose to get the same results as I use the query in the search box or in the SharePoint Search Query Tool.
 
I have a hub site (SharePoint Communication Site) with several group connected Teamsites connected to this hub site. When I enter the following query
Path:https://tenant.sharepoint.com/teams/* contentclass:STS_Site SiteTemplate:GROUP
in the Query Template box no results are returned.

But when I enter this same query in i.e. the SharePoint Searchbox I get a list of the teamsites back.
And when I add this same query in the SharePoint Search Query tool I also get the right results back.
Some Teamsites are private and some are public, and I'm Owner of all sites.

## Steps to Reproduce
1. Create new Communication Site
2. Make this site a hub site
3. Create several teamsites
4. Connect them to the hubsites
5. Add the webpart to the startpage of the hub
6. Configure webpart:
        - Search Query Keywords = *
        - Query Template =
        - Path:https://tenant.sharepoint.com/teams/* contentclass:STS_Site SiteTemplate:GROUP
        - No further Changes

## Solution
I posted my question on the Microsoft Tech Community and @mattipaukonen pointed me in the right direction to mention the 'EnableDynamicGroups' property.

https://techcommunity.microsoft.com/t5/SharePoint-Developer/SPFx-react-search-refiners-webpart-No-results-from-teamsites/m-p/312277#M6245

And I found the solution!

I added the following lines of code to the SearchServices.ts file:

searchQuery.Properties = [{
    Name: "EnableDynamicGroups",
    Value: {
        BoolVal: true,
        QueryPropertyValueTypeIndex: 3
    }
}] 

Should be a nice feature to make this optional in the webpart properties.

**Comment by wobba** [comment]
It's on my todo list to add this, but haven't needed it myself so far :-)

**Comment by wobba** [comment]
We're also in the process of moving the webpart to a the sp-dev-aolutions repo, so feel free to submit a PR there.

**Comment by wobba** [comment]
This has been fixed
