### ISSUE TITLE
Shared node_modules for all webparts

### ISSUE THREAD

**Issue by DavidFatena** [SharePoint/sp-dev-fx-webparts#75]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

Now, after git clone we have to go to every single webpart (currently 22) and use npm install which renders 22x 200MB of duplicit files.

In the future, we will most likely have more webparts, with more and more duplicit files.

Is there an easy way to make one node_modules folder shared with all webparts?

**Comment by waldekmastykarz** [comment]
You can add multiple web parts to the same project which would allow you to share the node_modules folder among them. If you choose to have a separate project for each web part then the consequence is a separate node_modules folder for each one of them.

**Comment by DavidFatena** [comment]
When I have one project with more webparts, they share the same config and other files. I would have to manually copy-paste the contents of all 22 configs to one and make other adjustments. 

Also, when I have one project with more webparts, I can't seperately version my webparts.

In my opinion this will need some more thoughts.

**Comment by AustinBreslinDev** [comment]
Hi @DavidFatena,

I'm making an assumption here, but you are asking this question for the Devs on your team and not your build server?

If so you could use symlinks on your local machines to reduce the npm install size and time while still keeping all the webparts on there working and tested versions.

It won't completely solve your problems, but should help. I do this for the samples folder for the SharePoint sp-dev-fx-webparts. There are just too many and would cause my virus scan to take too long.

```
mklink \J .\from C:\\shared_node_modules
```

For your build server I wouldn't recommend this. Your builds need to be 100% reproducible and you need to know they work.

If it's a problem for your build server, see which webparts are related enough to be in the same package and update configs, move folders around as required. When complete though you would be required to retest your webparts.

**Comment by nickpape-msft** [comment]
Another option would be to use the build tool we are using internally, [Rush](https://github.com/Microsoft/web-build-tools/wiki/Rush). If you wanted to keep all your webparts in different projects (perhaps for SPPKG packaging reasons), but keep them all in a mono-repo that only does a single installation of the node_modules folder, then Rush is your tool. It will also let you version all your web parts to differing versions of SPFx, if, perhaps, you wanted to upgrade them piecemeal.

**Comment by VesaJuvonen** [comment]
Closing as answered.
