### ISSUE TITLE
SPFX webpart deploy Golbally in Sharepoint 2016 ON premise

### ISSUE THREAD

**Issue by kbkotresh** [SharePoint/sp-dev-fx-webparts#751]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I have developed Sample Hello webpart and deployed to App catalog and it is working fine. 
When i am trying to add same webpart to Other web application its not showing in the "Add an App" page. 

Basically I want this webpart to be deployed as Golbally in SharePoint 2016 On premise envirionment.  So that i can add this webpart in all web applications.
I am Using Microsoft/Generator-sharePoint@1.0.2 version. 

Kindly suggest how to access the webpart in other Web application. 
More details 
1. create web application 
2.configure the App catalog in the Web application as site collection (Name AppCatalog).
3. create another Web application and create site collection as "WorkingCollection"
4. Navigate to Site Content->Click on Add an App 
5. I am not able to see the webpart .

Let me know if you need any further information.

**Comment by JCol79** [comment]
On Prem: Each Web application requires their own App catalog (Not share accross web apps). 

If you go to the "Manage App Catalog" (http://centralAdminHost:yourCAwebAppPort/_admin/ManageCorporateCatalog.aspx) on the top right you will see that the Web application is specified and there is a small drop down arrow to change Web apps.

**Comment by kbkotresh** [comment]
> On Prem: Each Web application requires their own App catalog (Not share accross web apps).
> 
> If you go to the "Manage App Catalog" (http://centralAdminHost:yourCAwebAppPort/_admin/ManageCorporateCatalog.aspx) on the top right you will see that the Web application is specified and there is a small drop down arrow to change Web apps.

Thank you for your suggestion . 
this will works for me .
