### ISSUE TITLE
react script-editor: padding not removable

### ISSUE THREAD

**Issue by physics515** [SharePoint/sp-dev-fx-webparts#756]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
react Script-Editor 
@wobba 

## Expected or Desired Behavior

On my SharePoint Modern Page the react script-editor had the ability to remove the extra padding for non-visible scripts. However with the latest round of updates from Microsoft, this no longer seems to be the case. The toggle button is still there when in edit mode but it seems to do nothing now. Is this an easy fix, or a fundamental change from our overlords?

## Observed Behavior

Explained above.

## Steps to Reproduce

I'm not really sure, other than look for yourself. It just randomly happened on my end without doing anything. I guess if no one else is experiencing the issue then it must be on my end, and I will try to rebuild.

**Comment by wobba** [comment]
Thank you @physics515. I updated the DOM hack to remove padding, and it now works again :)
