### ISSUE TITLE
Antivirus cought trojan

### ISSUE THREAD

**Issue by ValerasNarbutas** [SharePoint/sp-dev-fx-webparts#759]
## Category

- [ ] Question
- [x] Bug
- [x] Enhancement

## Expected or Desired Behavior
got new version of webpart react-calendar-feed
when installing with npm install
got antivirus alert:
d:\\react-calendar-feed\node_modules\.staging\flatmap-stream-0f3f9e37\index.min.js

containing trojan:js/coinminer
![image](https://user-images.githubusercontent.com/16476453/51269299-d5a59e80-19ca-11e9-9ae4-345a9c200110.png)

## Steps to Reproduce

copy webpart files from:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-calendar-feed
do npm install

## Submission Guidelines

Thanks for your contribution! Sharing is caring.
![image](https://user-images.githubusercontent.com/16476453/51269299-d5a59e80-19ca-11e9-9ae4-345a9c200110.png)

**Comment by hugoabernier** [comment]
@ValerasNarbutas thanks for catching this. It seems like the xml2js library is affected by the flatmap-stream vulnerability discussed in #708. I'm removing the libraries affected and will submit a PR without the libraries.

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas thanks for catching this. It seems like the xml2js library is affected by the flatmap-stream vulnerability discussed in #708. I'm removing the libraries affected and will submit a PR without the libraries.

Cool, thanks.

**Comment by hugoabernier** [comment]
@ValerasNarbutas I submitted a PR which removes the offending libraries. Thanks again for reporting this.

**Comment by VesaJuvonen** [comment]
Fixed with #763, thx @hugoabernier.
