### ISSUE TITLE
this.context.environment.type deprecated

### ISSUE THREAD

**Issue by DanielOlofsson77** [SharePoint/sp-dev-fx-webparts#76]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

**this.context.environment** seems to be deprecated when using the workbench in spo (it works as expected when running local workbench). How can I get this functionality in sharepoint online?

Best regards

**Comment by waldekmastykarz** [comment]
This seems to be the same issue as https://github.com/SharePoint/sp-dev-docs/issues/299.

**Comment by DanielOlofsson77** [comment]
Yes, exactly the same problem. Sorry for not looking further than sp-dev-fx-webparts.

**Comment by waldekmastykarz** [comment]
No problem, thanks for closing the issue :)
