### ISSUE TITLE
Ship build of react-search-refiners does not work

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-fx-webparts#761]
## Category

- [ ] Question
- [x ] Bug
- [] Enhancement

## Steps to Reproduce
I have this problem since the version 2.2.0.1. Because of that i have tested the latest version as follows:

I cloned the latest version of the react-search-refiners web part (branch=master), did "npm install" and after that created a production bundle with:

gulp build --ship
gulp bundle --ship
gulp package-solution --ship 

I have created a new O365 Tenant (it is not an upgrade from 2.2.0.0) and deployed the web part with <"skipFeatureDeployment": true,">. I placed the web parts search box and search results on a new created site. The configuration is OOB.

Package-solution

![image](https://user-images.githubusercontent.com/13345587/51354893-77091f00-1ab5-11e9-9410-1befa2ad8faa.png)

When i search something with the search box i get the following error:

![image](https://user-images.githubusercontent.com/13345587/51355026-fac30b80-1ab5-11e9-8234-f83ce6050e32.png)

The DevTools Console shows the following errors:

![image](https://user-images.githubusercontent.com/13345587/51355064-2219d880-1ab6-11e9-93de-67db87bdc836.png)

I have just uploaded 5 documents to this new tenant but the mapToIcon method has been called at least 1000 times and after that i see the following errors:

![image](https://user-images.githubusercontent.com/13345587/51355147-6d33eb80-1ab6-11e9-986b-e47d62215a08.png)

When i build, package and upload the web part without --ship, then it works perfectly. 

Do you have any idea, what causes the issue?   @FranckyC  @wobba 

Thank you!!!

**Comment by wobba** [comment]
@canturan can you pull down the code from https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch which is the new location for the webpart with the latest code. On the next merge, the sample will be removed from the sp-dev-fx-webparts repo.

The latest code should have a fix for this issue and we're up to v2.4.0.1 now, and be sure to read the upgrade notice in the readme - which will impact upgrade.

**Comment by canturan** [comment]
@wobba Thank you very much for the information. I have read, that the web part will be moved to another repository but did not catched that it is already moved. Great. I' ll of course give it a try.

**Comment by canturan** [comment]
@wobba I have tested the new version. Unfortunately it has also the same problem with the --ship build/package. 

I also wanted to mention since the version 2.2.0.1 that we have some SASS errors that causes the -ship build to fail. I have suppressed these in gulp file:

![image](https://user-images.githubusercontent.com/13345587/51686152-1f583f80-1ff0-11e9-8585-59823c5f57e7.png)


The other error are still the same:

![image](https://user-images.githubusercontent.com/13345587/51686207-3ac34a80-1ff0-11e9-99b3-89c7e05c643e.png)

I cannot follow what this infitie loop of maptoicon errors causes :(

**Comment by canturan** [comment]
@wobba Also additional info about my development environment. Maybe the problem is related with another package:

Project pnp-react-search-refiners version:2.4.0
Build tools version:3.8.33
Node version:v8.11.3
Gulp version: 4.0.0
SPFx Generator: 1.7.1

**Comment by wobba** [comment]
@canturan what query are you using and what render template - in order to try to reproduce the error. Do you have an idea @FranckyC?

**Comment by FranckyC** [comment]
Hi @canturan. I'll try to investigate this week end. Seems to be related to dynamic data.

**Comment by FranckyC** [comment]
@canturan Unfortunately, I'm not able to reproduce your issue even after repackaging and reinstalling the whole solution from scratch (wiping the node_modules completely, removed previous versions, etc.) using the latest version from https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch. I used the `"skipFeatureDeployment": true` setting. What kind of results are you displaying and what is the search box query?

**Comment by canturan** [comment]
@FranckyC Hi. I am also using the "skipFeatureDeployment: true". Actually it is not important what i type into the search box. It fails with each query. 

Should i record a video, how i install the web part? Would it help you? 

Interesting thing is, when i package the with Webpart without --ship and let it run locally, then it works without any problem. As i said, i have this problem since the version 2.2.0.1. The production package of the version 2.2.0.0 without any problem.

**Comment by wobba** [comment]
@canturan Latest version is v2.4.0.1 located at https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch

**Comment by FranckyC** [comment]
@canturan Sure a quick video could help to understand your issue. Also, just in case, is there something special with the results you are trying to display?

**Comment by canturan** [comment]
@FranckyC  One more question: Did you created a production version of the Webpart, as you tested it with:
gulp build --ship
gulp bundle --ship
gulp package-solution --ship

How did you suppressed the SASS errors?

**Comment by FranckyC** [comment]
@canturan Yes I've tried all those steps that's why I don't understand. For the SASS warnings, did you use the `build.addSuppression` cmd in your gulpfile.?

**Comment by canturan** [comment]
@FranckyC Yes, I have used "build.addSuppression" in my gulp file. I'll try to record a video tomorrow.. Thank you!

**Comment by FranckyC** [comment]
@canturan Thanks. Sorry for not being able to help you until then...

**Comment by canturan** [comment]
@FranckyC I have recorded everything from cloning the repository till the problem. You would see it video that i had problems with the packages because of the package-lock file. Also SharePoint had a temporary problem as i have first tested the Webpart. The relevant error message is the "Uncaught (in promise) RangeError: Maximum call stack size exceeded". You would also see the infinite post request when you search something with the search box. I hope, this would help us to identify the issue. Thank you again!!! 

[https://1drv.ms/v/s!Aq7SZU0MmmqImYFwh1eCF4FHgB3t3Q](url)

**Comment by FranckyC** [comment]
@canturan I see in your video a lot a error during the `gulp build --ship` step. Seems very similar to https://github.com/SharePoint/sp-dev-solutions/issues/52. First of all, can you update your Node.js version with the latest 8.x https://nodejs.org/dist/latest-v8.x/?

**Comment by canturan** [comment]
@FranckyC You are 🥇 . It was really the wrong configuration of the search box. Thank you very very much! 

Maybe you can also insert build.addSuppression for the SASS errors to the source code, to avoid the build errors. 

@wobba Thank you also very much for your support!  Great!!!
