### ISSUE TITLE
Tests failing on updating office-ui-fabric-react package

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-fx-webparts#762]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

After updating a package "office-ui-fabric-react" from "5.124.0 to "6.128.0", all my tests are failing with following error:

 FAIL  ***.test.tsx
  ● Test suite failed to run

    node_modules\office-ui-fabric-react\lib\components\Button\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './BaseButton';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (**.tsx:17:67)
      at Object.<anonymous> (**.test.tsx:7:29)

I'm using framework  Jest, enzyme, sinon. Please let me know why.

**Comment by xyz92** [comment]
@VelinGeorgiev Could you please let me know if you have any idea to resolve this?

**Comment by VelinGeorgiev** [comment]
Hey @xyz92 , I am not using Fabric UI in my solutions and I do not have a quick solution for you here. 

You might have to ignore some Fabric UI stuff to make it work. Have a look here: https://github.com/facebook/jest/issues/2550
