### ISSUE TITLE
react-search-refiners - Filter Panel too big for mobile app & mobile browser

### ISSUE THREAD

**Issue by CharlesVARAUT** [SharePoint/sp-dev-fx-webparts#765]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@FranckyC & @wobba 

## Expected or Desired Behavior

The filter panel of _react-search-refiners_ WebPart should be fully visible on browser and SharePoint mobile app and not depend of the screen resolution.

## Observed Behavior

The filter panel is too big for mobile screen and it is troncated.

## Steps to Reproduce

WebPart _react-search-refiners_ v.2.4.0.1 - master - f100c65f3656dee97f5d40a1be6454c77f3ccb94

Using the SharePoint mobile app or a mobile browser, open the filter panel of the WebPart.

## Submission Guidelines

Hi,
This bug seems to be linked to the use of `type={PanelType.custom}` and `customWidth="450px"` for this Panel in _FilterPanel.tsx_.
By replacing `type={PanelType.custom}` with `type={PanelType.medium}` and removing `customWidth="450px"` seems to solve it but i wanted to know if this choice of type was done to resolve another bug or issue.
Have a nice day :-)

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
@CharlesVARAUT could you log this issue over at https://github.com/SharePoint/sp-dev-solutions which is where the webpart has moved to?

**Comment by CharlesVARAUT** [comment]
@wobba done :)

**Comment by wobba** [comment]
Thank you : @CharlesVARAUT
