### ISSUE TITLE
react-real-time question

### ISSUE THREAD

**Issue by davidhartman** [SharePoint/sp-dev-fx-webparts#78]
#### Category
- [ x] Question
- [ ] Bug
- [ ] Enhancement

In the use case where you have multiple newsfeed lists on different sites, is there a way to pass not only the itemId, but also the listId of the item, and site url in a logic app? would a custom connector do this? or are we currently stuck creating a webhook for this?

Thanks!

**Comment by FranckyC** [comment]
Hi @davidhartman. Unfortunately, even you can retrieve custom properties from a SharePoint list item, properties like listId or siteUrl are not available in the output of the Logic App action. Maybe webhooks are your best solution in this case.

**Comment by davidhartman** [comment]
@FranckyC thanks for the reply! makes total sense!
