### ISSUE TITLE
Using custom CSS plus the ModuleLoader.loadCss() problem

### ISSUE THREAD

**Issue by JskB2** [SharePoint/sp-dev-fx-webparts#79]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hey guys, a couple of questions here, plus a potential issue: 

#### Using custom CSS files
Is it possible to create a custom CSS file in the src folder and use it across the Web Part? For example, creating a standard set of Angular views and styling the HTML with that CSS?

Or should that be done just by adding rules to the [webpart-name].module.scss file and using those in an Angular view?  The thing is that the classes or id rules from that file get a suffix (e.g. `_5944ac05`) while being compiled into CSS. Is there any way of removing those suffixes? I guess they are there in order to prevent those styles colliding with something else on the page which might by chance contain a same style name, but I'm just wondering if it's possible...

In a nutshell, I guess the question would be is it possible to add an use additional CSS and SCSS files? And can the SCSS suffixes somehow be omitted?

If by any chance a part of the answer contains the `ModuleLoader.loadCss()` method, please check out the text below too...

#### `ModuleLoader.loadCss() `problem
Has anyone had anything similar happening? While trying out the [AngularToDo](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x) example from the Docs, I keep getting an issue while trying to use the `ModuleLoader.loadCss()` method. Importing the `ModuleLoader` results with no issues, but whenever I call the `loadCss` method the Web Part fails to start and gulp reports the following error:

`Module not found: Error: Cannot resolve module 'resx-strings' in C:\*PROJECT_FOLDER*\node_modules\@microsoft\sp-module-loader\lib\DeveloperTools`

When the line containing the method call gets commented out, the Web Part loads up and there are no errors...

**Comment by waldekmastykarz** [comment]
> Is it possible to create a custom CSS file in the src folder and use it across the Web Part? For example, creating a standard set of Angular views and styling the HTML with that CSS?

Yes, you can include a regular .css file in your project and then in your code use `require('./myfile.css')` to load it inline in your web part. That way its contents would be embedded in the web part though so if you have multiple web parts and would like them to reuse the same CSS it might not be the perfect solution.

> Is there any way of removing those suffixes?

Yes, you can wrap your classes in `:global { ... }`, like:
```css
:global {
  .myclass {
  }
}
```
Everything inside `:global` will be left without suffix. Please note that it has the risk of conflicts of your classes with other classes that might be on the page. A thing that you could perhaps try would be to use the following construct:
```css
.myWebPart {
  :global {
    .myClass {
    }
  }
}
```
On the top element of your web part you would use ${styles.myWebPart}. In your Angular template you would use regular CSS classes without any suffix. The difference in this approach is that the generated CSS would be like `.myWebPart_5944ac05 .myClass` which helps you isolate your styles from other styles available on the page.

**Comment by JskB2** [comment]
Thanks a lot, Waldek!

**Comment by frankchen76** [comment]
For your 'resx-strings' error, please check [sp-module-loader loadCss broken in Drop 6  #286 ](https://github.com/SharePoint/sp-dev-docs/issues/286). you need to add `"@microsoft/sp-module-loader": "node_modules/@microsoft/sp-module-loader/dist/sp-module-loader.js",` in your config.json if you need to use LoadCss().

**Comment by JskB2** [comment]
Thx much!
