### ISSUE TITLE
SharePoint Framework WebPart & SharePoint Hosted

### ISSUE THREAD

**Issue by AlexLaberge** [SharePoint/sp-dev-fx-webparts#81]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

Hello, I'm checking out the HelloWorld sample & I've seen the part where it is deployed to a CDN
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn

I was wondering, can it be all SharePoint-Hosted (without CDN)? If so, any samples out there that shows how to do that (everything SharePoint-Hosted)?
 
Thank you for your time

Alex
#spfx, #spfx-webparts

**Comment by waldekmastykarz** [comment]
Yes, you can host web parts wherever you want. In fact, since a while SharePoint Online offers support for public CDN. You can find more information at https://blog.mastykarz.nl/publish-sharepoint-framework-client-side-web-parts-office-365-public-cdn/.

**Comment by AlexLaberge** [comment]
Thank you! I will check this out for sure.
