### ISSUE TITLE
React-script-editor not running Bootstrap Accordion script

### ISSUE THREAD

**Issue by eldoro80** [SharePoint/sp-dev-fx-webparts#818]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@wobba 

## Steps to Reproduce

Hi wobba, thanks for your great SPFX webpart! I'm pretty novice in SPFX, but your webpart got me wanting to learn more about the new FrameWork. And after hours of trial and error I've managed to learn enough about NPM, GULP, PowerShell and CDN to get the webpart running on a Test Tenant.

But now I'm stuck, unfortunately. I'm trying to run an Bootstrap Accordion Search solution. Here is a link to the project: [https://codepen.io/chrislanejones/pen/gmjGoW](https://codepen.io/chrislanejones/pen/gmjGoW)

I've made sure script are allowed on my tenant. In addition, the test script that's on the sample github page is working (TradingView Widget).

The HTML code I'm using links to .js and.css files that are stored localy in the sites SiteAssets library. When I open the HTML code localy the solution works fine (I can search and the accordion items are all closed, except for the first one, which is by design). When I add the code to the webpart, the scripts don't seem to work. All accordion items are closed and search doenst work.

I've attached the HTML code in a zip file. Couldnt manage to insert it directly as code.. Did I mentioned I'm novice ;-)
[index.zip](https://github.com/SharePoint/sp-dev-fx-webparts/files/2996986/index.zip)

I really hope you can give me some tips. 

With kind regards.. eldoro

**Comment by wobba** [comment]
@eldoro80 your zip does not include bootstrap/fonts/jquery, so I cannot test it (without an effort). That said, I would look into porting all of this to a proper SPFx solution instead. Should be pretty straight forward. There is also official docs on using jQuery accordion with SPFx at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part

**Comment by eldoro80** [comment]
@wobba Thanks for your reply. I'm learning step by step. Babysteps for now :-) Thanks for your link to the Microsoft documentation. Will definitely take a look.

Here is a zip with all of the css and scripts included. 
[Code.zip](https://github.com/SharePoint/sp-dev-fx-webparts/files/3002204/Code.zip)

**Comment by wobba** [comment]
@eldoro80 you are missing closing divs in the end of your markup which messes up the parsing/loading. Make sure to use valid markup and it works just fine.

**Comment by eldoro80** [comment]
@wobba Thanks! Shame on me ;-) I'll go and try it again.
