### ISSUE TITLE
react-aad-implicitflow

### ISSUE THREAD

**Issue by davidhartman** [SharePoint/sp-dev-fx-webparts#82]
#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

I'm working on rewriting the react-aad-implicitflow in angular. I'm able to successfully connect to Azure AD as a user. However whenever I try to call this.authCtx.aquireTokens(aadResource), I receive the following error: token renewal operation failed due to timeout. The interesting thing is that I watch the network traffic via fiddler when my app makes the this.authCtx.acquireTokens(aadResource) and it does return as a 302, with a bearer token. I think the problem is something with the adalRenewFrame|graph.microsoft.com that is loading. Any ideas as to what might be causing this?

**Comment by waldekmastykarz** [comment]
If you're using ADAL JS with Angular you don't need to call `this.authCtx.acquireTokens` yourself. Instead you could define the list of endpoints for which ADAL JS should retrieve AAD access token. ADAL JS ships with an HTTP interceptor that automatically monitors all web requests issued using the HTTP service and if the request URL matches one of the registered endpoints, ADAL JS will automatically retrieve the access token for it.

**Comment by davidhartman** [comment]
Thanks Waldek for all the help! When I tried doing it the angular way, i.e. setting adal up in the .config function when the app starts. I receive "AuthenticationContext is not defined at Object.AdalModule.provider.init()", which I know is because AuthenticationContext is not in the global namespace because we are using systemjs. However, I'm not sure how to get the AuthenticationContext into the global namespace. Any suggestions?

**Comment by davidhartman** [comment]
Waldek -

Of course after I post this I figure it out! :) I'm dealing with the infinite loop problem but it's fairly well documented so I should be able to figure it out.

@waldekmastykarz

**Comment by waldekmastykarz** [comment]
Looking forward to read more about your solution 🙂

**Comment by vortex2143** [comment]
I have the same issue, when I try to use the sample without any changes in the code. I installed the webpart on SPO and tried to use it within the workbench. I get on both the same error: token renewal operation failed due to timeout. The error occures when the acquireToken function is called.

**Comment by davidhartman** [comment]
I noticed that would sometimes happen if I had developer tools open in Chrome when the acquireToken function was called ...

@vortex2143
