### ISSUE TITLE
React Modern Script top/bottom padding

### ISSUE THREAD

**Issue by eldoro80** [SharePoint/sp-dev-fx-webparts#839]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@wobba 

## Expected Behavior

When setting property 'Remove top/bottom padding of web part container' to 'Remove Padding', the padding should be removed.

## Observed Behavior

The padding isnt removed. I am using the latest version on my tenant.

**Comment by wobba** [comment]
Fixed in the dev branch.

**Comment by eldoro80** [comment]
You the man! Thanks.

**Comment by wobba** [comment]
Was a matter of DOM hacking a few more levels up ;) not pretty, but it works - and is bound to break again at some point is my guess.
