### ISSUE TITLE
Property '$broadcast' does not exist on type '{}'

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-webparts#84]
#### Category
- [ ] Question

#### Observed Behavior

Getting the below error when I use angular in SPFX: 
![error](https://cloud.githubusercontent.com/assets/21008316/21367533/192854b0-c6c4-11e6-94a5-527e1f66d691.png)

I am not experiencing the same with the old solutions.

gulp serve command gives me the below errors

![gulperror](https://cloud.githubusercontent.com/assets/21008316/21367596/55315c40-c6c4-11e6-8f68-b8169c7362b9.png)

_

**Comment by waldekmastykarz** [comment]
Which version of the SharePoint Framework are you using?

**Comment by sprider** [comment]
Drop 6

**Comment by waldekmastykarz** [comment]
Could you update Angular to 1.5.x and install its typings using:

```
$ npm install @types/angular -D
```

**Comment by sprider** [comment]
getting this error now

![error](https://cloud.githubusercontent.com/assets/21008316/21600126/1198fe10-d13d-11e6-9adc-eb4baf610b07.png)

**Comment by waldekmastykarz** [comment]
Have you removed the old typings from the project? What version of Angular and Angular typings are  you using?

**Comment by sprider** [comment]
Could you please share the commands you are using after running yo @microsoft/sharepoint?

**Comment by waldekmastykarz** [comment]
Install Angular:

```
npm i angular -S
```

Install Angular TS Typings:

```
npm i @types/angular -D
```

**Comment by sprider** [comment]
I have executed the same commands but getting the same error. Please refer the code from the temporary location https://github.com/sprider/wordpress/tree/master/Temp/angular-web-tree

**Comment by waldekmastykarz** [comment]
I have an idea: could you change `ng.auto.IInjectorService` in here https://github.com/sprider/wordpress/blob/af442f80b51b23f323038971397687c095121ee5/Temp/angular-web-tree/src/webparts/webTree/WebTreeWebPart.ts#L21 to `angular.auto.IInjectorService` and see if it helps?

**Comment by waldekmastykarz** [comment]
OK, so the error is caused by the old Angular typings. Remove the ./typings/angular folder and from the ./typings/tsd.d.ts remove the reference to Angular typings and you will be able to build the project as expected.

**Comment by sprider** [comment]
That fixed the problem. Thank you Waldek.

**Comment by waldekmastykarz** [comment]
This sample is relatively old and based on TypeScript v1.x so it could be that the way TypeScript v2.x handles types and private names is different.
