### ISSUE TITLE
react-script-Editor not working on communication sites

### ISSUE THREAD

**Issue by rythm263** [SharePoint/sp-dev-fx-webparts#851]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

Mikael Svenson (@mikaelsvenson, techmikael.com)

## Expected or Desired Behavior

I expect that this webpart works for communication site template. But it does not seem to work for it even after setting "requiresCustomScript": false in ScriptEditorWebPart.manifest.json Did anyone test this webpart with a communication site?

## Observed Behavior

After deploying the app tenant wide, it can't find in a communication site.

## Steps to Reproduce

1. Build and deploy the solution. 
2. Add the app to a communication site
3. Try to find the webpart in the communication site.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by mrajkumar23** [comment]
Same Problem Bro. Let me know if you find any solution.

**Comment by TechLover23** [comment]
Same issue. You are right its not working on communication site. I tried to deploy tenant level. It shows in webpart in the gallery. Once we tried to add it to page generates error.

**Comment by jasjitchopra** [comment]
Same problem. Followed the same steps and get the same behavior. Will dig later in to the code when I get the chance to see why.

**Comment by amhrj** [comment]
https://github.com/SharePoint/sp-dev-fx-webparts/issues/660#issuecomment-438787547

**Comment by ntinykumar** [comment]
Its in my case also, Its not working or just says added in the communication site but not working or not able to see and add it.

**Comment by Zetkai84** [comment]
Need to enable scripting on the site with this command 
(Get-SPSite -Identity "https://your-host/sites/modern-site").DenyPermissionsMask = [Microsoft.SharePoint.SPBasePermissions]::EmptyMask
