### ISSUE TITLE
tslint error no-function-expression: Use arrow function instead of function expression

### ISSUE THREAD

**Issue by DesireChirag** [SharePoint/sp-dev-fx-webparts#865]
let myDropzone;
    let eventHandlers = {
      // This one receives the dropzone object as the first parameter
      // and can be used to additional work with the dropzone.js
      // object
      
       init :function (dz){
         myDropzone=dz;
       },

      let deletedQuestions = origQuestions.filter(obj =>
        !updatedQuestions.some(obj2 => obj.value == obj2.value))
     
     removedfile: function (file){
        let web:Web=new Web(_context.pageContext.web.absoluteUrl);     
        if(_fileUploadTo=="DocumentLibrary"){
          web.lists.getById(_listName).rootFolder.files.getByName(file.name).delete().then(t=>{
            //add your code here if you want to do more after deleting the file
          });
        }
        else{
          web.lists.getById(_listName).items.getById(Number(_itemId)).attachmentFiles.deleteMultiple(file.name).then(t=>{            
            //add your code here if you want to do more after deleting the file
          });
        }          
      },
      processing:function(file , xhr) {
        
        if(_fileUploadTo=="DocumentLibrary")
          myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/Lists/getById('${_parent.props.listName}')/rootfolder/files/add(overwrite=true,url='${file.name}')`;          
        else
        {          
          if(_itemId)
            myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/lists/getById('${_parent.props.listName}')/items(${_itemId})/AttachmentFiles/add(FileName='${file.name}')`;
          else
            alert('Item not found or query string value is null!');
        }
      },
      sending: function(file, xhr) {
        let _send = xhr.send;
        xhr.send =  function() {
          _send.call(xhr, file);
        };
      },
      error:function(file,error,xhr){
        if(_fileUploadTo!="DocumentLibrary")
          alert(`File '${file.name}' is already exists, please rename your file or select another file.`);
        //if(myDropzone)
        //  myDropzone.removeFile(file);
      }
     };

**Comment by DesireChirag** [comment]
1)  init :function (dz){
     myDropzone=dz;
   },
2) removedfile: function (file){
    let web:Web=new Web(_context.pageContext.web.absoluteUrl);     
    if(_fileUploadTo=="DocumentLibrary"){
      web.lists.getById(_listName).rootFolder.files.getByName(file.name).delete().then(t=>{
        //add your code here if you want to do more after deleting the file
      });
    }
3) processing:function(file , xhr) {
    
    if(_fileUploadTo=="DocumentLibrary")
      myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/Lists/getById('${_parent.props.listName}')/rootfolder/files/add(overwrite=true,url='${file.name}')`;          
    else
    {          
      if(_itemId)
        myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/lists/getById('${_parent.props.listName}')/items(${_itemId})/AttachmentFiles/add(FileName='${file.name}')`;
      else
        alert('Item not found or query string value is null!');
    }
  },
4) sending: function(file, xhr) {
    let _send = xhr.send;
    xhr.send =  function() {
      _send.call(xhr, file);
    };
  },
5) error:function(file,error,xhr){
    if(_fileUploadTo!="DocumentLibrary")
      alert(`File '${file.name}' is already exists, please rename your file or select another file.`);
    //if(myDropzone)
    //  myDropzone.removeFile(file);
  }
Please let us know how to convert above code in arrow function.

**Comment by sachinms15** [comment]
What is the fix for below highlighted issue
**error no-function-expression: Use arrow function instead of function expression**


let myDropzone;
    let eventHandlers = {
      // This one receives the dropzone object as the first parameter
      // and can be used to additional work with the dropzone.js
      // object
      init: function(dz){       
       myDropzone=dz;
      },
      removedfile: function(file){
        let web:Web=new Web(_context.pageContext.web.absoluteUrl);     
        if(_fileUploadTo=="DocumentLibrary"){
          web.lists.getById(_listName).rootFolder.files.getByName(file.name).delete().then(t=>{
            //add your code here if you want to do more after deleting the file
          });
        }
        else{
          web.lists.getById(_listName).items.getById(Number(_itemId)).attachmentFiles.deleteMultiple(file.name).then(t=>{            
            //add your code here if you want to do more after deleting the file
          });
        }          
      },
      processing: function (file, xhr) {
        
        if(_fileUploadTo=="DocumentLibrary")
          myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/Lists/getById('${_parent.props.listName}')/rootfolder/files/add(overwrite=true,url='${file.name}')`;          
        else
        {          
          if(_itemId)
            myDropzone.options.url = `${_context.pageContext.web.absoluteUrl}/_api/web/lists/getById('${_parent.props.listName}')/items(${_itemId})/AttachmentFiles/add(FileName='${file.name}')`;
          else
            alert('Item not found or query string value is null!')
        }
      },
      sending: function (file, xhr) {
        let _send = xhr.send;
        xhr.send = function () {
          _send.call(xhr, file);
        };
      },
      error:function(file,error,xhr){
        if(_fileUploadTo!="DocumentLibrary")
          alert(`File '${file.name}' is already exists, please rename your file or select another file.`);
        //if(myDropzone)
        //  myDropzone.removeFile(file);
      }
     };
    var djsConfig = {
      headers: {
        "X-RequestDigest": this.props.digest
      },
      addRemoveLinks:true
    };
    return (
      <DropzoneComponent eventHandlers={eventHandlers} djsConfig={djsConfig} config={componentConfig}>
        <div className="dz-message icon ion-upload">Drop files here or click to upload.</div>  
      </DropzoneComponent>
    );

**Comment by nanditachhajed** [comment]
Did you get any fix for this?

**Comment by JamesMcWhinney42** [comment]
Also struggling with this. Did you find a fix?
