### ISSUE TITLE
SPFx errors Javascript

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-fx-webparts#868]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Hello,
I get this error when executing my solution that contains 7 webparts, but just on the customer side , in my side everything works as expected.
"Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '@-moz-keyframes animation_do0sdn{from{opacity:0;}to{opacity:1;}}'.
Any suggestions please?

**Comment by hugoabernier** [comment]
Hey @FullStackRafik, did you ever solve your issue?

I'm closing old issues that haven't had any activity in over 6 months. If you still need help with this, please re-open a new issue and we'll see if we can get more community members to look at it.
