### ISSUE TITLE
Debugging react based modern spfx webpart using hosted workbench issues

### ISSUE THREAD

**Issue by monkey-butler** [SharePoint/sp-dev-fx-webparts#873]
## Category

- [ ] Question
- [x] Bug
- [] Enhancement

## Expected or Desired Behavior

We have been successful in developing multiple custom modern Web Parts against two tenants ( one used for development and one for build. Until recently the standard debugging method of serving from local machine against hosted workbench. Last week it appears our dev tenant stopped serving debug manifests, today our production tenant looks to be doing the same, has anyone else noticed this behaviour?

## Steps to Reproduce

We are using SPFX 1.7.1 and out of the box react with moment.js, @pnp/sp , @pnp/spfx-property-controls and @pnp/spfx-controls-react and have not been able to debug at all. On the same tenant a simple hello example using SPFX 1.8.2 debugs successfully on both tenants and the same issue affects multiple users.

##Has anyone seen similar issues?

Is 1.7.1 not working with a recently rolled out update?

Further investigation indicates that the issue is related to the version number not being updated so workbench serves the version from the appcatalog - has a change to SPO made this an issue?

**Comment by hugoabernier** [comment]
@monkey-butler did you ever get a resolution to this issue? I'm closing old issues that haven't had any activity in a while.

If you're still having this issue, please feel free to re-open a new issue.
