### ISSUE TITLE
File system conflict (baseSvc.ts)

### ISSUE THREAD

**Issue by dluc** [SharePoint/sp-dev-fx-webparts#875]
The repository contains files incompatible with case insensitive filesystems, so it's not possible to clone the repo correctly.

1. Go to https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angular-ngofficeuifabric-file-upload/src/webparts/angularFileUpload/app/services
2. Notice how there are two files with the same name, but different case: "BaseSvc.ts" and "baseSvc.ts"

When cloning the repo, one will get his error:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'samples/angular-ngofficeuifabric-file-upload/src/webparts/angularFileUpload/app/services/BaseSvc.ts'
  'samples/angular-ngofficeuifabric-file-upload/src/webparts/angularFileUpload/app/services/baseSvc.ts'
```

**Comment by jsuddsjr** [comment]
It appears that both files are identical, so one of them should be removed.

**Comment by jackpoz** [comment]
I opened a PR for this issue https://github.com/SharePoint/sp-dev-fx-webparts/pull/1025
