### ISSUE TITLE
use react-property-bag-editor without internet connection

### ISSUE THREAD

**Issue by cmuellerd** [SharePoint/sp-dev-fx-webparts#878]
## Category

- [x] Question

Sample:
react-property-bag-editor

I want to use it on OnPremise without Internet Connection.
Whats to change so no CDN is needed.
Actual it does not find the react 0.48.1 Manifest.
Thanks

**Comment by hugoabernier** [comment]
@cmuellerd did you ever get a resolution for this?

I'm closing old issues that haven't had any activities for a while, but please feel free to re-open it if you're still running into this issue.
