### ISSUE TITLE
spfx 1.8.2 @microsoft/sp-http/dist/index-internal"' has no exported member 'SPHttpClientBatch'.

### ISSUE THREAD

**Issue by ashavibapat** [SharePoint/sp-dev-fx-webparts#883]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors
**@msekkappan**

## Expected or Desired Behavior
Using spfx 1.8.2 I get the errors as below.
I had upgraded from spfx 1.8.1 recently using cli.

## Observed Behavior
errros when trying to gulp build 
Module ..../node_modules/@microsoft/sp-http/dist/index-internal"' has no exported member 'SPHttpClientBatch'.
Property 'beginBatch' does not exist on type 'SPHttpClient'.
Module '"webparts/speAdminUi/components/PeoplePicker/OfficeUiFabricPeoplePicker"' has no exported member 'OfficeUiFabricPeoplePicker'.

## Steps to Reproduce

Downloaded this sample and added required component files to my own spfx project

package.json for reference
{
  "name": "speadminui",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-lodash-subset": "1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "1.8.2",
    "@microsoft/sp-property-pane": "1.8.2",
    "@microsoft/sp-webpart-base": "1.8.2",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.7.22",
    "@types/react-dom": "16.8.0",
    "@types/webpack-env": "1.13.1",
    "ag-grid-community": "^20.2.0",
    "ag-grid-react": "^20.2.0",
    "bootstrap": "^4.3.1",
    "date-fns": "^1.30.1",
    "office-ui-fabric-core": "^10.1.0",
    "office-ui-fabric-react": "6.143.0",
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0"
  },
  "resolutions": {
    "@types/react": "16.7.22"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "^0.1.6",
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@types/chai": "3.4.34",
    "@types/jest": "^24.0.12",
    "@types/mocha": "2.2.38",
    "@types/node": "^12.0.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

**Comment by hugoabernier** [comment]
@ashavibapat did you ever resolve this issue? 

I'm closing old issues that haven't had any activity for a while. If you're still experiencing this issue, please feel free to re-open the issue and maybe we can get folks from the community to look at this again.
