### ISSUE TITLE
Changing width and height for js-modern-calendar

### ISSUE THREAD

**Issue by mdev23** [SharePoint/sp-dev-fx-webparts#890]
Hi, 

I am using these samples and they are great. In regards to the js-modern-calendar web part, wanted to see if width and height can be minimized, it seems to occupying lot of space on modern page. If its possible,  can someone please mention where I need to modify the width-height parameters in the code, thanks in advance.

**Comment by hugoabernier** [comment]
@mdev23  did you ever get the solution to this issue?

I'm closing issues that haven't had any activity for a while. If you found the solution to this, feel free to add a comment below. If you still have the issue, feel free to re-open it and we'll see if members of the community can help.
