### ISSUE TITLE
How to have choice options in Property Pane look like the Page Layout option? 

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-fx-webparts#903]
Which propertypane option allows me to have choices laid out like this: 

![image](https://user-images.githubusercontent.com/5871660/60127445-14434000-9745-11e9-943d-c6e666ad3d7d.png)

**Comment by hugoabernier** [comment]
@simkessy take a look at the [Chartinator sample web part](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-chartcontrol/src/webparts/chartinator/ChartinatorWebPart.ts) in the [React ChartControl sample](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-chartcontrol). You'll want to search for `PropertyPaneChoiceGroup`

You'll find a few examples of displaying property pane options as per this image:
![Property Pane](https://raw.githubusercontent.com/SharePoint/sp-dev-fx-webparts/master/samples/react-chartcontrol/assets/Chartinator.gif)

I hope this is what you're looking for?

**Comment by hugoabernier** [comment]
@simkessy  I hope that my answer above helped. I'll close this issue, but feel free to re-open it if you need more help with this.
