### ISSUE TITLE
react-calendar webpart for on prem

### ISSUE THREAD

**Issue by bumblebee333** [SharePoint/sp-dev-fx-webparts#904]
Has anybody tried to convert the react-calendar webpart/custom app to be used on prem.  I tried to create a new project via sp 2019 onprem yeoman template, migrated the code files, , i keep running into issues like below. I replaced all the react and @microsoft/sharepoint references to be that for on prem.

Error - 'tslint' sub task errored after 24 s
 FatalError in plugin 'gulp-cache'
Message:

Invalid source file: D:/Source/Sharepoint 2019 Upgrade/react-calendar/src/services/parseRecurrentEvent.d.ts. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.

Any help or guidance is appreciated.

Thanks,
Rakesh

- [x ] Question
- [ ] Bug
- [] Enhancement

My package.json
{
  "name": "react-calendar",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@pnp/pnpjs": "^1.3.0",
    "@pnp/spfx-controls-react": "1.12.0",
    "@pnp/spfx-property-controls": "1.14.1",
    "@types/draft-js": "^0.10.30",
    "@types/es6-promise": "0.0.33",
    "@types/globalize": "0.0.34",
    "@types/jquery": "^3.3.29",
    "@types/react-big-calendar": "^0.20.13",
    "@types/webpack-env": "1.13.1",
    "@uifabric/fluent-theme": "^0.16.7",
    "draft-js": "^0.10.5",
    "draftjs-to-html": "^0.8.4",
    "globalize": "^1.4.2",
    "immutable": "^4.0.0-rc.12",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "office-ui-fabric-react": "6.143.0",
    "react-big-calendar": "^0.20.4",
    "react-draft-wysiwyg": "^1.13.2",
    "spfx-uifabric-themes": "^0.6.0",
    "xml2js": "^0.4.19",
    "typescript": "^3.2.4"
  },
  "resolutions": {
    "@types/react": "15.6.6"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by hugoabernier** [comment]
@bumblebee333 were you able to do what you were trying to achieve? If so, we'd love to hear how you did it.

I'll close this issue because there hasn't been any activity on it for a while, but feel free to re-open it if you still need help with this.
