### ISSUE TITLE
react-script-editor: stale version history

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-fx-webparts#907]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors
@wobba 

## Expected or Desired Behavior
Version history is up-to-date.

## Observed Behavior
Version history is several versions behind.

## Notes
I know it's nitpicking, but sometimes I refer non-technical users to the web part and the old date makes the component look dated - or more stable than it is.

(Apart from that: thank you for your work on this component!)

**Comment by wobba** [comment]
Thank you and done :)
