### ISSUE TITLE
NPM Install error for latest react-script-Editor

### ISSUE THREAD

**Issue by SharePointGuys** [SharePoint/sp-dev-fx-webparts#908]
## Category
- [] Question
- [x] Bug
- [] Enhancement

## Authors
@wobba

## Expected or Desired Behavior

After I update all code from Git, I run 

NPM Install

No error should be generated

## Observed Behavior

λ npm install
npm WARN @uifabric/utilities@6.41.4 requires a peer of react@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@6.41.4 requires a peer of react-dom@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@6.41.4 requires a peer of react@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@6.41.4 requires a peer of react-dom@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@6.193.1 requires a peer of react@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@6.193.1 requires a peer of react-dom@>=16.3.2-0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN tslint@5.9.1 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of typescript@^2.1.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@2.28.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@2.11.2 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev || >= 2.5.0-dev || >= 2.6.0-dev || >= 2.7.0-dev but none is installed. You must install peer dependencies yourself.npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 576249 packages in 18.612s
found 4892 vulnerabilities (3402 low, 1349 moderate, 141 high)
  run `npm audit fix` to fix them, or `npm audit` for details

## Steps to Reproduce

1) Git pull origin master
2) Go to samples\react-script-editor
3) npm install

## Submission Guidelines
Maybe you could please upload a stable version SPPKG to the github. 

Thank you very much.

July 8, 2019

**Comment by wobba** [comment]
@SharePointGuys try this:
npm i
npm dedupe
gulp

**Comment by SharePointGuys** [comment]
thanks a lot @wobba for your quick reply. 

Still, it seems some errors, please refer to the screenshot below:
![image](https://user-images.githubusercontent.com/43420322/60836123-e9b8a480-a192-11e9-9d11-27544b6d86f1.png)

**Comment by SharePointGuys** [comment]
E:\p\sp-dev-fx-webparts\samples\react-script-editor (master -> origin)  
λ note --version                                                        
'note' is not recognized as an internal or external command,            
operable program or batch file.                                         
                                                                        
E:\p\sp-dev-fx-webparts\samples\react-script-editor (master -> origin)  
λ node -v                                                               
v10.16.0                                                                
                                                                        
E:\p\sp-dev-fx-webparts\samples\react-script-editor (master -> origin)  
λ npm -v                                                                
6.9.0                                                                   
                                                                        
E:\p\sp-dev-fx-webparts\samples\react-script-editor (master -> origin)  
λ gulp --version                                                        
CLI version: 2.2.0                                                      
Local version: 3.9.1

**Comment by wobba** [comment]
Try removing the node_modules folder and rebuild. I had no issues today and code haven't changed in a long while as it uses SPFx v1.5.1.

**Comment by SharePointGuys** [comment]
Thanks a lot @wobba 

I am trying to work it out. If possible, could you please upload a SPPKG file, it would be very helpful for me to figure out many things.

Currently I am stuck at the following error:
![image](https://user-images.githubusercontent.com/43420322/60910851-dc152480-a24f-11e9-97ba-a71b4451fd51.png)

**Comment by SharePointGuys** [comment]
By the way, I am working on SharePoint 2019 on-prem

**Comment by SharePointGuys** [comment]
Hallelujah. I think the article (https://github.com/scfrederic/from-sponline-to-sp2019/blob/master/README.md) is very helpful and the solution works for SharePoint 2019 on-premise. Thanks to @scfrederic. 

Reference: https://github.com/SharePoint/sp-dev-fx-webparts/issues/835

Thanks to @wobba again.

**Comment by wobba** [comment]
@SharePointGuys Curious, did you just switch back down to 1.4.1 without any other changes? If so, I can change that to make it 2019 compatible. Or submit a PR and tag me :)

**Comment by SharePointGuys** [comment]
@wobba Yes, that is what I did by reference the [article](https://github.com/scfrederic/from-sponline-to-sp2019/blob/master/README.md). Changed "@microsoft/...": "^1.4.1" from "^1.5.1". Thank you.

**Comment by fleagleman** [comment]
Hi, I've managed to get this able to package and get deployed to my site. 
HOWEVER.
When I add the web part (it adds successfully btw), the code disappears when I attempt to save. Doesn't matter what code I add, it does not save.
