### ISSUE TITLE
react-search-refiners build of june 7th 2018

### ISSUE THREAD

**Issue by HansK76** [SharePoint/sp-dev-fx-webparts#910]
I have gotten the previous build working, but would like to use this one, as I understand you can use version 1.4.1 on SharePoint on-premise.
It works fine in my local workbench, but when deploying to my onpremise/ offline environment. The Search box does not show when I add it to a page.
The refiner just keeps spinning.

**Comment by hugoabernier** [comment]
Hey @HansK76 did you ever solve this issue?

I'll close the issue because there hasn't been any activity for a while, but absolutely feel free to re-open it if you need more help with this.
