### ISSUE TITLE
NPM install error - Build failed after several errors thrown

### ISSUE THREAD

**Issue by wradez** [SharePoint/sp-dev-fx-webparts#913]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

**@wobba**

## Expected or Desired Behavior

I pull from github, cd to the react-script-editor sample, and run npm install.

All packages should be installed and the sample should be ready to build. No error should be generated.

## Observed Behavior

$ npm i

> deasync@0.1.13 install /Users/wradez/NREL-Projects/sharepoint-projects/sp-dev-fx-webparts/samples/react-script-editor/node_modules/deasync
> node ./build.js

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:203:13)
gyp ERR! stack     at Pipe.<anonymous> (net.js:588:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wradez/NREL-Projects/sharepoint-projects/sp-dev-fx-webparts/samples/react-script-editor/node_modules/deasync
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wradez/.npm/_logs/2019-07-10T18_13_15_534Z-debug.log

## Steps to Reproduce

Git pull
Go to samples\react-script-editor
npm install

## Useful Information

$ node -v
v12.6.0
$ npm -v
6.9.0
$ gulp -v
CLI version: 2.2.0
Local version: 3.9.1

**Comment by wradez** [comment]
I was able to figure out the issue. It was due to the new version of node that I had. I reverted back to v8.16.0 and everything is working now.

**Comment by lsteixeira** [comment]
Hi,
Keep up the good work. ;) 
I've faced the same issue with the latest 2.29.2 using node 12.6.0 on react-native 0.58.6.

It's supposed to work on top of the latest node v12?

Thanks. ;)

**Comment by lsteixeira** [comment]
Reverted to node v8.16.1.
Working fine.

**Comment by michalhainc** [comment]
Having this too, please investigate... latest node was installed by VS2019 enterprise

**Comment by wobba** [comment]
node v12 is not supported with SPFx. Follow SPFx install guidelines at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
