### ISSUE TITLE
Event-stream@3.3.6 not in npm registry

### ISSUE THREAD

**Issue by Tbuente-IT** [SharePoint/sp-dev-fx-webparts#915]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@msekkappan 
@VesaJuvonen 

## Expected or Desired Behavior

I am trying to install the modern calendar web part.

## Observed Behavior

Upon cloning and setting my directory, I try to run npm install, and get this error:

npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\pause-stream-007661ec\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\pause-stream-007661ec\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\pause-stream-007661ec\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\request-progress-a61f8379\test\test.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\split-4511dd1e\examples\pretty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\pause-stream-007661ec\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\split-4511dd1e\readme.markdown'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\pause-stream-007661ec\readme.markdown'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\multi-line.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\nested-interpolation.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\no-interpolation.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockClientSideWebPartManifests.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\raw-tagged-template-expression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockHost.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\simple-interpolation.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockWebPartContext.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\es6-templates-09be6d19\test\examples\tagged-template-expression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockWebPartManifestInstance.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockClientSideWebPartManifests.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockHost.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockWebPartContext.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\MockWebPartManifestInstance.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\sp-webpart-base-5c45bf0c\lib\test-api\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\node-sass-7a864b43\test\fixtures\watcher\main\partials\_one.scss'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\node-sass-7a864b43\test\fixtures\watcher\main\partials\_three.scss'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\node-sass-7a864b43\test\fixtures\watcher\main\partials\_two.scss'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\node-sass-7a864b43\test\fixtures\watcher\main\three.scss'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-529673b1\lib\jsdom\living'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\node-sass-7a864b43\test\fixtures\watcher\main\two.scss'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-529673b1\lib'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\normalizers\get-1.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\normalizers\get-fixed.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-211f276b\lib\cli\logic\test'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\normalizers\get-primitive-fixed.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\normalizers\get.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\normalizers\primitive.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\plain.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-211f276b\lib\cli'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\profile.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\weak-plain.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\memoizee-036f05eb\test\weak.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-211f276b\lib\cli\logic\test\repo\b\package.json'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\FocusZone\examples'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\Persona.checklist.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\Persona.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\Persona.styles.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\Persona.types.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\Persona.base.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\PersonaConsts.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\PersonaInitialsColor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\PersonaPage.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\WINDOWS\system32\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-30df5273\lib\components\Persona\index.js'

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-connect'

**Comment by systemsmaven** [comment]
I'm having the same exact issue.  Thought I was doing something wrong.  LOL

**Comment by svoltmer** [comment]
Same error as well. Has there been a resolution?

**Comment by elswork** [comment]
Me too

**Comment by JBorras-summar** [comment]
The same error.
If you try to install manually event stream and check versions, 3.3.6 is not in the list of versions.
It goes from 3.3.5 to 4.4.0.
Maybe when developing this webpart existed and after was discarted.

![imagen](https://user-images.githubusercontent.com/57090420/69424628-65be1e00-0d29-11ea-90f3-af0ee415bd06.png)


https://www.npmjs.com/package/event-stream

I'll try to change dependencies in development branch and if I sucess I'll make a pull request

**Comment by ollij** [comment]
I'm having the same problem with react-rss-reader.

**Comment by ollij** [comment]
This is what I did to fix this with react-rss-reader web part. Warning: I haven't tested any other web part with this fix.

1. Open react-rss-reader folder in Visual Studio Code.
2. Locate gulp-connect entry, and look for requires section for event-stream 3.3.6.
![image](https://user-images.githubusercontent.com/10028657/70617203-be8e2180-1c18-11ea-8bb5-6a46e902e207.png)
3. Replace the "3.3.6" with "4.0.0".
4. Few lines down, you will find event stream section.
![image](https://user-images.githubusercontent.com/10028657/70617297-f006ed00-1c18-11ea-9b87-b6c69a5d0b56.png)
5. Replace the version number in both version and resolved url with 4.0.0.
6. Replace the integrity with sha512-DOB0pW11hF+A572U9vmYbQuLVvzXb2ZQhP14wAhMesOLoWVmWNKZ05niYwgUEEO7Ex+lbPpsqT+pch4O7Ijqmg==
7. From the requires section, remove flatmap-stream 0.1.0 line (this is already gone from dev branch but currently exists in master branch.
8. Your json should look like this.
![image](https://user-images.githubusercontent.com/10028657/70617445-4b38df80-1c19-11ea-840b-05d1fc4e0ca4.png)
9. Save the file and run npm install again.

**Comment by hugoabernier** [comment]
@Tbuente-IT did @ollij 's solution solve your issue? 

I'll go ahead and close this issue because there hasn't been any activity on it for a while, but feel free to re-open it if you're still experiencing the issue.
