### ISSUE TITLE
Problem with uploading new SPFx packages to app catalog modern experience

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-fx-webparts#919]
## Category

- [ ] Question
- [x] Bug
- [] Enhancement

## Expected or Desired Behavior

Not limited but also affecting this article: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

When you upload an spfx package to Apps for SharePoint library in your app catalog, we expect to see the dialog "Do you trust XXX solution?"

## Observed Behavior

Today I noticed this library opens in the modern experience. In that UI, uploading a file does not open this dialog and the application is not deployed, but the file is uploaded.
As a result the app cannot be used, graph permissions do not show up in the SharePoint Admin API management.

I had to delete the app, switch to classic experience and re-upload it.

This library should not open in modern experience unless this issue is resolved.

## Steps to Reproduce

Build any SPFx web part package that needs graph API permissions.
Upload it to the app catalog library while in modern experience.

**Comment by shaipetel** [comment]
Also, might be a good idea to update documentation until this is resolved, that uploading requires the user to switch to classic experience.

**Comment by hugoabernier** [comment]
@shaipetel  I'm going through issues and closing the ones where there hasn't been any activity in a while. 

I'll close the issue, but if this is still an issue that needs resolving, please do not hesitate to re-open it, and then maybe we can get members of the community to look at it with fresh eyes.
