### ISSUE TITLE
I want a version that support well on Sharepoint 2019.

### ISSUE THREAD

**Issue by xmj523** [SharePoint/sp-dev-fx-webparts#920]
Where can I get a well-supported version of webpart for Sharepoint 2019?
Does anyone know or have this resources? Thank you in advance.

**Comment by hugoabernier** [comment]
Hey @xmj523 did you ever get the answer you were looking for?

I'll go ahead and close this issue because there hasn't been any activity for a while, but if you still need help with this, feel free to re-open it and maybe someone will be able to help.
