### ISSUE TITLE
Sharepoint modern  hub site and association

### ISSUE THREAD

**Issue by sandippal972258** [SharePoint/sp-dev-fx-webparts#921]
Hello team,

Is there any way for get all associated modern site collection based on hub site id?
I want to make one web part from where i can show all associated site with current hub site.

Any one can help me here?
Thanks 
Sandip Pal

**Comment by hugoabernier** [comment]
@sandippal972258 did you ever get a resolution for this?

The always-amazing @wobba has a [great article](https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html) that may help you achieve what you want.

I'll close this issue as there hasn't been any activity for a while, but feel free to re-open it if you need more help.

**Comment by wobba** [comment]
`contentclass:sts_site DepartmentId:<site id of hub> -SiteID:<site id of hub>`

should do what you want, listing all sites, excluding the hub using KQL and search
