### ISSUE TITLE
Unit testing MS SharePoint Components

### ISSUE THREAD

**Issue by markyroden** [SharePoint/sp-dev-fx-webparts#922]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@VelinGeorgiev 

## Expected or Desired Behavior

The test runner should runn successfully on a simple test of the SharePoint list view component

## Observed Behavior

The test runner fails with the following error
Test suite failed to run

    C:\REpo\SPFx\sp-dev-fx-webparts\samples\react-jest-testing\node_modules\@microsoft\sp-core-library\lib\index.js:11
    export { default as _BrowserDetection } from './BrowserDetection';
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest/node_modules/jest-runtime/build/script_transformer.js:316:17)

## Steps to Reproduce

- Download this project: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-jest-testing
- Navigate to root and perform an ‘npm install’.
- Once project is ready, perform ‘npm test’, and observe output.
- There should be one test failure but the test will run.

- (Rename and) Put the included ‘HelloAdvanced.tsx’ file into the /components directory.
- (Rename and) Put the included ‘HelloAdvanced.test.tsx’ into the /test directory.
- Perform an ‘npm install –-save-dev @pnp/spfx-controls-react’.
- Run ‘npm test’.
- The test runner will fail with the reported error above

This is not specific to the ListView, it can be repeated with other OOB components from the pnp list as well.

[HelloAdvanced.test.tsx.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/3408449/HelloAdvanced.test.tsx.txt)
[HelloAdvanced.tsx.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/3408452/HelloAdvanced.tsx.txt)

**Comment by hugoabernier** [comment]
@markyroden did you ever get a resolution for this.

I'll close this issue because there hasn't been any activity on it for a while, but if you still need help with this, please don't hesitate to re-open it.
