### ISSUE TITLE
Search Refiners checkbox label language is not translated.

### ISSUE THREAD

**Issue by AhmedAldhubaibi** [SharePoint/sp-dev-fx-webparts#928]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I am using the modern search web part and I have added a search refiners web part. The problem is that, the result checkbox labels are not being translated. 

Hier is my used managed property for date and size:
![edit refiners](https://user-images.githubusercontent.com/32773458/61949447-3b429b00-afab-11e9-952e-1e81a4447a79.PNG)

The results options are displayed in English:

![Englich labels](https://user-images.githubusercontent.com/32773458/61949493-57463c80-afab-11e9-9626-75a2be7a5609.PNG)

For the managed properties Created and Size there are no ows_taxid properties. Also There are no labels translation in loc file for these values.

I know that these values (or later, and up ..) are coming form the api search results. Any suggestions?

## Authors

@FranckyC @VesaJuvonen

**Comment by hugoabernier** [comment]
This looks like a great opportunity for anyone who'd like to contribute to this repo. Any takers?
