### ISSUE TITLE
List From Webpart after converting to spfx 1.8 missing manifest.js

### ISSUE THREAD

**Issue by chinthaka321** [SharePoint/sp-dev-fx-webparts#929]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I convert the list form webpart to spfx 1.8. Successful converted build successfully. When I run on local workbench I can see the webpart. This should be the same for the SharePoint online.

## Observed Behavior

But When I tried to open the workbench from SharePoint online its saying giving error 
Your web part will not appear in the toolbox. 

Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.

Click here for more information.
![image](https://user-images.githubusercontent.com/7530412/61961266-7e802680-b00a-11e9-8dd9-c04df013ad73.png)

Its not even showing webpart on the select webpart list.

## Steps to Reproduce

Convert List From to spfx 1.8 then try to run in SharePoint online. 

package.json
---------------------
{
  "name": "react-list-form",
  "version": "1.0.0",
  "description": "The `React List Form web part` is a web part for adding a list form to any page. It provides a working example of implementing generic SharePoint list forms using the **SharePoint Framework (SPFx)** and the *React* and *Office UI Fabric* libraries.",
  "main": "gulpfile.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "serve": "gulp serve",
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@microsoft/sp-core-library": "^1.8.2",
    "@microsoft/sp-lodash-subset": "^1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "^1.8.2",
    "@microsoft/sp-webpart-base": "^1.8.2",
    "@tinymce/tinymce-react": "^3.2.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "^16.7.22",
    "@types/react-dnd": "~2.0.34",
    "@types/webpack-env": "1.13.1",
    "moment": "^2.24.0",
    "react-dnd": "^9.3.2",
    "react-dnd-html5-backend": "^9.3.2",
    "react-html-parser": "^2.0.2",
    "spfx-uifabric-themes": "~0.1.3",
    "tinymce": "^5.0.12"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "^0.7.7",
    "@microsoft/rush-stack-compiler-3.2": "^0.3.26",
    "@microsoft/rush-stack-compiler-3.3": "^0.1.6",
    "@microsoft/sp-build-web": "^1.8.2",
    "@microsoft/sp-module-interfaces": "^1.8.2",
    "@microsoft/sp-tslint-rules": "^1.8.2",
    "@microsoft/sp-webpart-workbench": "^1.8.2",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "5.0.0",
    "typescript": "^3.3.4000",
    "unlazy-loader": "^0.1.3",
    "url-loader": "^2.1.0",
    "webpack-bundle-analyzer": "^3.3.2"
  }
}

Node version 10.15.3

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
Hey @chinthaka321 did @Choggo 's version update solve this issue for you?

I'll go ahead and mark this issue as closed, as there hasn't been any activity on it for a while.

If you need more help with this, feel free to re-open it.
