### ISSUE TITLE
After update i cannot build new project and tsd install angular is not working. 

### ISSUE THREAD

**Issue by jbranders** [SharePoint/sp-dev-fx-webparts#93]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I have an issue after the update from spfx. 
The tsd install angular is deprecated and now i get errors in my projects, even if i create a new project it still the same i cannot build my solution without erros for angular. Have any please a solution how i can create a project install typings for angular and use them? Also after the update the sp-module-loader is not installed correctly, please let me know what i could do. 

Thank you in advance.

**Comment by frankchen76** [comment]
After drop6, SPFx aligned with latest Typescript by using @types instead of tsd. Try to add your angular definition using `"@types/angular": "^1.5.20"` for a new project. 
For sp-module-loader, it actually changed to sp-loader. The old "ModuleLoader" was changed to "SPComponentLoader". Also change your import to `import { SPComponentLoader } from '@microsoft/sp-loader';`.

**Comment by jbranders** [comment]
Yes, Thanks for the reply. It's worked for me transformed the samle ToDo webpart to the latest angular ng-office-ui-fabric and SharePoint Framework version. Thank you for the support.

**Comment by jbranders** [comment]
It's not working error TS4063: Parameter '$q' of constructor from exported class has or is using private name 'ng'. i get this error message, i don't know what i'm doing wrong but it seems the ng is a private name? But in the code examples it works fine?

**Comment by waldekmastykarz** [comment]
Code examples are outdated and based on TypeScript 1 whereas SPFx RC0 uses TypeScript 2. Could you try changing the namespace from `ng` to `angular` and see if that works for you?

**Comment by jbranders** [comment]
Yes, that's working. Thanks you for the helpful comment.
