### ISSUE TITLE
Typo import in BirthdayWebPart.ts (React-Birthday sample)

### ISSUE THREAD

**Issue by Scheevel** [SharePoint/sp-dev-fx-webparts#931]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@VesaJuvonen
@joaojmendes 

### typo in BirthdayWebParts.ts:line15 "...Birdthays..."
`import Birdthays from './components/Birthdays';`

**Comment by joaojmendes** [comment]
hello is possible to give more information? I created new REPO , and installed all dependencies running  npm install and after did gulp build and compiled without errors.  

Thank you!

**Comment by Scheevel** [comment]
No error - it's only a misspelling of the import variable.  I was going to fix with a pull request, but my branch folder structure is different now and I don't match the repo folders any more.  ...I could direct edit on GitHub and create a pull request (like I did for the .md) if that would be more efficient.

**Comment by joaojmendes** [comment]
yes, I will change. thank you.
