### ISSUE TITLE
react-script-editor web part does not preserve its properties when upgraded to SPFx 1.8.2

### ISSUE THREAD

**Issue by prusak82** [SharePoint/sp-dev-fx-webparts#936]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@wobba 

## Expected or Desired Behavior

After upgrading existing project to SPFx 1.8.2 this should work the same as it works in version 1.4.1 (currently in repo)
I upgraded project using o365 guidelines (I can share my upgraded project with you)

## Observed Behavior

After I make any changes to any web part properties (using property pane or editing script content using TextField) - title, removePadding, spPageContextInfo or script - and I publish / republish page - when I edit again - properties are not preserved.

## Steps to Reproduce

1. Use script editor web part (when editing specific Modern Site Page)
2. Setup some properties (title, removePadding, spPageContextInfo and of course script) - please use not default values.
3. Publish page where web part was used
4. Edit again page and try to edit previously added script editor web part
5. Suddenly all recently setup properties are re-initialized to default values :-(

## Submission Guidelines

I tried to debug where issue is introduced and I found following thing - when I comment out lines in **ScriptEditorWebPart.ts** (see below) - properties are preserved between publishing and editing page again. But this removes core functionality of this web part.

``` ts
public render(): void {
    if (this.displayMode == DisplayMode.Read) {
      // if (this.properties.removePadding) {
      //   let element = this.domElement.parentElement;
      //   // check up to 5 levels up for padding and exit once found
      //   for (let i = 0; i < 5; i++) {
      //     const style = window.getComputedStyle(element);
      //     const hasPadding = style.paddingTop !== "0px";
      //     if (hasPadding) {
      //       element.style.paddingTop = "0px";
      //       element.style.paddingBottom = "0px";
      //       element.style.marginTop = "0px";
      //       element.style.marginBottom = "0px";
      //     }
      //     element = element.parentElement;
      //   }
      // }
      // this.domElement.innerHTML = this.properties.script;
      // this.executeScript(this.domElement);
    } else {
      this.renderEditor();
    }
  }
```
I guess something crucial was introduced in newer version of SPFx that breaks this web part from proper functioning.
Any help would be very appreciated. 
Thank you for advance.

**Comment by wobba** [comment]
This is not a web part bug, but an upgrade bug. The part stays at 1.4.1 in order to support SharePoint on-prem. And there is no need to upgrade, as 1.4.1 has all needed features for the current code base.

**Comment by prusak82** [comment]
Thank you for very quick response. 
Let's wait then for next SP on premise version (hopefully additional SPFx capabilities will be offered there, e.g. SPFx extensions) :-)
I also understand reported issue is SPFx 1.8.2 issue rather than this web part problem.
I will use then 1.4.1 version.

PS.
To support web part setting **supportsThemeVariants** (I am using this web part also to put some styled HTML on SharePoint Modern Site Page)  I will use CSS hack proposed by @StfBauer 
```css
.CanvasZone,
.CanvasSection,
.Controlzone,
.ControlZoneEmphasisBackground {
background-color: inherit;
color: inherit;
}
```

**Comment by wobba** [comment]
@prusak82 When upgrading, did you use the O365 CLI to properly upgrade all files? And, the likelyhood of an update for SPFx on-prem are pretty slim.

**Comment by prusak82** [comment]
@wobba Yes I used O365 CLI (spfx project upgrade) and applied all suggestions from upgradeReport.md generated by the tool 

Additionally I upgraded 2 NPMs not mentioned by O365
@microsoft/sp-loader => from 1.4.1 to 1.8.2 
@microsoft/load-themed-styles => from 1.4.1 to 1.9.16 

I also tested this with original NPMs (the same effect) 
@microsoft/sp-loader => 1.4.1 
@microsoft/load-themed-styles => 1.4.1 

Here are me dependencies and devDependencies - maybe you will remark something weird / not matching

```json
"dependencies": {
    "@microsoft/load-themed-styles": "^1.9.16",
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-loader": "^1.8.2",
    "@microsoft/sp-webpart-base": "1.8.2",
    "@pnp/spfx-controls-react": "^1.14.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.7.22",
    "@types/react-dom": "16.8.0",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "6.143.0",
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "react-html-parser": "^2.0.2"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "0.7.7",
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "gulp-sequence": "1.0.0",
    "tslint-microsoft-contrib": "5.0.0",
    "webpack-bundle-analyzer": "^2.13.1"
  }
```

**Comment by prusak82** [comment]
BTW - I am using react-html-parser instead of dangerouslySetInnerHTML
And I started using RichText control from @pnp/spfx-controls-react (if user wants just put some HTML - I introduced new Toggle Property editHtmlDirectly)

```ts
{editHtmlDirectly ?
                  <TextField multiline rows={15} onChanged={this._onScriptEditorTextChanged} value={script} />
                  :
                  <div className={styles.richTextParent}>
                    <RichText value={script} onChange={this._onScriptEditorTextChanged} className={styles.richText} />
                  </div>
                }
```

**Comment by wobba** [comment]
Not sure what could cause this actually, but for the time being I probably won't do the changes you have done, which all makes sense, as they are not crucial to the web parts functionality - while still maintaining backwards compatibility for on-prem.

If you manage to upgrade it all, feel free to submit a PR, and I might can create a separate branch/version for it.
