### ISSUE TITLE
All of sudden issue with gulp command

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-fx-webparts#942]
Platform: SharePoint 2019, SPFx version in solution: 1.4.1

Giving following error when I do `gulp serve` command.
![image](https://user-images.githubusercontent.com/7568187/63024895-bd94ef80-bec5-11e9-8b3c-b2a0ceb6f7ce.png)

Edit: I have deleted node_modules folder then ran `npm install`, but still same issue

**Comment by BtrPrime** [comment]
I guess I am seeing something related this too. I just started learning to build SPFx following the tutorials.

Installed Node 10 x86
npm install -g yo
npm install -g gulp
npm install -g @microsoft/generator-sharepoint

Was advised to check to run to verify installations
npm list -g --depth=0

But I see empty 
C:\Users\@@@@\AppData\Roaming\npm
`-- (empty)

Not sure if this is an issue. But then went on and ran the following on a folder I created 
yo @microsoft/sharepoint

I see this error
![image](https://user-images.githubusercontent.com/11891588/63127890-76ac0600-bf68-11e9-875b-b5f739133959.png)

Running npm install, installing gulp, or anything seems to work. 

Are there any issues with the dependencies? I see errors at flatten

**Comment by hugoabernier** [comment]
@ymihir I hope you got a resolution to this issue?

I'll go ahead and close it as there hasn't been any activity on it for a while. If you're still experiencing issues, feel free to open a new issue. When you do, I encourage you to fill the provided issue template, as it helps route the issue to the appropriate people and -- hopefully -- gets an answer sooner.
