### ISSUE TITLE
Manage Site Design webpart error

### ISSUE THREAD

**Issue by navarrorc** [SharePoint/sp-dev-fx-webparts#945]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Observed Behavior
 @joaojmendes 
I'm the tenant administrator and have tried this in my development tenant.
I get the following error when viewing the page that contains the webpart:
### react-manage-sitedesigns-client-side-solution
`
AADSTS65001: The user or administrator has not consented to use the application with ID 'ed197c7b-92d6-4ce6-a1ab-f91ec9f8f32f' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
 Trace ID: ffe27c0d-b0bd-43e5-983e-57e4ce840c00
 Correlation ID: 4f57e0a3-5dee-41ec-acf0-5ffdbde2f668
 Timestamp: 2019-08-15 18:58:51Z`
![image](https://user-images.githubusercontent.com/215220/63118937-8e818b00-bf64-11e9-8cf0-c9376f7a1bb4.png)

## Steps to Reproduce

Just install the Spfx client solution in your apps catalog site collection and deploy to all sites. Add the Site Designs webpart to a page and you will get the error.

**Comment by joaojmendes** [comment]
Hello,

I saw that the webApiPermissionRequests is missing in package-solution.json file.

Please add this entries :

"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.AccessAsUser.All"
      }
      ]

Build and deploy and go to SharePoint admin center –> API Management and approve .

The web part it will work.

Thank you!
João Mendes

**Comment by navarrorc** [comment]
Adding the missing configuration did the trick. Thank you.
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "react-manage-sitedesigns-client-side-solution",
    "id": "50025bb6-5fda-4a16-b45e-5f27b19aac72",
    "version": "1.0.0.1",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "isDomainIsolated": false,
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.AccessAsUser.All"
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/react-manage-sitedesigns.sppkg"
  }
}
```

**Comment by joaojmendes** [comment]
The missing configuration will be fixed in the PR that was created.

Thank you very much for testing.
This issue can be closed.

**Comment by navarrorc** [comment]
Thank you!
