### ISSUE TITLE
Unexpected behavior when editing single event in a recurring series in React-calendar

### ISSUE THREAD

**Issue by amortsell** [SharePoint/sp-dev-fx-webparts#953]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@joelfmrodrigues 

## Expected or Desired Behavior

When editing a single event that's part of a recurring series, e.g., change the description, the specific event should be updated with the new description, but the rest of the events in the recurring series should remain unchanged.

## Observed Behavior

When I click a single event that's part of a recurring series and make a change to that event, the selected event is updated, but also a new recurring series with the updated event as the start date is created.

## Steps to Reproduce
1. Create an event recurring weekly every monday for two months.
2. Click the third (or any event after the first one) event of the series.
3. Enter a new description for the selected event and save your changes.

**Comment by amortsell** [comment]
I will try to resolve this in a pr coming soon. Probably beginning of next week.

**Comment by joelfmrodrigues** [comment]
Hi @amortsell,

I'm not the author of the sample, just contributed with some changes. I've seen your first message reporting the issue, and flagged it as a to-do to see if I could help...but haven't had the chance at all as I'm currently very busy 

The author is João Mendes. Try to link him here to see if he can help - I'm on the phone and @ links don't seem to work

Cheers

**Comment by amortsell** [comment]
Hi Joel,

 I tried to look into the history to find the author, and saw only your and
Vesa's names in previous commits. Sorry for any inconvenience. My plan was
to fix the issue myself, but since it would be my first pr other than
translation issues, I thought that I'd better register an issue first. Then
I didn't have time to fix it at once so it stayed in needs triage status
for longer than I initially planned.

Regards

Anders Mörtsell

**Comment by joelfmrodrigues** [comment]
That's absolutely fine, not disturbing at all and I would help if I had the chance.
Being your first PR, let me know if you have any questions I could help with. More than happy to help - also, there's plenty of info and videos to help with that 🙂

**Comment by amortsell** [comment]
Fixed by PR #980.
