### ISSUE TITLE
react-calendar-feed not fetching results in proper order

### ISSUE THREAD

**Issue by Rajrup-net** [SharePoint/sp-dev-fx-webparts#955]
I am trying to fetch using react-calendar-feed from my Event calendar list but events are not coming in proper order.. Another issue I noticed is if i try to fetch next 2 weeks result then previous and next both links are not working. Please help
![Capture](https://user-images.githubusercontent.com/23724113/63406481-ad21cf00-c407-11e9-918b-a973263b9488.PNG)

**Comment by hugoabernier** [comment]
@Rajrup-net, I submitted pull request #948 a few days ago which (I hope) addresses this issue.  Let me know if you still experience the issue after the update, and I'll investigate further.

**Comment by Mike05-921** [comment]
Thanks for your response.. As you suggested I tried with the new solution.. during build its not giving any error but when I am doing gulp bundle --ship that time its throwing following error..

Error - [webpack] 'dist':
calendar-feed-summary-web-part.js from UglifyJs
Unexpected token: name (Parser) [calendar-feed-summary-web-part.js:62128,6]

**Comment by Rajrup-net** [comment]
Thanks for your response.. As you suggested I tried with the new solution.. during build its not giving any error but when I am doing gulp bundle --ship that time its throwing following error..

Error - [webpack] 'dist':
calendar-feed-summary-web-part.js from UglifyJs
Unexpected token: name (Parser) [calendar-feed-summary-web-part.js:62128,6]

**Comment by Rajrup-net** [comment]
The above mentioned error I resolved by using gulp bundle -debug instead of gulp bundle --ship.
After doing all changes mentioned in #735, this solutionI have deployed to my tenant and still item is not coming in proper order.

**Comment by Rajrup-net** [comment]
Hi @hugoabernier , the solution is working now.. Thanks for your help
