### ISSUE TITLE
crud sample not work in FF and Edge

### ISSUE THREAD

**Issue by kocka5** [SharePoint/sp-dev-fx-webparts#96]
Hello, Crud sample not work in FireFox 50.1.0 - all request return 403 code text:  -2147024891,System.UnauthorizedAccessException.
in Edge work reading, but update write "Item with ID: 7726 successfully updated", but in site I see 403 error code and item is not updated. Create, delete does not work also.

  Pavel

**Comment by waldekmastykarz** [comment]
Is it a particular web part that isn't working or all of them in the sample?
