### ISSUE TITLE
react-invitation-manager

### ISSUE THREAD

**Issue by renato87milagres** [SharePoint/sp-dev-fx-webparts#965]
# Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

I was trying to build this solution  react-invitation-manager to test in my environment 
and I`m getting this error :

16:31:54] Error - [webpack] 'dist':
./lib/webparts/invitationManager/InvitationManagerWebPart.js
Module not found: Error: Can't resolve 'invitationManagerStrings'

can someone help me ?

Thanks a lot

**Comment by hugoabernier** [comment]
Hey @renato87milagres did you ever resolve this issue?

I'll mark it as closed because there hasn't been any activity here for a while, but feel free to re-open it if you need more help.

And if you solve the issue and remember how you did so, feel free to add a comment to help others.
