### ISSUE TITLE
react-rxjs-event-emitter - RefrenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by Manaf-Ibrahim** [SharePoint/sp-dev-fx-webparts#967]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Authors

@VelinGeorgiev 
@VesaJuvonen 

## Expected or Desired Behavior

Run `gulp serve` and be able to preview the webpart in the workbench.

## Observed Behavior

Upon running `gulp serve` the following error log occurs:
`internal/util/inspect.js:31
const types = internalBinding('types');
                      ^`

`ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:137:5)
    at require (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:110:12)
    at util.js:25:21
    at req_ (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:137:5)
    at require (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:110:12)
    at fs.js:42:21
    at req_ (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\manaf.ibrahim\Documents\Dev\Sharepoint\sp-dev-fx-webparts\samples\react-rxjs-event-emitter\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)`

## Steps to Reproduce

Clone repository, run `npm i` then `gulp serve`.

**Comment by VelinGeorgiev** [comment]
That error seems related to gulp itself (globally installed on your machine) not the sample. Could please confirm tuat you are running gulp version 3.9.1 which is supported by the SharePoint Framework?

**Comment by Manaf-Ibrahim** [comment]
Thanks @VelinGeorgiev I can confirm this tomorrow but if possible would we be able to validate this with the official Microsoft documentation for starting with the spfx as I followed this before attempting to work with the example and found no mention of the gulp version only Node? Please correct me if I am wrong or misunderstood any documentation as I am new to spfx and thank you once again to the hard work you have put in to provide this example

**Comment by VesaJuvonen** [comment]
Hi @Manaf-Ibrahim - we do call out the specific npm version in our documentation at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment, so double checking the versions is always the step #1 in troubleshooting if the details were not included in the initial issue submission.

**Comment by Manaf-Ibrahim** [comment]
Thanks @VesaJuvonen,

I have double checked this and can confirm that I am running version 3.9.1:

![image](https://user-images.githubusercontent.com/29912376/63820174-9c370780-c98b-11e9-9bd0-8fed3d04de5c.png)

Please don't hesitate to let me know if you need any further information from me at all.

**Comment by TracyGH** [comment]
I ran into the same issue with the react-mega-menu extension sample.  Superficial Googling led me to believe it's a Node/Gulp version compatibility issue.  But, I noticed that the HelloWorld scaffolded projects created from the current Yeoman generator work fine using the same versions these samples fail on.  

What version of the SPFx framework are you using?  Most/many of the samples are still configured for 1.7.0, but the latest framework version is 1.9.1. 

![image](https://user-images.githubusercontent.com/38665906/64648659-3b1e2380-d3d0-11e9-8e03-14f9d6a242d4.png)

Here are the rough steps I completed for upgrading the sample extension:

**1. Navigate to the sample directory and run the following commands:**
- npm install @microsoft/decorators@latest --save
- npm install @microsoft/sp-application-base@latest --save
- npm install @microsoft/sp-build-web@latest --save
- npm install @microsoft/sp-core-library@latest --save
- npm install @microsoft/sp-dialog@latest --save
- npm install @microsoft/sp-module-interfaces@latest --save
- npm install @microsoft/sp-webpart-workbench@latest --save
- npm install natives@1.1.6 --save

**2. Replace the '@microsoft/rush-stack-compiler-2.9' property in the package-lock.json file with the following:**
```
    "@microsoft/rush-stack-compiler-2.9": {
      "version": "0.7.16",
      "resolved": "https://registry.npmjs.org/@microsoft/rush-stack-compiler-2.9/-/rush-stack-compiler-2.9-0.7.16.tgz",
      "integrity": "sha512-a3sHfyEYj1aPgd87DYDX1InyP7YMYGRg6w62Ems0sLM67gUni6JGqKwLjqPsfFe9pKoT9hXvv1ltkTvxqh629g==",
      "dev": true,
      "requires": {
        "@microsoft/api-extractor": "7.1.8",
        "@microsoft/node-core-library": "3.13.0",
        "@types/node": "8.5.8",
        "tslint": "~5.12.1",
        "tslint-microsoft-contrib": "~5.2.1",
        "typescript": "~2.9.2"
      }
    }
```
_**Or run the following:  npm install @microsoft/rush-stack-compiler-3.2 
(The Yeoman generated 'HelloWorld' SPFx extension still uses version 2.9, so I updated the package-lock.json file instead of updating the package.)**_

**Comment by Manaf-Ibrahim** [comment]
Thank you @TracyGH,

This makes a lot of sense as I have setup the environment with SPFx V1.9 - ill try out the steps above to upgrade the solution to the latest working dependencies.

Thank you again for your response.

**Comment by VelinGeorgiev** [comment]
Thanks @TracyGH !

That is weird because it has to be backwards compatible. So maybe something happened between 1.7 and 1.9. I will test as well once I have the chance to .

**Comment by titleofliberty** [comment]
I was able to follow @TracyGH 's advice and upgrade all of the packages you list. When I searched the package-lock.json file I didn't find a @microsoft/rush-stack-compiler-2.9. I pasted in the v3.2 code and tried to serve the project but I got the following error:


> Build target: DEBUG
> D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
>             throw new Error(prefix + os.EOL +
>             ^
> 
> Error: JSON validation failed:
> D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\config\tslint.json
> 
> Error: #/ (Defines configuration options for the...)
>        Additional properties not allowed: ```
> lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
>     at validateObjectWithCallback (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
>     at JsonSchema.validateObjectWithCallback (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
>     at JsonSchema.validateObject (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
>     at TslintCmdTask._readConfigFile (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
>     at TslintCmdTask.onRegister (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\gulp-core-build-typescript\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
>     at Object.initialize (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\sp-build-common\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
>     at SPWebBuildRig.initialize (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
>     at SPWebBuildRig.initialize (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:28:15)
>     at Object.exports.initialize (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
>     at Object.<anonymous> (D:\TFSMS\VSS\Marion Smith\sp-dev-fx-webparts\samples\react-facebook-plugin\gulpfile.js:7:7)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
> 

```

**Comment by hugoabernier** [comment]
@Manaf-Ibrahim did you get a resolution to this issue? 

I'll go ahead and mark this issue as closed since there hasn't been any activity for a while, but feel free to re-open it if you need more help.
