### ISSUE TITLE
Using webpack magic comments

### ISSUE THREAD

**Issue by peni4142** [SharePoint/sp-dev-fx-webparts#969]
- [X] Question
- [ ] Bug
- [x] Enhancement

I tried to use a dynamic import via request in a webpart-project:
```
export function importOther(){
    // @ts-ignore
    import(/* webpackIgnore: true */ "https://xxx.sharepoint.com/:u:/s/anypage/xxxx");
}
```
But it seems webpack is ignoring that magic comment:
`Module not found: Error: Can't resolve 'https://xxx.sharepoint.com/:u:/s/anypage/xxxx`

Is this desired?
Is there another approach for a dynamic import?

I already asked on stackoverflow for help:
https://stackoverflow.com/questions/57675343/using-webpack-magic-comments-in-an-typescript-sharepoint-modern-ui-project
There you will find further information

**Comment by hugoabernier** [comment]
Hey @peni4142  did you ever get an answer to this? If so, we'd love to know what you found.

I'll go ahead and mark this issue as closed. If you need more help with this, feel free to open a new issue.
