### ISSUE TITLE
Issue installing the generator

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-fx-webparts#97]
#### Category
- [x ] Question

#### Expected or Desired Behavior
I run `npm install -g @microsoft/generator-sharepoint` on a new machine after doing the other steps and get the error below. Any suggestions how I make it work? Anything to clean up or similar? This is on a windows box and I'm running in a window with admin privileges.

`npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/microsoft/generator-sharepoint)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:microsoft/generator-sharepoint)
npm ERR! git clone git@github.com:microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\miksv\AppData\Roaming\npm-cache\_git
-remotes\git-github-com-microsoft-generator-sharepoint-7880b29f'...
npm ERR! git clone git@github.com:microsoft/generator-sharepoint ERROR: Repository not found.
npm ERR! git clone git@github.com:microsoft/generator-sharepoint fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:microsoft/generator-sharepoint
npm ERR! git clone git@github.com:microsoft/generator-sharepoint Please make sure you have the correct access rights
npm ERR! git clone git@github.com:microsoft/generator-sharepoint and the repository exists.
npm ERR! addLocal Could not install microsoft/generator-sharepoint
npm ERR! Error: ENOENT: no such file or directory, stat 'C:\repos\microsoft\generator-sharepoint'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "-g" "@microsoft/generator-sharepoint"
npm ERR! cwd C:\repos
npm ERR! node -v v6.9.4
npm ERR! npm -v 1.4.9
npm ERR! path C:\repos\microsoft\generator-sharepoint
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\repos\npm-debug.log
npm ERR! not ok code 0`

**Comment by TomGoorts** [comment]
How did you solve this error?

**Comment by wobba** [comment]
In my case it was Windows 10 ubuntu who had some npm stuff installed which messed up the tool chain.
