### ISSUE TITLE
React Script Editor - safe for Production Tenant with Site Level App Catalog

### ISSUE THREAD

**Issue by mwsaunders** [SharePoint/sp-dev-fx-webparts#972]
## Category
- [X] Question

@Wobba
Hi, 
First, I would like to thank the creator(s) of the React Script Editor.

I have a need to use CSS to hide the webpart header and Column Titles on a single modern page using the List View webpart.  
I am planning on using the React Script Editor in a Site Level App Catalog (so the app is not available on all sites.)  This particular site will be managed only by experienced Site Admins.
I have tested this on a development tenant and it works as expected.

When doing npm install for the React Script Editor it reports... 
found 3392 vulnerabilities (1570 low, 426 moderate, 1389 high, 7 critical)

Question: under these parameters with 7 critical issues and 1389 high issues - is this solution safe to use on a Production Tenant?

Regards,

**Comment by wobba** [comment]
Hi,
those warnings are for the build deps of the web part for that SPFx target version and can be ignored. The web part itself don't use external libs when actually running (outside of SPFx and we have to trust what Microsoft ships).

Which leads to - the unsafe part is what your editors put into the web part :) Seems you have vetted this and done your ROI so you are all good. That said, you never HAVE to hide anything. It's an ask and a want, but nothing you HAVE to. DOM manipulation is easy, but I will never recommend it, and as you know, it may well break at any time ;)

And if you click the option in the script ed wp to hide the zone borders, it also uses DOM manipulation - and have broken twice 😁

**Comment by mwsaunders** [comment]
Thank you for the confirmation.
