### ISSUE TITLE
react-content-query-webpart moment handlebar helper not working properly

### ISSUE THREAD

**Issue by XopherDesign** [SharePoint/sp-dev-fx-webparts#976]
I can only get the moment helper to act on the current date, it ignores any date passed in.
{{moment "YYYY"}}
{{moment "2011-09-03T00:00:00-07:00" "YYYY"}}
For example both of these lines result in "2019" when the 2nd one should output "2011" am I missing something?

**Comment by spplante** [comment]
Hi @XopherDesign , sorry for the delay :)

Refer to [this page](https://www.npmjs.com/package/handlebars-helper-moment) for the documentation on the helper.

Try this instead :

```handlebars
{{moment "2011-09-03T00:00:00-07:00" format="YYYY"}}
```

👍

**Comment by hugoabernier** [comment]
Hey @XopherDesign  did you get any success with the method suggested by @spplante ?

I'll go ahead and close this issue, but feel free to open a new issue if you need more help. I also encourage you to use the issue template provided, as it helps route your issue to the appropriate people and -- hopefully -- helps get an answer sooner.

Thank you @spplante for your solution.
