### ISSUE TITLE
sp-pnp-js causes Gulp build errors

### ISSUE THREAD

**Issue by ShaunCurtis** [SharePoint/sp-dev-fx-webparts#98]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
No build error on gulp serve

#### Observed Behavior

Error - typescript - node_modules\@types\core-js\index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\core-js\index.d.ts(867,13): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\es6-promise\index.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\es6-promise\index.d.ts(42,19): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(5,15): error TS2304: Cannot find name 'HeadersInit'.

#### Steps to Reproduce
Build a webpart with yeoman
Add following import to webpart.ts
import pnp from "sp-pnp-js";

I've seen various comments about commenting out references, but either I can see which files to do the commenting on or the references aren't in my files.  I've built the standard helloworld web part, run gulp server and added the webpart to the workbench - all works fine.  Then add the module reference to the web part ts files.  Gulp does the rebuild and errors.

All the errors are highlighted when you bring up the individual files in VS Code.  I'm too green at this game at the moment to figure out where to go to try and fix them!

**Comment by VelinGeorgiev** [comment]
What yoman template of SPFx are you using? 
Is it "No javaScript web framework"?

You are not suppose to have core-js types and in the same time es6-promise types in the solution. Probably this causes the duplicate identifier error.

The steps to add "sp-pnp-js" are:

- open the SPFx project package.json file
- add the sp-pnp-js there in the dependencies like:

```
    "dependencies": {
        "@microsoft/sp-client-base": "~1.0.0",
        "@microsoft/sp-core-library": "~1.0.0",
        "@microsoft/sp-webpart-base": "~1.0.0",
        "sp-pnp-js":"2.0.3"
      },
```
- open the cmd.exe 
- go to the project folder 
- run "npm install" from the command line to install the sp-pnp-js library
- go to your HelloWorldWebPart.ts file
- import it `import pnp from "sp-pnp-js";`

This works for me.
