### ISSUE TITLE
Arrows and dots not working in react-carousel

### ISSUE THREAD

**Issue by pandiarajank** [SharePoint/sp-dev-fx-webparts#986]
Arrows and dots are not working even after updating the properties in SliderSettings(Carousel.tsx)

Please help

**Comment by hugoabernier** [comment]
@pandiarajank did you ever resolve this issue?

I'll mark this issue as closed as there hasn't been any activity for a while, but absolutely feel free to open a new issue if you're still experiencing issues.

If you do so, I encourage you to take the time to fill the issue template provided, as it helps route issues to the appropriate authors and -- hopefully -- helps get your issues the attention they deserve.
