### ISSUE TITLE
External links in samples

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-fx-webparts#989]
#77  Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Observed Behavior

I was reviewing a sample, and I found out that it was pulling data from typicode.com.

I'd like to know if there are policies regarding  how the published samples interact with external sites. It would be nice to have those unusual external links listed as a warning in the readme file, as some organizations do not allow it.

## Steps to Reproduce

Run the React Hook sample locally.

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
Thanks @PathToSharePoint . `Typicode` is often used to provide placeholder samples, especially when running web parts in local mode.

The samples in this repository are all intended to demonstrate various concepts. Just like any other open-source code that you download you from the web, we encourage you to review the code before you deploy it in your own production environment.

These samples are provided by community members and reviewed by community members.There are no guarantees that the code directly -- or indirectly, through linked libraries -- does not access external resources.

I absolutely sympathize with your concerns, as the majority of my clients deal with high-sensitivity and high-security environments. 

As a gentle reminder, each sample comes with the following disclaimer:

> THIS CODE IS PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.

With that being said, feel free to raise issues like this one to help other members of the community identify potential pitfalls before using samples in their environment.
