### ISSUE TITLE
React-Content-Query-Webpart  Error: JSON validation failed:

### ISSUE THREAD

**Issue by Noeky** [SharePoint/sp-dev-fx-webparts#990]
When I'm trying to run a gulp command I receive the following error 
C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
C:\_dev\SharePointWebparts\samples\react-content-query-webpart\config\tslint.json

Error: #/ (Defines configuration options for the...)
       Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
    at validateObjectWithCallback (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at TslintCmdTask._readConfigFile (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
    at TslintCmdTask.onRegister (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
    at SPWebBuildRig.initialize (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:28:15)
    at Object.exports.initialize (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\_dev\SharePointWebparts\samples\react-content-query-webpart\gulpfile.js:29:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)

At this moment I'm running the following versions
PS C:\_dev\SharePointWebparts\samples\react-content-query-webpart> node -v
v8.9.4
PS C:\_dev\SharePointWebparts\samples\react-content-query-webpart> npm -v
5.6.0
PS C:\_dev\SharePointWebparts\samples\react-content-query-webpart> gulp -v
CLI version: 2.2.0
Local version: 3.9.1

Is there anything that I'm doing wrong?

**Comment by spplante** [comment]
@Noeky , it works fine for me for both the 1.1 version and the 1.4 version with the following versions:

node -v : v8.15.0
npm -v : 6.4.1
gulp -v : 3.9.1 (local version)

Did you get this after after trying to update packages by any chance? Because if you google your error there is plenty of results related specifically to SPFx with the exact same error :

https://www.c-sharpcorner.com/article/resolving-spfx-component-all-gulp-commands-failed-error-in-o365/

https://sharepoint.stackexchange.com/questions/248853/updating-spfx-breaks-gulp

Otherwise, did you try with the 1.4.1 version? If you do not want to support SharePoint 2016, I strongly advise you to use the 1.4.1 version instead (The 1.4.1 version is zipped at the root of the project).

Let me know if this helps

**Comment by abhsha** [comment]
@spplante : Do we have code working for latest SPFx framework? I am also facing similar issue after upgrading to latest Sharepoint framework. Older version are working anyhow.

**Comment by spplante** [comment]
The latest available is the 1.4.1 (zip file at the root of the project).

Upgrading from 1.4 to 1.8 will surely require some changes as their is multiple breaking changes

**Comment by hugoabernier** [comment]
Hey @Noeky  did @spplante 's suggestions help you solve this issue?

I'll mark this issue as closed. If you need more help with this, please do not hesitate to re-open the issue.

Thank you @spplante with your help!

**Comment by manishkaushal2015** [comment]
[Node version 10.19.0]
SP FX version generator-sharepoint@1.10.0

@spplante  I am getting the issue when installing REACT-CONTENT-QUERY-WEBPART
Any help is extremely appreciated. Below is detailed error log:

`npm install -g windows-build-tools npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> windows-build-tools@5.2.2 postinstall C:\Users\manis\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js
Downloading python-2.7.15.amd64.msi
[>                                    ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\manis\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\manis\.windows-build-tools\vs_BuildTools.exe.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Status from the installers:
---------- Visual Studio Build Tools ----------
2020-04-02T16:06:37 : Verbose : [InstallerImpl]: Rpc connection was closed.
2020-04-02T16:06:37 : Verbose : [InstallerImpl]: Stream was closed
2020-04-02T16:06:37 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2020-04-02T16:06:37 : Verbose : [SetupUpdaterImpl]: Stream was closed
2020-04-02T16:06:38 : Verbose : Restarting the system after an installation operation.
------------------- Python --------------------
Still waiting for installer log file...
Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\manis\.windows-build-tools
Now configuring Python...
All done!
+windows-build-tools@5.2.2
added 144 packages from 98 contributors in 35.408s
PS C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart> npm list --dempth=0 windows-build-tools                                                                                                                    react-content-query-webpart@1.0.11 C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart
-- (empty)
PS C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart> npm clean-install
npm WARN prepare removing existing node_modules/ before installation
[           .......] | extractTree: sill extract string_decoder@1.0.3 extracted to C:\Sample webparts\sp-dev-fx-webparts[           .......] | extractTree: sill extract string_decoder@1.0.3 extr
> phantomjs-prebuilt@2.1.16 install C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt
> node install.js
PhantomJS not found on PATH
Download already available at C:\Users\manis\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\manis\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1586333024608\phantomjs-2.1.1-windows -> C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
> deasync@0.1.11 install C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync
> node ./build.js
C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at findVisualStudio2015 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14)
gyp ERR! stack     at regSearchKeys (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.11 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\manis\AppData\Roaming\npm-cache\_logs\2020-04-08T08_03_53_981Z-debug.log`
