### ISSUE TITLE
Enable the script editor in the modern pages of sharepoint online

### ISSUE THREAD

**Issue by suoko** [SharePoint/sp-dev-fx-webparts#991]
I'm trying to push the script editor to sharepoint online modern pages and I wrote this little guide:

- create an appcatalog
- `git clone https://github.com/SharePoint/sp-dev-fx-webparts`
- `cd sp-dev-fx-webparts/samples/react-script-editor`
- `sudo npm install -g yo gulp && sudo npm install -g @microsoft/generator-sharepoint && npm i tslint  && npm i ajv-keywords && npm install && gulp trust-dev-cert && gulp serve`
- `gulp  --ship`
- `gulp package-solution --ship`
- upload .sppkg file from sharepoint\solution to your tenant App Catalog

I've succesfully installed the app in the sharepoint tenant app catalog, added to a modern site, but then the webpart does not appear when editing a page.
I've tried changing the setting skipFeatureDeployment to true to make the package tenant wide but in this case the app won't even show among the installable apps of a site.

I could uppload succesfully the react-webcam app so my appcatalog is ok.
I tried with 1.5.1 version of spf framework but the problem is still there.
Is it mandatory to enable the CDN via sharepoint online shell below command ?
- `Set-SPOTenantCdnEnabled -CdnType Public`

Do you have any suggestion on how to debug this ?

**EDIT:** 
I found out that, when installed, the "modern script editor" app is available in the sharepoint online but not in the office365 sites, while the "webcam app" is available in the office365 sites but not in sharepoint online.
Is there a settings about the availability of an app somewhere in the config files ? I'm using the default packages from github

**Comment by suoko** [comment]
I solved it by:
- setting "requiresCustomScript" to false in "src/webparts/scriptEditor/ScriptEditorWebPart.manifest.json" 
- putting a short description, a long description and an icon in the properties of the app in the appcatalog

Below I paste a script useful to change version number (in case of app update) and configurations:
```
nano config/package-solution.json 
nano sharepoint/solution/debug/AppManifest.xml
nano src/webparts/scriptEditor/ScriptEditorWebPart.manifest.json
npm install
gulp trust-dev-cert
gulp --ship
gulp package-solution --ship
```

**Comment by JulienValentin78** [comment]
For me, setting "requiresCustomScript" to false in "src/webparts/scriptEditor/ScriptEditorWebPart.manifest.json" doesn't do anything. When I tried to deploy the React Script Editor, everything is Ok but I have to force enabling Customs Scripts with PowerShell Cmdlet to made appear the WebPart in the list.
Is this normal behavior?

**Comment by suoko** [comment]
In my case I enabled custom scripts for users in the admin center of share point, but that was for classic pages only, not modern ones as far as I understood.
Unfortunately documentation is almost missing and the classic version of sharepoint is being deprecated.

I tried the tenant wide option too before I discovered the solution that I wrote in my second comment: you have to set the SkipFeatureDeployment to true in the package-solution.json file and flag it once you deploy the package in the app catalog. 
You can try that, if it works you should find the app installed in all sites as default

**Comment by hugoabernier** [comment]
Hey @suoko, it looks like you solve the issue.

If you don't mind, I'll mark this issue as closed, but feel free to re-open it if you need more help.

And thank you for documenting your solution.
