### ISSUE TITLE
Tradingview Script not running in react-script-editor

### ISSUE THREAD

**Issue by kemppaik** [SharePoint/sp-dev-fx-webparts#992]
## Category

- [x] Question
- [x] Bug
- [ ] Enhancement

I am trying to use the Modern Script Editor to run a widget from TradingView, the Market Overview Widget.  When I add the code into the Modern Script Editor webpart, only the footer appears.

![image](https://user-images.githubusercontent.com/55152539/64986766-fb01e980-d884-11e9-991d-3f7a863a2db2.png)

I have used the code that is on the TradingView page for the Market Overview Widget, without modifications.

If I use the Advanced Chart Widget code on the TradingView widget page, this widget will work in the Modern Script Editor - however, this is not the widget we want to use.

Any ideas on why the other widgets for TradingView are not running?

Thanks,.

**Comment by hugoabernier** [comment]
Hey @kemppaik did you ever resolve this issue? If so, we'd love to hear how you resolved it.

I'll go ahead and mark this issue as closed since there hasn't been any activity on it, but feel free to re-open it if you need more help.

**Comment by latemodel99** [comment]
We are trying to do the same thing in our environment but running into the exact same issue.  Did anyone figure out a way to do this?
