### ISSUE TITLE
Best polyfills for Spfx and React

### ISSUE THREAD

**Issue by simonssspirit** [SharePoint/sp-dev-fx-webparts#994]
#77  Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Observed Behavior

The Spxf Webpart examples for React do not work on IE11.

Please suggest the best polyfills to use with React and Spxf.

## Steps to Reproduce

Thanks for your contribution! Sharing is caring.

**Comment by gobigfoot** [comment]
The PnP team has created an IE-11 polyfill library. https://pnp.github.io/pnpjs/documentation/polyfill/

**Comment by hugoabernier** [comment]
Hey @simonssspirit I hope that @gobigfoot 's response helped solve your issue?

I'll go ahead and mark the issue as closed. Feel free to re-open it if you need more help.

Thanks @gobigfoot  for your help with this.
