### ISSUE TITLE
 Assertion `args[1]->IsString()' failed error while trying to rebuild the "react-content-query-webpart"

### ISSUE THREAD

**Issue by devendrasv** [SharePoint/sp-dev-fx-webparts#996]
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [ ] Question
- [x ] Bug
- [] Enhancement
![error](https://user-images.githubusercontent.com/3216636/65126928-aba8ee00-da29-11e9-8752-e2f9350d22e8.png)

Hi, 

I am trying to rebuild the webpart here "https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-content-query-webpart" but getting the error (Please see the attachment). 

I tried to run "npm install --unsafe-perm=true" but it start the gulp --clean but getting lot of errors,

Could you please suggest how to build this webpart. Thanks for the help.

-Devendra

**Comment by devendrasv** [comment]
Quick update: When I tried from another machine its started working..

**Comment by lumayara** [comment]
I am having the same issue. Any updates on this?

**Comment by legendgod** [comment]
I experience same issue when try to run "gulp serve" for react-file-upload.
sigh... I am getting various kind of error try to setup each samples. I think entire sample library is out-dated.
