### ISSUE TITLE
React-Calendar not loading single event to be edited

### ISSUE THREAD

**Issue by jonesron** [SharePoint/sp-dev-fx-webparts#997]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

@joaojmendes 

When I run the React-Calendar webpart in the workbench on my dev site,  I can create new single Event but when I go to edit the event, the panel doesn't load.

![image](https://user-images.githubusercontent.com/7633261/65162561-7095c300-da07-11e9-9b43-a4b8a0536ec6.png)

As far as I can tell, the await it tries to return for this.returnExceptionRecurrenceInfo(event.RecurrenceData); in src/controls/Event/event.tsx.

![image](https://user-images.githubusercontent.com/7633261/65162955-23662100-da08-11e9-9d10-da73f98e81a0.png)

The promise then tries to find the occurrence pattern.  Since there is no occurrence, the promise then returns an error.

![image](https://user-images.githubusercontent.com/7633261/65163280-abe4c180-da08-11e9-9170-d882dade95dc.png)

If the event has any occurrence, even a single day, the edit panel will load.  It only occurs in a single Event.

This may be a simple fix, and I will try an suggestions posted.  I'll also keep looking into it and will let you know if I find anything.

Thanks

**Comment by RyanRamdewar** [comment]
i can confirm this change has worked for me as well. line 817 of events.tsx

> I changed the line to this:
> let keys = recurrenceInfo !== null ? Object.keys(recurrenceInfo.recurrence.rule[0].repeat[0]) : [];
> 
> Is that a valid fix or is there another suggestion? Otherwise the issue can be closed.
> 
> Thanks

**Comment by kenhansen01** [comment]
I handled this by checking recurrence value. If it was an empty string I set state to showRecurrenceSeriesInfo: false, this triggers the default new item view with the switch to enable recurrence. https://github.com/kenhansen01/sp-react-calendar/blob/master/src/controls/Event/event.tsx

**Comment by prathimapilli** [comment]
> I changed the line to this:
> let keys = recurrenceInfo !== null ? Object.keys(recurrenceInfo.recurrence.rule[0].repeat[0]) : [];
> 
> Is that a valid fix or is there another suggestion? Otherwise the issue can be closed.
> 
> Thanks

Its Working for me as well in chrome but not working in ie if anybody has idea pls let me know

**Comment by essineden** [comment]
This actually fixed my problem -- thanks!

**Comment by hugoabernier** [comment]
@jonesron it looks like you solved this issue.

I'll go ahead and mark is as closed, but feel free to re-open it if you need more help with this.
