### ISSUE TITLE
Suggestion:  make this sticky on the page so that it scrolls with the content

### ISSUE THREAD

**Issue by CrackerboxOnline** [SharePoint/sp-dev-fx-webparts#998]
**I did not not read the full list completely and apologies if this is the wrong place to post a suggestion or already raised.**

Provide an option to allow the web part to remain on screen as the user scrolls through the content.

What would be really cool is if the web part indicates where the user is up to in the navigation as they scroll.

I know I'm asking a lot.

Great work BTW.

**Comment by hugoabernier** [comment]
Thanks @CrackerboxOnline . I'd recommend that you open a suggestion at https://sharepoint.uservoice.com/. This issue list is really intended for web part samples.

If you open a suggestion on UserVoice, the community can upvote your suggestion which increases the chances that the product group will see it.

I hope this helps?
